/* Space Tyrants — late-game balance of power, inter-rival politics, coalitions,
   physical embargoes, flagships, scalable rival rearmament, and complete
   defeated-faction cleanup. All military growth still begins with visible,
   resource-backed projects and fleets. */

const STX_GB_VERSION=1;
const STX_GB_THREAT_LEVELS=[
  {min:0,label:"Minor"},{min:22,label:"Notable"},{min:42,label:"Major Power"},{min:62,label:"Strategic Threat"},{min:80,label:"Existential Threat"}
];
const STX_GB_FLAGSHIP_NAMES=["Sovereign Dawn","Indomitable","Crown of Stars","Resolute","Astral Dominion","Unbroken Oath","Radiant Spear","Eternal Horizon","Majesty","Final Argument","Celestial Throne","Defiant Star"];

function stxGBId(prefix){return`${prefix}${Math.floor(random()*1e9)}`}
function stxGBEscape(value){return String(value??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[c])}
function stxGBPairKey(a,b){return a<b?`${a}:${b}`:`${b}:${a}`}
function stxGBThreatKey(observer,target){return`${observer}>${target}`}
function stxGBAlive(id){return !!empire(id)&&owned(id).length>0&&!empire(id).stxEliminated}
function stxGBFleetPower(id){try{return Math.max(0,Number(empireFleet(id))||0)}catch(_){return state.fleets.filter(f=>f.owner===id&&!f.destroyed).reduce((n,f)=>n+(Number(f.strength)||0),0)}}
function stxGBTechPower(e){return Object.values(e?.tech||{}).reduce((n,v)=>n+(Number(v)||0),0)}
function stxGBPower(owner){const e=empire(owner),worlds=owned(owner),fleet=stxGBFleetPower(owner),industry=Math.max(0,Number(empireIndustry(owner))||0),population=Math.max(0,Number(totalPop(owner))||0),technology=stxGBTechPower(e),score=fleet+industry*7.5+worlds.length*9+population*34+technology*4;return{owner,fleet,industry,worlds:worlds.length,population,technology,score}}
function stxGBRecentAggression(owner,window=420){return(empire(owner)?.stxAggressionHistory||[]).filter(x=>state.simTime-(x.time||0)<window)}
function stxGBAggressionScore(owner,window=420){return stxGBRecentAggression(owner,window).reduce((n,x)=>n+(Number(x.weight)||1),0)}
function stxGBRecordAggression(owner,type,detail,weight=1,target=null){const e=empire(owner);if(!e)return;e.stxAggressionHistory=Array.isArray(e.stxAggressionHistory)?e.stxAggressionHistory:[];e.stxAggressionHistory.unshift({id:stxGBId("agr"),type,detail,weight,target,time:state.simTime});e.stxAggressionHistory=e.stxAggressionHistory.filter(x=>state.simTime-x.time<720).slice(0,30)}
function stxGBExpansionRate(owner,window=260){return owned(owner).reduce((n,p)=>n+(p.ownershipHistory||[]).filter(h=>h.owner===owner&&state.simTime-(h.time||0)<window).length,0)}
function stxGBFriendship(observer,target){const rel=relation(observer,target),pair=typeof stxRDPair==="function"?stxRDPair(observer,target):null,goodwill=pair?.goodwill||0;return clamp(Math.max(0,rel)*22+goodwill*.28,0,34)}
function stxGBThreatLevel(score){return STX_GB_THREAT_LEVELS.slice().reverse().find(x=>score>=x.min)||STX_GB_THREAT_LEVELS[0]}
function stxGBThreatAssessment(observer,target){
  if(observer===target)return{score:0,level:"Minor",reasons:[]};const them=stxGBPower(target),us=stxGBPower(observer),ratio=them.score/Math.max(12,us.score),planetRatio=them.worlds/Math.max(1,us.worlds),aggression=stxGBAggressionScore(target),expansion=stxGBExpansionRate(target),proximity=frontierDistance(observer,target),pair=typeof stxRDPair==="function"?stxRDPair(observer,target):null,broken=(pair?.grievances||[]).filter(g=>g.against===target&&/broken|war declaration|embargo|conquest/i.test(`${g.type} ${g.text}`)).slice(0,5).length;
  let score=8+clamp(Math.log2(Math.max(.25,ratio))*19,-12,34)+clamp((planetRatio-1)*12,-5,19)+aggression*4.2+expansion*2.6+(proximity<700?10:proximity<1200?6:proximity>2200?-4:0)+broken*4-stxGBFriendship(observer,target);
  if(ratio>2.2)score+=9;if(aggression===0)score-=4;score=clamp(score,0,100);const level=stxGBThreatLevel(score),reasons=[];if(ratio>=1.65)reasons.push(`${empire(target).name} is ${ratio.toFixed(1)}× stronger overall`);else if(ratio>=1.12)reasons.push("Their strategic power is ahead");if(planetRatio>=1.6)reasons.push(`${them.worlds} worlds versus ${us.worlds}`);if(aggression>=5)reasons.push(`${aggression.toFixed(0)} recent aggression pressure`);if(expansion>=2)reasons.push(`${expansion} recent territorial gains`);if(proximity<900)reasons.push("Close shared frontier");if(broken)reasons.push("Remembered broken agreements or attacks");if(!reasons.length)reasons.push("No dominant strategic warning");return{observer,target,score,level:level.label,reasons:reasons.slice(0,4),ratio,planetRatio,aggression,expansion,proximity};
}

function stxGBDefaultState(){return{version:STX_GB_VERSION,threats:{},coalitions:[],embargoBattles:[],eliminated:[],nextStrategicAt:state.simTime+18,nextPoliticsAt:state.simTime+32,nextCoalitionAt:state.simTime+85,lastTickAt:state.simTime,playerFlagshipPrompted:false}}
function stxGBEnsureState(reset=false){
  if(!state.empires?.length)return null;const saved=!reset&&empire(0)?.stxGalacticBalance;if(reset||!state.galacticBalance||state.galacticBalance.version!==STX_GB_VERSION)state.galacticBalance=saved?.version===STX_GB_VERSION?saved:stxGBDefaultState();const s=state.galacticBalance;s.threats=s.threats||{};s.coalitions=Array.isArray(s.coalitions)?s.coalitions:[];s.embargoBattles=Array.isArray(s.embargoBattles)?s.embargoBattles:[];s.eliminated=Array.isArray(s.eliminated)?s.eliminated:[];s.nextStrategicAt=Number.isFinite(s.nextStrategicAt)?s.nextStrategicAt:state.simTime+18;s.nextPoliticsAt=Number.isFinite(s.nextPoliticsAt)?s.nextPoliticsAt:state.simTime+32;s.nextCoalitionAt=Number.isFinite(s.nextCoalitionAt)?s.nextCoalitionAt:state.simTime+85;s.lastTickAt=Number.isFinite(s.lastTickAt)?s.lastTickAt:state.simTime;state.empires.forEach(e=>{e.stxAggressionHistory=Array.isArray(e.stxAggressionHistory)?e.stxAggressionHistory:[];if(e.stxEliminated&&!s.eliminated.includes(e.id))s.eliminated.push(e.id)});empire(0).stxGalacticBalance=s;return s;
}
function stxGBPersist(){if(state.empires?.length&&state.galacticBalance)empire(0).stxGalacticBalance=state.galacticBalance}
const STX_GB_generateGalaxy=generateGalaxy;
generateGalaxy=function(){STX_GB_generateGalaxy();state.galacticBalance=null;stxGBEnsureState(true)};
const STX_GB_loadGame=loadGame;
loadGame=function(){const ok=STX_GB_loadGame();if(ok){state.galacticBalance=empire(0)?.stxGalacticBalance||null;stxGBEnsureState(false);stxGBCleanupEliminated()}return ok};
const STX_GB_saveGame=saveGame;
saveGame=function(notify=true){stxGBPersist();return STX_GB_saveGame(notify)};

function stxGBMilitaryTarget(owner){
  const e=empire(owner),p=stxGBPower(owner),policy=e?.foreignPolicy||{},neighbors=state.empires.filter(x=>x.id!==owner&&stxGBAlive(x.id)).map(x=>({id:x.id,d:frontierDistance(owner,x.id),fleet:stxGBFleetPower(x.id),threat:stxGBThreatAssessment(owner,x.id).score})).sort((a,b)=>a.d-b.d),danger=neighbors.filter(x=>x.d<1900||x.threat>=62).sort((a,b)=>b.fleet-a.fleet)[0],economic=p.worlds*13+p.industry*4.8+p.population*26+p.technology*3.2,matching=danger?danger.fleet*(.42+(policy.aggression||.4)*.22+(policy.caution||.4)*.16):0,war=state.wars.some(w=>w.active&&(w.a===owner||w.b===owner));return Math.ceil(clamp(Math.max(24,economic,matching)*(war?1.18:1),24,520));
}
function stxGBBestDevelopmentWorld(owner,type){return owned(owner).filter(p=>!p.underAttack&&!p.localProject).sort((a,b)=>{if(type==="shipyard")return(b.infra.factory+b.pop*6)-(a.infra.factory+a.pop*6);if(type==="factory")return(b.infra.mine+b.pop*4)-(a.infra.mine+a.pop*4);return Math.max(...Object.values(b.quality||{}))-Math.max(...Object.values(a.quality||{}))})[0]||null}
function stxGBRearmEmpire(e){
  if(!e||e.id===0||!stxGBAlive(e.id))return false;const actual=stxGBFleetPower(e.id),target=stxGBMilitaryTarget(e.id),worlds=owned(e.id),industry=empireIndustry(e.id);e.stxMilitaryTarget=target;e.stxMilitaryGap=Math.max(0,target-actual);if(industry<Math.max(3,worlds.length*.72)){const p=stxGBBestDevelopmentWorld(e.id,"factory");if(p&&startLocalProject(p,"factory","Galactic development catch-up"))return true}
  let yard=typeof stxBestFleetYard==="function"?stxBestFleetYard(e.id):worlds.filter(p=>p.infra.shipyard>0&&!p.underAttack)[0];if(!yard&&worlds.length>=3){const p=stxGBBestDevelopmentWorld(e.id,"shipyard");if(p&&p.infra.factory>0&&startLocalProject(p,"shipyard","Strategic naval development"))return true}
  if(actual>=target*.88||!yard)return false;const queued=worlds.reduce((n,p)=>n+(p.buildQueue||[]).filter(q=>q.type==="fleet"||q.type==="patrol").length,0);if(queued>=Math.max(1,Math.ceil(worlds.length/4)))return false;if(typeof stxQueueFleetCommission==="function"&&stxQueueFleetCommission(yard,actual<target*.52?"fleet":(random()<.7?"fleet":"patrol"),"Visible strategic rearmament")){addDirective(e,"fleet",yard.id,95);setModifier(e,"shipbuilding",1.18,70);if(stxGBThreatAssessment(e.id,0).score>=62)e.stxEmergencyRearmUntil=state.simTime+90;return true}return false;
}
function stxGBExpansionCatchup(e,rules,worldCount){if(!e||e.id===0)return rules;const alive=state.empires.filter(x=>stxGBAlive(x.id)),counts=alive.map(x=>owned(x.id).length).sort((a,b)=>a-b),median=counts[Math.floor(counts.length/2)]||worldCount,neutral=state.planets.filter(p=>p.owner===null).length,lag=Math.max(0,median-worldCount),stalled=Math.max(0,state.simTime-(e.lastExpansion||0)),pressure=neutral>16?2:neutral>7?1:0;return{...rules,maxWorlds:Math.max(rules.maxWorlds,worldCount+lag+pressure,Math.min(12,3+Math.floor(state.simTime/190))),cooldown:Math.max(22,rules.cooldown*(lag?Math.max(.62,1-lag*.11):stalled>190&&neutral? .72:1)),intent:clamp(rules.intent+lag*.1+(stalled>180&&neutral?.12:0),.06,.98)}}
if(typeof stxRDExpansionRules==="function"){
  const STX_GB_expansionRules=stxRDExpansionRules;stxRDExpansionRules=function(e,worldCount=owned(e.id).length){return stxGBExpansionCatchup(e,STX_GB_expansionRules(e,worldCount),worldCount)};
}

function stxGBAllAgreements(){state.rivalDiplomacy=state.rivalDiplomacy||{agreements:[]};state.rivalDiplomacy.agreements=Array.isArray(state.rivalDiplomacy.agreements)?state.rivalDiplomacy.agreements:[];return state.rivalDiplomacy.agreements}
function stxGBAgreement(kind,a,b){return stxGBAllAgreements().find(x=>x.active!==false&&x.kind===kind&&x.expiresAt>state.simTime&&((x.by===a&&x.with===b)||(x.by===b&&x.with===a)||(x.a===a&&x.b===b)||(x.a===b&&x.b===a)))||null}
function stxGBAddAgreement(kind,a,b,duration=170,extra={}){const existing=stxGBAgreement(kind,a,b);if(existing)return existing;const record=typeof stxRDAddAgreement==="function"?stxRDAddAgreement(kind,a,b,duration,extra):{id:stxGBId("gba"),kind,by:a,with:b,createdAt:state.simTime,expiresAt:state.simTime+duration,active:true,...extra};return record}
function stxGBEmbargoesAgainst(owner){return stxGBAllAgreements().filter(x=>x.active!==false&&x.kind==="embargo"&&x.with===owner&&x.by!==owner&&x.expiresAt>state.simTime)}
function stxGBEmbargoRoute(embargo){
  const by=owned(embargo.by),against=owned(embargo.with);if(!by.length||!against.length)return null;let from=null,to=null,best=Infinity;by.forEach(a=>against.forEach(b=>{const d=dist(a,b);if(d<best){best=d;from=a;to=b}}));if(!from||!to)return null;const t=.58;return{from,to,x:from.x+(to.x-from.x)*t,y:from.y+(to.y-from.y)*t,distance:best};
}
function stxGBEmbargoStrength(by,against){const fleets=state.fleets.filter(f=>f.owner===by&&!f.destroyed).sort((a,b)=>(b.strength||0)-(a.strength||0)),fleetIds=fleets.slice(0,2).map(f=>f.id),strength=Math.max(9,fleets.slice(0,2).reduce((n,f)=>n+(f.strength||0)*.3,0)+empireIndustry(by)*1.5);return{strength,fleetIds}}
function stxGBImposeEmbargo(by,against,reason="strategic pressure",coalitionId=null){
  if(by===against||!stxGBAlive(by)||!stxGBAlive(against)||getWar(by,against)||stxGBAgreement("embargo",by,against))return null;const force=stxGBEmbargoStrength(by,against),record=stxGBAddAgreement("embargo",by,against,165,{bilateral:false,reason,coalitionId,strength:force.strength,fleetIds:force.fleetIds,acknowledged:false});record.by=by;record.with=against;record.bilateral=false;record.reason=reason;record.strength=record.strength||force.strength;record.fleetIds=record.fleetIds||force.fleetIds;empire(by).commercialAccess[against]=0;empire(against).commercialAccess[by]=0;state.ships.filter(s=>s.commercial&&((s.owner===by&&state.planets.find(p=>p.id===s.to)?.owner===against)||(s.owner===against&&state.planets.find(p=>p.id===s.to)?.owner===by))).forEach(s=>{s.stxEmbargoRerouted=true;s.speed*=.72});if(typeof stxRDAddGrievance==="function")stxRDAddGrievance(against,by,"embargo",`${empire(by).name} imposed an embargo over ${reason}`,2);if(by===0)stxGBRecordAggression(0,"embargo",`${empire(0).name} embargoed ${empire(against).name}`,1.5,against);galacticNews(`${empire(by).name.toUpperCase()} EMBARGOES ${empire(against).name.toUpperCase()}`,`Segmented interdiction patrols are appearing across affected trade lanes. Commerce will stop while the embargo remains active.`,"warning");renderTransmissions();renderRivals();updateBadges();return record;
}

function stxGBRelationStatus(a,b){if(getWar(a,b))return"At War";if(stxGBAgreement("mutual-defense",a,b))return"Allied";const rel=relation(a,b),pair=typeof stxRDPair==="function"?stxRDPair(a,b):null,tension=pair?.tension||0;if(rel>.5&&tension<34)return"Friendly";if(rel>-.08&&tension<48)return"Neutral";if(rel>-.38&&tension<70)return"Suspicious";return"Hostile"}
function stxGBSharedThreat(a,b){return state.empires.filter(e=>e.id!==a&&e.id!==b&&stxGBAlive(e.id)).map(e=>({id:e.id,score:Math.min(stxGBThreatAssessment(a,e.id).score,stxGBThreatAssessment(b,e.id).score)})).sort((x,y)=>y.score-x.score)[0]||null}
function stxGBRelationshipPolitics(){
  const alive=state.empires.filter(e=>stxGBAlive(e.id));for(let i=0;i<alive.length;i++)for(let j=i+1;j<alive.length;j++){const a=alive[i],b=alive[j];if(getWar(a.id,b.id))continue;const status=stxGBRelationStatus(a.id,b.id),shared=stxGBSharedThreat(a.id,b.id);if(a.id!==0&&b.id!==0&&status==="Friendly"&&!stxGBAgreement("trade-agreement",a.id,b.id)&&random()<.12)stxGBAddAgreement("trade-agreement",a.id,b.id,190,{bilateral:true});if(a.id!==0&&b.id!==0&&shared?.score>=67&&!stxGBAgreement("mutual-defense",a.id,b.id)&&random()<.2)stxGBAddAgreement("mutual-defense",a.id,b.id,220,{bilateral:true,sharedThreat:shared.id});const ab=stxGBThreatAssessment(a.id,b.id),ba=stxGBThreatAssessment(b.id,a.id);if(a.id!==0&&ab.score>=72&&ab.aggression>=5&&status!=="Friendly"&&random()<.12)stxGBImposeEmbargo(a.id,b.id,"balance-of-power pressure");if(b.id!==0&&ba.score>=72&&ba.aggression>=5&&status!=="Friendly"&&random()<.12)stxGBImposeEmbargo(b.id,a.id,"balance-of-power pressure")}
}
function stxGBAIEmbargoResponses(force=false){
  stxGBAllAgreements().filter(x=>x.active!==false&&x.kind==="embargo"&&x.with!==0&&x.expiresAt>state.simTime).forEach(embargo=>{const target=empire(embargo.with);if(!target||!stxGBAlive(target.id)||getWar(target.id,embargo.by)||!force&&state.simTime<(embargo.nextResponseAt||0))return;embargo.nextResponseAt=state.simTime+rand(38,62);target.stxEmergencyRearmUntil=Math.max(target.stxEmergencyRearmUntil||0,state.simTime+85);stxGBRearmEmpire(target);if(typeof stxRDMobilize==="function")stxRDMobilize(target.id,embargo.by,true);const alternative=state.empires.filter(e=>e.id!==target.id&&e.id!==embargo.by&&stxGBAlive(e.id)&&!getWar(e.id,target.id)&&!stxGBAgreement("embargo",e.id,target.id)).sort((a,b)=>relation(target.id,b.id)-relation(target.id,a.id))[0];if(alternative)stxGBAddAgreement("trade-agreement",target.id,alternative.id,145,{embargoDiversion:embargo.id,bilateral:true});const ratio=stxGBPower(target.id).score/Math.max(1,stxGBPower(embargo.by).score),policy=target.foreignPolicy||{},willing=ratio>=.78&&(policy.aggression||0)>=.58;if(!willing||!force&&random()>.18+(policy.aggression||0)*.18)return;const pair=typeof stxRDPair==="function"?stxRDPair(target.id,embargo.by):null;if(pair){pair.escalationStage=Math.max(5,pair.escalationStage||0);pair.ultimatumRejectedAt=state.simTime-12;pair.tension=Math.max(78,pair.tension||0)}const war=declareWar(target.id,embargo.by,`an attempt to break ${empire(embargo.by).name}'s embargo`);if(war){war.warGoal={type:"break-embargo",targetId:embargo.id,label:`Break ${empire(embargo.by).name} embargo`,status:"active",limited:true};war.stxLimitedWar=true;embargo.aiChallengeWarId=war.id;embargo.challengedAt=state.simTime;galacticNews(`${target.name.toUpperCase()} CHALLENGES EMBARGO`,`${target.name} has rerouted trade, mobilized visible fleets, and opened a limited war to break ${empire(embargo.by).name}'s blockade.`,"danger")}})
}

function stxGBActiveCoalition(target=null){return state.galacticBalance?.coalitions?.find(c=>c.status==="active"&&(target===null||c.target===target))||null}
function stxGBHegemonCandidate(){const alive=state.empires.filter(e=>stxGBAlive(e.id)).map(e=>({e,power:stxGBPower(e.id)})).sort((a,b)=>b.power.score-a.power.score);if(alive.length<4)return null;const median=alive[Math.floor(alive.length/2)].power.score,leader=alive[0],aggression=stxGBAggressionScore(leader.e.id);if(leader.power.score<82||leader.power.score<median*(aggression>=5?1.35:1.65))return null;return{...leader,median,aggression}}
function stxGBFormCoalition(target,members,aggression){
  const c={id:stxGBId("coal"),name:`${empire(target).name} Containment Coalition`,target,members:[...new Set(members)],status:"active",posture:aggression>=5?"Coordinated Pressure":"Defensive Balance",createdAt:state.simTime,lastAidAt:-999,nextEscalationAt:state.simTime+rand(45,75)};state.galacticBalance.coalitions.push(c);for(let i=0;i<c.members.length;i++)for(let j=i+1;j<c.members.length;j++)stxGBAddAgreement("mutual-defense",c.members[i],c.members[j],260,{coalitionId:c.id,bilateral:true});if(aggression>=5)c.members.filter(id=>id!==0&&!getWar(id,target)&&stxGBRelationStatus(id,target)!=="Friendly").forEach(id=>stxGBImposeEmbargo(id,target,"coalition containment",c.id));galacticNews(`${c.name.toUpperCase()} FORMS`,`${c.members.map(id=>empire(id).name).join(", ")} have begun ${c.posture.toLowerCase()} against ${empire(target).name}. Their response uses pacts, freight, rearmament, embargoes, and—only if escalation continues—coordinated war.`,"warning");if(target===0||c.members.includes(0))logEvent(`${c.name} formed with ${c.members.length} members.`,"warning");return c;
}
function stxGBMaybeCoalition(){
  const s=stxGBEnsureState(false);if(state.simTime<s.nextCoalitionAt)return;s.nextCoalitionAt=state.simTime+rand(55,85);const hegemon=stxGBHegemonCandidate();if(!hegemon||stxGBActiveCoalition(hegemon.e.id))return;const target=hegemon.e.id,members=state.empires.filter(e=>e.id!==target&&stxGBAlive(e.id)).map(e=>({id:e.id,assessment:stxGBThreatAssessment(e.id,target),friendship:stxGBFriendship(e.id,target)})).filter(x=>x.assessment.score>=50+(x.friendship>20?12:0)).sort((a,b)=>b.assessment.score-a.assessment.score).slice(0,4).map(x=>x.id);if(members.length>=2)stxGBFormCoalition(target,members,hegemon.aggression);
}
function stxGBCoalitionAid(c){
  if(state.simTime-(c.lastAidAt||-999)<32)return;c.lastAidAt=state.simTime;const members=c.members.filter(stxGBAlive),receiver=members.map(id=>({id,need:empireNeed(id)[0]})).filter(x=>x.need&&typeof stxRTEmpireAvailable==="function").sort((a,b)=>(b.need.orders*35-b.need.amount)-(a.need.orders*35-a.need.amount))[0];if(!receiver)return;const donor=members.filter(id=>id!==receiver.id&&stxRTEmpireAvailable(id,receiver.need.resource)>20).sort((a,b)=>stxRTEmpireAvailable(b,receiver.need.resource)-stxRTEmpireAvailable(a,receiver.need.resource))[0];if(donor===undefined)return;const source=typeof stxRTSource==="function"?stxRTSource(donor,receiver.need.resource):null,dest=typeof stxRTDestination==="function"?stxRTDestination(receiver.id,receiver.need.resource):null,amount=Math.ceil(Math.min(28,stxRTEmpireAvailable(donor,receiver.need.resource)*.25));if(source&&dest&&amount>3){source.stock[receiver.need.resource]-=amount;stxRTDispatchCargo(source,dest,donor,receiver.need.resource,amount,{stxCoalitionAid:c.id,tradeKind:"coalition-aid"});if(c.target===0||c.members.includes(0))galacticNews("COALITION AID CONVOY",`${empire(donor).name} dispatched ${amount} ${stxRTLabel(receiver.need.resource)} to ${empire(receiver.id).name}.`,"trade",dest.id)}}
function stxGBCoalitionTick(){
  state.galacticBalance.coalitions.filter(c=>c.status==="active").forEach(c=>{c.members=c.members.filter(stxGBAlive);if(!stxGBAlive(c.target)||c.members.length<2){c.status="dissolved";return}const candidate=stxGBHegemonCandidate();if(!candidate||candidate.e.id!==c.target&&stxGBPower(c.target).score<candidate.median*1.25){c.status="dissolved";return}stxGBCoalitionAid(c);const aggression=stxGBAggressionScore(c.target),wars=state.wars.filter(w=>w.active&&(w.a===c.target||w.b===c.target));if(aggression<9||state.simTime<c.nextEscalationAt)return;c.nextEscalationAt=state.simTime+rand(45,75);const fighting=new Set(wars.map(w=>w.a===c.target?w.b:w.a)),candidateMember=c.members.filter(id=>id!==0&&!fighting.has(id)&&!getWar(id,c.target)).sort((a,b)=>stxGBFleetPower(b)-stxGBFleetPower(a))[0];if(candidateMember!==undefined&&wars.length<2&&stxGBThreatAssessment(candidateMember,c.target).score>=76){const w=declareWar(candidateMember,c.target,`coordinated containment of ${empire(c.target).name}`);if(w)c.posture="Coordinated War"}})
}

function stxGBUpdateThreats(){
  const alive=state.empires.filter(e=>stxGBAlive(e.id));for(const observer of alive)for(const target of alive){if(observer.id===target.id)continue;const assessment=stxGBThreatAssessment(observer.id,target.id);state.galacticBalance.threats[stxGBThreatKey(observer.id,target.id)]={...assessment,updatedAt:state.simTime};if(assessment.score>=62){const pair=typeof stxRDPair==="function"?stxRDPair(observer.id,target.id):null,friend=stxGBFriendship(observer.id,target.id),aggressive=assessment.aggression>0;if(pair){pair.tension=clamp((pair.tension||0)+(aggressive?1.15:.32)*(1-friend/55),0,100);if(aggressive&&relation(observer.id,target.id)<.55)adjustRelation(observer.id,target.id,-.004)}if(observer.id!==0)empire(observer.id).stxEmergencyRearmUntil=Math.max(empire(observer.id).stxEmergencyRearmUntil||0,state.simTime+55)}}
}

function stxGBFlagshipFleet(owner){const id=empire(owner)?.stxFlagshipId,f=id&&fleetRecord(id);return f&&!f.destroyed&&f.isFlagship?f:null}
function stxGBFlagshipEligible(owner){return stxGBAlive(owner)&&stxGBFleetPower(owner)>=100&&state.fleets.some(f=>f.owner===owner&&!f.destroyed)}
function stxGBFlagshipName(e,f){const used=new Set(state.fleets.map(x=>x.flagshipName).filter(Boolean)),seed=Math.abs(String(`${e.name}:${f.id}`).split("").reduce((n,c)=>Math.imul(n^c.charCodeAt(0),16777619),2166136261));for(let i=0;i<STX_GB_FLAGSHIP_NAMES.length;i++){const name=STX_GB_FLAGSHIP_NAMES[(seed+i)%STX_GB_FLAGSHIP_NAMES.length];if(!used.has(name))return name}return`${e.name.split(" ")[0]} Ascendant`}
function stxGBDesignateFlagship(owner,fleetId,automatic=false){
  const e=empire(owner),f=fleetRecord(fleetId);if(!e||!f||f.owner!==owner||f.destroyed||stxGBFlagshipFleet(owner)||!stxGBFlagshipEligible(owner))return false;f.isFlagship=true;f.flagshipName=stxGBFlagshipName(e,f);f.flagshipDesignatedAt=state.simTime;f.flagshipBonus=.08;f.maxServiceStrength=Math.max(f.maxServiceStrength||0,f.strength||0);f.strength=(f.strength||0)*1.08;f.status=`Flagship formation · ${f.status}`;e.stxFlagshipId=f.id;e.stxFlagshipCooldownUntil=state.simTime+95;galacticNews(`${e.name.toUpperCase()} DESIGNATES FLAGSHIP ${f.flagshipName.toUpperCase()}`,`${f.name}, commanded by Admiral ${f.admiral?.name||"Unknown"}, becomes the empire's unique flagship formation. Its combat bonus is modest, but nearby formations gain coordination.`,"good",f.location||f.homePort);if(owner===0&&!automatic)showToast(`${f.flagshipName} designated as the Mandate flagship`);return true;
}
function stxGBAutoFlagships(){state.empires.filter(e=>e.id!==0&&stxGBAlive(e.id)&&stxGBFlagshipEligible(e.id)&&!stxGBFlagshipFleet(e.id)&&state.simTime>=(e.stxFlagshipCooldownUntil||0)).forEach(e=>{const f=state.fleets.filter(x=>x.owner===e.id&&!x.destroyed).sort((a,b)=>(b.strength||0)-(a.strength||0)||(b.veterans||0)-(a.veterans||0))[0];if(f)stxGBDesignateFlagship(e.id,f.id,true)});if(stxGBFlagshipEligible(0)&&!stxGBFlagshipFleet(0)&&!state.galacticBalance.playerFlagshipPrompted){state.galacticBalance.playerFlagshipPrompted=true;galacticNews("FLAGSHIP DESIGNATION AVAILABLE","Fleet Power has reached 100. Choose one active formation in Famous Fleets to become the Mandate's unique flagship.","good");updateBadges()}}
function stxGBFlagshipLoss(f,where){
  const e=empire(f.owner);if(!e)return;e.stxFlagshipId=null;e.stxFlagshipCooldownUntil=state.simTime+120;f.isFlagship=false;f.flagshipLost=true;setModifier(e,"militaryMorale",.72,85);const survivors=state.fleets.filter(x=>x.owner===f.owner&&!x.destroyed&&x.id!==f.id);let shaken=0,retreated=0;survivors.forEach(x=>{const veteran=x.veterans||0,trait=/Veteran|Tactician|Unyielding/i.test(x.admiral?.trait||"")?.1:0,losing=state.battles.some(b=>(b.attackerFleetIds||[]).includes(x.id)&&b.attackerStrength<b.defenderStrength||(b.defenderFleetIds||[]).includes(x.id)&&b.defenderStrength<b.attackerStrength),chance=clamp(.34+(losing?.14:0)-veteran*.34-trait,.05,.52);if(random()<chance){x.strength=Math.max(.5,(x.strength||0)*.88);x.readiness="shaken";x.status=`Shaken by loss of ${f.flagshipName}`;shaken++;if(x.location&&state.planets.find(p=>p.id===x.location)?.owner!==x.owner){x.location=x.homePort;x.status="Retreated after flagship loss";retreated++}}});galacticNews(`${e.name.toUpperCase()} FLAGSHIP ${String(f.flagshipName||f.name).toUpperCase()} DESTROYED`,`${e.name} suffers a major morale shock. ${shaken} surviving formation${shaken===1?" was":"s were"} shaken${retreated?`, and ${retreated} withdrew`:""}. Veteran crews were less likely to break.`,"danger",where?.id||f.homePort);if(f.owner===0)logEvent(`The flagship ${f.flagshipName||f.name} was destroyed. Fleet morale has fallen temporarily.`,"danger");
}
const STX_GB_retireFleet=retireFleet;
retireFleet=function(f,destroyedAt,reason){const wasFlagship=!!f?.isFlagship&&!f?.destroyed;const result=STX_GB_retireFleet(f,destroyedAt,reason);if(wasFlagship)stxGBFlagshipLoss(f,destroyedAt);return result};
const STX_GB_deployFleet=deployFleet;
deployFleet=function(from,to,owner,strength,extra={}){const flagship=stxGBFlagshipFleet(owner),support=flagship&&flagship.id!==extra.fleetId&&flagship.location===from?.id;if(support)extra={...extra,speedBoost:(extra.speedBoost||1)*1.08,stxFlagshipSupport:flagship.id};return STX_GB_deployFleet(from,to,owner,strength,extra)};

function stxGBEliminateEmpire(id,conqueror=null){
  const e=empire(id),s=stxGBEnsureState(false);if(!e||id===0||e.stxEliminated||owned(id).length)return false;e.stxEliminated=true;e.stxEliminatedAt=state.simTime;e.stxEliminatedBy=conqueror;s.eliminated.push(id);state.ships=state.ships.filter(ship=>ship.owner!==id);state.battles=state.battles.filter(b=>b.attacker!==id&&b.defender!==id);state.fleets.filter(f=>f.owner===id&&!f.destroyed).forEach(f=>{f.destroyed=true;f.status="Disbanded after imperial collapse";f.destroyedAt=state.simTime});state.wars.filter(w=>w.active&&(w.a===id||w.b===id)).forEach(w=>endWar(w,"total conquest"));state.contracts.filter(c=>c.active&&(c.a===id||c.b===id)).forEach(c=>{c.active=false;c.endReason="faction destroyed"});state.proposals.filter(p=>p.status==="pending"&&(p.from===id||p.to===id)).forEach(p=>p.status="cancelled");(state.rivalDiplomacy?.requests||[]).filter(q=>q.status==="pending"&&(q.from===id||q.to===id)).forEach(q=>q.status="cancelled");stxGBAllAgreements().filter(a=>a.active!==false&&(a.by===id||a.with===id||a.a===id||a.b===id)).forEach(a=>a.active=false);s.coalitions.forEach(c=>{c.members=c.members.filter(x=>x!==id);if(c.target===id||c.members.length<2)c.status="dissolved"});(state.deepSpaceOperations||[]).filter(o=>o.owner===id).forEach(o=>o.active=false);(state.deepSpaceBases||[]).filter(b=>b.owner===id&&b.status!=="wreck").forEach(b=>{if(typeof stxDSDestroyBase==="function")stxDSDestroyBase(b,conqueror,`${e.name} ceased to exist`);else{b.status="wreck";b.destroyedAt=state.simTime;b.owner=id}});galacticNews(`${e.name.toUpperCase()} HAS FALLEN`,`${e.name} lost its final world. Its fleets, trade routes, embargoes, requests, invasion plans, coalition membership, and surviving independent installations have been resolved.`,"danger");logEvent(`${e.name} was completely conquered and removed from Rival Powers.`,conqueror===0?"good":"warning");renderRivals();renderTransmissions();updateBadges();return true;
}
function stxGBCleanupEliminated(){state.empires.filter(e=>e.id!==0&&!e.stxEliminated&&!owned(e.id).length).forEach(e=>stxGBEliminateEmpire(e.id,e.stxLastConqueror??null))}
const STX_GB_resolveBattle=resolveBattle;
resolveBattle=function(b,p,index){const oldOwner=p?.owner,attacker=b?.attacker,result=STX_GB_resolveBattle(b,p,index);if(p&&oldOwner!==null&&p.owner===attacker&&oldOwner!==attacker){stxGBRecordAggression(attacker,"conquest",`${empire(attacker).name} conquered ${p.name}`,2.2,oldOwner);if(empire(oldOwner))empire(oldOwner).stxLastConqueror=attacker}stxGBCleanupEliminated();return result};
const STX_GB_declareWar=declareWar;
declareWar=function(a,b,reason="border dispute"){const existing=getWar(a,b),targetPower=stxGBPower(b).score,actorPower=stxGBPower(a).score,w=STX_GB_declareWar(a,b,reason);if(w&&!existing&&!w.stxGBAggressionRecorded){w.stxGBAggressionRecorded=true;const weaker=actorPower>targetPower*1.45;stxGBRecordAggression(a,"war-declaration",`${empire(a).name} declared war on ${empire(b).name}${weaker?" while substantially stronger":""}`,weaker?4:2.6,b)}return w};

function stxGBNormalizeEmbargoes(){stxGBAllAgreements().filter(x=>x.active!==false&&x.kind==="embargo"&&x.expiresAt>state.simTime).forEach(e=>{const force=stxGBEmbargoStrength(e.by,e.with);e.strength=Number.isFinite(e.strength)?e.strength:force.strength;e.fleetIds=Array.isArray(e.fleetIds)?e.fleetIds:force.fleetIds;e.bilateral=false})}
function stxGBEmbargoChoice(){const active=stxGBEmbargoesAgainst(0).filter(e=>!getWar(0,e.by));if(!active.length)return null;return{id:`stx-break-embargo-${Math.floor(state.simTime)}`,cat:"War",title:"BREAK EMBARGO",desc:"Commit available fleets to attack the enforcement patrols. This is a real fleet movement and battle.",effects:[`${active.length} hostile embargo${active.length===1?"":"es"}`,"Choose exact fleet count","ATTACKING DECLARES WAR"],stxSpecialFifth:true,stxFleetOrderKind:"breakEmbargo",apply:()=>{}}}
const STX_GB_openCommandPhase=openCommandPhase;
openCommandPhase=function(){const result=STX_GB_openCommandPhase();if(!$("commandModal")?.hidden){const special=stxGBEmbargoChoice();if(special&&!state.commandChoices.some(c=>c.stxFleetOrderKind==="breakEmbargo")){state.commandChoices=state.commandChoices.filter(c=>!c.stxSpecialFifth).slice(0,4);state.commandChoices.push(special);state.commandSelected.clear();renderCommands()}}return result};
const STX_GB_renderCommands=renderCommands;
renderCommands=function(){STX_GB_renderCommands();const grid=$("commandGrid");if(!grid)return;[...grid.children].forEach((button,i)=>{const choice=state.commandChoices[i];if(choice?.stxFleetOrderKind!=="breakEmbargo")return;button.classList.add("stx-gb-break-embargo");button.style.setProperty("--cat","#ff5b45");const cat=button.querySelector?.(".command-cat");if(cat)cat.textContent="ADDITIONAL OPTION · WAR";button.onclick=()=>{if(typeof stxFCAOpenDirect==="function")stxFCAOpenDirect("breakEmbargo")}})};

if(typeof stxFCARenderTargets==="function"){
  const STX_GB_fcaRenderTargets=stxFCARenderTargets;stxFCARenderTargets=function(order){if(order?.kind!=="breakEmbargo")return STX_GB_fcaRenderTargets(order);const box=$("stxFCATargetList");stxFCAAllocations={};stxFCAUiDestinations=stxGBEmbargoesAgainst(0).filter(e=>!getWar(0,e.by)).map(e=>{const route=stxGBEmbargoRoute(e);return{key:`embargo:${e.id}`,type:"embargo",id:e.id,name:empire(e.by).name,embargo:e,planet:route?.to,point:route,subtitle:`${Math.round(e.strength||0)} blockade strength · attacking declares war`}});box.innerHTML=stxFCAUiDestinations.map(t=>`<label class="stx-fca-target"><input type="radio" name="stx-fca-breakEmbargo" value="${stxGBEscape(t.key)}"><span><b>Break ${stxGBEscape(t.name)} Embargo</b><small>${stxGBEscape(t.subtitle)}</small></span></label>`).join("")||'<div class="subtle">No non-war embargo remains to attack.</div>'};
  const STX_GB_fcaShow=stxFCAShow;stxFCAShow=function(){STX_GB_fcaShow();const order=stxFCAQueue[0];if(order?.kind!=="breakEmbargo")return;$("stxFCAKicker").textContent="SPECIAL WAR COMMAND · BREAK EMBARGO";$("stxFCATitle").textContent="Attack Embargo Enforcement";$("stxFCADesc").textContent="Choose the enforcing faction and exact number of surviving fleets. Confirmation declares war immediately; your ships then travel to and fight the visible blockade patrols.";$("stxFCATargetLabel").textContent="Select Embargo to Break";stxFCASyncUi()};
  const STX_GB_fcaConfirm=stxFCAConfirm;stxFCAConfirm=function(){const order=stxFCAQueue[0];if(order?.kind!=="breakEmbargo")return STX_GB_fcaConfirm();const selected=stxFCASelectedDestinations()[0],count=stxFCACount();if(!selected||!count||!stxGBLaunchEmbargoBreak(selected.embargo,count))return showToast("The embargo attack could not be launched");stxFCAFinish(true)};
  const confirmButton=$("stxFCAConfirm");if(confirmButton)confirmButton.onclick=stxFCAConfirm;
}
function stxGBLaunchEmbargoBreak(embargo,count){
  if(!embargo||embargo.active===false||embargo.with!==0||getWar(0,embargo.by))return false;const route=stxGBEmbargoRoute(embargo),chosen=typeof stxFCAFree==="function"?stxFCAFree(route?.to).slice(0,count):state.fleets.filter(f=>f.owner===0&&!f.destroyed).slice(0,count);if(!route||chosen.length!==count||typeof stxDSCreateTransit!=="function"||state.ships.length+chosen.length>279)return false;const war=declareWar(0,embargo.by,"an attack on embargo enforcement fleets");if(!war)return false;stxGBRecordAggression(0,"embargo-break",`The Mandate attacked ${empire(embargo.by).name} embargo patrols`,2.5,embargo.by);embargo.challengedAt=state.simTime;embargo.breakFleetIds=[];embargo.breakArrived=[];for(const f of chosen){if(typeof stxFCADetachBattle==="function")stxFCADetachBattle(f);const transit=state.ships.find(s=>s.fleetId===f.id),fromPoint=transit||((typeof stxFCAPosition==="function"&&stxFCAPosition(f))||state.planets.find(p=>p.id===f.location)||playerWorlds()[0]);if(transit)state.ships.splice(state.ships.indexOf(transit),1);const fromPlanet=state.planets.find(p=>p.id===f.location)||state.planets.find(p=>p.id===f.homePort)||playerWorlds()[0];f.location=null;f.status=`Attacking ${empire(embargo.by).name} embargo patrols`;const ship=stxDSCreateTransit({type:"fleet",owner:0,fromPoint,targetPoint:route,fromPlanetId:fromPlanet?.id,toPlanetId:route.to.id,fleetId:f.id,mission:"break-embargo",strength:f.strength,vesselName:f.name,speedBoost:1.18,extra:{stxEmbargoId:embargo.id,warId:war.id,status:f.status}});if(!ship)return false;embargo.breakFleetIds.push(f.id);if(typeof stxFCACommitted!=="undefined")stxFCACommitted.add(f.id)}galacticNews("MANDATE FLEETS ATTACK EMBARGO PATROLS",`${chosen.length} formation${chosen.length===1?" is":"s are"} moving toward the blockade. The attack has declared war on ${empire(embargo.by).name}.`,"danger",route.to.id);logEvent(`BREAK EMBARGO: ${chosen.length} fleets committed against ${empire(embargo.by).name}. War declared.`,"danger");return true;
}
function stxGBStartEmbargoBattle(embargo){if(!embargo||state.galacticBalance.embargoBattles.some(b=>b.embargoId===embargo.id&&b.active))return;const route=stxGBEmbargoRoute(embargo),fleets=(embargo.breakFleetIds||[]).map(fleetRecord).filter(f=>f&&!f.destroyed),attack=fleets.reduce((n,f)=>n+(f.strength||0),0);if(!route||!attack)return;state.galacticBalance.embargoBattles.push({id:stxGBId("ebb"),embargoId:embargo.id,owner:0,defender:embargo.by,x:route.x,y:route.y,attackerStrength:attack,defenderStrength:Math.max(8,embargo.strength||8),attackerInitial:attack,defenderInitial:Math.max(8,embargo.strength||8),fleetIds:fleets.map(f=>f.id),elapsed:0,maxDuration:14,active:true,fxClock:0});fleets.forEach(f=>f.status=`Engaged with embargo patrols of ${empire(embargo.by).name}`)}
if(typeof stxDSHandleTransitArrival==="function"){
  const STX_GB_deepArrival=stxDSHandleTransitArrival;stxDSHandleTransitArrival=function(s){if(s?.stxDeepMission!=="break-embargo")return STX_GB_deepArrival(s);const embargo=stxGBAllAgreements().find(e=>e.id===s.stxEmbargoId),f=fleetRecord(s.fleetId);if(!embargo||!f)return;embargo.breakArrived=[...new Set([...(embargo.breakArrived||[]),f.id])];f.location=null;f.strength=s.strength;f.status="Forming for embargo assault";if((embargo.breakFleetIds||[]).every(id=>embargo.breakArrived.includes(id)))stxGBStartEmbargoBattle(embargo)};
}
function stxGBReturnEmbargoFleet(f,point,status){const home=playerWorlds().sort((a,b)=>Math.hypot(a.x-point.x,a.y-point.y)-Math.hypot(b.x-point.x,b.y-point.y))[0];if(!home)return;f.status=status;f.location=null;if(typeof stxDSCreateTransit==="function")stxDSCreateTransit({type:"fleet",owner:0,fromPoint:point,targetPoint:home,fromPlanetId:home.id,toPlanetId:home.id,fleetId:f.id,mission:"planet",strength:f.strength,vesselName:f.name,speedBoost:1.12,extra:{stxFinalPlanetId:home.id,retreat:true,status}})}
function stxGBResolveEmbargoBattle(b){const embargo=stxGBAllAgreements().find(e=>e.id===b.embargoId),win=b.attackerStrength>b.defenderStrength,remaining=Math.max(.5,b.attackerStrength),fleets=b.fleetIds.map(fleetRecord).filter(Boolean),total=fleets.reduce((n,f)=>n+(f.strength||0),0)||1;fleets.forEach(f=>{const share=(f.strength||0)/total,survivor=remaining*share;f.battles=(f.battles||0)+1;f.strength=survivor;f.veterans=clamp((f.veterans||0)+(win?.055:.02),0,.92);if(survivor<=.8)retireFleet(f,{id:null,name:"the embargo line",x:b.x,y:b.y},"destroyed while breaking an embargo");else stxGBReturnEmbargoFleet(f,b,win?"Returning after breaking the embargo":"Withdrawing from failed embargo assault")});if(embargo){if(win){embargo.active=false;embargo.brokenAt=state.simTime;embargo.brokenBy=0;galacticNews(`${empire(embargo.by).name.toUpperCase()} EMBARGO BROKEN`,"Mandate fleets defeated the enforcement patrols. The blockade indicators are collapsing, although the resulting war continues.","good")}else{embargo.strength=Math.max(6,b.defenderStrength);galacticNews("EMBARGO ASSAULT REPELLED",`${empire(embargo.by).name} retained control of the blockade line. The embargo remains in force during the new war.`,"danger")}}b.active=false;b.resolvedAt=state.simTime;renderRivals();updateHud(true)}
function stxGBTtickEmbargoBattles(dt){state.galacticBalance.embargoBattles.filter(b=>b.active).forEach(b=>{b.elapsed+=dt;const ad=(.18+b.attackerStrength*.0065),dd=(.16+b.defenderStrength*.006);b.defenderStrength=Math.max(0,b.defenderStrength-ad*dt*rand(.86,1.14));b.attackerStrength=Math.max(0,b.attackerStrength-dd*dt*rand(.86,1.14));if(b.attackerStrength<=.5||b.defenderStrength<=.5||b.elapsed>=b.maxDuration)stxGBResolveEmbargoBattle(b)});state.galacticBalance.embargoBattles=state.galacticBalance.embargoBattles.filter(b=>b.active||state.simTime-(b.resolvedAt||0)<35)}

function stxGBStrategicTick(){const s=stxGBEnsureState(false);if(state.simTime<s.nextStrategicAt)return;s.nextStrategicAt=state.simTime+rand(20,30);stxGBUpdateThreats();state.empires.slice(1).forEach(stxGBRearmEmpire);stxGBAutoFlagships();stxGBCleanupEliminated();stxGBNormalizeEmbargoes();stxGBAIEmbargoResponses();stxGBCoalitionTick();if(state.simTime>=s.nextPoliticsAt){s.nextPoliticsAt=state.simTime+rand(36,58);stxGBRelationshipPolitics()}stxGBMaybeCoalition();stxGBPersist();if(!$("rivalsModal")?.hidden)renderRivals()}
const STX_GB_simulate=simulate;
simulate=function(dt){const result=STX_GB_simulate(dt);stxGBTtickEmbargoBattles(dt);stxGBStrategicTick();return result};

function stxGBEmbargoCard(e){const route=stxGBEmbargoRoute(e);return`<article class="transmission-card urgent stx-gb-embargo"><div class="card-kicker">ACTIVE EMBARGO // ${stxGBEscape(empire(e.by)?.name)}</div><div class="card-title"><strong>Trade lanes under interdiction</strong><span class="news-time">${fmtEta(e.expiresAt-state.simTime)}</span></div><p class="card-copy">${stxGBEscape(e.reason||"Strategic pressure")} · approximately ${Math.round(e.strength||0)} enforcement strength is visible along ${stxGBEscape(route?.to?.name||"Mandate frontier")} routes.</p><div class="choice-row"><span class="stx-gb-warning">BREAK EMBARGO appears as an additional command option. Attacking declares war.</span></div></article>`}
function stxGBFlagshipPrompt(){if(!stxGBFlagshipEligible(0)||stxGBFlagshipFleet(0))return"";return`<article class="transmission-card governor stx-gb-flagship-prompt"><div class="card-kicker">ADMIRALTY // PRESTIGE COMMAND</div><div class="card-title"><strong>Designate the Imperial Flagship</strong></div><p class="card-copy">Fleet Power has reached 100. Select one active formation in Famous Fleets; only one flagship may serve at a time.</p><div class="choice-row"><button class="choice-btn primary-choice" id="stxGBOpenFleets">Open Famous Fleets</button></div></article>`}
const STX_GB_renderTransmissions=renderTransmissions;
renderTransmissions=function(){STX_GB_renderTransmissions();const box=$("transmissionList");if(!box)return;const embargoes=stxGBEmbargoesAgainst(0).filter(e=>!getWar(0,e.by));const html=embargoes.map(stxGBEmbargoCard).join("")+stxGBFlagshipPrompt();if(html)box.insertAdjacentHTML("beforeend",html);const open=$("stxGBOpenFleets");if(open)open.onclick=()=>switchHubTab("fleets")};

function stxGBDecorateFleetRegistry(){const box=$("fleetGrid");if(!box)return;const fleets=state.fleets.slice().sort((a,b)=>Number(a.destroyed)-Number(b.destroyed)||b.victories-a.victories||b.battles-a.battles),cards=[...box.querySelectorAll?.(".fleet-card")||[]],current=stxGBFlagshipFleet(0),eligible=stxGBFlagshipEligible(0);cards.forEach((card,i)=>{const f=fleets[i];if(!f)return;if(f.isFlagship){card.classList.add("stx-gb-flagship-card");card.insertAdjacentHTML("afterbegin",`<div class="stx-gb-flagship-banner">✦ FLAGSHIP ${stxGBEscape(f.flagshipName)} · +${Math.round((f.flagshipBonus||.08)*100)}% COMBAT PRESTIGE</div>`)}else if(f.owner===0&&!f.destroyed&&eligible&&!current)card.insertAdjacentHTML("beforeend",`<button class="choice-btn stx-gb-designate" data-stx-flagship="${f.id}">Designate as Flagship</button>`)});box.querySelectorAll?.("[data-stx-flagship]").forEach(b=>b.onclick=()=>{if(stxGBDesignateFlagship(0,b.dataset.stxFlagship)){renderFleetRegistry();renderTransmissions();updateHud(true)}})}
const STX_GB_renderFleetRegistry=renderFleetRegistry;
renderFleetRegistry=function(){STX_GB_renderFleetRegistry();stxGBDecorateFleetRegistry()};

function stxGBCoalitionSummary(){const active=state.galacticBalance?.coalitions?.filter(c=>c.status==="active")||[];if(!active.length)return"";return`<div class="stx-gb-coalitions">${active.map(c=>`<span><b>${stxGBEscape(c.name)}</b>${stxGBEscape(c.posture)} · ${c.members.map(id=>stxGBEscape(empire(id)?.name)).join(" + ")}</span>`).join("")}</div>`}
function stxGBDecorateRivals(){const grid=$("rivalGrid");if(!grid)return;const rivals=state.empires.filter(e=>e.id!==0&&stxGBAlive(e.id)),cards=[...grid.querySelectorAll?.(".rival-card")||[]];cards.forEach((card,i)=>{const e=rivals[i];if(!e)return;const assessment=stxGBThreatAssessment(e.id,0),ourView=stxGBThreatAssessment(0,e.id),coalition=stxGBActiveCoalition(0),member=coalition?.members.includes(e.id),embargo=stxGBEmbargoesAgainst(0).find(x=>x.by===e.id);card.insertAdjacentHTML("beforeend",`<div class="stx-gb-balance"><span><label>Their view of us</label><b>${stxGBEscape(assessment.level)}</b></span><span><label>Our view of them</label><b>${stxGBEscape(ourView.level)}</b></span><span><label>AI relationship</label><b>${stxGBEscape(stxGBRelationStatus(0,e.id))}</b></span><span><label>Military target</label><b>${Math.round(e.stxMilitaryTarget||stxGBMilitaryTarget(e.id))}</b></span>${member?'<em>ANTI-HEGEMONY COALITION MEMBER</em>':""}${embargo?'<em class="hostile">EMBARGO ENFORCER</em>':""}</div>`)});const summary=$("warSummary");if(summary)summary.insertAdjacentHTML("beforeend",stxGBCoalitionSummary())}
const STX_GB_renderRivals=renderRivals;
// Rendering must never remove empire identities used by fleet history and trade.
renderRivals=function(){
  if(state.stxSelectedRivalId!=null&&!stxGBAlive(state.stxSelectedRivalId))state.stxSelectedRivalId=state.empires.find(e=>e.id!==0&&stxGBAlive(e.id))?.id??null;
  STX_GB_renderRivals();stxGBDecorateRivals();
};

function stxGBDrawEmbargoes(){const t=performance.now()/1000;ctx.save();stxGBAllAgreements().filter(e=>e.active!==false&&e.kind==="embargo"&&e.expiresAt>state.simTime).forEach(e=>{const route=stxGBEmbargoRoute(e);if(!route||(!visible(route.from.x,route.from.y,240)&&!visible(route.to.x,route.to.y,240)))return;const a=worldToScreen(route.from.x,route.from.y),b=worldToScreen(route.to.x,route.to.y);ctx.strokeStyle="rgba(255,104,57,.62)";ctx.lineWidth=2;ctx.setLineDash([9,6,2,6]);ctx.lineDashOffset=-(t*18)%23;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);for(let i=0;i<3;i++){const phase=(t*.055+i/3)%1,x=a.x+(b.x-a.x)*phase,y=a.y+(b.y-a.y)*phase,angle=Math.atan2(b.y-a.y,b.x-a.x);ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.fillStyle="#ff8d55";ctx.shadowColor="#ff5c42";ctx.shadowBlur=9;ctx.beginPath();ctx.moveTo(7,0);ctx.lineTo(-4,-3);ctx.lineTo(-2,0);ctx.lineTo(-4,3);ctx.closePath();ctx.fill();ctx.restore()}if(state.camera.zoom>.5){ctx.fillStyle="#ff9b64";ctx.font="800 8px system-ui";ctx.textAlign="center";ctx.fillText(`EMBARGO · ${empire(e.by)?.name||"Unknown"}`, (a.x+b.x)/2,(a.y+b.y)/2-9)}});ctx.restore()}
const STX_GB_drawTradeCorridors=drawTradeCorridors;
drawTradeCorridors=function(){STX_GB_drawTradeCorridors();stxGBDrawEmbargoes()};
function stxGBFlagshipPoint(f){const ship=state.ships.find(s=>s.fleetId===f.id);if(ship)return ship;if(f.deepSpaceBaseId&&typeof stxDSBase==="function")return stxDSBase(f.deepSpaceBaseId);return state.planets.find(p=>p.id===f.location)||state.planets.find(p=>p.id===f.homePort)||null}
function stxGBDrawFlagships(){const t=performance.now()/1000;state.fleets.filter(f=>f.isFlagship&&!f.destroyed).forEach(f=>{const p=stxGBFlagshipPoint(f);if(!p||!visible(p.x,p.y,80))return;const s=worldToScreen(p.x,p.y),r=clamp(17*state.camera.zoom,10,26),color=empire(f.owner)?.color||"#fff";ctx.save();ctx.translate(s.x,s.y);ctx.rotate(t*.22);ctx.strokeStyle="#ffe48b";ctx.shadowColor=color;ctx.shadowBlur=14;ctx.lineWidth=1.6;ctx.beginPath();ctx.moveTo(0,-r);ctx.lineTo(r*.58,0);ctx.lineTo(0,r);ctx.lineTo(-r*.58,0);ctx.closePath();ctx.stroke();ctx.rotate(-t*.44);ctx.setLineDash([3,5]);ctx.beginPath();ctx.arc(0,0,r*1.35,0,6.283);ctx.stroke();ctx.restore();if(state.camera.zoom>.58){ctx.fillStyle="#ffe9a4";ctx.font="900 8px system-ui";ctx.textAlign="center";ctx.fillText(`FLAGSHIP · ${f.flagshipName}`,s.x,s.y-r*1.7)}})}
function stxGBDrawEmbargoBattles(){const t=performance.now()/1000;state.galacticBalance.embargoBattles.filter(b=>b.active).forEach(b=>{if(!visible(b.x,b.y,140))return;const s=worldToScreen(b.x,b.y),r=clamp(68*state.camera.zoom,32,90),ac=empire(b.owner)?.color||"#6cf",dc=empire(b.defender)?.color||"#f65";ctx.save();ctx.globalCompositeOperation="lighter";for(let i=0;i<7;i++){const a=t*(i%2?-.7:.72)+i*.9,p={x:s.x+Math.cos(a)*r,y:s.y+Math.sin(a)*r*.48},q={x:s.x-Math.cos(a)*r*.65,y:s.y-Math.sin(a)*r*.34};drawCombatCraft(p,q,i%2?ac:dc,3,i===0)}ctx.strokeStyle="#ff864e";ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(s.x,s.y,r+9,0,6.283);ctx.stroke();ctx.restore()})}
const STX_GB_draw=draw;
draw=function(){STX_GB_draw();stxGBDrawFlagships();stxGBDrawEmbargoBattles()};

function stxGBInstallStyles(){if($("stxGBStyles"))return;const style=document.createElement("style");style.id="stxGBStyles";style.textContent=`
.command-card.stx-gb-break-embargo{grid-column:1/-1;border-color:rgba(255,86,57,.72)!important;background:linear-gradient(135deg,rgba(255,72,47,.2),rgba(75,10,24,.6))!important;box-shadow:0 0 22px rgba(255,72,47,.12)}.command-card.stx-gb-break-embargo h3{color:#ffb19d}.stx-gb-warning{padding:7px 9px;border:1px solid rgba(255,88,59,.38);border-radius:8px;background:rgba(255,70,45,.09);color:#ffb29f;font-size:.61rem;font-weight:900}.stx-gb-flagship-card{border-color:rgba(255,225,126,.55)!important;box-shadow:0 0 18px rgba(255,213,95,.09)}.stx-gb-flagship-banner{margin:-13px -13px 11px;padding:7px 10px;background:linear-gradient(90deg,rgba(255,211,91,.18),rgba(111,87,255,.12));border-bottom:1px solid rgba(255,225,126,.28);color:#ffe9a5;font-size:.55rem;font-weight:950;letter-spacing:.1em}.stx-gb-designate{margin-top:9px;width:100%;border-color:rgba(255,221,119,.42)!important;color:#ffe39a}.stx-gb-balance{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin:9px 0 0;padding-top:8px;border-top:1px solid rgba(255,255,255,.07)}.stx-gb-balance>span{padding:6px;border-radius:7px;background:rgba(5,12,28,.55)}.stx-gb-balance label,.stx-gb-balance b{display:block}.stx-gb-balance label{font-size:.46rem;color:#7287a1;text-transform:uppercase}.stx-gb-balance b{margin-top:2px;font-size:.58rem;color:#edf6ff}.stx-gb-balance em{grid-column:1/-1;padding:5px 7px;border-radius:6px;background:rgba(255,177,68,.09);color:#ffc46f;font-size:.49rem;font-style:normal;font-weight:950;letter-spacing:.06em}.stx-gb-balance em.hostile{background:rgba(255,78,76,.1);color:#ff9e92}.stx-gb-coalitions{display:grid;gap:5px;margin-top:7px}.stx-gb-coalitions span{display:block;padding:8px;border:1px solid rgba(255,181,73,.22);border-radius:8px;background:rgba(255,173,61,.06);font-size:.58rem;color:#9fb0c6}.stx-gb-coalitions b{display:block;color:#ffc66e;font-size:.64rem}.stx-gb-embargo{border-color:rgba(255,91,63,.42)!important}
`;document.head.appendChild(style)}

globalThis.SpaceTyrantsGalacticBalance={version:STX_GB_VERSION,ensureState:stxGBEnsureState,power:stxGBPower,militaryTarget:stxGBMilitaryTarget,threat:stxGBThreatAssessment,threatLevel:stxGBThreatLevel,relationStatus:stxGBRelationStatus,imposeEmbargo:stxGBImposeEmbargo,embargoesAgainst:stxGBEmbargoesAgainst,respondToEmbargo:stxGBAIEmbargoResponses,formCoalition:stxGBFormCoalition,activeCoalition:stxGBActiveCoalition,designateFlagship:stxGBDesignateFlagship,flagship:stxGBFlagshipFleet,eliminateEmpire:stxGBEliminateEmpire,expansionCatchup:stxGBExpansionCatchup,recordAggression:stxGBRecordAggression};
stxGBEnsureState(false);stxGBNormalizeEmbargoes();stxGBInstallStyles();stxGBCleanupEliminated();
