import assert from 'node:assert/strict';
import test from 'node:test';
import {createSimulation} from './simulation-harness.mjs';
function lab(){const h=createSimulation();h.run(`state.p=playerWorlds()[0];state.p.pop=1;state.p.capacity=2;state.p.infra.factory=3;state.p.infra.shipyard=2;state.p.stock.trained=.2;state.p.reserveVessels=200;state.p.underAttack=false;empire(0).credits=10000;for(const r of RESOURCES.concat(['components','equipment']))state.p.stock[r]=10000;state.p.stxLocalProjects=[];state.p.localProject=null;state.p.stxOrbitalProjects=[];state.p.orbitalProject=null;state.p.physicalProjects=[];state.p.buildQueue=[];state.ships=[];state.fleets=[];`);return h}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
test('construction priority reallocates finite effort; suspension preserves progress and remaining stock',()=>{const h=lab();h.run(`startLocalProject(state.p,'city');startLocalProject(state.p,'city');state.a=stxIDProjects(state.p)[0];state.b=stxIDProjects(state.p)[1];stxIDPriority(state.p,state.a.id,'Emergency');stxSDAllocatePlanet(state.p);tickLocalProject(state.p,5)`);assert.ok(h.run('state.a.q.progress>state.b.q.progress'));h.run(`stxIDPriority(state.p,state.a.id,'Suspended');state.before=state.a.q.progress;tickLocalProject(state.p,5)`);near(h.run('state.a.q.progress'),h.run('state.before'));assert.equal(h.run('stxIDShare(state.a)'),0);near(h.run('stxIDShare(state.b)'),1)});
test('cancellation refunds only unused delivered goods exactly once',()=>{const h=lab();h.run(`startLocalProject(state.p,'city');stxSDAllocatePlanet(state.p);state.d=stxIDProjects(state.p)[0];state.d.q.progress=.4;state.returned=stxIDRefund(state.d).iron;state.before=state.p.stock.iron;state.id=state.d.id`);assert.equal(h.run('stxIDCancel(state.p,state.id)'),true);near(h.run('state.p.stock.iron'),h.run('state.before+state.returned'));assert.equal(h.run('stxIDCancel(state.p,state.id)'),false);assert.equal(h.run('state.p.stxLocalProjects.length'),0)});
test('rush quotes are charged once and survive save reload',()=>{const h=lab();h.run(`startLocalProject(state.p,'city');state.d=stxIDProjects(state.p)[0];state.cost=stxIDRushCost(state.d,3);state.before=empire(0).credits`);assert.equal(h.run('stxIDRush(state.p,state.d.id,3)'),true);near(h.run('empire(0).credits'),h.run('state.before-state.cost'));assert.equal(h.run('stxIDRush(state.p,state.d.id,3)'),false);h.run('state.pid=state.p.id;saveGame(false);loadGame();state.p=state.planets.find(p=>p.id===state.pid)');assert.equal(h.run('state.p.stxLocalProjects[0].imperialRush'),3)});
test('designer conserves reserve hulls, personnel and fee, preserves template and fleet identity',()=>{const h=lab();h.run(`state.f=stxIFDDesign(state.p,{escorts:10,heavy:5},'Northwind','Intercept','Cautious');stxIFDSaveTemplate('Northwind',state.f.imperialComposition)`);assert.ok(h.run('state.f'));assert.equal(h.run('state.p.reserveVessels'),185);near(h.run('state.p.stock.trained'),.197);assert.equal(h.run('empire(0).credits'),9970);h.run('state.id=state.f.id;saveGame(false);loadGame();state.f=fleetRecord(state.id)');assert.equal(h.run('state.f.imperialDoctrine'),'Cautious');assert.equal(h.run('state.f.imperialComposition.heavy'),5);assert.equal(h.run('empire(0).imperialTemplates.Northwind.escorts'),10)});
test('light and heavy designs trade travel speed for combat power',()=>{const h=lab();assert.ok(h.run('stxIFDStats({escorts:20}).speed>stxIFDStats({heavy:20}).speed'));assert.ok(h.run('stxIFDStats({escorts:20}).power<stxIFDStats({heavy:20}).power'));assert.equal(h.run('stxIFDComposition({heavy:-1})'),null)});
function crossing(h,{offset=0,peace=false,evasive=false}={}){h.run(`state.enemy=owned(1)[0];${peace?'':'declareWar(0,1,"a direct imperial declaration");'}state.a=registerFleet(0,state.p,50);state.b=registerFleet(1,state.enemy,50);state.a.imperialDoctrine='${evasive?'Evasive':'Aggressive'}';state.b.imperialDoctrine='${evasive?'Evasive':'Aggressive'}';state.sa=stxDSCreateTransit({type:'fleet',owner:0,fromPoint:{x:-500,y:0},targetPoint:{x:500,y:0},fromPlanetId:state.p.id,toPlanetId:state.p.id,fleetId:state.a.id,mission:'planet',strength:50,extra:{stxFinalPlanetId:state.p.id}});state.sb=stxDSCreateTransit({type:'fleet',owner:1,fromPoint:{x:0,y:${-500-offset}},targetPoint:{x:0,y:500},fromPlanetId:state.enemy.id,toPlanetId:state.enemy.id,fleetId:state.b.id,mission:'planet',strength:50,extra:{stxFinalPlanetId:state.enemy.id}});state.sa.speed=100;state.sb.speed=100;`)}
test('simultaneous hostile crossings create one physical encounter with no teleport to planets',()=>{const h=lab();crossing(h);h.run('tickShips(5)');assert.equal(h.run('stxIFDEncounters().length'),1);assert.ok(h.run('Math.abs(stxIFDEncounters()[0].x)<60'));assert.equal(h.run('state.battles.length'),0);assert.equal(h.run('state.sa.x'),h.run('state.sb.x'));h.run('tickShips(.5)');assert.equal(h.run('stxIFDEncounters().length'),1)});
test('crossed route lines at different times and peaceful/evasive fleets do not fight',()=>{for(const options of [{offset:800},{peace:true},{evasive:true}]){const h=lab();crossing(h,options);h.run('tickShips(5)');assert.equal(h.run('stxIFDEncounters().length'),0)}});
test('relative motion detects high speed pass-through without endpoint overlap',()=>{const h=lab();assert.ok(h.run('stxIFDContact({x:-100,y:0},{x:100,y:0},{x:1000,y:0},{x:-1000,y:0},.2,10)')>0);assert.equal(h.run('stxIFDContact({x:-100,y:0},{x:0,y:100},{x:100,y:0},{x:0,y:100},1,10)'),null)});
test('encounters save and load with participants; winner resumes mission and loser retreats',()=>{const h=lab();crossing(h);h.run('tickShips(5);state.aid=state.a.id;state.bid=state.b.id;saveGame(false);loadGame();state.a=fleetRecord(state.aid);state.b=fleetRecord(state.bid)');assert.equal(h.run('stxIFDEncounters().length'),1);h.run('state.b.strength=.01;tickShips(.5)');assert.equal(h.run('stxIFDEncounters().length'),0);assert.ok(h.run('state.a.victories>0'));assert.equal(h.run('state.a.imperialEncounter'),undefined);assert.ok(h.run('state.ships.some(s=>s.fleetId===state.a.id)'))});
test('replacement construction consumes raw material and crew and retains admiral and veterans',()=>{const h=lab();h.run(`state.f=stxIFDDesign(state.p,{line:10},'Veterans');state.f.veterans=.8;state.admiral=state.f.admiral.name;state.f.strength*=.5;stxIFDReconcile(state.f);state.before=state.p.stock.iron`);assert.equal(h.run('stxIFDReinforce(state.p,state.f)'),true);near(h.run('state.p.stock.iron'),h.run('state.before-20'));assert.equal(h.run('stxIFDReinforce(state.p,state.f)'),false);h.run('stxIFDTickReinforcements(1000)');assert.equal(h.run('stxIFDStats(state.f.imperialComposition).count'),10);assert.equal(h.run('state.f.veterans'),.8);assert.equal(h.run('state.f.admiral.name'),h.run('state.admiral'))});
test('mandate credit quote matches commission receipt and blocks concealed charges atomically',()=>{const h=lab();h.run(`state.c={...COMMANDS.find(c=>c.id==='fleetCommission'),targetObj:state.p};state.commandChoices=[state.c];state.commandSelected=new Set([0]);renderCommands();state.before=empire(0).credits`);assert.equal(h.run('stxIMQuote(state.c).credits'),30);assert.equal(h.run('issueCommands()'),true);near(h.run('empire(0).credits'),h.run('state.before-30'));
 h.run(`state.commandChoices=[{id:'test',title:'Free test',cat:'Industry',effects:[],apply:e=>{e.credits-=999;state.p.infra.city++}}];state.commandSelected=new Set([0]);renderCommands();state.before=empire(0).credits;state.cities=state.p.infra.city`);assert.equal(h.run('issueCommands()'),false);near(h.run('empire(0).credits'),h.run('state.before'));assert.equal(h.run('state.p.infra.city'),h.run('state.cities'))});
test('policy allowance caps ongoing costs after empire expansion',()=>{const h=lab();h.run(`stxPolicyActivate(0,'mining-surge');state.active=stxPolicyState(empire(0)).active.find(a=>a.id==='mining-surge');state.cap=state.active.imperialAllowance.equipment;state.before=state.p.stock.equipment;stxPolicyPay(state.p,STX_POLICIES['mining-surge'].upkeep,100000);stxPolicyPay(state.p,STX_POLICIES['mining-surge'].upkeep,100000)`);near(h.run('state.before-state.p.stock.equipment'),h.run('state.cap'))});
test('physical projects appear exactly once and suspended jobs do not advance',()=>{const h=lab();h.run(`stxOLQueueProject(state.p,'factory');state.list=stxIDProjects(state.p);state.d=state.list.find(d=>d.kind==='physical')`);assert.equal(h.run('state.list.filter(d=>d.q===state.d.q).length'),1);h.run(`stxIDPriority(state.p,state.d.id,'Suspended');state.before=state.d.q.progress;stxOLTickProject(state.p,state.d.q,100)`);near(h.run('state.d.q.progress'),h.run('state.before'))});
test('colony mandate quotes its actual expedition fee and full colony recipe',()=>{const h=lab();h.run(`state.target=state.planets.find(p=>p.owner===null);state.c={...COMMANDS.find(c=>c.id==='claim'),targetObj:state.target};state.commandChoices=[state.c];state.commandSelected=new Set([0]);renderCommands();state.quote=stxIMQuote(state.c)`);assert.ok(h.run('state.quote.credits>0'));assert.equal(h.run('state.quote.resources.iron'),24);assert.equal(h.run('issueCommands()'),true);assert.ok(h.run('playerWorlds().some(p=>p.expansionProject)'))});
