/* Space Tyrants mobile HUD, orientation layouts, popup intelligence, and touch camera controls. */
const mobileStyle=document.createElement("style");
mobileStyle.id="spaceTyrantsMobileLayout";
mobileStyle.textContent=`
.mobile-only{display:none!important}.mobile-popover{display:none}
@media(max-width:900px){
  .mobile-only{display:inline-grid!important}
  .topbar{left:8px!important;right:8px!important;top:max(6px,env(safe-area-inset-top))!important;min-height:50px!important;height:50px!important;padding:5px 7px!important;border-radius:14px!important;gap:6px!important}
  .brand{min-width:38px!important;max-width:38px!important;gap:0!important}.brand-mark{width:36px!important;height:36px!important;border-radius:11px!important;font-size:16px!important}.brand>div:last-child{display:none!important}
  .top-actions{margin-left:auto!important;gap:4px!important;align-items:center!important}.top-actions .icon-btn{width:40px!important;min-width:40px!important;height:40px!important;border-radius:11px!important;padding:0!important}
  #homeBtn,#saveBtn,#planetToggle{display:none!important}
  .hud-stats{display:none!important;position:fixed!important;z-index:72!important;left:8px!important;right:8px!important;top:calc(max(6px,env(safe-area-inset-top)) + 56px)!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:6px!important;padding:10px!important;border:1px solid var(--line)!important;border-radius:14px!important;background:linear-gradient(145deg,rgba(14,23,50,.98),rgba(5,9,24,.98))!important;box-shadow:var(--shadow)!important;backdrop-filter:blur(18px)!important}
  .hud-stats.mobile-open{display:grid!important}.hud-stat{display:block!important;padding:8px!important;border:1px solid rgba(128,161,229,.11)!important;border-radius:9px!important;background:rgba(71,96,158,.08)!important}.hud-stat label{font-size:.52rem!important}.hud-stat b{font-size:.78rem!important}
  .mobile-popover{position:fixed;z-index:76;right:8px;top:calc(max(6px,env(safe-area-inset-top)) + 56px);min-width:174px;padding:7px;border:1px solid var(--line);border-radius:13px;background:linear-gradient(145deg,rgba(14,23,50,.98),rgba(5,9,24,.98));box-shadow:var(--shadow);backdrop-filter:blur(18px)}
  .mobile-popover.mobile-open{display:grid;gap:5px}.mobile-popover button{min-height:44px;padding:8px 12px;border:1px solid rgba(120,161,255,.18);border-radius:9px;background:rgba(72,97,159,.12);text-align:left;font-weight:800;cursor:pointer}
  .right-panel{display:none!important;z-index:74!important}.right-panel.mobile-open{display:flex!important;flex-direction:column!important;position:fixed!important;left:8px!important;right:8px!important;top:calc(max(6px,env(safe-area-inset-top)) + 56px)!important;width:auto!important;max-height:min(70vh,520px)!important;border-radius:15px!important;background:linear-gradient(145deg,rgba(14,23,50,.98),rgba(5,9,24,.98))!important;box-shadow:var(--shadow)!important}.right-panel.mobile-open .events{max-height:none!important;overflow:auto!important;overscroll-behavior:contain!important}
  .bottombar{left:8px!important;right:8px!important;bottom:max(6px,env(safe-area-inset-bottom))!important;min-height:48px!important;height:48px!important;padding:6px 8px!important;border-radius:13px!important;gap:8px!important}.clock-row{font-size:.56rem!important}.clock-track{height:5px!important;margin-top:4px!important}.speed-btn{height:34px!important;min-width:32px!important}.hint,.perf{display:none!important}
  .modal-wrap{padding:max(8px,env(safe-area-inset-top)) 8px max(8px,env(safe-area-inset-bottom))!important}.command-panel,.rivals-panel,.news-panel{max-height:calc(100dvh - 16px - env(safe-area-inset-top) - env(safe-area-inset-bottom))!important;overflow:auto!important;overscroll-behavior:contain!important}.command-grid{grid-template-columns:1fr!important}.command-card{min-height:0!important}.command-head{gap:8px!important}.command-head h2{font-size:1.15rem!important}.command-footer{position:sticky;bottom:0;padding-top:8px;background:linear-gradient(transparent,rgba(5,8,20,.98) 28%)}.rival-grid,.fleet-grid{grid-template-columns:1fr!important}.hub-tabs{overflow-x:auto!important;white-space:nowrap!important}.start-card{max-height:calc(100dvh - 16px)!important;overflow:auto!important}.living-start-grid{grid-template-columns:1fr!important;min-height:0!important}.start-visual{display:none!important}.living-start .start-copy{padding:28px 20px!important}.living-start h1{font-size:clamp(2.8rem,15vw,4.5rem)!important}
}
@media(max-width:900px) and (orientation:landscape){
  .left-panel{display:flex!important;left:8px!important;right:auto!important;top:calc(max(6px,env(safe-area-inset-top)) + 56px)!important;bottom:calc(max(6px,env(safe-area-inset-bottom)) + 54px)!important;width:min(28vw,240px)!important;height:auto!important;transform:none!important;border-radius:14px!important}.left-panel .panel-head{padding:9px 10px 7px!important}.left-panel .panel-head h2{font-size:.93rem!important;margin:3px 0 1px!important}.left-panel .subtle{font-size:.58rem!important}.left-panel .planet-body{padding:7px 8px 10px!important}.left-panel .owner-row{margin-bottom:6px!important}.left-panel .owner-chip,.left-panel .status-chip{font-size:.55rem!important;padding:4px 6px!important}.left-panel .planet-identity{padding:7px 8px!important;margin-bottom:6px!important}.left-panel .planet-identity b{font-size:.7rem!important}.left-panel .planet-identity small{font-size:.52rem!important}.left-panel .metric-grid{gap:4px!important;margin:6px 0!important}.left-panel .metric{padding:6px!important}.left-panel .metric label{font-size:.47rem!important}.left-panel .metric b{font-size:.64rem!important}.left-panel .section-label{margin:8px 0 4px!important;font-size:.51rem!important}.left-panel .resource-row,.left-panel .facility-row,.left-panel .order-row{padding:5px 6px!important;font-size:.58rem!important}.left-panel .project-row,.left-panel .dependency-card{padding:6px 7px!important}.left-panel .project-head strong,.left-panel .card-title strong{font-size:.61rem!important}.left-panel .project-desc,.left-panel .card-copy{font-size:.52rem!important}.left-panel .project-meta,.left-panel .dependency-meta{font-size:.48rem!important}
  .bottombar{left:calc(min(28vw,240px) + 16px)!important}
  .right-panel.mobile-open{left:auto!important;width:min(42vw,330px)!important}
}
@media(max-width:900px) and (orientation:portrait){
  .left-panel{display:flex!important;left:8px!important;right:8px!important;top:auto!important;bottom:calc(max(6px,env(safe-area-inset-bottom)) + 54px)!important;width:auto!important;height:clamp(190px,32vh,300px)!important;transform:none!important;border-radius:15px!important}.left-panel .panel-head{padding:8px 11px 6px!important}.left-panel .panel-head h2{font-size:1rem!important;margin:2px 0!important}.left-panel .subtle{font-size:.58rem!important}.left-panel .planet-body{padding:7px 9px 12px!important}.left-panel .metric-grid{grid-template-columns:repeat(3,1fr)!important;gap:4px!important;margin:6px 0!important}.left-panel .metric{padding:6px!important}.left-panel .metric label{font-size:.47rem!important}.left-panel .metric b{font-size:.64rem!important}.left-panel .section-label{margin:8px 0 4px!important}.left-panel .project-row,.left-panel .dependency-card{padding:7px 8px!important}.left-panel .project-desc{font-size:.56rem!important}
  .right-panel.mobile-open{bottom:calc(max(6px,env(safe-area-inset-bottom)) + 54px)!important;max-height:56vh!important}
}
@media(max-width:430px){.top-actions{gap:2px!important}.top-actions .icon-btn{width:38px!important;min-width:38px!important;height:38px!important}.hud-stats{grid-template-columns:repeat(2,minmax(0,1fr))!important}}
`;
document.head.appendChild(mobileStyle);

const mobileQuery=()=>window.matchMedia("(max-width: 900px)").matches;
const topActions=document.querySelector(".top-actions");
const rightPanel=document.querySelector(".right-panel");
const hudStats=document.querySelector(".hud-stats");

function makeMobileButton(id,label,title){const b=document.createElement("button");b.type="button";b.id=id;b.className="icon-btn mobile-only";b.textContent=label;b.title=title;b.setAttribute("aria-label",title);b.setAttribute("aria-expanded","false");return b}
const hudStatsBtn=makeMobileButton("mobileStatsBtn","▦","Empire status");
const planetNewsBtn=makeMobileButton("mobilePlanetNewsBtn","☷","Planet news");
const mobileMenuBtn=makeMobileButton("mobileMenuBtn","•••","More controls");
const mobileMenu=document.createElement("div");mobileMenu.id="mobileMenu";mobileMenu.className="mobile-popover";mobileMenu.innerHTML='<button type="button" data-mobile-action="home">⌂ Center on capital</button><button type="button" data-mobile-action="save">▣ Save game</button><button type="button" data-mobile-action="close">× Close menu</button>';
if(topActions){topActions.insertBefore(hudStatsBtn,topActions.firstChild);topActions.insertBefore(planetNewsBtn,hudStatsBtn.nextSibling);topActions.appendChild(mobileMenuBtn)}
document.body.appendChild(mobileMenu);

function setExpanded(btn,on){btn?.setAttribute("aria-expanded",on?"true":"false")}
function closeMobilePopups(except=null){if(except!==hudStats){hudStats?.classList.remove("mobile-open");setExpanded(hudStatsBtn,false)}if(except!==rightPanel){rightPanel?.classList.remove("mobile-open");setExpanded(planetNewsBtn,false)}if(except!==mobileMenu){mobileMenu.classList.remove("mobile-open");setExpanded(mobileMenuBtn,false)}}
function toggleMobilePopup(panel,btn){if(!mobileQuery())return;const opening=!panel.classList.contains("mobile-open");closeMobilePopups(opening?panel:null);panel.classList.toggle("mobile-open",opening);setExpanded(btn,opening)}
hudStatsBtn.onclick=e=>{e.stopPropagation();toggleMobilePopup(hudStats,hudStatsBtn)};
planetNewsBtn.onclick=e=>{e.stopPropagation();toggleMobilePopup(rightPanel,planetNewsBtn)};
mobileMenuBtn.onclick=e=>{e.stopPropagation();toggleMobilePopup(mobileMenu,mobileMenuBtn)};
mobileMenu.onclick=e=>{const action=e.target.closest("[data-mobile-action]")?.dataset.mobileAction;if(!action)return;if(action==="home")$("homeBtn")?.click();else if(action==="save")$("saveBtn")?.click();closeMobilePopups()};
document.addEventListener("pointerdown",e=>{if(!mobileQuery())return;const target=e.target;if(hudStats?.classList.contains("mobile-open")&&!hudStats.contains(target)&&target!==hudStatsBtn)closeMobilePopups();else if(rightPanel?.classList.contains("mobile-open")&&!rightPanel.contains(target)&&target!==planetNewsBtn)closeMobilePopups();else if(mobileMenu.classList.contains("mobile-open")&&!mobileMenu.contains(target)&&target!==mobileMenuBtn)closeMobilePopups()},true);
window.addEventListener("keydown",e=>{if(e.key==="Escape")closeMobilePopups()});
function syncMobileLayout(){if(!mobileQuery())closeMobilePopups();else{document.documentElement.style.setProperty("--mobile-vh",`${window.innerHeight*.01}px`);closeMobilePopups()}}
window.addEventListener("resize",syncMobileLayout);window.addEventListener("orientationchange",()=>setTimeout(syncMobileLayout,0));syncMobileLayout();

/* Touch-only pointer handling replaces the core's single-pointer drag while preserving mouse controls. */
const touchPointers=new Map();let touchDrag=null,pinch=null,pinchUsed=false;
function touchMidpoint(){const pts=[...touchPointers.values()];if(pts.length<2)return null;return{x:(pts[0].x+pts[1].x)/2,y:(pts[0].y+pts[1].y)/2}}
function touchDistance(){const pts=[...touchPointers.values()];if(pts.length<2)return 0;return Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y)}
function beginPinch(){const mid=touchMidpoint(),distance=touchDistance();if(!mid||distance<=0)return;const anchor=screenToWorld(mid.x,mid.y);pinch={distance,zoom:state.camera.zoom,anchor};touchDrag=null;pinchUsed=true;canvas.classList.remove("dragging")}
function selectFromTouch(x,y){const w=screenToWorld(x,y),n=state.planets.filter(p=>Math.hypot(p.x-w.x,p.y-w.y)<Math.max(34,p.r+18)/state.camera.zoom).sort((a,b)=>Math.hypot(a.x-w.x,a.y-w.y)-Math.hypot(b.x-w.x,b.y-w.y))[0];if(n){state.selected=n;n.intel=Math.min(1,n.intel+.1);renderPlanet();$("leftPanel")?.classList.add("open")}}
canvas.addEventListener("pointerdown",e=>{if(e.pointerType!=="touch")return;e.preventDefault();e.stopImmediatePropagation();touchPointers.set(e.pointerId,{x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false});try{canvas.setPointerCapture(e.pointerId)}catch{}if(touchPointers.size===1){pinchUsed=false;touchDrag={id:e.pointerId,x:e.clientX,y:e.clientY,cx:state.camera.x,cy:state.camera.y,moved:false};canvas.classList.add("dragging")}else if(touchPointers.size===2)beginPinch()},true);
canvas.addEventListener("pointermove",e=>{if(e.pointerType!=="touch"||!touchPointers.has(e.pointerId))return;e.preventDefault();e.stopImmediatePropagation();const p=touchPointers.get(e.pointerId);p.x=e.clientX;p.y=e.clientY;if(Math.hypot(p.x-p.startX,p.y-p.startY)>4)p.moved=true;if(touchPointers.size>=2){if(!pinch)beginPinch();const mid=touchMidpoint(),distance=touchDistance();if(pinch&&mid&&distance>0){const zoom=clamp(pinch.zoom*(distance/pinch.distance),.22,2.15);state.camera.zoom=zoom;state.camera.x=clamp(pinch.anchor.x-(mid.x-innerWidth/2)/zoom,0,WORLD.w);state.camera.y=clamp(pinch.anchor.y-(mid.y-innerHeight/2)/zoom,0,WORLD.h)}return}if(touchDrag&&touchDrag.id===e.pointerId&&!pinchUsed){const dx=e.clientX-touchDrag.x,dy=e.clientY-touchDrag.y;if(Math.hypot(dx,dy)>4)touchDrag.moved=true;state.camera.x=clamp(touchDrag.cx-dx/state.camera.zoom,0,WORLD.w);state.camera.y=clamp(touchDrag.cy-dy/state.camera.zoom,0,WORLD.h)}},true);
function finishTouchPointer(e){if(e.pointerType!=="touch"||!touchPointers.has(e.pointerId))return;e.preventDefault();e.stopImmediatePropagation();const p=touchPointers.get(e.pointerId),wasPinching=!!pinch||pinchUsed;touchPointers.delete(e.pointerId);if(touchPointers.size<2)pinch=null;if(touchPointers.size===1){const [id,left]=touchPointers.entries().next().value;touchDrag={id,x:left.x,y:left.y,cx:state.camera.x,cy:state.camera.y,moved:true}}else if(touchPointers.size===0){if(!wasPinching&&touchDrag&&!touchDrag.moved&&!p.moved)selectFromTouch(e.clientX,e.clientY);touchDrag=null;pinchUsed=false;canvas.classList.remove("dragging")}}
canvas.addEventListener("pointerup",finishTouchPointer,true);canvas.addEventListener("pointercancel",finishTouchPointer,true);
