const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const fs=require('fs'),http=require('http'),assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'../..');
const hook=`globalThis.__qb={get state(){return {playState,down,franchise,menuOpen,seriesOffense,seriesDefense,replay:!!replay,ballLive,gameTime,receivers,defenders,transition}},setupPlay,throwBall,beginCountdown,showMainMenu,resumeGame,trainReceiver,endMatchup,finishPlayAtSpot,resolveCatch,resolveDivingCatch,tryJuke,updateRunAfterCatch,updateJump,receiverNormalCatchDistance,checkpoint,saveFranchise,loadSlot,checkBallContact,checkEmergencyDiveCatch, centerThrowDirection,update, loop, get camera(){return camera}, get ball(){return ball},get ballVel(){return ballVel},get ballPrev(){return ballPrev},captureReplay,finishReplay,scheduleResult,markCatch,get frames(){return replayFrames},set(v){if(v.down!==undefined)down=v.down;if(v.state)playState=v.state;if(v.ballLive!==undefined)ballLive=v.ballLive;if(v.record!==undefined)replayRecording=v.record;if(v.eligible!==undefined)replayEligible=v.eligible;if(v.ballSpot!==undefined)ballSpotYards=v.ballSpot;if(v.seriesOffense!==undefined)seriesOffense=v.seriesOffense;if(v.seriesDefense!==undefined)seriesDefense=v.seriesDefense},advance(ms){gameTime+=ms;if(transition&&gameTime>=transition.at){const f=transition.fn;transition=null;f()}},runTransition(){if(transition){const f=transition.fn;transition=null;f()}}};\n`;
const server=http.createServer((req,res)=>{try{const path=root+req.url.split('?')[0];let data=fs.readFileSync(path);if(path.endsWith('/game.js'))data=data.toString().replace('})();',hook+'})();');res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(data)}catch{res.statusCode=404;res.end('missing')}});
(async()=>{await new Promise(r=>server.listen(8765,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.QB_CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/game/receiver-window-qb.html');await page.waitForFunction(()=>!!window.__qb);assert.deepEqual(errors,[]);assert.equal(await page.locator('#startLayer').isVisible(),true);
await page.click('#startBtn');assert.equal(await page.evaluate(()=>__qb.state.playState),'call');
await page.evaluate(()=>{__qb.set({down:3,ballSpot:12,seriesOffense:1});__qb.checkpoint()});await page.reload();await page.click('#startBtn');assert.equal(await page.evaluate(()=>__qb.state.down),3);assert.equal(await page.evaluate(()=>__qb.state.seriesOffense),1);
// Menus pause time and prevent reset/hotkeys from altering play state.
await page.click('#menuBtn');let frozen=await page.evaluate(()=>__qb.state.gameTime);await page.keyboard.press('r');assert.equal(await page.evaluate(()=>__qb.state.down),3);assert.equal(await page.evaluate(()=>__qb.state.gameTime),frozen);
// New game occupies another slot, loading restores the old one.
await page.click('#newGameBtn');assert.equal(await page.evaluate(()=>__qb.state.franchise.round),1);await page.click('#savesBtn');await page.locator('#saveSlots button').first().click();await page.click('#startBtn');assert.equal(await page.evaluate(()=>__qb.state.down),3);
// Training athleticism and size changes physics; capped training does not spend cash.
await page.evaluate(()=>{const f=__qb.state.franchise;f.cash=10000;const p=f.team[0];p.athleticism=50;p.size=50;p.trainingByStat.athleticism=0;__qb.trainReceiver(0,'athleticism');if(p.athleticism<=50)throw Error('ATH did not improve');p.size=100;__qb.setupPlay();const r=__qb.state.receivers[0];if(r.mesh.scale.y<=p.appearance.scaleY)throw Error('size did not grow');p.trainingByStat.athleticism=5;const cash=f.cash;__qb.trainReceiver(0,'athleticism');if(f.cash!==cash)throw Error('training cap spent cash')});
// Every completed loss pays once and waits at the manager.
await page.evaluate(()=>{const f=__qb.state.franchise;const cash=f.cash;__qb.endMatchup(false);if(f.cash<=cash)throw Error('no loss payout');const paid=f.cash;__qb.runTransition();if(f.cash!==paid)throw Error('double payout');});
await page.click('#continueBtn');
// Replay eligibility, frozen score, behind-ball camera and restored pose.
await page.evaluate(()=>{__qb.set({record:true,eligible:true,state:'thrown'});__qb.ball.visible=true;for(let i=0;i<12;i++){__qb.ball.position.set(0,2+i*.05,20-i);__qb.captureReplay(true)}const cash=__qb.state.franchise.cash;__qb.set({state:'dead'});__qb.scheduleResult(()=>{window.replayCompleted=true},0);__qb.runTransition();if(!__qb.state.replay)throw Error('no replay');window.replayCash=cash;});
await page.waitForFunction(()=>__qb.camera.position.z>__qb.ball.position.z);await page.click('#skipReplay');assert.equal(await page.evaluate(()=>window.replayCompleted),true);assert.equal(await page.evaluate(()=>__qb.state.franchise.cash===window.replayCash),true);
// Juke visibly changes momentum and fools nearby defenders, with a cooldown.
await page.evaluate(()=>{__qb.setupPlay();const [r]=__qb.state.receivers,[d]=__qb.state.defenders;d.mesh.position.copy(r.mesh.position).add(new THREE.Vector3(0,0,-2));r.profile.tricks=100;r.profile.evasion=100;const original=Math.random;Math.random=()=>0;try{if(!__qb.tryJuke(r))throw Error('juke failed');if(!(d.fakeUntil>__qb.state.gameTime))throw Error('defender not fooled');if(__qb.tryJuke(r))throw Error('no cooldown')}finally{Math.random=original}});
// Input focus must preserve cloud password and not start/reset plays.
await page.click('#menuBtn');await page.click('#savesBtn');await page.fill('#cloudPassword','r X 1234');assert.equal(await page.inputValue('#cloudPassword'),'r X 1234');assert.equal(await page.evaluate(()=>__qb.state.playState),'call');
// Original clean catches, elevated catches, rescue-only dives and interceptions.
await page.evaluate(()=>{
  const q=__qb;
  const arrange=()=>{q.setupPlay();q.set({state:'thrown',ballLive:true});const r=q.state.receivers[0];for(const d of q.state.defenders)d.mesh.position.set(100,0,100);for(const other of q.state.receivers.slice(1))other.mesh.position.set(100,0,100);r.trackingBall=true;r.catchPose=1;return r};
  const original=Math.random;Math.random=()=>0;
  try{
    let r=arrange();q.ball.position.copy(r.mesh.position).add(new THREE.Vector3(0,1.34*r.mesh.scale.y,0));q.ballPrev.copy(q.ball.position);if(!q.checkBallContact()||q.state.playState!=='run')throw Error('clean catch regression');
    r=arrange();r.profile.athleticism=100;r.profile.size=100;r.mesh.scale.set(1.1,1.2,1.1);r.jumpY=.8;r.mesh.position.y=.8;q.ball.position.copy(r.mesh.position).add(new THREE.Vector3(0,1.82*r.mesh.scale.y,0));q.ballPrev.copy(q.ball.position);if(!q.checkBallContact()||q.state.playState!=='run')throw Error('high catch failed');
    r=arrange();r.profile.athleticism=100;r.profile.catching=100;r.heading.set(1,0,0);q.ball.position.copy(r.mesh.position).add(new THREE.Vector3(1.75,.2,0));q.ballPrev.copy(q.ball.position);if(!q.checkBallContact()||q.state.playState!=='divecatch')throw Error('rescue dive failed');
    q.setupPlay();q.set({state:'thrown',ballLive:true});const d=q.state.defenders[0];for(const r of q.state.receivers)r.mesh.position.set(100,0,100);d.ballSeen=true;q.ball.position.copy(d.mesh.position).add(new THREE.Vector3(0,1.34*d.mesh.scale.y,0));q.ballPrev.copy(q.ball.position);const before=q.state.seriesDefense;if(!q.checkBallContact()||q.state.seriesDefense!==before+1)throw Error('interception did not award series');
    q.setupPlay();q.set({down:4});q.throwBall();if(q.state.playState!=='thrown')throw Error('throw failed');
  }finally{Math.random=original}
});
assert.deepEqual(errors,[]);
for(const [width,height] of [[390,844],[844,390]]){await page.setViewportSize({width,height});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('#closeSaves').isVisible(),true)}
console.log('PASS: startup, save migration/slots/checkpoint reload, pause/input gating, progression, payout, replay isolation, juke cooldown, clean/high/diving catches, interceptions, mobile overflow.');await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
