const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm'),fs=require('node:fs'),{webcrypto}=require('node:crypto');const P=require('./progression.js');
function context(){
  const records=new Map();let writes=0;const fb={db:{},doc:(db,collection,id)=>{assert.equal(collection,'lobbies');assert.match(id,/^receiver-window-qb-save--/);return id},getDoc:async id=>({exists:()=>records.has(id),data:()=>records.get(id)}),setDoc:async(id,record)=>{writes++;records.set(id,record)},Bytes:{fromUint8Array:x=>x},serverTimestamp:()=>123};
  const c=vm.createContext({QBProgression:P,crypto:webcrypto,TextEncoder,TextDecoder,Uint8Array,Blob,Response,CompressionStream,DecompressionStream,fake:fb});
  const source=fs.readFileSync(__dirname+'/cloud-save.js','utf8').replace('async function awCloudFirebase(){','async function awCloudFirebase(){return fake;');vm.runInContext(source,c);return {api:c.QBCloud,records,get writes(){return writes}};
}
function fixture(){const player=()=>P.migratePlayer({name:'Receiver',speed:60,cutting:60,turning:60,evasion:60,catching:60,strength:60});return{cash:345,round:4,wins:3,team:Array.from({length:4},player),market:Array.from({length:5},player)}}
test('encrypted Firebase record round trips through Arcane Wilds rules surface',async()=>{const c=context(),f=fixture();await c.api.save(' My Team ','pass123',f);const record=[...c.records.values()][0];assert.equal(record.gameType,'receiver-window-qb-cloud-save');assert.equal(record.iterations,210000);assert.equal(record.cipher,'AES-GCM-256');assert.ok(record.payload instanceof Uint8Array);assert.equal(JSON.stringify(record).includes('pass123'),false);const restored=await c.api.load('my team','pass123');assert.deepEqual(restored,P.validateSave(f));});
test('wrong password blocks both restore and overwrite, without writing a new record',async()=>{const c=context();await c.api.save('team','correct',fixture());await assert.rejects(c.api.load('team','wrong'));await assert.rejects(c.api.save('team','wrong',fixture()));assert.equal(c.writes,1);});
test('missing saves and malformed payloads fail safely',async()=>{const c=context();await assert.rejects(c.api.load('missing','password'));await c.api.save('team','password',fixture());[...c.records.values()][0].iterations=1;await assert.rejects(c.api.load('team','password'));});
