/* Franchise screens use the same game data and controls as the field. */
(function(root){
'use strict';
const F=root.QBFranchise,$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>(Number(v)||0).toLocaleString(undefined,{maximumFractionDigits:1});
function uniformSVG(identity,kit,number='11'){
 return `<svg class="uniformPortrait" viewBox="0 0 180 230" role="img" aria-label="${esc(identity.name)} uniform"><ellipse cx="90" cy="220" rx="54" ry="7" fill="#000" opacity=".22"/><path d="M52 33Q53 4 90 4Q128 4 128 33L123 60H57Z" fill="${kit.helmet}"/><path d="M58 39H125V56H67Z" fill="#172332" stroke="${kit.secondary}" stroke-width="4"/><text x="90" y="32" font-size="24" text-anchor="middle">${esc(identity.logo)}</text><path d="M60 65L29 80L16 118L44 126L53 105V148H127V105L138 126L166 118L150 80L120 65Z" fill="${kit.jersey}"/><path d="M34 80L49 90M132 89L148 81" stroke="${kit.secondary}" stroke-width="10"/><text x="90" y="121" text-anchor="middle" font-size="38" font-weight="900" fill="${kit.number}">${esc(number)}</text><text x="113" y="86" text-anchor="middle" font-size="12">${esc(identity.logo)}</text><path d="M53 148H127L121 186H96L90 157L84 186H58Z" fill="${kit.pants}"/><path d="M57 149L63 181M122 149L117 181" stroke="${kit.accent}" stroke-width="5"/><path d="M61 186V209H81V186M100 186V209H120V186" fill="${kit.socks}"/><path d="M60 205H81V218H44Q43 207 60 205M100 205H120Q137 207 137 218H100Z" fill="${kit.shoes}"/><path d="M45 216H81M100 216H136" stroke="${kit.accent}" stroke-width="3"/></svg>`;
}
function diagram(play,index,paths){
 const primary=F.primary(play),palette=['#62d9ff','#ffd166','#7cffae','#ff82c6'];
 const x=v=>12+(v+26)*3.35,y=v=>174-(30-v)*2.5;
 let art='<rect x="1" y="1" width="198" height="194" rx="12" fill="#12352f"/>';
 for(let row=25;row<190;row+=25)art+=`<path d="M8 ${row}H192" stroke="#e9fff1" opacity=".13"/>`;
 art+='<path d="M8 174H192" stroke="#6fb5ee" opacity=".65"/>';
 paths.forEach((points,i)=>{const route=play.routes[i],block=route==='Lead',pts=points.map(p=>`${x(p.x).toFixed(1)},${Math.max(10,Math.min(187,y(p.z))).toFixed(1)}`).join(' '),last=points.at(-1),start=points[0],endX=x(last.x),endY=Math.max(10,Math.min(187,y(last.z)));
 art+=`<polyline points="${pts}" fill="none" stroke="${palette[i]}" stroke-width="${i===primary?3:1.8}" ${block?'stroke-dasharray="3 3"':''}/><circle cx="${x(start.x)}" cy="${y(start.z)}" r="${i===primary?6:4}" fill="${palette[i]}"/><text x="${x(start.x)}" y="${y(start.z)+16}" text-anchor="middle" font-size="10" fill="white">${['X','H','Y','Z'][i]}</text>`;
 if(block)art+=`<path d="M${endX-5} ${endY}h10" stroke="${palette[i]}" stroke-width="3"/>`;
 else art+=`<path d="M${endX-3} ${endY+5}l3 -5 3 5" fill="none" stroke="${palette[i]}" stroke-width="2"/>`;
 if(root.QBVariety.isOption(route))art+=`<path d="M${endX-15} ${endY}h30" stroke="${palette[i]}" stroke-dasharray="4 3"/><text x="${endX}" y="${endY-6}" fill="white" font-size="10">?</text>`;
 });
 for(const motion of root.QBVariety.motions(play)){
   const start={x:(play.xs||[-18,-6,6,18])[motion.slot],z:30+(play.depths?.[motion.slot]??(motion.slot%2)*.35)},points=root.QBVariety.motionPath(motion,start);
   art+=`<polyline points="${points.map(p=>`${x(p.x).toFixed(1)},${Math.min(191,y(p.z)+3).toFixed(1)}`).join(' ')}" fill="none" stroke="white" stroke-dasharray="4 3" stroke-width="2"/><circle cx="${x(start.x)}" cy="${y(start.z)+3}" r="3" fill="none" stroke="white"/>`;
 }

 return `<svg class="playDiagram" viewBox="0 0 200 196" role="img" aria-label="${esc(play.name)} routes. Primary ${['X','H','Y','Z'][primary]}. Dashed routes show blocks, options or pre-snap motion.">${art}</svg>`;
}
function qbHTML(book){const q=book.qb;return `<div class="metricGrid">${[['COMP / ATT',`${q.completions} / ${q.attempts}`],['COMP %',q.attempts?n(q.completions/q.attempts*100)+'%':'—'],['PASS YARDS',n(q.yards)],['TD / INT',`${q.touchdowns} / ${q.interceptions}`],['YARDS / ATT',q.attempts?n(q.yards/q.attempts):'—'],['LONG',n(book.longest)]].map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('')}</div>`;}
const statNames={targets:'Targets',catches:'Catches',yards:'Yards',touchdowns:'TD',yac:'YAC',drops:'Drops',contested:'Contested',brokenTackles:'Broken tackles',stiffArms:'Stiff arms',hurdles:'Hurdles',jukes:'Jukes',blocks:'Blocks'};
function receiversHTML(book){return `<div class="statTableWrap"><table class="statTable"><thead><tr><th scope="col">Receiver</th>${F.receiverKeys.map(k=>`<th scope="col">${statNames[k]}</th>`).join('')}<th scope="col">Yds / catch</th></tr></thead><tbody>${Object.values(book.receivers).sort((a,b)=>b.yards-a.yards).map(r=>`<tr><th scope="row">${esc(r.name)}</th>${F.receiverKeys.map(k=>`<td>${n(r[k])}</td>`).join('')}<td>${r.catches?n(r.yards/r.catches):'—'}</td></tr>`).join('')||'<tr><td colspan="14">Complete a play to begin your franchise history.</td></tr>'}</tbody></table></div>`;}
function create(ctx){
 let open=false,returnFocus=null,tab='Suggested',draft=null,editKit='home';
 const f=()=>ctx.franchise();
 function close(){open=false;$('franchiseLayer').hidden=true;returnFocus?.focus();}
 function modal(title,html){if(!open)returnFocus=document.activeElement;open=true;ctx.pauseInput();$('franchiseTitle').textContent=title;$('franchiseContent').innerHTML=html;$('franchiseLayer').hidden=false;$('closeFranchise').focus();}
 $('closeFranchise').onclick=close;
 document.addEventListener('keydown',e=>{if(open&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close();}},true);
 function matchup(round){const own=f().identity,other={...F.opponent(round),name:ctx.opponent(round).name},record=f().opponentResults[round],top=[...f().team].sort((a,b)=>ctx.overall(b)-ctx.overall(a))[0],def=ctx.defense(round);
 return `<div class="matchupTeams"><article><div class="teamKicker">YOUR FRANCHISE</div><h3>${esc(own.logo)} ${esc(own.name)}</h3>${uniformSVG(own,own[own.active])}<p>${f().wins} W · ${f().losses||0} L</p><small>TOP RECEIVER · ${esc(top.name)} · ${ctx.overall(top)} OVR</small></article><div class="versus">VS</div><article><div class="teamKicker">ROUND ${round}</div><h3>${esc(other.logo)} ${esc(other.name)}</h3>${uniformSVG(other,other,'24')}<p>${esc(def.name)}</p><small>${def.strength>5?'Heavy hitters':def.strength<0?'Finesse tacklers':'Balanced tackling'} · ${def.speed>.1?'Fast secondary':'Measured pursuit'}</small><p class="meetingRecord">Previous meetings: ${record?.wins??(round<f().round?1:0)} W · ${record?.losses||0} L</p></article></div>`;}
 function hub(){const own=f().identity,round=ctx.round(),other=F.opponent(round),q=f().career.qb,last=f().lastGame;
 $('franchiseHub').innerHTML=`<div class="hubEyebrow">FRANCHISE ${ctx.slot()+1} · ROUND ${round}</div><div class="hubMatchup"><div><span class="teamKicker">NEXT MATCHUP</span><h2>${esc(own.logo)} ${esc(own.name)}<span>vs ${esc(other.logo)} ${esc(ctx.opponent(round).name)}</span></h2><p>${esc(ctx.defense(round).name)} · ${round<f().round?'REMATCH · 20% PRIZE':'CAMPAIGN'}</p></div>${uniformSVG(own,own[own.active])}</div><div class="metricGrid"><div><small>CASH</small><strong>$${n(f().cash)}</strong></div><div><small>RECORD</small><strong>${f().wins}–${f().losses||0}</strong></div><div><small>CAREER YARDS</small><strong>${n(q.yards)}</strong></div><div><small>PASSING TD</small><strong>${q.touchdowns}</strong></div></div><div class="hubBottom"><span>${last?`LAST RESULT · ${last.won?'WIN':'LOSS'} ${last.score.join('–')} vs ${esc(last.opponent)}`:'Your franchise story starts with the next snap.'}</span><span>${f().team.map(p=>esc(p.name.split(' ').at(-1))+' '+ctx.overall(p)).join(' · ')}</span></div>`;
 }
 function manager(round){$('matchupPreview').innerHTML=matchup(round);const last=f().lastGame;$('lastGameSummary').innerHTML=last?`<details><summary>LAST GAME · ${last.won?'WIN':'LOSS'} ${last.score.join('–')} vs ${esc(last.opponent)} — box score</summary>${qbHTML(last)}${receiversHTML(last)}</details>`:'';}
 function uniform(){
  if(!ctx.canCustomize()){modal('Uniform Designer','<p>Finish the current play to edit your uniform. Your home and away designs are saved with this franchise.</p>');return;}
  draft=F.identity(f().identity);editKit=draft.active;renderUniform();
 }
 function renderUniform(){
  modal('Uniform Designer',`<div class="designerLayout"><div><div id="uniformPreview">${uniformSVG(draft,draft[editKit])}</div><p class="tinyNote">Helmet emblems, chest logo and jersey numbers carry onto the field.</p></div><div class="designerFields"><label>Franchise name<input id="uniformName" maxlength="32" value="${esc(draft.name)}"></label><div class="studioTabs">${['home','away'].map(k=>`<button data-kit="${k}" aria-pressed="${k===editKit}" class="${k===editKit?'selected':''}">${k.toUpperCase()}</button>`).join('')}</div><div class="colorGrid">${F.colors.map(k=>`<label>${k[0].toUpperCase()+k.slice(1)}<input type="color" data-color="${k}" aria-label="${k} color" value="${draft[editKit][k]}"></label>`).join('')}</div><label>Game uniform<select id="activeUniform"><option value="home" ${draft.active==='home'?'selected':''}>Home</option><option value="away" ${draft.active==='away'?'selected':''}>Away</option></select></label><div class="teamKicker">TEAM EMBLEM</div><div class="emojiGrid">${F.logos.map(e=>`<button data-logo="${e}" aria-label="Team logo ${e}" aria-pressed="${draft.logo===e}">${e}</button>`).join('')}</div><details><summary>More emblems</summary><div class="emojiGrid">${F.moreLogos.map(e=>`<button data-logo="${e}" aria-label="Team logo ${e}">${e}</button>`).join('')}</div></details><label>Or paste an emoji<input id="customEmoji" maxlength="24" value="${esc(draft.logo)}"></label><p id="uniformStatus" role="status"></p><button id="saveUniform" class="primary">SAVE UNIFORMS</button></div></div>`);
  const refresh=()=>$('uniformPreview').innerHTML=uniformSVG(draft,draft[editKit]);
  $('uniformName').oninput=e=>{draft.name=e.target.value;refresh();};$('activeUniform').onchange=e=>draft.active=e.target.value;
  document.querySelectorAll('[data-kit]').forEach(b=>b.onclick=()=>{editKit=b.dataset.kit;renderUniform();document.querySelector(`[data-kit="${editKit}"]`).focus();});
  document.querySelectorAll('[data-color]').forEach(b=>b.oninput=()=>{draft[editKit][b.dataset.color]=b.value;refresh();});
  document.querySelectorAll('[data-logo]').forEach(b=>b.onclick=()=>{draft.logo=b.dataset.logo;$('customEmoji').value=draft.logo;document.querySelectorAll('[data-logo]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.logo===draft.logo)));refresh();});
  $('customEmoji').oninput=e=>{const logo=F.emoji(e.target.value,'');if(logo){draft.logo=logo;refresh();$('uniformStatus').textContent='';}else $('uniformStatus').textContent='Choose or paste one emoji.';};
  $('saveUniform').onclick=()=>{if(!ctx.canCustomize())return;f().identity=F.identity(draft);ctx.save();ctx.refreshUniform();hub();$('uniformStatus').textContent='Home and away uniforms saved.';};
 }
 function records(){const labels={longestCompletion:'Longest completion',longestTouchdown:'Longest touchdown',mostYac:'Most YAC on one play',receivingGame:'Receiving yards in a game',touchdownGame:'Receiving TD in a game',brokenTacklesGame:'Broken tackles in a game',winStreak:'Longest win streak',highestScore:'Highest score'};
 const defeated=Math.max(f().round-1,Object.values(f().opponentResults).filter(r=>r.wins>0).length);
 modal('Franchise Records',`<p class="tinyNote">Statistics begin with this upgrade. Existing wins, opponents and roster progress are preserved.</p>${qbHTML(f().career)}<div class="recordsGrid">${F.recordKeys.map(k=>`<article><small>${labels[k]}</small><strong>${n(f().records[k].value)}</strong><span>${esc(f().records[k].name)}</span></article>`).join('')}<article><small>Opponents defeated</small><strong>${defeated}</strong></article><article><small>Career catches</small><strong>${Object.values(f().career.receivers).reduce((s,r)=>s+r.catches,0)}</strong></article></div><h3>Receiver careers</h3>${receiversHTML(f().career)}<h3>Current matchup</h3>${qbHTML(f().currentGame)}${receiversHTML(f().currentGame)}`);
 }
 function player(id){const p=f().team.find(p=>p.id===id);if(!p)return;const book=F.box();if(f().career.receivers[id])book.receivers[id]=f().career.receivers[id];modal(p.name,`<div class="playerDetailHero">${uniformSVG(f().identity,f().identity[f().identity.active],11+f().team.indexOf(p)*7)}<div><h3>${ctx.overall(p)} OVR · ${esc(ctx.style(p))}</h3><p>Football IQ ${F.awareness(p)} · Chemistry ${F.chemistryLevel(p)} / 100</p><p>Familiar routes sharpen timing gradually. Chemistry adds at most 2% to timing and tracking.</p><div class="traitBadges">${traits(p)}</div></div></div>${receiversHTML(book)}<h3>Favorite concepts</h3><p>${Object.entries(p.chemistry.concepts).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([k,v])=>`${esc(k)} (${v})`).join(' · ')||'Complete plays together to build familiarity.'}</p>`);}
 function traits(p){return [['speed','⚡ Elite Speed'],['evasion','🌀 Elite Evasion'],['strength','💪 Power'],['catching','🙌 Sure Hands'],['athleticism','🚀 High Flyer'],['cutting','✂️ Precision Cuts']].filter(([k])=>p[k]>=90).map(([,label])=>`<span>${label}</span>`).join('')||`<span>${esc(ctx.style(p))}</span>`;}
 function playbook(){const all=ctx.plays(),situation=ctx.situation(),ranked=all.map((p,i)=>({i,...F.suggestion(p,situation)})).sort((a,b)=>b.score-a.score).slice(0,6),selected=ctx.selected();
 modal('Playbook',`<div class="studioTabs">${['Suggested',...ctx.categories()].map(c=>`<button data-studio-category="${c}" class="${c===tab?'selected':''}">${c}</button>`).join('')}</div><p>${esc(F.suggestion(all[selected],situation).reason)}</p><div class="studioPlayLayout"><div class="studioPlayGrid">${all.map((p,i)=>({p,i})).filter(({p,i})=>tab==='Suggested'?ranked.some(r=>r.i===i):ctx.category(p)===tab).map(({p,i})=>`<button class="playBtn ${i===selected?'selected':''}" data-studio-play="${i}">${diagram(p,i,ctx.paths(p))}<span>${esc(p.name)}</span><small>PRIMARY ${['X','H','Y','Z'][F.primary(p)]}</small></button>`).join('')}</div><article class="playDetail">${detail(all[selected],selected)}<button id="callSelectedPlay" class="primary" ${ctx.canChoosePlay()?'':'disabled'}>USE THIS PLAY</button></article></div>`);
 document.querySelectorAll('[data-studio-category]').forEach(b=>b.onclick=()=>{tab=b.dataset.studioCategory;playbook();});document.querySelectorAll('[data-studio-play]').forEach(b=>b.onclick=()=>{ctx.previewPlay(Number(b.dataset.studioPlay));playbook();});$('callSelectedPlay').onclick=()=>{ctx.choosePlay(ctx.selected());close();};
 }
 function detail(p,i){const best=p.screen!=null?'YAC Specialist / Blocking Receiver':p.routes.some(r=>['Go','Fade','Post'].includes(r))?'Deep Threat / Possession Receiver':'Route Technician / Possession Receiver';return `<h3>${esc(p.name)}</h3>${diagram(p,i,ctx.paths(p))}<p><b>Primary:</b> ${['X','H','Y','Z'][F.primary(p)]} · <b>Best for:</b> ${best}</p><p>${esc(p.hint||'Read the coverage and use the open receiver.')}</p><small>Solid = route · dashed = block / option · white dashed = motion</small>`;}
 return {get isOpen(){return open;},close,hub,manager,uniform,records,player,traits,playbook,detail,diagram:(p,i)=>diagram(p,i,ctx.paths(p))};
}
root.QBFranchiseUI={create,diagram,uniformSVG};
})(globalThis);
