const PLAYER_URL='https://api.sleeper.app/v1/players/nfl?active=true';
const STATE_URL='https://api.sleeper.app/v1/state/nfl';
const FFC_URL=(format,teams,year)=>`https://fantasyfootballcalculator.com/api/v1/adp/${format}?teams=${teams}&year=${year}&position=all`;
const PLAYER_WEEK_URL=(id,year)=>`https://api.sleeper.com/stats/nfl/player/${encodeURIComponent(id)}?season=${year}&season_type=regular&grouping=week`;
const POS=['QB','RB','WR','TE'],FLEX_POS=['RB','WR','TE'];
const NFL_TEAMS=new Set(['ARI','ATL','BAL','BUF','CAR','CHI','CIN','CLE','DAL','DEN','DET','GB','HOU','IND','JAX','KC','LV','LAC','LAR','MIA','MIN','NE','NO','NYG','NYJ','PHI','PIT','SEA','SF','TB','TEN','WAS']);
const TEAM_COLORS={
ARI:['#97233F','#000000'],ATL:['#A71930','#000000'],BAL:['#241773','#9E7C0C'],BUF:['#00338D','#C60C30'],CAR:['#0085CA','#101820'],CHI:['#0B162A','#C83803'],CIN:['#FB4F14','#000000'],CLE:['#311D00','#FF3C00'],DAL:['#003594','#869397'],DEN:['#FB4F14','#002244'],DET:['#0076B6','#B0B7BC'],GB:['#203731','#FFB612'],HOU:['#03202F','#A71930'],IND:['#002C5F','#A2AAAD'],JAX:['#006778','#101820'],KC:['#E31837','#FFB81C'],LV:['#000000','#A5ACAF'],LAC:['#0080C6','#FFC20E'],LAR:['#003594','#FFA300'],MIA:['#008E97','#FC4C02'],MIN:['#4F2683','#FFC62F'],NE:['#002244','#C60C30'],NO:['#D3BC8D','#101820'],NYG:['#0B2265','#A71930'],NYJ:['#125740','#000000'],PHI:['#004C54','#A5ACAF'],PIT:['#101820','#FFB612'],SEA:['#002244','#69BE28'],SF:['#AA0000','#B3995D'],TB:['#D50A0A','#34302B'],TEN:['#0C2340','#4B92DB'],WAS:['#5A1414','#FFB612']
};
const DEFAULT_SETTINGS={teams:12,draftSlot:1,rounds:15,slots:{QB:1,RB:2,WR:2,TE:1,FLEX:2,BENCH:6}};
const STORE={draft:'ffcc-draft-v3',custom:'ffcc-custom-rankings-v2',scoring:'ffcc-scoring-v2',active:'ffcc-active-ranking-v2',settings:'ffcc-settings-v3',mode:'ffcc-mode-v2'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>Number.isFinite(+v)?+v:0,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fmt=(v,d=1)=>Number.isFinite(+v)?(+v).toFixed(d):'—';
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||structuredClone(f)}catch{return structuredClone(f)}};

let players=[],playerMap=new Map(),draft=load(STORE.draft,{mine:[],other:[],history:[]}),custom=load(STORE.custom,{}),scoring=localStorage.getItem(STORE.scoring)||'ppr',activeRanking=localStorage.getItem(STORE.active)||'base:ppr',settings=normalizeSettings(load(STORE.settings,DEFAULT_SETTINGS));
let appMode='rankings',seasonYear=new Date().getFullYear(),latestCompleteYear=seasonYear-1,seasonStatus='',adpFeeds={ppr:new Map(),half:new Map(),standard:new Map()},adpLoading=false,rankingWork=[],draggingId=null,currentProfileId=null,profileHistorySpan=1,weeklyCache=new Map(),profileToken=0;

function normalizeSettings(s){const out=structuredClone(DEFAULT_SETTINGS);if(s&&typeof s==='object'){out.teams=clamp(parseInt(s.teams)||12,4,20);out.draftSlot=clamp(parseInt(s.draftSlot)||1,1,out.teams);out.rounds=clamp(parseInt(s.rounds)||15,1,30);for(const k of Object.keys(out.slots))out.slots[k]=clamp(parseInt(s.slots?.[k])||0,0,20)}return out}
function persist(){localStorage.setItem(STORE.draft,JSON.stringify(draft));localStorage.setItem(STORE.custom,JSON.stringify(custom));localStorage.setItem(STORE.scoring,scoring);localStorage.setItem(STORE.active,activeRanking);localStorage.setItem(STORE.settings,JSON.stringify(settings));localStorage.setItem(STORE.mode,appMode)}
function idOf(p){return String(p?.player_id??'')}
function playerById(id){return playerMap.get(String(id))||null}
function normalizeName(name){return String(name||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(jr|sr|ii|iii|iv)\b/g,'').replace(/[^a-z0-9]/g,'')}
function eligible(){return players.filter(p=>POS.includes(p.position)&&p.full_name&&NFL_TEAMS.has(String(p.team||'').toUpperCase())&&p.active!==false&&!/retired/i.test(String(p.status||'')))}
function teamColors(team){return TEAM_COLORS[String(team||'').toUpperCase()]||['#18334f','#0e1b2d']}
function teamStyle(team){const [a,b]=teamColors(team);return`--team-primary:${a};--team-secondary:${b}`}
function labelMode(m){return m==='ppr'?'PPR':m==='half'?'Half PPR':'Standard'}
function rawSleeperRank(p){const r=Number(p.search_rank);return Number.isFinite(r)&&r>0?r:null}
function riskFor(p){const x=((p.injury_status||'')+' '+(p.status||'')+' '+(p.practice_participation||'')).toLowerCase();if(/suspend|reserve|injured reserve|\bir\b|out|nfi/.test(x))return'red';if(/question|doubt|pup|limited|probable|day-to-day/.test(x))return'yellow';return'green'}
function riskLabel(p){const r=riskFor(p);if(r==='red')return p.injury_status||p.status||'Unavailable';if(r==='yellow')return p.injury_status||p.practice_participation||p.status||'Monitor';return'Clear'}
function playerAge(p){if(Number.isFinite(+p.age))return+p.age;if(p.birth_date){const d=new Date(p.birth_date);if(!isNaN(d))return Math.floor((Date.now()-d.getTime())/31557600000)}return null}
function individualRisk(p){let score=riskFor(p)==='red'?88:riskFor(p)==='yellow'?48:8,reasons=[];if(riskFor(p)!=='green')reasons.push(riskLabel(p));const age=playerAge(p);if(age!=null&&((p.position==='RB'&&age>=29)||(p.position==='WR'&&age>=31)||(p.position==='TE'&&age>=32)||(p.position==='QB'&&age>=37))){score+=12;reasons.push(`age ${age} at ${p.position}`)}const depth=num(p.depth_chart_order||p.depth_chart_position);if(depth>=3){score+=9;reasons.push('depth-chart competition')}return{score:clamp(score,0,100),reasons}}

function ffcKey(p){return normalizeName(p.full_name)}
function ffcAdp(p,mode){const v=adpFeeds[mode]?.get(ffcKey(p));return Number.isFinite(v)?v:null}
function compositeSignals(p,mode=scoring){const s=rawSleeperRank(p),ppr=ffcAdp(p,'ppr'),half=ffcAdp(p,'half'),std=ffcAdp(p,'standard');const weights=mode==='ppr'?{ppr:.55,half:.20,standard:.10,sleeper:.15}:mode==='half'?{ppr:.20,half:.50,standard:.15,sleeper:.15}:{ppr:.10,half:.15,standard:.60,sleeper:.15};const raw=[['FFC PPR',ppr,weights.ppr],['FFC Half',half,weights.half],['FFC Standard',std,weights.standard],['Sleeper',s,weights.sleeper]].filter(x=>Number.isFinite(x[1])&&x[1]>0);return raw}
function compositeValue(p,mode=scoring){const sig=compositeSignals(p,mode);if(!sig.length)return 9999;const w=sig.reduce((a,x)=>a+x[2],0);return sig.reduce((a,x)=>a+x[1]*x[2],0)/w}
function marketRange(p,mode=scoring){const vals=compositeSignals(p,mode).map(x=>x[1]);return vals.length?{lo:Math.min(...vals),hi:Math.max(...vals)}:{lo:null,hi:null}}
function directFfcAdp(p,mode=scoring){return ffcAdp(p,mode)}
function baseOrder(mode=scoring){return eligible().slice().sort((a,b)=>compositeValue(a,mode)-compositeValue(b,mode)||(rawSleeperRank(a)||9999)-(rawSleeperRank(b)||9999)||a.full_name.localeCompare(b.full_name)).map(idOf)}
function rankingMeta(){if(activeRanking.startsWith('base:')){const m=activeRanking.split(':')[1]||scoring;return{name:`Composite ${labelMode(m)}`,mode:m,order:baseOrder(m),base:true}}const r=custom[activeRanking];if(r){const valid=new Set(eligible().map(idOf)),seen=new Set(),order=[];for(const id of r.order||[]){const s=String(id);if(valid.has(s)&&!seen.has(s)){seen.add(s);order.push(s)}}for(const id of baseOrder(r.mode||scoring))if(!seen.has(id))order.push(id);return{name:r.name||'Custom Board',mode:r.mode||scoring,order,base:false}}return{name:`Composite ${labelMode(scoring)}`,mode:scoring,order:baseOrder(scoring),base:true}}
function rankMap(){return new Map(rankingMeta().order.map((id,i)=>[String(id),i+1]))}
function sourceCount(){return 1+['ppr','half','standard'].filter(k=>adpFeeds[k].size).length}

function renderPlayerBlock(p,sub=''){return`<div class="playerBlock" style="${teamStyle(p.team)}" data-profile="${idOf(p)}"><span class="teamMark">${esc(p.team)}</span><span><span class="playerName">${esc(p.full_name)}</span><span class="playerMeta">${esc(sub||`${p.position} • ${p.team}`)}</span></span></div>`}
function renderStatus(p){return`<span class="status ${riskFor(p)}"><i class="dot"></i>${esc(riskLabel(p))}</span>`}
function renderRange(p){const r=marketRange(p),c=compositeValue(p);if(!Number.isFinite(r.lo)||!Number.isFinite(r.hi))return'<span class="sub">—</span>';const span=Math.max(1,r.hi-r.lo),left=clamp((c-r.lo)/Math.max(1,r.hi)*100,0,95),width=clamp(span/Math.max(30,r.hi)*100,8,100);return`<div class="marketStack"><b>${fmt(r.lo,1)}–${fmt(r.hi,1)}</b><div class="rangeBar"><span style="left:${Math.min(92,left)}%;width:${Math.min(100-left,width)}%"></span></div></div>`}
function renderSelectors(){const sel=$('#rankingSelect'),current=activeRanking;let html='<option value="base:ppr">Composite PPR</option><option value="base:half">Composite Half PPR</option><option value="base:standard">Composite Standard</option>';for(const [id,r] of Object.entries(custom))html+=`<option value="${esc(id)}">${esc(r.name)} (${labelMode(r.mode)})</option>`;sel.innerHTML=html;sel.value=[...sel.options].some(o=>o.value===current)?current:`base:${scoring}`;$('#customRankCount').textContent=Object.keys(custom).length}
function filteredPool(prefix,includeDrafted=true){const q=$(`#${prefix}Search`).value.toLowerCase().trim(),pos=$(`#${prefix}Position`).value,risk=$(`#${prefix}Risk`).value;const unavailable=unavailableSet();return eligible().filter(p=>(includeDrafted||!unavailable.has(idOf(p)))&&(!q||(p.full_name||'').toLowerCase().includes(q)||(p.team||'').toLowerCase().includes(q)||(p.position||'').toLowerCase().includes(q))&&(pos==='ALL'||p.position===pos)&&(risk==='ALL'||riskFor(p)===risk))}
function sortPool(pool,sort){const ranks=rankMap();pool.sort((a,b)=>sort==='name'?a.full_name.localeCompare(b.full_name):sort==='composite'?compositeValue(a)-compositeValue(b):sort==='ffc'?(directFfcAdp(a)||9999)-(directFfcAdp(b)||9999):sort==='sleeper'?(rawSleeperRank(a)||9999)-(rawSleeperRank(b)||9999):sort==='availability'?availabilityProbability(a)-availabilityProbability(b):sort==='risk'?individualRisk(a).score-individualRisk(b).score:(ranks.get(idOf(a))||9999)-(ranks.get(idOf(b))||9999));return pool}

function renderRankings(){if(!players.length)return;const ranks=rankMap(),sort=$('#rankSortMain').value,pool=sortPool(filteredPool('rank',true),sort);$('#rankingRows').innerHTML=pool.map(p=>`<tr class="teamRow" style="${teamStyle(p.team)}"><td><b>#${ranks.get(idOf(p))||'—'}</b></td><td>${renderPlayerBlock(p,`${p.position} • ${p.team}`)}</td><td><span class="pos">${p.position}</span></td><td>${renderStatus(p)}</td><td><div class="marketStack"><b>${fmt(compositeValue(p),1)}</b><small>${compositeSignals(p).length} signals</small></div></td><td>${fmt(directFfcAdp(p),1)}</td><td>${rawSleeperRank(p)||'—'}</td><td>${renderRange(p)}</td><td><button class="btn small" data-profile="${idOf(p)}">View</button></td></tr>`).join('')||'<tr><td colspan="9" class="empty">No active players match these filters.</td></tr>';const order=rankingMeta().order;$('#activePlayerCount').textContent=eligible().length;$('#adpSourceCount').textContent=`${sourceCount()}/4`;const top=playerById(order[0]);$('#topRankedPlayer').textContent=top?top.full_name:'—'}

function unavailableSet(){return new Set([...draft.mine,...draft.other].map(String))}
function counts(){return Object.fromEntries(POS.map(pos=>[pos,draft.mine.map(playerById).filter(p=>p&&p.position===pos).length]))}
function pickOwner(overall){const teams=settings.teams,round=Math.floor((overall-1)/teams)+1,slotInRound=((overall-1)%teams)+1;return round%2?slotInRound:teams-slotInRound+1}
function nextMyOverallPick(){for(let n=draft.history.length+1;n<=settings.teams*settings.rounds;n++)if(pickOwner(n)===settings.draftSlot)return n;return null}
function recentPositionRun(position){const last=draft.history.slice(-6).map(h=>playerById(h.id)).filter(Boolean);return last.filter(p=>p.position===position).length}
function availabilityProbability(p){const next=nextMyOverallPick();if(!next)return 0;const market=compositeValue(p),delta=market-next;let prob=100/(1+Math.exp(-delta/7));prob-=recentPositionRun(p.position)*5;if(market<=draft.history.length+2)prob-=10;return clamp(Math.round(prob),3,97)}
function availabilityClass(prob){return prob<30?'hot':prob<65?'mid':'safe'}
function rosterUsage(c=counts()){const fixedFilled=POS.reduce((s,pos)=>s+Math.min(c[pos],settings.slots[pos]),0),flexExtras=FLEX_POS.reduce((s,pos)=>s+Math.max(0,c[pos]-settings.slots[pos]),0),flexFilled=Math.min(settings.slots.FLEX,flexExtras),starterFilled=fixedFilled+flexFilled,benchUsed=Math.max(0,draft.mine.length-starterFilled);return{fixedFilled,flexFilled,starterFilled,benchUsed}}
function candidateNeed(p,c=counts()){if(c[p.position]<settings.slots[p.position])return{score:28,label:`fills ${p.position} starter`};if(FLEX_POS.includes(p.position)){const use=rosterUsage(c);if(use.flexFilled<settings.slots.FLEX)return{score:15,label:'fills FLEX'}}const use=rosterUsage(c);if(use.benchUsed<settings.slots.BENCH)return{score:4,label:'adds bench depth'};return{score:-12,label:'roster slot pressure'}}
function rosterIdentity(c){const total=draft.mine.length;if(!total)return'Balanced';const wrShare=c.WR/total,rbShare=c.RB/total;if(wrShare>=.5&&c.WR>=3)return'WR Heavy';if(rbShare>=.5&&c.RB>=3)return'RB Heavy';if(c.QB>=2&&total<=7)return'QB Early';if(c.TE>=2&&total<=7)return'TE Heavy';return'Balanced'}
function stackScore(p){let score=0;for(const id of draft.mine){const q=playerById(id);if(!q||q.team!==p.team)continue;if((q.position==='QB'&&['WR','TE'].includes(p.position))||(p.position==='QB'&&['WR','TE'].includes(q.position)))score+=10;else if(q.position==='RB'&&p.position==='RB')score+=2}return score}
function recommendationScore(p,c=counts()){const ranks=rankMap(),rank=ranks.get(idOf(p))||9999,base=100-Math.min(90,rank/3),need=candidateNeed(p,c).score,urgency=(100-availabilityProbability(p))*.18,stack=stackScore(p),risk=individualRisk(p).score*.28;return base+need+urgency+stack-risk}
function recommendationReason(p){const parts=[candidateNeed(p).label,`${availabilityProbability(p)}% chance to last`];if(stackScore(p)>=8)parts.push('stack fit');if(individualRisk(p).score<20)parts.push('low risk');return parts.join(' • ')}
function draftCapital(){let total=0,details=[];for(const h of draft.history.filter(x=>x.who==='mine')){const p=playerById(h.id);if(!p)continue;const base=Number.isFinite(h.baseAtPick)?h.baseAtPick:compositeValue(p),cap=Math.round(base-h.pick);total+=cap;details.push({p,pick:h.pick,cap})}return{total,details}}
function portfolioRisk(){const ps=draft.mine.map(playerById).filter(Boolean);if(!ps.length)return{score:0,label:'Low',reasons:['No players drafted yet']};let score=ps.reduce((s,p)=>s+individualRisk(p).score,0)/ps.length,reasons=[];const teams={};for(const p of ps)teams[p.team]=(teams[p.team]||0)+1;const maxTeam=Math.max(...Object.values(teams));if(maxTeam>=4){score+=(maxTeam-3)*7;reasons.push(`${maxTeam} players share one NFL offense`)}const red=ps.filter(p=>riskFor(p)==='red').length,yellow=ps.filter(p=>riskFor(p)==='yellow').length;if(red)reasons.push(`${red} red availability flag${red>1?'s':''}`);if(yellow)reasons.push(`${yellow} monitor flag${yellow>1?'s':''}`);score=clamp(Math.round(score),0,100);return{score,label:score<25?'Low':score<50?'Moderate':score<70?'Elevated':'High',reasons}}
function addPick(id,who){id=String(id);if(unavailableSet().has(id))return;const p=playerById(id),ranks=rankMap();if(who==='mine')draft.mine.push(id);else draft.other.push(id);draft.history.push({id,who,pick:draft.history.length+1,time:Date.now(),rankAtPick:ranks.get(id)||null,baseAtPick:p?Math.round(compositeValue(p)):null});persist();renderDraft()}
function undoMy(i){const id=draft.mine[i];draft.mine.splice(i,1);for(let j=draft.history.length-1;j>=0;j--){if(draft.history[j].id===id&&draft.history[j].who==='mine'){draft.history.splice(j,1);break}}draft.history.forEach((h,j)=>h.pick=j+1);persist();renderDraft()}
function clearMine(){const mine=new Set(draft.mine.map(String));draft.mine=[];draft.history=draft.history.filter(h=>!(h.who==='mine'&&mine.has(String(h.id))));draft.history.forEach((h,j)=>h.pick=j+1);persist();renderDraft()}
function newDraft(){if(!confirm('Start a new draft? This clears tracked picks but keeps rankings and settings.'))return;draft={mine:[],other:[],history:[]};persist();renderDraft()}
function renderDraft(){if(!players.length)return;const ranks=rankMap(),sort=$('#draftSort').value,pool=sortPool(filteredPool('draft',false),sort);$('#draftRows').innerHTML=pool.map(p=>{const prob=availabilityProbability(p);return`<tr class="teamRow" style="${teamStyle(p.team)}"><td><b>#${ranks.get(idOf(p))||'—'}</b></td><td>${renderPlayerBlock(p,`${p.position} • ${p.team}`)}</td><td><span class="pos">${p.position}</span></td><td>${renderStatus(p)}</td><td>${fmt(compositeValue(p),1)}</td><td><span class="reach ${availabilityClass(prob)}">${prob}%</span></td><td><div class="actions"><button class="btn small primary" data-pick="mine" data-id="${idOf(p)}">My Pick</button><button class="btn small" data-pick="other" data-id="${idOf(p)}">Other Pick</button></div></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No available players match these filters.</td></tr>';const next=nextMyOverallPick(),capital=draftCapital(),port=portfolioRisk(),c=counts();$('#availableCount').textContent=Math.max(0,eligible().length-unavailableSet().size);$('#myCount').textContent=draft.mine.length;$('#nextPickMetric').textContent=next?`#${next}`:'—';$('#capitalMetric').textContent=(capital.total>0?'+':'')+capital.total;$('#capitalMetric').className=capital.total>=0?'capitalPos':'capitalNeg';$('#portfolioMetric').textContent=port.label;$('#teamLean').textContent=rosterIdentity(c);$('#nextPickSummary').textContent=next?`Next turn: pick ${next} • ${Math.max(0,next-draft.history.length-1)} picks before you`:'Draft complete';renderRoster(c);renderRecommendations();renderIntelligence(c);renderRiskDashboard(port);renderHistory()}
function renderRoster(c){$('#roster').innerHTML=draft.mine.length?draft.mine.map((id,i)=>{const p=playerById(id);if(!p)return'';const h=draft.history.find(x=>x.id===id&&x.who==='mine'),cap=h&&Number.isFinite(h.baseAtPick)?Math.round(h.baseAtPick-h.pick):null;return`<div class="pick" style="${teamStyle(p.team)}"><div class="pickNum">${i+1}</div><div><b data-profile="${id}" style="cursor:pointer">${esc(p.full_name)}</b><div class="sub">${p.position} • ${esc(p.team)}${cap!=null?` • <span class="${cap>=0?'capitalPos':'capitalNeg'}">${cap>=0?'+':''}${cap} capital</span>`:''}</div></div><button class="remove" data-remove-mine="${i}">×</button></div>`}).join(''):'<div class="empty">Use “My Pick” to build your roster.</div>';const use=rosterUsage(c);let rows=POS.map(x=>`<div class="barRow"><b>${x}</b><div class="bar"><div class="fill" style="width:${settings.slots[x]?Math.min(100,c[x]/settings.slots[x]*100):(c[x]?100:0)}%"></div></div><span>${c[x]}/${settings.slots[x]}</span></div>`).join('');rows+=`<div class="barRow"><b>FLEX</b><div class="bar"><div class="fill" style="width:${settings.slots.FLEX?Math.min(100,use.flexFilled/settings.slots.FLEX*100):0}%"></div></div><span>${use.flexFilled}/${settings.slots.FLEX}</span></div><div class="barRow"><b>Bench</b><div class="bar"><div class="fill" style="width:${settings.slots.BENCH?Math.min(100,use.benchUsed/settings.slots.BENCH*100):0}%"></div></div><span>${use.benchUsed}/${settings.slots.BENCH}</span></div>`;$('#shape').innerHTML=rows}
function uniqueCategory(pool,fn,used){const sorted=pool.slice().sort(fn);return sorted.find(x=>!used.has(idOf(x)))||sorted[0]}
function renderRecommendations(){const pool=eligible().filter(p=>!unavailableSet().has(idOf(p))),ranks=rankMap(),used=new Set(),recs=[];if(!pool.length){$('#recs').innerHTML='<div class="empty">No players available.</div>';return}const overall=uniqueCategory(pool,(a,b)=>recommendationScore(b)-recommendationScore(a),used);if(overall){used.add(idOf(overall));recs.push(['Best Overall',overall])}const value=uniqueCategory(pool,(a,b)=>(ranks.get(idOf(a))||9999)-(ranks.get(idOf(b))||9999),used);if(value){used.add(idOf(value));recs.push(['Best Value',value])}const urgent=uniqueCategory(pool.filter(p=>(ranks.get(idOf(p))||9999)<140),(a,b)=>availabilityProbability(a)-availabilityProbability(b),used);if(urgent){used.add(idOf(urgent));recs.push(['Most Urgent',urgent])}const fit=uniqueCategory(pool,(a,b)=>candidateNeed(b).score-candidateNeed(a).score||recommendationScore(b)-recommendationScore(a),used);if(fit)recs.push(['Roster Fit',fit]);$('#recs').innerHTML=recs.map(([label,p])=>`<div class="rec"><div><div class="recLabel">${label}</div><b data-profile="${idOf(p)}" style="cursor:pointer">${esc(p.full_name)}</b><div class="sub">${p.position} • ${esc(p.team)} • ${esc(recommendationReason(p))}</div></div><span class="score">${Math.round(recommendationScore(p))}</span></div>`).join('')}
function renderIntelligence(c){const boxes=[],next=nextMyOverallPick(),use=rosterUsage(c),capital=draftCapital();if(next)boxes.push(`<div class="insight good"><strong>Next turn: pick ${next}</strong>${Math.max(0,next-draft.history.length-1)} selections happen before you. The survival estimate is based on composite market position plus recent positional runs.</div>`);const holes=POS.filter(p=>c[p]<settings.slots[p]).map(p=>`${p} ${c[p]}/${settings.slots[p]}`);if(holes.length)boxes.push(`<div class="insight warnBox"><strong>Starting lineup needs</strong>${holes.join(' • ')}${use.flexFilled<settings.slots.FLEX?` • FLEX ${use.flexFilled}/${settings.slots.FLEX}`:''}</div>`);else boxes.push('<div class="insight good"><strong>Starter structure covered</strong>Prioritize value, upside, stacks, and contingency depth.</div>');const last=draft.history.slice(-6).map(h=>playerById(h.id)).filter(Boolean),run=POS.map(pos=>({pos,n:last.filter(p=>p.position===pos).length})).sort((a,b)=>b.n-a.n)[0];if(run&&run.n>=3)boxes.push(`<div class="insight warnBox"><strong>${run.pos} run detected</strong>${run.n} of the last ${last.length} picks were ${run.pos}s.</div>`);boxes.push(`<div class="insight ${capital.total>=0?'good':'warnBox'}"><strong>Draft capital: ${capital.total>=0?'+':''}${capital.total}</strong>${capital.total>=0?'You are beating composite market cost overall.':'You are spending ahead of composite market cost overall.'}</div>`);$('#intelligence').innerHTML=boxes.join('')}
function renderRiskDashboard(port){if(!draft.mine.length){$('#riskDashboard').innerHTML='<div class="empty">Draft players to build your risk view.</div>';return}const ps=draft.mine.map(playerById).filter(Boolean).sort((a,b)=>individualRisk(b).score-individualRisk(a).score);$('#riskDashboard').innerHTML=`<div><b>${port.label} risk • ${port.score}/100</b><div class="riskGauge"><div class="riskFill" style="width:${port.score}%"></div></div><div class="sub">${port.reasons.length?esc(port.reasons.join(' • ')):'No major concentration flags.'}</div></div><div class="riskList" style="margin-top:10px">${ps.slice(0,5).map(p=>{const r=individualRisk(p);return`<div class="riskItem ${r.score>=65?'badBox':r.score>=40?'warnBox':'good'}"><strong data-profile="${idOf(p)}" style="cursor:pointer">${esc(p.full_name)} • ${r.score}/100</strong><div class="sub">${r.reasons.length?esc(r.reasons.join(' • ')):'No major current risk flags'}</div></div>`}).join('')}</div>`}
function renderHistory(){$('#history').innerHTML=draft.history.length?draft.history.slice().reverse().slice(0,30).map(h=>{const p=playerById(h.id);if(!p)return'';const cap=h.who==='mine'&&Number.isFinite(h.baseAtPick)?Math.round(h.baseAtPick-h.pick):null;return`<div class="historyRow ${h.who==='mine'?'mine':'other'}"><b>${h.pick}</b><span><span data-profile="${idOf(p)}" style="cursor:pointer;font-weight:800">${esc(p.full_name)}</span>${cap!=null?` <span class="${cap>=0?'capitalPos':'capitalNeg'}">${cap>=0?'+':''}${cap}</span>`:''}</span><span class="sub">${h.who==='mine'?'Mine':'Other'}</span></div>`}).join(''):'<div class="empty">Draft picks will appear here.</div>'}

function initRankingWork(){const meta=rankingMeta();rankingWork=meta.order.slice();$('#rankBase').value=meta.mode;$('#rankName').value=meta.base?`My ${labelMode(meta.mode)} Rankings`:meta.name;renderRankList()}
function createRanking(){const mode=$('#rankBase').value;rankingWork=baseOrder(mode);$('#rankName').value=`My ${labelMode(mode)} Rankings`;$('#rankStatus').textContent=`Reset from current composite ${labelMode(mode)} market board.`;renderRankList()}
function renderRankList(){if(!rankingWork.length)return;const q=$('#rankSearch').value.toLowerCase().trim(),positions=new Map(rankingWork.map((id,i)=>[id,i+1]));$('#rankList').innerHTML=rankingWork.map(id=>playerById(id)).filter(Boolean).filter(p=>!q||(p.full_name||'').toLowerCase().includes(q)||(p.team||'').toLowerCase().includes(q)||(p.position||'').toLowerCase().includes(q)).map(p=>`<div class="rankRow" draggable="true" data-rank-id="${idOf(p)}" style="${teamStyle(p.team)}"><span class="rankNum">${positions.get(idOf(p))}</span><span class="handle">☰</span><div class="rankPlayer"><span class="miniTeam">${esc(p.team)}</span><span><b>${esc(p.full_name)}</b><div class="sub">${p.position} • ${esc(p.team)}</div></span></div><span class="pill">${p.position}</span><span class="baseRank">Composite ${fmt(compositeValue(p,$('#rankBase').value),1)}</span><span class="rankMove"><button class="btn small" data-rank-move="up" data-id="${idOf(p)}">↑</button><button class="btn small" data-rank-move="down" data-id="${idOf(p)}">↓</button><button class="btn small" data-rank-move="top" data-id="${idOf(p)}">Top</button></span></div>`).join('')}
function moveRank(id,action){const i=rankingWork.indexOf(String(id));if(i<0)return;let to=i;if(action==='up')to=Math.max(0,i-1);if(action==='down')to=Math.min(rankingWork.length-1,i+1);if(action==='top')to=0;if(to===i)return;const [x]=rankingWork.splice(i,1);rankingWork.splice(to,0,x);renderRankList()}
function placePlayerAtRank(){const p=resolvePlayer($('#rankPlayerFind').value),target=clamp(parseInt($('#rankTarget').value)||1,1,rankingWork.length);if(!p){$('#rankStatus').textContent='Player not found in the active pool.';return}const id=idOf(p),from=rankingWork.indexOf(id);if(from>=0)rankingWork.splice(from,1);rankingWork.splice(target-1,0,id);$('#rankStatus').textContent=`Moved ${p.full_name} to #${target}.`;$('#rankPlayerFind').value=p.full_name;renderRankList();setTimeout(()=>document.querySelector(`[data-rank-id="${CSS.escape(id)}"]`)?.scrollIntoView({block:'center',behavior:'smooth'}),0)}
function saveRanking(){if(!rankingWork.length)return;const name=$('#rankName').value.trim()||`My ${labelMode($('#rankBase').value)} Rankings`;let id=Object.keys(custom).find(k=>custom[k].name===name);if(!id)id='custom:'+Date.now();custom[id]={version:2,name,mode:$('#rankBase').value,order:rankingWork.slice(),savedAt:new Date().toISOString()};activeRanking=id;scoring=custom[id].mode;$('#scoring').value=scoring;persist();renderAll();$('#rankStatus').textContent=`Saved “${name}” and made it the active board.`}
function exportRanking(){if(!rankingWork.length)return;const payload={app:'Fantasy Football Command Center',version:2,name:$('#rankName').value.trim()||'Custom Rankings',mode:$('#rankBase').value,order:rankingWork,savedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=payload.name.replace(/[^a-z0-9]+/gi,'_').toLowerCase()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importRanking(file){const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);if(!Array.isArray(x.order)||!x.order.length)throw Error('Missing player order');const mode=['ppr','half','standard'].includes(x.mode)?x.mode:scoring,valid=new Set(eligible().map(idOf)),seen=new Set(),imported=[];for(const id of x.order.map(String)){if(valid.has(id)&&!seen.has(id)){seen.add(id);imported.push(id)}}for(const id of baseOrder(mode))if(!seen.has(id))imported.push(id);rankingWork=imported;$('#rankBase').value=mode;$('#rankName').value=x.name||'Imported Rankings';$('#rankStatus').textContent=`Imported ${rankingWork.length} active players. Save when ready.`;renderRankList()}catch(e){$('#rankStatus').textContent='Import failed: '+e.message}};rd.readAsText(file)}
function handleRankDrop(targetId){if(!draggingId||draggingId===targetId)return;const from=rankingWork.indexOf(draggingId),to=rankingWork.indexOf(targetId);if(from<0||to<0)return;const [x]=rankingWork.splice(from,1);rankingWork.splice(to,0,x);renderRankList()}
function resolvePlayer(text){const q=String(text||'').trim().toLowerCase();if(!q)return null;return eligible().find(p=>(p.full_name||'').toLowerCase()===q)||eligible().filter(p=>(p.full_name||'').toLowerCase().includes(q)||(p.team||'').toLowerCase()===q).sort((a,b)=>compositeValue(a)-compositeValue(b))[0]||null}
function renderPlayerOptions(){$('#playerOptions').innerHTML=eligible().slice().sort((a,b)=>a.full_name.localeCompare(b.full_name)).map(p=>`<option value="${esc(p.full_name)}">${esc(p.team)} ${p.position}</option>`).join('')}

function fantasyPoints(s,mode=scoring){const recPts=mode==='ppr'?1:mode==='half'?.5:0;return num(s.pass_yd)*.04+num(s.pass_td)*4-num(s.pass_int)*2+num(s.rush_yd)*.1+num(s.rush_td)*6+num(s.rec_yd)*.1+num(s.rec_td)*6+num(s.rec)*recPts-num(s.fum_lost)*2+num(s.pass_2pt)*2+num(s.rush_2pt)*2+num(s.rec_2pt)*2}
function parseWeekly(data,year){let rows=[];if(Array.isArray(data))rows=data;else if(data&&Array.isArray(data.stats))rows=data.stats;else if(data&&typeof data==='object')rows=Object.entries(data).map(([week,row])=>({...row,week:row?.week??week}));return rows.map((row,i)=>{const stats=row?.stats||row||{},week=parseInt(row?.week??row?.week_num??row?.metadata?.week??i+1);return{year,week:Number.isFinite(week)?week:i+1,stats,points:fantasyPoints(stats)}}).filter(x=>x.week>=1&&x.week<=18&&Number.isFinite(x.points)).sort((a,b)=>a.week-b.week)}
async function loadWeekly(id,year){const key=`${id}:${year}`;if(weeklyCache.has(key))return weeklyCache.get(key);let rows=[];try{const data=await fetch(PLAYER_WEEK_URL(id,year)).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});rows=parseWeekly(data,year)}catch{}weeklyCache.set(key,rows);return rows}
function seriesSummary(rows){const played=rows.filter(x=>x.points>0||Object.keys(x.stats||{}).some(k=>num(x.stats[k])>0)),pts=played.map(x=>x.points),mean=avg(pts),variance=pts.length?avg(pts.map(v=>(v-mean)**2)):0,sd=Math.sqrt(variance);return{games:played.length,total:pts.reduce((a,b)=>a+b,0),avg:mean,high:pts.length?Math.max(...pts):0,low:pts.length?Math.min(...pts):0,boom:pts.filter(x=>x>=20).length,solid:pts.filter(x=>x>=15).length,consistency:mean?clamp(100-(sd/mean)*48,0,100):0,rows:played}}
function ppgScore(p,ppg){const ranges={QB:[10,25],RB:[4,20],WR:[4,20],TE:[3,16]},r=ranges[p.position]||[4,20];return clamp((ppg-r[0])/(r[1]-r[0])*100,0,100)}
function performanceMetrics(p,rows){const s=seriesSummary(rows),last4=s.rows.slice(-4),recent=avg(last4.map(x=>x.points)),recentScore=s.avg?clamp((recent/s.avg)*70,0,100):0,availability=clamp((s.games/17)*100,0,100),boomRate=s.games?s.boom/s.games*100:0,floorRate=s.games?s.rows.filter(x=>x.points>=s.avg*.7).length/s.games*100:0;return[{label:'Fantasy PPG',score:ppgScore(p,s.avg),display:fmt(s.avg,1)},{label:'Consistency',score:s.consistency,display:`${Math.round(s.consistency)}%`},{label:'Recent form',score:recentScore,display:fmt(recent,1)},{label:'Games played',score:availability,display:`${s.games}/17`},{label:'20+ point rate',score:boomRate,display:`${Math.round(boomRate)}%`},{label:'Floor hit rate',score:floorRate,display:`${Math.round(floorRate)}%`}]} 
function performanceBarsHtml(metrics){return`<div class="performanceBars">${metrics.map(m=>`<div class="perfMetric"><label>${esc(m.label)}</label><div class="heatBar"><span class="heatMarker" style="left:${clamp(m.score,0,100)}%"></span></div><span class="perfValue">${esc(m.display)}</span></div>`).join('')}</div>`}
function chartColor(value,mean){if(!mean)return'#ffd166';const ratio=value/mean;return ratio<.65?'#ff5c68':ratio<1.15?'#ffd166':'#56df8f'}
function pointsChart(series){const data=series.slice().sort((a,b)=>a.year-b.year||a.week-b.week),pts=data.map(x=>x.points);if(!data.length)return'<div class="empty">Weekly game data was not returned for this span.</div>';const width=Math.max(780,data.length*52),height=270,ml=45,mr=18,mt=18,mb=46,plotW=width-ml-mr,plotH=height-mt-mb,max=Math.max(10,Math.ceil(Math.max(...pts,1)/10)*10),x=i=>ml+(data.length===1?plotW/2:i*plotW/(data.length-1)),y=v=>mt+plotH-(v/max)*plotH,mean=avg(pts),path=data.map((d,i)=>`${i?'L':'M'} ${x(i).toFixed(1)} ${y(d.points).toFixed(1)}`).join(' ');let grid='';for(let v=0;v<=max;v+=Math.max(5,max/5)){grid+=`<line x1="${ml}" x2="${width-mr}" y1="${y(v)}" y2="${y(v)}" stroke="#20344f" stroke-width="1"/><text x="${ml-7}" y="${y(v)+4}" fill="#7f9ab6" font-size="10" text-anchor="end">${Math.round(v)}</text>`}let labels='',circles='',seps='';data.forEach((d,i)=>{const xx=x(i),col=chartColor(d.points,avg(data.filter(z=>z.year===d.year).map(z=>z.points)));labels+=`<text x="${xx}" y="${height-18}" fill="#819ab3" font-size="9" text-anchor="middle">'${String(d.year).slice(-2)} W${d.week}</text>`;circles+=`<circle cx="${xx}" cy="${y(d.points)}" r="5" fill="${col}" stroke="#07101d" stroke-width="2"><title>${d.year} Week ${d.week}: ${fmt(d.points,1)} fantasy points</title></circle>`;if(i>0&&data[i-1].year!==d.year)seps+=`<line x1="${xx-26}" x2="${xx-26}" y1="${mt}" y2="${height-mb}" stroke="#52759e" stroke-dasharray="5 5"/><text x="${xx-20}" y="${mt+12}" fill="#9fb7cf" font-size="10">${d.year}</text>`});return`<div class="chartLegend"><span><i class="legendDot red"></i>Below typical</span><span><i class="legendDot yellow"></i>Around typical</span><span><i class="legendDot green"></i>Strong game</span><span>Dashed line = season boundary</span></div><div class="chartScroller"><svg class="pointsChart" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="Fantasy points by game">${grid}${seps}<line x1="${ml}" x2="${width-mr}" y1="${y(mean)}" y2="${y(mean)}" stroke="#b99cff" stroke-width="1.5" stroke-dasharray="4 5"/><path d="${path}" fill="none" stroke="#a8c8e8" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>${circles}${labels}</svg></div>`}
function seasonTotalsHtml(seriesByYear){return`<div class="seasonTotals"><table><thead><tr><th>Season</th><th>Games</th><th>FPPG</th><th>Total</th><th>High</th><th>Low</th><th>15+ games</th><th>20+ games</th></tr></thead><tbody>${[...seriesByYear.entries()].sort((a,b)=>b[0]-a[0]).map(([year,rows])=>{const s=seriesSummary(rows);return`<tr><td>${year}</td><td>${s.games||'—'}</td><td>${fmt(s.avg,1)}</td><td>${fmt(s.total,1)}</td><td>${fmt(s.high,1)}</td><td>${fmt(s.low,1)}</td><td>${s.solid}</td><td>${s.boom}</td></tr>`}).join('')}</tbody></table></div>`}
async function openPlayerProfile(id){const p=playerById(id);if(!p)return;currentProfileId=idOf(p);profileHistorySpan=1;const token=++profileToken;$('#playerModalTitle').innerHTML=`<h2>${esc(p.full_name)}</h2><div class="sub">${p.position} • ${esc(p.team)} • ${labelMode(scoring)} • active player</div>`;$('#playerModalBody').innerHTML='<div class="empty">Loading last season game-by-game performance…</div>';$('#playerModal').classList.add('open');await renderProfile(p,1,token)}
async function renderProfile(p,span=1,token=profileToken){profileHistorySpan=span;const years=Array.from({length:span},(_,i)=>latestCompleteYear-(span-1-i)),entries=await Promise.all(years.map(async y=>[y,await loadWeekly(idOf(p),y)]));if(token!==profileToken||currentProfileId!==idOf(p))return;const byYear=new Map(entries),flat=entries.flatMap(x=>x[1]),latest=byYear.get(latestCompleteYear)||[],sum=seriesSummary(latest),risk=individualRisk(p),ranks=rankMap(),sig=compositeSignals(p),metrics=performanceMetrics(p,latest);$('#playerModalBody').innerHTML=`<div class="profileHero" style="${teamStyle(p.team)}"><div class="profileHeroTop"><div><div class="teamMark">${esc(p.team)}</div><h3 style="margin:8px 0 0;font-size:20px">${esc(p.full_name)}</h3><div class="playerMeta">${p.position} • ${esc(p.team)} • ${esc(riskLabel(p))}</div></div><div><b style="font-size:28px">#${ranks.get(idOf(p))||'—'}</b><div class="playerMeta">selected rank</div></div></div></div><div class="profileGrid"><div class="statTile"><b>${fmt(compositeValue(p),1)}</b><span>Composite ADP</span></div><div class="statTile"><b>${fmt(directFfcAdp(p),1)}</b><span>FFC ${labelMode(scoring)} ADP</span></div><div class="statTile"><b>${rawSleeperRank(p)||'—'}</b><span>Sleeper market rank</span></div><div class="statTile"><b>${fmt(sum.avg,1)}</b><span>${latestCompleteYear} fantasy PPG</span></div><div class="statTile"><b>${fmt(sum.high,1)}</b><span>${latestCompleteYear} best game</span></div><div class="statTile"><b>${risk.score}/100</b><span>Risk score</span></div></div><div class="settingsSection">Performance profile • red → green</div>${performanceBarsHtml(metrics)}<div class="settingsSection">Fantasy points by game</div><div class="historyControls"><span class="sub">History:</span><button class="historySpanBtn ${span===1?'active':''}" data-history-span="1">Last season</button><button class="historySpanBtn ${span===3?'active':''}" data-history-span="3">Last 3 seasons</button><button class="historySpanBtn ${span===5?'active':''}" data-history-span="5">Last 5 seasons</button><span class="sub">Each point is one regular-season game.</span></div>${pointsChart(flat)}<div class="settingsSection">Season totals</div>${seasonTotalsHtml(byYear)}<div class="settingsSection">Market + availability context</div><div class="profileFoot"><div class="contextCard"><b>Composite inputs</b><div class="sub" style="margin-top:5px">${sig.length?sig.map(x=>`${esc(x[0])}: ${fmt(x[1],1)}`).join(' • '):'No external market inputs available.'}</div></div><div class="contextCard"><b>${riskFor(p)==='green'?'Clear to draft':riskFor(p)==='yellow'?'Monitor':'High availability risk'}</b><div class="sub" style="margin-top:5px">${risk.reasons.length?esc(risk.reasons.join(' • ')):'No major current injury, suspension, or role flags in the active player feed.'}</div></div></div>`}
function openCompare(prefillId){const p=prefillId?playerById(prefillId):null;if(p)$('#compareA').value=p.full_name;$('#compareModal').classList.add('open');$('#compareB').focus()}
async function runCompare(){const a=resolvePlayer($('#compareA').value),b=resolvePlayer($('#compareB').value);if(!a||!b){$('#compareOutput').innerHTML='<div class="empty">Could not resolve one of those active players.</div>';return}$('#compareA').value=a.full_name;$('#compareB').value=b.full_name;$('#compareOutput').innerHTML='<div class="empty">Loading last-season game logs…</div>';const [ar,br]=await Promise.all([loadWeekly(idOf(a),latestCompleteYear),loadWeekly(idOf(b),latestCompleteYear)]),sa=seriesSummary(ar),sb=seriesSummary(br),ra=individualRisk(a),rb=individualRisk(b),ranks=rankMap();const metric=(label,va,vb,lower=false,display=x=>x)=>{const aw=lower?va<vb:va>vb,bw=lower?vb<va:vb>va;return`<div class="compareCell">${label}</div><div class="compareCell ${aw?'winner':''}">${display(va)}</div><div class="compareCell ${bw?'winner':''}">${display(vb)}</div>`};let rows=`<div class="compareCell"></div><div class="compareCell"><b>${esc(a.full_name)}</b><div class="sub">${a.position} • ${esc(a.team)}</div></div><div class="compareCell"><b>${esc(b.full_name)}</b><div class="sub">${b.position} • ${esc(b.team)}</div></div>`;rows+=metric('Selected rank',ranks.get(idOf(a))||9999,ranks.get(idOf(b))||9999,true,x=>x===9999?'—':'#'+x);rows+=metric('Composite ADP',compositeValue(a),compositeValue(b),true,x=>fmt(x,1));rows+=metric(`${latestCompleteYear} FPPG`,sa.avg,sb.avg,false,x=>fmt(x,1));rows+=metric('Best game',sa.high,sb.high,false,x=>fmt(x,1));rows+=metric('Consistency',sa.consistency,sb.consistency,false,x=>Math.round(x)+'%');rows+=metric('Games with stats',sa.games,sb.games,false,x=>x);rows+=metric('Risk score',ra.score,rb.score,true,x=>x+'/100');$('#compareOutput').innerHTML=`<div class="compareGrid">${rows}</div>`}

function openSettings(){settings=normalizeSettings(settings);$('#setTeams').value=settings.teams;$('#setDraftSlot').value=settings.draftSlot;$('#setRounds').value=settings.rounds;for(const k of ['QB','RB','WR','TE','FLEX','BENCH'])$('#set'+k).value=settings.slots[k];$('#setDraftSlot').max=settings.teams;$('#settingsModal').classList.add('open')}
async function saveSettings(){const oldTeams=settings.teams,teams=clamp(parseInt($('#setTeams').value)||12,4,20);settings={teams,draftSlot:clamp(parseInt($('#setDraftSlot').value)||1,1,teams),rounds:clamp(parseInt($('#setRounds').value)||15,1,30),slots:{}};for(const k of ['QB','RB','WR','TE','FLEX','BENCH'])settings.slots[k]=clamp(parseInt($('#set'+k).value)||0,0,20);persist();$('#settingsModal').classList.remove('open');renderAll();if(oldTeams!==teams)await loadAdpFeeds()}
function restoreSettings(){settings=structuredClone(DEFAULT_SETTINGS);persist();openSettings();renderAll()}
function setMode(mode){appMode=['rankings','draft','builder'].includes(mode)?mode:'rankings';$$('.modeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===appMode));$$('.modePanel').forEach(p=>p.classList.toggle('active',p.dataset.panel===appMode));if(appMode==='builder'&&!rankingWork.length)initRankingWork();persist();if(appMode==='builder')renderRankList();if(appMode==='draft')renderDraft();if(appMode==='rankings')renderRankings()}
function renderAll(){if(!players.length)return;renderSelectors();renderPlayerOptions();const meta=rankingMeta();$('#rankingDescription').textContent=`Using ${meta.name} • ${labelMode(meta.mode)}`;$('#liveState').textContent=`${eligible().length} active skill players`;renderRankings();renderDraft();if(rankingWork.length)renderRankList()}

async function loadLeagueState(){try{const s=await fetch(STATE_URL).then(r=>r.json());const y=parseInt(s.season);if(y){seasonYear=y;seasonStatus=String(s.season_type||'');latestCompleteYear=(String(s.season_type||'').toLowerCase()==='complete'?y:y-1)}}catch{}}
function makeFfcMap(data){const map=new Map();for(const row of data?.players||[]){const key=normalizeName(row.name||row.player_name);const adp=Number(row.adp);if(key&&Number.isFinite(adp)&&adp>0)map.set(key,adp)}return map}
async function loadAdpFeeds(){if(adpLoading)return;adpLoading=true;$('#adpState').textContent='Refreshing composite ADP…';$('#adpState').className='dataBadge';const formats=[['ppr','ppr'],['half','half-ppr'],['standard','standard']];const results=await Promise.all(formats.map(async([key,format])=>{try{const data=await fetch(FFC_URL(format,settings.teams,seasonYear)).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});return[key,makeFfcMap(data)]}catch{return[key,new Map()]}}));for(const [key,map] of results)adpFeeds[key]=map;adpLoading=false;const n=sourceCount();$('#adpState').textContent=n>1?`Composite live • ${n}/4 signals`:'Sleeper-only fallback • FFC unavailable';$('#adpState').className='dataBadge '+(n>1?'good':'warn');renderAll()}
async function boot(){try{await loadLeagueState();const data=await fetch(PLAYER_URL).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});players=Object.entries(data||{}).map(([id,p])=>({...p,player_id:p.player_id||id,team:String(p.team||'').toUpperCase(),full_name:p.full_name||[p.first_name,p.last_name].filter(Boolean).join(' ')})).filter(p=>p.active!==false);playerMap=new Map(players.map(p=>[idOf(p),p]));$('#scoring').value=scoring;if(!activeRanking)activeRanking=`base:${scoring}`;renderAll();setMode('rankings');loadAdpFeeds()}catch(e){$('#adpState').textContent='Could not load active Sleeper player feed';$('#adpState').className='dataBadge warn';$('#rankingRows').innerHTML='<tr><td colspan="9" class="empty">Active player feed unavailable. Reload to try again.</td></tr>'}}

$$('.modeBtn').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
['rankSearchMain','rankPositionMain','rankRiskMain','rankSortMain'].forEach(id=>$('#'+id).addEventListener(id==='rankSearchMain'?'input':'change',renderRankings));
['draftSearch','draftPosition','draftRisk','draftSort'].forEach(id=>$('#'+id).addEventListener(id==='draftSearch'?'input':'change',renderDraft));
$('#scoring').addEventListener('change',e=>{scoring=e.target.value;if(activeRanking.startsWith('base:'))activeRanking='base:'+scoring;persist();renderAll()});
$('#applyRankingBtn').addEventListener('click',()=>{activeRanking=$('#rankingSelect').value;const m=rankingMeta().mode;scoring=m;$('#scoring').value=m;persist();rankingWork=[];renderAll()});
$('#newDraftBtn').addEventListener('click',newDraft);$('#clearMineBtn').addEventListener('click',clearMine);$('#settingsBtn').addEventListener('click',openSettings);$('#saveSettingsBtn').addEventListener('click',saveSettings);$('#defaultSettingsBtn').addEventListener('click',restoreSettings);
$('#compareFromRankingsBtn').addEventListener('click',()=>openCompare());$('#profileCompareBtn').addEventListener('click',()=>openCompare(currentProfileId));$('#runCompareBtn').addEventListener('click',runCompare);
$('#createRankingBtn').addEventListener('click',createRanking);$('#saveRankingBtn').addEventListener('click',saveRanking);$('#exportRankingBtn').addEventListener('click',exportRanking);$('#placeRankBtn').addEventListener('click',placePlayerAtRank);$('#rankSearch').addEventListener('input',renderRankList);$('#rankBase').addEventListener('change',()=>{$('#rankStatus').textContent='Base changed. Use “Reset From Composite” to rebuild from it.';renderRankList()});$('#importRankingInput').addEventListener('change',e=>{if(e.target.files[0])importRanking(e.target.files[0]);e.target.value=''});
$('#rankList').addEventListener('dragstart',e=>{const r=e.target.closest('[data-rank-id]');if(!r)return;draggingId=r.dataset.rankId;r.classList.add('dragging')});$('#rankList').addEventListener('dragend',e=>{e.target.closest('[data-rank-id]')?.classList.remove('dragging');draggingId=null});$('#rankList').addEventListener('dragover',e=>{if(e.target.closest('[data-rank-id]'))e.preventDefault()});$('#rankList').addEventListener('drop',e=>{const r=e.target.closest('[data-rank-id]');if(r){e.preventDefault();handleRankDrop(r.dataset.rankId)}});$('#rankList').addEventListener('click',e=>{const b=e.target.closest('[data-rank-move]');if(b)moveRank(b.dataset.id,b.dataset.rankMove)});
$('#draftRows').addEventListener('click',e=>{const b=e.target.closest('[data-pick]');if(b){addPick(b.dataset.id,b.dataset.pick);return}});$('#roster').addEventListener('click',e=>{const b=e.target.closest('[data-remove-mine]');if(b)undoMy(+b.dataset.removeMine)});
document.body.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close){$('#'+close.dataset.close)?.classList.remove('open');return}const profile=e.target.closest('[data-profile]');if(profile&&!e.target.closest('[data-pick]')){openPlayerProfile(profile.dataset.profile);return}const span=e.target.closest('[data-history-span]');if(span&&currentProfileId){const p=playerById(currentProfileId);if(p){$('#playerModalBody').innerHTML='<div class="empty">Expanding game-by-game history…</div>';renderProfile(p,+span.dataset.historySpan,profileToken)}}});
$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal.open').forEach(m=>m.classList.remove('open'))});

boot();
