function createEnemyPlan(state,e){
  if(e.stunned>0){e.stunned--;return{kind:"wait",stunned:true}}
  if(e.type==="commander"){const ids=aliveEnemies(state).filter(x=>x.id!==e.id&&manhattan(x,e)<=2).map(x=>x.id);if(ids.length)return{kind:"command",targetIds:ids}}
  if(e.type==="bomber"){if(e.bombArmed&&e.bombTarget)return{kind:"explode",center:{...e.bombTarget}};const t=chooseTargetPosition(state,e);return{kind:"mark",center:{r:t.r,c:t.c}}}
  if(e.type==="archer"){const t=nearestAlignedHero(state,e,2,6);if(t)return{kind:"shoot",target:{r:t.r,c:t.c}}}
  if(e.type==="hook"){const t=nearestAlignedHero(state,e,2,5);if(t)return{kind:"pull",target:{r:t.r,c:t.c}}}
  const adj=aliveHeroes(state).filter(h=>manhattan(h,e)===1).sort((a,b)=>a.hp-b.hp)[0];
  if(adj)return e.type==="brute"?{kind:"attackPush",target:{r:adj.r,c:adj.c}}:{kind:"attack",target:{r:adj.r,c:adj.c}};
  const path=greedyPath(state,e,chooseTargetPosition(state,e),e.type==="raider"?2:1);
  return path.length?{kind:e.type==="raider"?"charge":"move",path}:{kind:"wait"};
}
function applyCommanderPlanning(){for(const c of aliveEnemies().filter(e=>e.type==="commander"&&e.plan.kind==="command"))for(const id of c.plan.targetIds||[]){const t=game.enemies.find(e=>e.id===id&&e.alive);if(!t)continue;t.commanded=true;if(["move","charge"].includes(t.plan.kind)){const end=t.plan.path?.at(-1)||t,goal=chooseTargetPosition(game,{...t,...end}),extra=greedyPath(game,t,goal,1,end)[0];if(extra&&!t.plan.path.some(p=>sameCell(p,extra)))t.plan.path.push(extra)}}}
function assignInitiative(){aliveEnemies().slice().sort((a,b)=>(ENEMY_DATA[a.type].initiative-(a.commanded?.5:0))-(ENEMY_DATA[b.type].initiative-(b.commanded?.5:0))||a.id-b.id).forEach((e,i)=>e.order=i+1)}
function getMoveTargets(state,h){return ORTHOGONAL.map(d=>({r:h.r+d.r,c:h.c+d.c})).filter(p=>inside(p.r,p.c)&&!occupied(state,p.r,p.c,h.id))}
function firstUnitInDirection(state,o,d,max){for(let n=1;n<=max;n++){const r=o.r+d.r*n,c=o.c+d.c*n;if(!inside(r,c))break;const e=enemyAt(state,r,c);if(e)return{enemy:e,distance:n,delta:d};if(heroAt(state,r,c))break}return null}
function getAttackTargets(state,h){if(!h?.alive)return[];if(["blade","shield","banner"].includes(h.type))return ORTHOGONAL.map(d=>enemyAt(state,h.r+d.r,h.c+d.c)).filter(Boolean).map(e=>({r:e.r,c:e.c,enemyId:e.id}));if(h.type==="spear"){const out=[],ranges=state.upgrades.spearFlexible?[1,2]:[2];for(const d of ORTHOGONAL)for(const n of ranges){const r=h.r+d.r*n,c=h.c+d.c*n;if(!inside(r,c))continue;let blocked=false;for(let s=1;s<n;s++)if(occupied(state,h.r+d.r*s,h.c+d.c*s,h.id))blocked=true;const e=blocked?null:enemyAt(state,r,c);if(e)out.push({r,c,enemyId:e.id})}return out}if(h.type==="bow")return ORTHOGONAL.map(d=>firstUnitInDirection(state,h,d,4)).filter(Boolean).map(x=>({r:x.enemy.r,c:x.enemy.c,enemyId:x.enemy.id,delta:x.delta}));return[]}
function getSpecialTargets(h){if(h.type==="blade")return ORTHOGONAL.map(d=>({r:h.r+d.r,c:h.c+d.c})).filter(p=>inside(p.r,p.c)&&!heroAt(game,p.r,p.c));if(h.type==="shield")return[{r:h.r,c:h.c},...ORTHOGONAL.map(d=>({r:h.r+d.r,c:h.c+d.c}))].filter(p=>inside(p.r,p.c)&&!enemyAt(game,p.r,p.c));if(h.type==="spear"){const out=[];for(const d of ORTHOGONAL)for(let n=1;n<=game.upgrades.spearReach;n++){const r=h.r+d.r*n,c=h.c+d.c*n;if(!inside(r,c))break;const ally=heroAt(game,r,c);if(ally&&ally.id!==h.id)break;out.push({r,c,delta:d,distance:n});if(enemyAt(game,r,c))break}return out}const range=h.type==="bow"?4:game.upgrades.bannerRange,out=[];for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)if(manhattan(h,{r,c})<=range&&(h.type!=="banner"||!enemyAt(game,r,c)))out.push({r,c});return out}
function getBannerPickTargets(){return pendingBanner?pendingBanner.eligibleIds.map(id=>game.heroes.find(h=>h.id===id&&h.alive)).filter(Boolean).map(h=>({r:h.r,c:h.c,heroId:h.id})):[]}
function getActionTargets(h,mode=actionMode){if(!h||h.acted)return[];if(mode==="move")return getMoveTargets(game,h);if(mode==="attack")return getAttackTargets(game,h);if(mode==="guard")return[{r:h.r,c:h.c,heroId:h.id}];if(mode==="special")return h.cooldown===0?getSpecialTargets(h):[];if(mode==="bannerPick")return getBannerPickTargets();return[]}
function bladeSweepArea(h,t){const dr=t.r-h.r,sa=dr?{r:t.r,c:t.c-1}:{r:t.r-1,c:t.c},sb=dr?{r:t.r,c:t.c+1}:{r:t.r+1,c:t.c};return[t,sa,sb].filter(p=>inside(p.r,p.c))}
function plusArea(center,diag=false){return[{r:0,c:0},...ORTHOGONAL,...(diag?DIAGONAL:[])].map(d=>({r:center.r+d.r,c:center.c+d.c})).filter(p=>inside(p.r,p.c))}
function lineArea(h,t){const dr=Math.sign(t.r-h.r),dc=Math.sign(t.c-h.c),out=[];for(let n=1;n<=manhattan(h,t);n++)out.push({r:h.r+dr*n,c:h.c+dc*n});return out}
function getPreviewArea(h,mode,t){if(!h||!t)return{friendly:[],hostile:[]};if(["move","guard","bannerPick"].includes(mode))return{friendly:[t],hostile:[]};if(mode==="attack")return{friendly:[],hostile:[t]};if(mode!=="special")return{friendly:[],hostile:[]};if(h.type==="blade")return{friendly:[],hostile:bladeSweepArea(h,t)};if(h.type==="shield")return{friendly:plusArea(t,game.upgrades.shieldDiagonal),hostile:[]};if(h.type==="spear")return{friendly:[],hostile:lineArea(h,t)};if(h.type==="bow")return{friendly:[],hostile:plusArea(t,game.upgrades.bowDiagonal)};return{friendly:plusArea(t),hostile:[]}}
function adjacentGuardian(state,t){return state.enemies.find(e=>e.alive&&e.type==="guardian"&&e.id!==t.id&&manhattan(e,t)===1)||null}
function damageEnemy(state,id,amount,source=null){const e=state.enemies.find(x=>x.id===id&&x.alive);if(!e)return{hit:false,killed:false};const g=adjacentGuardian(state,e);if(g&&!e.shieldBroken){e.shieldBroken=true;return{hit:false,killed:false,blocked:true}}let dmg=amount;if(source&&state.upgrades.finisher&&e.hp<e.maxHp)dmg++;e.hp-=dmg;if(e.hp<=0)e.alive=false;return{hit:true,killed:!e.alive}}
function applyBasicAttack(state,h,id){const t=state.enemies.find(e=>e.id===id&&e.alive);if(!t)return;const d={r:Math.sign(t.r-h.r),c:Math.sign(t.c-h.c)};damageEnemy(state,id,1,h);if(h.type==="bow"&&state.upgrades.bowPierce){let passed=false;for(let n=1;n<=6;n++){const r=h.r+d.r*n,c=h.c+d.c*n;if(!inside(r,c))break;const e=enemyAt(state,r,c);if(e){if(!passed&&e.id===id){passed=true;continue}if(passed){damageEnemy(state,e.id,1,h);break}}if(heroAt(state,r,c)&&!(r===h.r&&c===h.c))break}}}
function finishAction(h){h.acted=true;selectedHeroId=null;actionMode="move";previewTarget=null;previewLocked=false;pendingBanner=null;render()}
function finishSpecial(h){h.cooldown=Math.max(1,HERO_DATA[h.type].cooldown-game.upgrades.cooldownReduction);finishAction(h)}
function executeAction(h,mode,t){if(!h||h.acted)return;if(mode==="move"){h.r=t.r;h.c=t.c;return finishAction(h)}if(mode==="attack"){const e=enemyAt(game,t.r,t.c);if(e)applyBasicAttack(game,h,e.id);return finishAction(h)}if(mode==="guard"){h.guard=Math.max(h.guard,1);return finishAction(h)}if(mode==="bannerPick"){const a=game.heroes.find(x=>x.id===t.heroId&&x.alive),b=game.heroes.find(x=>x.id===pendingBanner?.bannerId&&x.alive);if(a)a.acted=false;if(b)finishSpecial(b);return}if(mode!=="special")return;const area=getPreviewArea(h,mode,t);if(h.type==="blade"){for(const p of area.hostile){const e=enemyAt(game,p.r,p.c);if(e)damageEnemy(game,e.id,1+game.upgrades.bladePower,h)}return finishSpecial(h)}if(h.type==="shield"){for(const p of area.friendly){const a=heroAt(game,p.r,p.c);if(a)a.guard=Math.max(a.guard,1)}return finishSpecial(h)}if(h.type==="spear"){for(const p of area.hostile){const e=enemyAt(game,p.r,p.c);if(e){damageEnemy(game,e.id,1,h);if(e.alive)e.stunned=Math.max(e.stunned,1)}}return finishSpecial(h)}if(h.type==="bow"){for(const p of area.hostile){const e=enemyAt(game,p.r,p.c);if(e)damageEnemy(game,e.id,1,h)}return finishSpecial(h)}const allies=[];for(const p of area.friendly){const a=heroAt(game,p.r,p.c);if(a){a.guard=Math.max(a.guard,1);allies.push(a)}}const eligible=allies.filter(a=>a.id!==h.id&&a.acted);if(!eligible.length)return finishSpecial(h);pendingBanner={bannerId:h.id,center:{r:t.r,c:t.c},eligibleIds:eligible.map(a=>a.id)};actionMode="bannerPick";previewTarget=null;previewLocked=false;render()}
function clonePlan(p){return p?{...p,target:p.target?{...p.target}:undefined,center:p.center?{...p.center}:undefined,path:p.path?.map(x=>({...x})),targetIds:p.targetIds?.slice()}:{kind:"wait"}}
function cloneState(s){return{heroes:s.heroes.map(h=>({...h})),enemies:s.enemies.map(e=>({...e,bombTarget:e.bombTarget?{...e.bombTarget}:null,plan:clonePlan(e.plan)})),upgrades:{...s.upgrades},reserveUsed:s.reserveUsed,damageEvents:0}}
function generateSolverActions(state,h){return[{kind:"wait"},{kind:"guard"},...getMoveTargets(state,h).map(p=>({kind:"move",...p})),...getAttackTargets(state,h).map(p=>({kind:"attack",enemyId:p.enemyId}))]}
function applySolverAction(state,id,a){const h=state.heroes.find(x=>x.id===id&&x.alive);if(!h)return;if(a.kind==="guard")h.guard=1;else if(a.kind==="move"){h.r=a.r;h.c=a.c}else if(a.kind==="attack")applyBasicAttack(state,h,a.enemyId)}
function countFlawlessLines(limit=8){const initial=cloneState(game),order=initial.heroes.filter(h=>h.alive).map(h=>h.id);let count=0;function search(state,i){if(count>=limit)return;if(i>=order.length){const result=cloneState(state);simulateEnemyPhase(result);if(result.damageEvents===0&&!result.enemies.some(e=>e.alive&&e.r===BEACON.r&&e.c===BEACON.c)&&result.heroes.some(h=>h.alive))count++;return}const h=state.heroes.find(x=>x.id===order[i]&&x.alive);if(!h)return search(state,i+1);for(const a of generateSolverActions(state,h)){const next=cloneState(state);applySolverAction(next,h.id,a);search(next,i+1);if(count>=limit)break}}search(initial,0);return count}
function ensureFlawlessLine(){let safe=countFlawlessLines();if(!safe){const pressure={explode:11,shoot:10,attackPush:9,charge:8,attack:7,pull:6,move:3,command:2,mark:1,wait:0},list=aliveEnemies().filter(e=>e.plan.kind!=="wait").sort((a,b)=>pressure[b.plan.kind]-pressure[a.plan.kind]);for(const e of list){e.plan={kind:"wait",forced:true};safe=countFlawlessLines();if(safe)break}}game.safeLines=Math.max(1,safe)}
function damageHero(state,id,attacker=null,melee=false){const h=state.heroes.find(x=>x.id===id&&x.alive);if(!h)return{blocked:false,killed:false};if(h.guard>0){h.guard--;if(state.upgrades.counter&&melee&&attacker){const e=state.enemies.find(x=>x.id===attacker&&x.alive);if(e&&manhattan(e,h)===1)damageEnemy(state,e.id,1)}return{blocked:true,killed:false}}if(h.armor>0){h.armor--;return{blocked:true,killed:false}}if(state.upgrades.reserve&&!state.reserveUsed){state.reserveUsed=true;return{blocked:true,killed:false}}h.hp--;state.damageEvents=(state.damageEvents||0)+1;if(h.hp<=0)h.alive=false;return{blocked:false,killed:!h.alive}}
function pushHero(state,h,e){if(state.upgrades.brace)return;const r=h.r+Math.sign(h.r-e.r),c=h.c+Math.sign(h.c-e.c);if(inside(r,c)&&!occupied(state,r,c,h.id)){h.r=r;h.c=c}}
function executePlan(state,e,p){if(!e.alive||p.kind==="wait"||p.kind==="command")return;if(["move","charge"].includes(p.kind)){for(const step of p.path||[]){const h=heroAt(state,step.r,step.c);if(h){damageHero(state,h.id,e.id,true);break}const blocker=enemyAt(state,step.r,step.c);if(blocker&&blocker.id!==e.id)break;e.r=step.r;e.c=step.c}return}if(["attack","shoot","attackPush"].includes(p.kind)){const h=heroAt(state,p.target.r,p.target.c);if(!h)return;const res=damageHero(state,h.id,e.id,p.kind!=="shoot");if(p.kind==="attackPush"&&!res.blocked&&h.alive)pushHero(state,h,e);return}if(p.kind==="pull"){const h=heroAt(state,p.target.r,p.target.c);if(!h)return;const r=h.r+Math.sign(e.r-h.r),c=h.c+Math.sign(e.c-h.c);if(inside(r,c)&&!occupied(state,r,c,h.id)){h.r=r;h.c=c}return}if(p.kind==="mark"){e.bombArmed=true;e.bombTarget={...p.center};return}if(p.kind==="explode"){for(const h of state.heroes.filter(h=>h.alive&&Math.abs(h.r-p.center.r)<=1&&Math.abs(h.c-p.center.c)<=1))damageHero(state,h.id,e.id);for(const x of state.enemies.filter(x=>x.alive&&Math.abs(x.r-p.center.r)<=1&&Math.abs(x.c-p.center.c)<=1))damageEnemy(state,x.id,2);e.alive=false}}
function simulateEnemyPhase(state){for(const planned of state.enemies.filter(e=>e.alive).slice().sort((a,b)=>(a.order||999)-(b.order||999))){const e=state.enemies.find(x=>x.id===planned.id&&x.alive);if(e)executePlan(state,e,e.plan)}}
function availableEnemyTypes(r){const t=["grunt"];if(r>=4)t.push("raider");if(r>=7)t.push("archer");if(r>=10)t.push("brute");if(r>=13)t.push("hook");if(r>=16)t.push("guardian");if(r>=20)t.push("bomber");if(r>=24)t.push("commander");return t}
function edgeCells(){const out=[];for(let i=0;i<SIZE;i++)out.push({r:0,c:i},{r:SIZE-1,c:i});for(let i=1;i<SIZE-1;i++)out.push({r:i,c:0},{r:i,c:SIZE-1});return out}
function prepareIncoming(){const live=aliveEnemies().length,cap=Math.min(19,7+Math.floor(game.round/2));let count=game.round>=22?4:game.round>=10?3:game.round>=4?2:1;count=Math.max(0,Math.min(count,cap-live));const edges=shuffle(edgeCells().filter(p=>!occupied(game,p.r,p.c))),types=availableEnemyTypes(game.round),incoming=[];for(let i=0;i<count&&i<edges.length;i++){let type=types[randomInt(types.length)];if(["bomber","commander"].includes(type)&&incoming.some(x=>x.type===type))type="grunt";incoming.push({...edges[i],type})}game.incoming=incoming}
function spawnIncoming(){for(const s of game.incoming)if(!occupied(game,s.r,s.c))game.enemies.push(makeEnemy(s.type,s.r,s.c));game.incoming=[]}
function planCellSets(){const danger=new Set,route=new Set,marked=new Set,explode=new Set,forced=new Set;for(const e of aliveEnemies()){const p=e.plan||{kind:"wait"};if(["attack","shoot","attackPush","pull"].includes(p.kind)&&p.target)danger.add(key(p.target.r,p.target.c));if(["move","charge"].includes(p.kind))for(const x of p.path||[])route.add(key(x.r,x.c));if(["mark","explode"].includes(p.kind)&&p.center)for(const x of plusArea(p.center,true))(p.kind==="mark"?marked:explode).add(key(x.r,x.c));if(p.kind==="pull"&&p.target){const r=p.target.r+Math.sign(e.r-p.target.r),c=p.target.c+Math.sign(e.c-p.target.c);if(inside(r,c))forced.add(key(r,c))}if(p.kind==="attackPush"&&p.target){const r=p.target.r+Math.sign(p.target.r-e.r),c=p.target.c+Math.sign(p.target.c-e.c);if(inside(r,c))forced.add(key(r,c))}}return{danger,route,marked,explode,forced}}
function intentSymbol(e){return({wait:e.plan?.stunned?"×":"·",attack:"!",attackPush:"»",shoot:"→",pull:"↶",mark:"○",explode:"×",command:"+",charge:"»",move:"›"})[e.plan?.kind]||"·"}
