function render(){
  if(!game)return;const h=selectedHero(),targets=getActionTargets(h),targetKeys=new Set(targets.map(t=>key(t.r,t.c))),preview=previewTarget?getPreviewArea(h,actionMode,previewTarget):{friendly:[],hostile:[]},friendlyKeys=new Set(preview.friendly.map(p=>key(p.r,p.c))),hostileKeys=new Set(preview.hostile.map(p=>key(p.r,p.c))),sets=planCellSets();
  for(const cell of cells){const r=+cell.dataset.r,c=+cell.dataset.c,k=key(r,c);cell.className="cell";cell.innerHTML="";if(sets.route.has(k))cell.classList.add("enemy-route");if(sets.danger.has(k))cell.classList.add("enemy-danger");if(sets.marked.has(k))cell.classList.add("enemy-marked");if(sets.explode.has(k))cell.classList.add("enemy-explode");if(sets.forced.has(k))cell.classList.add("forced-destination");if(targetKeys.has(k)){cell.classList.add("legal");if(actionMode==="move")cell.classList.add("move-target")}if(friendlyKeys.has(k))cell.classList.add("preview-friendly");if(hostileKeys.has(k))cell.classList.add("preview-hostile");if(r===BEACON.r&&c===BEACON.c){const b=document.createElement("div");b.className="beacon";cell.appendChild(b)}const hero=heroAt(game,r,c),enemy=enemyAt(game,r,c),spawn=game.incoming.find(x=>x.r===r&&x.c===c);if(hero)cell.appendChild(renderHero(hero));else if(enemy)cell.appendChild(renderEnemy(enemy));else if(spawn)cell.appendChild(renderSpawn(spawn))}
  drawIntentLayer();roundLabel.textContent=String(game.round).padStart(2,"0");enemyCount.textContent=String(aliveEnemies().length).padStart(2,"0");renderSquad();renderControls();
}
function makePieceVisual(file,letter,alt){if(assetStatus.get(file)!==false){const img=document.createElement("img");img.className="piece-image";img.src=ASSET_ROOT+file;img.alt=alt;img.draggable=false;img.addEventListener("error",()=>{assetStatus.set(file,false);img.replaceWith(makeFallback(letter))},{once:true});return img}return makeFallback(letter)}
function makeFallback(letter){const s=document.createElement("span");s.className="piece-fallback";s.textContent=letter;return s}
function renderHealthPips(current,max){const w=document.createElement("span");w.className="health-pips";for(let i=1;i<=max;i++){const p=document.createElement("span");p.className="health-pip";if(i<=current)p.classList.add("filled");if(current===1&&i===1)p.classList.add("last");w.appendChild(p)}return w}
function renderHero(h){const d=HERO_DATA[h.type],u=document.createElement("div");u.className="unit hero";if(h.id===selectedHeroId)u.classList.add("selected");if(h.acted)u.classList.add("acted");u.title=d.name;u.appendChild(makePieceVisual(d.image,d.letter,d.name));u.appendChild(renderHealthPips(h.hp,h.maxHp));if(h.cooldown>0){const c=document.createElement("span");c.className="cooldown-mark";c.textContent=String(h.cooldown);u.appendChild(c)}if(h.guard>0||h.armor>0){const s=document.createElement("span");s.className="status-mark";s.textContent=h.guard>0?"◇":"□";u.appendChild(s)}return u}
function renderEnemy(e){const d=ENEMY_DATA[e.type],u=document.createElement("div");u.className="unit enemy";if(e.commanded)u.classList.add("commanded");u.title=e.type.toUpperCase();u.appendChild(makePieceVisual(d.image,d.letter,e.type));u.appendChild(renderHealthPips(e.hp,e.maxHp));const o=document.createElement("span");o.className="order-mark";o.textContent=String(e.order||"");u.appendChild(o);const i=document.createElement("span");i.className="intent-mark";i.textContent=intentSymbol(e);u.appendChild(i);return u}
function renderSpawn(s){const d=ENEMY_DATA[s.type],w=document.createElement("div");w.className="spawn-ghost";w.title=`Incoming ${s.type}`;w.appendChild(makePieceVisual(d.image,d.letter,`Incoming ${s.type}`));return w}
function renderSquad(){squadStatus.innerHTML="";for(const h of game.heroes){const d=document.createElement("span");d.className="squad-dot";if(!h.alive)d.classList.add("lost");else if(h.hp===1)d.classList.add("wounded");squadStatus.appendChild(d)}}
function renderControls(){const h=selectedHero(),can=!!(h&&!h.acted&&game.phase==="player"),pick=actionMode==="bannerPick";moveButton.disabled=!can||pick;attackButton.disabled=!can||pick;guardButton.disabled=!can||pick;specialButton.disabled=!can||h?.cooldown>0||pick;endButton.disabled=game.phase!=="player"||pick;moveButton.classList.toggle("active",actionMode==="move");attackButton.classList.toggle("active",actionMode==="attack");guardButton.classList.toggle("active",actionMode==="guard");specialButton.classList.toggle("active",actionMode==="special"||pick);specialButton.classList.toggle("special-ready",can&&h.cooldown===0);if(!h){unitLine.textContent=game.phase==="player"?"SELECT A UNIT":"";specialButton.textContent="SPECIAL"}else if(pick){unitLine.textContent="RALLY · CHOOSE ONE ALLY";specialButton.textContent="RALLY"}else{const d=HERO_DATA[h.type];unitLine.textContent=`${d.name} · ${h.hp}/${h.maxHp}`;specialButton.textContent=h.cooldown>0?`${d.special} ${h.cooldown}`:d.special}}
function cellCenter(p){return{x:p.c*100+50,y:p.r*100+50}}
function svgLine(from,to,opt={}){const a=cellCenter(from),b=cellCenter(to),l=document.createElementNS("http://www.w3.org/2000/svg","line");l.setAttribute("x1",a.x);l.setAttribute("y1",a.y);l.setAttribute("x2",b.x);l.setAttribute("y2",b.y);l.setAttribute("stroke",opt.color||"#111");l.setAttribute("stroke-width",opt.width||"4");l.setAttribute("stroke-linecap","round");l.setAttribute("opacity",opt.opacity||".82");if(opt.dash)l.setAttribute("stroke-dasharray",opt.dash);if(opt.marker)l.setAttribute("marker-end",`url(#${opt.marker})`);intentLayer.appendChild(l)}
function drawIntentLayer(){intentLayer.innerHTML='<defs><marker id="arrowBlack" markerWidth="8" markerHeight="8" refX="6" refY="4" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L8,4 L0,8 Z" fill="#111"></path></marker><marker id="arrowRed" markerWidth="8" markerHeight="8" refX="6" refY="4" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L8,4 L0,8 Z" fill="#c91919"></path></marker></defs>';for(const e of aliveEnemies()){const p=e.plan||{kind:"wait"};if(["move","charge"].includes(p.kind)&&p.path?.length)svgLine(e,p.path.at(-1),{color:"#111",width:p.kind==="charge"?"6":"4",marker:"arrowBlack",dash:p.kind==="charge"?"12 6":null});if(["attack","shoot","attackPush"].includes(p.kind)&&p.target)svgLine(e,p.target,{color:"#c91919",width:p.kind==="shoot"?"3":"5",marker:"arrowRed",dash:p.kind==="shoot"?"9 5":null});if(p.kind==="pull"&&p.target)svgLine(e,p.target,{color:"#c91919",width:"4",marker:"arrowRed",dash:"5 5"});if(p.kind==="attackPush"&&p.target){const x={r:p.target.r+Math.sign(p.target.r-e.r),c:p.target.c+Math.sign(p.target.c-e.c)};if(inside(x.r,x.c))svgLine(p.target,x,{color:"#c91919",width:"4",marker:"arrowRed"})}if(p.kind==="command")for(const id of p.targetIds||[]){const x=game.enemies.find(y=>y.id===id&&y.alive);if(x)svgLine(e,x,{color:"#111",width:"3",dash:"6 7",opacity:".6"})}}}
function setActionMode(mode){const h=selectedHero();if(!h||h.acted||game.phase!=="player"||actionMode==="bannerPick")return;if(mode==="special"&&h.cooldown>0)return;actionMode=mode;previewTarget=null;previewLocked=false;render()}
function onCellEnter(ev){if(!hoverCapable||previewLocked||game?.phase!=="player")return;const h=selectedHero();if(!h)return;const t=legalTargetAt(+ev.currentTarget.dataset.r,+ev.currentTarget.dataset.c);if(t){previewTarget=t;render()}}
function onCellLeave(){if(!hoverCapable||previewLocked||game?.phase!=="player")return;previewTarget=null;render()}
function legalTargetAt(r,c){const h=selectedHero();return h?getActionTargets(h).find(t=>t.r===r&&t.c===c)||null:null}
function onCellClick(ev){if(!game||game.phase!=="player"||game.over)return;const r=+ev.currentTarget.dataset.r,c=+ev.currentTarget.dataset.c,clicked=heroAt(game,r,c),current=selectedHero();if(actionMode!=="bannerPick"&&clicked&&!clicked.acted&&(!current||!legalTargetAt(r,c))){selectedHeroId=clicked.id;actionMode="move";previewTarget=null;previewLocked=false;pendingBanner=null;return render()}if(!current||current.acted)return;const target=legalTargetAt(r,c);if(!target){previewTarget=null;previewLocked=false;return render()}const same=previewTarget&&previewTarget.r===r&&previewTarget.c===c;if(!hoverCapable&&!same){previewTarget=target;previewLocked=true;return render()}executeAction(current,actionMode,target)}
moveButton.addEventListener("click",()=>setActionMode("move"));attackButton.addEventListener("click",()=>setActionMode("attack"));guardButton.addEventListener("click",()=>setActionMode("guard"));specialButton.addEventListener("click",()=>setActionMode("special"));endButton.addEventListener("click",endPlayerTurn);
async function endPlayerTurn(){if(game.phase!=="player"||game.over||actionMode==="bannerPick")return;game.phase="enemy";selectedHeroId=null;actionMode="move";previewTarget=null;previewLocked=false;render();const ordered=aliveEnemies().slice().sort((a,b)=>(a.order||999)-(b.order||999));for(const planned of ordered){if(game.over)break;const e=game.enemies.find(x=>x.id===planned.id&&x.alive);if(!e)continue;executePlan(game,e,e.plan);render();flashBoard();await delay(115);checkGameOver()}if(game.over)return;spawnIncoming();game.enemies=game.enemies.filter(e=>e.alive);checkGameOver();if(game.over)return;game.completedRounds=game.round;if(game.completedRounds%5===0)showUpgradeChoices();else{game.round++;beginRound()}}
function delay(ms){return new Promise(r=>setTimeout(r,ms))}function flashBoard(){boardEl.classList.remove("flash");void boardEl.offsetWidth;boardEl.classList.add("flash")}function checkGameOver(){if(!game.heroes.some(h=>h.alive)||game.enemies.some(e=>e.alive&&e.r===BEACON.r&&e.c===BEACON.c))endGame()}function endGame(){game.over=true;game.phase="over";finalRound.textContent=String(game.completedRounds||Math.max(0,game.round-1));gameOverOverlay.classList.add("show");render()}
const UPGRADE_POOL=[
{id:"bladePower",max:2,symbol:"B+",name:"HEAVY EDGE",text:"Sweep deals one more damage.",apply(){game.upgrades.bladePower++}},
{id:"shieldDiagonal",max:1,symbol:"S+",name:"WIDE BULWARK",text:"Bulwark also protects diagonal spaces.",apply(){game.upgrades.shieldDiagonal=true}},
{id:"spearReach",max:1,symbol:"P+",name:"LONG SHAFT",text:"Impale may target four spaces away.",apply(){game.upgrades.spearReach=4}},
{id:"spearFlexible",max:1,symbol:"P1",name:"SHORT GRIP",text:"Spear attacks at range one or two.",apply(){game.upgrades.spearFlexible=true}},
{id:"bowDiagonal",max:1,symbol:"W+",name:"WIDE VOLLEY",text:"Volley also hits diagonal spaces.",apply(){game.upgrades.bowDiagonal=true}},
{id:"bowPierce",max:1,symbol:"W2",name:"PIERCING SHOT",text:"Bow attacks may hit a second enemy in line.",apply(){game.upgrades.bowPierce=true}},
{id:"bannerRange",max:1,symbol:"N+",name:"LONG STANDARD",text:"Rally may be placed three spaces away.",apply(){game.upgrades.bannerRange=3}},
{id:"counter",max:1,symbol:"↺",name:"COUNTER",text:"A guarded adjacent attacker takes one damage.",apply(){game.upgrades.counter=true}},
{id:"cooldown",max:2,symbol:"★",name:"BATTLE RHYTHM",text:"All special cooldowns become one round shorter.",apply(){game.upgrades.cooldownReduction++}},
{id:"reserve",max:1,symbol:"◇",name:"LAST STAND",text:"The first unguarded hit each round is blocked.",apply(){game.upgrades.reserve=true}},
{id:"brace",max:1,symbol:"▣",name:"BRACE",text:"Your warriors can no longer be pushed.",apply(){game.upgrades.brace=true}},
{id:"finisher",max:1,symbol:"×2",name:"FINISHER",text:"Attacks deal extra damage to wounded enemies.",apply(){game.upgrades.finisher=true}},
{id:"medic",max:99,symbol:"+",name:"FIELD MEDIC",text:"Heal every surviving warrior.",apply(){for(const h of aliveHeroes())h.hp=h.maxHp}},
{id:"armor",max:99,symbol:"□",name:"LIGHT PLATE",text:"Every survivor blocks one future hit.",apply(){for(const h of aliveHeroes())h.armor++}},
{id:"focus",max:99,symbol:"◎",name:"BATTLE FOCUS",text:"Every surviving special becomes ready.",apply(){for(const h of aliveHeroes())h.cooldown=0}},
{id:"rescue",max:99,symbol:"●",name:"RESCUE",text:"Return one lost warrior with one health.",available(){return game.heroes.some(h=>!h.alive)},apply(){reviveOneHero()}}
];
function showUpgradeChoices(){game.phase="upgrade";selectedHeroId=null;actionMode="move";previewTarget=null;pendingBanner=null;upgradeCards.innerHTML="";for(const u of getUpgradeOptions(3)){const card=document.createElement("button");card.type="button";card.className="card";card.innerHTML=`<div class="card-symbol">${u.symbol}</div><div class="card-name">${u.name}</div><div class="card-text">${u.text}</div>`;card.addEventListener("click",()=>chooseUpgrade(u));upgradeCards.appendChild(card)}upgradeOverlay.classList.add("show");render()}
function getUpgradeOptions(count){let a=UPGRADE_POOL.filter(u=>(typeof u.available!=="function"||u.available())&&(game.upgradeRanks[u.id]||0)<u.max);if(a.length<count)a=a.concat(UPGRADE_POOL.filter(u=>["medic","armor","focus"].includes(u.id)));const out=[];for(const u of shuffle(a)){if(!out.some(x=>x.id===u.id))out.push(u);if(out.length>=count)break}return out}
function chooseUpgrade(u){game.upgradeRanks[u.id]=(game.upgradeRanks[u.id]||0)+1;u.apply();upgradeOverlay.classList.remove("show");game.round++;beginRound()}
function reviveOneHero(){const f=game.heroes.find(h=>!h.alive);if(!f)return;const open=[{r:3,c:3},{r:3,c:2},{r:3,c:4},{r:2,c:3},{r:4,c:3},...edgeCells()].find(p=>inside(p.r,p.c)&&!occupied(game,p.r,p.c));if(!open)return;Object.assign(f,{alive:true,hp:1,acted:true,guard:0,cooldown:Math.max(2,f.cooldown),r:open.r,c:open.c})}
beginButton.addEventListener("click",()=>{loadingOverlay.classList.remove("show");newGame()});restartButton.addEventListener("click",newGame);createBoard();loadAssets();
