"use strict";

const SIZE=7,BEACON={r:3,c:3},ASSET_ROOT="../graphics/lastfive/";
const ORTHOGONAL=[{r:-1,c:0},{r:1,c:0},{r:0,c:-1},{r:0,c:1}],DIAGONAL=[{r:-1,c:-1},{r:-1,c:1},{r:1,c:-1},{r:1,c:1}];
const HERO_DATA={blade:{letter:"B",name:"BLADE",special:"SWEEP",cooldown:3,image:"player_blade.png"},shield:{letter:"S",name:"SHIELD",special:"BULWARK",cooldown:4,image:"player_shield.png"},spear:{letter:"P",name:"SPEAR",special:"IMPALE",cooldown:3,image:"player_spear.png"},bow:{letter:"W",name:"BOW",special:"VOLLEY",cooldown:4,image:"player_bow.png"},banner:{letter:"N",name:"BANNER",special:"RALLY",cooldown:5,image:"player_banner.png"}};
const ENEMY_DATA={grunt:{letter:"G",hp:1,initiative:5,image:"enemy_grunt.png"},raider:{letter:"R",hp:1,initiative:3,image:"enemy_raider.png"},archer:{letter:"A",hp:1,initiative:7,image:"enemy_archer.png"},brute:{letter:"B",hp:3,initiative:6,image:"enemy_brute.png"},hook:{letter:"H",hp:2,initiative:2,image:"enemy_hook.png"},guardian:{letter:"D",hp:2,initiative:4,image:"enemy_guardian.png"},bomber:{letter:"O",hp:1,initiative:8,image:"enemy_bomber.png"},commander:{letter:"C",hp:2,initiative:1,image:"enemy_commander.png"}};
const ASSET_FILES=[...Object.values(HERO_DATA).map(x=>x.image),...Object.values(ENEMY_DATA).map(x=>x.image)];
const boardEl=document.getElementById("board"),intentLayer=document.getElementById("intentLayer"),roundLabel=document.getElementById("roundLabel"),squadStatus=document.getElementById("squadStatus"),enemyCount=document.getElementById("enemyCount"),unitLine=document.getElementById("unitLine"),moveButton=document.getElementById("moveButton"),attackButton=document.getElementById("attackButton"),guardButton=document.getElementById("guardButton"),specialButton=document.getElementById("specialButton"),endButton=document.getElementById("endButton"),loadingOverlay=document.getElementById("loadingOverlay"),loadingIcons=document.getElementById("loadingIcons"),loadingFill=document.getElementById("loadingFill"),beginButton=document.getElementById("beginButton"),upgradeOverlay=document.getElementById("upgradeOverlay"),upgradeCards=document.getElementById("upgradeCards"),gameOverOverlay=document.getElementById("gameOverOverlay"),finalRound=document.getElementById("finalRound"),restartButton=document.getElementById("restartButton");
const assetStatus=new Map(),hoverCapable=window.matchMedia("(hover: hover) and (pointer: fine)").matches;
let cells=[],nextId=1,seed=(Date.now()^0x9e3779b9)>>>0,selectedHeroId=null,actionMode="move",previewTarget=null,previewLocked=false,pendingBanner=null,game=null;
function random(){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296}function randomInt(max){return Math.floor(random()*max)}function shuffle(items){const copy=items.slice();for(let i=copy.length-1;i>0;i--){const j=randomInt(i+1);[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function key(r,c){return`${r},${c}`}function inside(r,c){return r>=0&&r<SIZE&&c>=0&&c<SIZE}function manhattan(a,b){return Math.abs(a.r-b.r)+Math.abs(a.c-b.c)}function sameCell(a,b){return a.r===b.r&&a.c===b.c}
function createBoard(){for(const oldCell of boardEl.querySelectorAll(".cell"))oldCell.remove();cells=[];for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){const cell=document.createElement("button");cell.type="button";cell.className="cell";cell.dataset.r=String(r);cell.dataset.c=String(c);cell.setAttribute("role","gridcell");cell.setAttribute("aria-label",`Row ${r+1}, column ${c+1}`);cell.addEventListener("click",onCellClick);cell.addEventListener("pointerenter",onCellEnter);cell.addEventListener("pointerleave",onCellLeave);boardEl.insertBefore(cell,intentLayer);cells.push(cell)}}
function loadAssets(){loadingIcons.innerHTML="";let completed=0;const jobs=ASSET_FILES.map(file=>new Promise(resolve=>{const icon=document.createElement("img");icon.className="loading-icon";icon.alt="";icon.src=ASSET_ROOT+file;loadingIcons.appendChild(icon);const finish=success=>{assetStatus.set(file,success);icon.classList.add(success?"loaded":"failed");completed++;loadingFill.style.width=`${completed/ASSET_FILES.length*100}%`;resolve()};icon.addEventListener("load",()=>finish(true),{once:true});icon.addEventListener("error",()=>finish(false),{once:true})}));Promise.all(jobs).then(()=>beginButton.disabled=false)}
function makeHero(type,r,c){return{id:nextId++,type,r,c,alive:true,maxHp:2,hp:2,acted:false,guard:0,cooldown:0,armor:0}}
function makeEnemy(type,r,c){const data=ENEMY_DATA[type];return{id:nextId++,type,r,c,hp:data.hp,maxHp:data.hp,alive:true,stunned:0,shieldBroken:false,bombArmed:false,bombTarget:null,commanded:false,plan:{kind:"wait"}}}
function emptyUpgrades(){return{bladePower:0,shieldDiagonal:false,spearReach:3,spearFlexible:false,bowDiagonal:false,bowPierce:false,bannerRange:2,counter:false,cooldownReduction:0,reserve:false,brace:false,finisher:false}}
function newGame(){nextId=1;selectedHeroId=null;actionMode="move";previewTarget=null;previewLocked=false;pendingBanner=null;seed=(Date.now()^0x9e3779b9)>>>0;game={round:1,completedRounds:0,phase:"player",heroes:[makeHero("blade",3,2),makeHero("shield",3,3),makeHero("spear",2,3),makeHero("bow",4,3),makeHero("banner",3,4)],enemies:[makeEnemy("grunt",0,3),makeEnemy("grunt",6,3),makeEnemy("grunt",3,0)],incoming:[],upgrades:emptyUpgrades(),upgradeRanks:{},reserveUsed:false,safeLines:0,over:false};upgradeOverlay.classList.remove("show");gameOverOverlay.classList.remove("show");beginRound()}
function aliveHeroes(state=game){return state.heroes.filter(h=>h.alive)}function aliveEnemies(state=game){return state.enemies.filter(e=>e.alive)}function heroAt(state,r,c){return state.heroes.find(h=>h.alive&&h.r===r&&h.c===c)||null}function enemyAt(state,r,c){return state.enemies.find(e=>e.alive&&e.r===r&&e.c===c)||null}
function occupied(state,r,c,ignoreId=null){return!!(state.heroes.some(h=>h.alive&&h.id!==ignoreId&&h.r===r&&h.c===c)||state.enemies.some(e=>e.alive&&e.id!==ignoreId&&e.r===r&&e.c===c))}function selectedHero(){return game?.heroes.find(h=>h.id===selectedHeroId&&h.alive)||null}
function beginRound(){if(game.over)return;game.phase="player";game.reserveUsed=false;selectedHeroId=null;actionMode="move";previewTarget=null;previewLocked=false;pendingBanner=null;for(const hero of game.heroes){if(!hero.alive)continue;hero.acted=false;hero.guard=0;if(hero.cooldown>0)hero.cooldown--}for(const enemy of game.enemies){if(!enemy.alive)continue;enemy.shieldBroken=false;enemy.commanded=false;enemy.plan=createEnemyPlan(game,enemy)}applyCommanderPlanning();assignInitiative();ensureFlawlessLine();prepareIncoming();render()}
function chooseTargetPosition(state,enemy){const candidates=aliveHeroes(state).map(hero=>({r:hero.r,c:hero.c,weight:hero.hp===1?-.35:0}));candidates.push({r:BEACON.r,c:BEACON.c,weight:.75});candidates.sort((a,b)=>manhattan(enemy,a)+a.weight-(manhattan(enemy,b)+b.weight));return candidates[0]||BEACON}
function lineClear(state,from,to,ignoreA=null,ignoreB=null){if(from.r!==to.r&&from.c!==to.c)return false;const dr=Math.sign(to.r-from.r),dc=Math.sign(to.c-from.c);let r=from.r+dr,c=from.c+dc;while(r!==to.r||c!==to.c){const unit=heroAt(state,r,c)||enemyAt(state,r,c);if(unit&&unit.id!==ignoreA&&unit.id!==ignoreB)return false;r+=dr;c+=dc}return true}
function nearestAlignedHero(state,enemy,minRange,maxRange){return aliveHeroes(state).filter(hero=>{const aligned=hero.r===enemy.r||hero.c===enemy.c,distance=manhattan(hero,enemy);return aligned&&distance>=minRange&&distance<=maxRange&&lineClear(state,enemy,hero,enemy.id,hero.id)}).sort((a,b)=>manhattan(a,enemy)-manhattan(b,enemy))[0]||null}
function greedyPath(state,unit,target,maxSteps,start=null){const path=[];let current=start?{...start}:{r:unit.r,c:unit.c};for(let step=0;step<maxSteps;step++){const options=ORTHOGONAL.map(d=>({r:current.r+d.r,c:current.c+d.c})).filter(p=>inside(p.r,p.c)).filter(p=>!occupied(state,p.r,p.c,unit.id)).sort((a,b)=>manhattan(a,target)-manhattan(b,target));if(!options.length||manhattan(options[0],target)>=manhattan(current,target))break;current=options[0];path.push({...current})}return path}
