/* Rendering: moving villagers, more distinct high-threat enemies, and a larger map. */
function drawVillageNPC(n){
 const s=worldToScreen(n.x,n.y),near=dist(n,game.player)<1.45,bob=Math.sin(elapsed*6+n.phase)*1.2;shadowAt(n.x,n.y,14,.22);ctx.save();ctx.translate(s.x,s.y-13+bob);const step=Math.sin(elapsed*7+n.phase)*3;ctx.strokeStyle='#2b3441';ctx.lineWidth=4;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-3,4);ctx.lineTo(-5+step*.25,15);ctx.moveTo(3,4);ctx.lineTo(5-step*.25,15);ctx.stroke();ctx.fillStyle=n.color;ctx.beginPath();ctx.moveTo(-9,-10);ctx.lineTo(9,-10);ctx.lineTo(7,7);ctx.lineTo(-7,7);ctx.closePath();ctx.fill();ctx.fillStyle='#e2bda2';ctx.beginPath();ctx.arc(0,-17,6.5,0,TAU);ctx.fill();ctx.fillStyle='#49382f';ctx.beginPath();ctx.arc(0,-19,6.6,Math.PI,TAU);ctx.fill();ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillText(n.role==='Blacksmith'?'⚒':n.role==='Merchant'?'👜':n.role==='Quest Keeper'?'!':n.role==='Alchemist'?'⚗':'•',0,-31);if(near){ctx.fillStyle='rgba(4,9,16,.88)';ctx.strokeStyle='rgba(255,255,255,.2)';ctx.beginPath();ctx.roundRect(-60,-55,120,22,10);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font='900 9px system-ui';ctx.fillText(`${isTouch?'USE':'E'} • ${n.name} • ${n.role}`,0,-40)}ctx.restore()
}
const _baseDrawInteractable=drawInteractable;
drawInteractable=function(o){if(o?.npc)return drawVillageNPC(o);return _baseDrawInteractable(o)};
const _baseDrawEnemyBody=drawEnemyBody;
drawEnemyBody=function(e){
 const c=e.flash>0?'#fff':e.color;ctx.fillStyle=c;ctx.strokeStyle='rgba(0,0,0,.5)';ctx.lineWidth=2;
 if(e.hidden){ctx.globalAlpha=.18;ctx.beginPath();ctx.ellipse(0,-5,17,7,0,0,TAU);ctx.fill();return}
 if(e.ai==='bladeDancer'){ctx.beginPath();ctx.moveTo(0,-31);ctx.lineTo(11,-10);ctx.lineTo(6,4);ctx.lineTo(-6,4);ctx.lineTo(-11,-10);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle='#dffaff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-8,-8);ctx.lineTo(-22,-20);ctx.moveTo(8,-8);ctx.lineTo(22,-20);ctx.stroke();ctx.fillStyle='#d9c1ac';ctx.beginPath();ctx.arc(0,-20,5,0,TAU);ctx.fill();return}
 if(e.ai==='mortarWitch'){ctx.beginPath();ctx.moveTo(0,-34);ctx.lineTo(14,4);ctx.lineTo(-14,4);ctx.closePath();ctx.fill();ctx.fillStyle='#e3c0ae';ctx.beginPath();ctx.arc(0,-20,6,0,TAU);ctx.fill();ctx.strokeStyle=e.proj;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(10,-4);ctx.lineTo(20,-28);ctx.stroke();ctx.fillStyle=e.proj;ctx.beginPath();ctx.arc(20,-31,6,0,TAU);ctx.fill();return}
 if(e.ai==='chainWarden'){ctx.fillRect(-13,-23,26,25);ctx.fillStyle='#a98e68';ctx.fillRect(-18,-17,7,21);ctx.fillRect(11,-17,7,21);ctx.strokeStyle='#d8c49d';ctx.lineWidth=2;for(let i=0;i<4;i++){ctx.beginPath();ctx.arc(17+i*3,-5+i*3,3,0,TAU);ctx.stroke()}ctx.fillStyle='#c2aa82';ctx.beginPath();ctx.arc(0,-27,8,0,TAU);ctx.fill();return}
 if(e.ai==='mirrorMage'){ctx.beginPath();ctx.moveTo(0,-33);ctx.lineTo(13,3);ctx.lineTo(-13,3);ctx.closePath();ctx.fill();ctx.strokeStyle='#e6ecff';ctx.lineWidth=1.5;for(let i=0;i<3;i++){ctx.save();ctx.rotate(i*TAU/3+elapsed*.7);ctx.strokeRect(9,-16,8,14);ctx.restore()}ctx.fillStyle='#cdd5ff';ctx.beginPath();ctx.arc(0,-21,5,0,TAU);ctx.fill();return}
 if(e.ai==='burrower'){ctx.beginPath();ctx.ellipse(0,-9,18,14,0,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#d0b17d';for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(i*6,-18);ctx.lineTo(i*7,-30);ctx.lineTo(i*3,-18);ctx.fill()}ctx.fillStyle='#fff0b3';ctx.beginPath();ctx.arc(-6,-11,2,0,TAU);ctx.arc(6,-11,2,0,TAU);ctx.fill();return}
 if(e.ai==='warPriest'){ctx.beginPath();ctx.moveTo(0,-34);ctx.lineTo(16,4);ctx.lineTo(-16,4);ctx.closePath();ctx.fill();ctx.strokeStyle=e.proj;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-17,13,0,TAU);ctx.stroke();ctx.fillStyle='#ead6c1';ctx.beginPath();ctx.arc(0,-21,6,0,TAU);ctx.fill();ctx.fillStyle=e.proj;ctx.fillRect(-2,-14,4,15);ctx.fillRect(-7,-9,14,4);return}
 if(e.ai==='stormCaller'||e.ai==='bossOracle'){ctx.beginPath();ctx.moveTo(-15,-2);ctx.lineTo(-8,-25);ctx.lineTo(0,-34);ctx.lineTo(8,-25);ctx.lineTo(15,-2);ctx.closePath();ctx.fill();ctx.strokeStyle=e.proj;ctx.lineWidth=2;for(let i=0;i<3;i++){const a=elapsed*1.8+i*TAU/3;ctx.beginPath();ctx.arc(Math.cos(a)*18,-15+Math.sin(a)*7,3,0,TAU);ctx.stroke()}ctx.fillStyle='#d9edf0';ctx.beginPath();ctx.arc(0,-22,5,0,TAU);ctx.fill();return}
 if(e.ai==='executioner'||e.ai==='bossExecutioner'){ctx.fillRect(-14,-24,28,26);ctx.fillStyle='#b09a88';ctx.beginPath();ctx.moveTo(-11,-25);ctx.lineTo(0,-38);ctx.lineTo(11,-25);ctx.closePath();ctx.fill();ctx.strokeStyle=e.proj;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(13,1);ctx.lineTo(22,-31);ctx.stroke();ctx.fillStyle=e.proj;ctx.beginPath();ctx.moveTo(17,-33);ctx.lineTo(30,-39);ctx.lineTo(25,-24);ctx.closePath();ctx.fill();return}
 return _baseDrawEnemyBody(e);
};
const _baseDrawEnemy=drawEnemy;
drawEnemy=function(e){_baseDrawEnemy(e);if(e.trait&&!e.boss){const s=worldToScreen(e.x,e.y,47);ctx.save();ctx.fillStyle='rgba(5,9,15,.8)';ctx.beginPath();ctx.roundRect(s.x-27,s.y-8,54,12,6);ctx.fill();ctx.fillStyle='#ffd477';ctx.font='900 7px system-ui';ctx.textAlign='center';ctx.fillText(e.trait.toUpperCase(),s.x,s.y);ctx.restore()}};

const _baseGearCard=gearCard;
gearCard=function(item,label){
 if(!item)return `<div class="gear-card empty-gear"><div class="rarity">${label}</div><div class="gear-preview">＋</div><div class="choice-name">Empty Trinket Slot</div></div>`;
 let stats;if(item.slot==='weapon')stats=[['Power',Math.round(item.power*(item.damage||1))],['Attack',`${item.attack.toFixed(2)}x`],['Range',(item.range||0).toFixed(1)],['Forge',`+${item.forge||0}`]];
 else if(item.slot==='armor')stats=[['Bonus HP',`+${Math.round(item.hpBonus)}`],['HP scale',`${Math.round(item.hp*100)}%`],['Armor',`${Math.round(item.armorBonus*100)}%`],['Move',`${Math.round(item.move*100)}%`]];
 else stats=Object.entries(item.mods||{}).slice(0,4).map(([k,v])=>[capitalize(k),`+${Math.round(v*100)}%`]);
 const aff=[item.prefixText,item.suffixText].filter(Boolean).map(t=>`<div class="affix-line">${t}</div>`).join('');return `<div class="gear-card" style="border-color:${colorAlpha(rarityColors[item.rarity],.38)}"><div class="rarity" style="color:${rarityColors[item.rarity]}">${label} • ${item.rarity}</div><div class="gear-preview">${item.icon}</div><div class="choice-name">${item.name}</div>${item.desc&&item.slot==='trinket'?`<div class="trinket-desc">${item.desc}</div>`:''}<div class="stats">${stats.map(([a,b])=>`<div class="stat">${a}<b>${b}</b></div>`).join('')}</div>${aff}</div>`;
};
openLootOverlay=function(){
 if(!game.loot)return;let currentHtml;if(game.loot.slot==='trinket')currentHtml=`<div class="trinket-compare">${(game.player.trinkets||[]).map((t,i)=>gearCard(t,`Trinket ${i+1}`)).join('')}</div>`;else currentHtml=gearCard(game.loot.slot==='weapon'?game.player.weapon:game.player.armorGear,'Equipped');$('lootCompare').innerHTML=currentHtml+gearCard(game.loot,'Found');$('lootCompare').classList.toggle('trinket-loot',game.loot.slot==='trinket');showOverlay('lootOverlay')
};
const _baseEquipLoot=equipLoot;
equipLoot=function(){
 const item=game.loot;if(!item)return;if(item.slot!=='trinket')return _baseEquipLoot();ensureExpansionState();const empty=game.player.trinkets.findIndex(t=>!t);if(empty>=0){game.player.trinkets[empty]=item;game.loot=null;closeOverlay('lootOverlay');recomputePlayerStats(true);toastMsg(`Equipped ${item.name} in trinket slot ${empty+1}.`);saveGame();updateHUD();return}closeOverlay('lootOverlay');renderTrinketPicker(item);showOverlay('trinketSlotPanel')
};
function renderTrinketPicker(item){$('trinketChoices').innerHTML=game.player.trinkets.map((t,i)=>`<button class="trinket-slot-choice" data-slot="${i}">${gearCard(t,`Replace slot ${i+1}`)}</button>`).join('');$('trinketFound').innerHTML=gearCard(item,'New Trinket');$('trinketChoices').querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.slot);game.player.trinkets[i]=game.loot;game.loot=null;closeOverlay('trinketSlotPanel');recomputePlayerStats(true);saveGame();toastMsg(`Trinket slot ${i+1} replaced.`)})}
renderInventory=function(){
 ensureExpansionState();const p=game.player;const spellHtml=p.unlocked.map(id=>{const s=SPELLS[id],ups=p.upgrades[id]||[];return `<div class="feature" style="border-color:${colorAlpha(rarityColors[s.rarity],.25)}"><b>${s.icon} ${s.name} <span style="color:${rarityColors[s.rarity]};float:right">${s.rarity}</span></b><span>${s.desc}</span><div style="margin-top:8px;font-size:9px;color:#d9e7f5">${ups.length?ups.map(uid=>UPGRADE_POOLS[id]?.find(v=>v[0]===uid)?.[1]).filter(Boolean).join(' • '):'No mutations yet'}</div></div>`}).join('');
 const mats=Object.entries(MATERIALS).map(([k,m])=>`<div class="material-row"><span>${m.icon} ${m.name}</span><b>${game.materials[k]||0}</b></div>`).join('');const quests=game.quests.active.filter(q=>!q.claimed).map(q=>`<div class="quest-row"><span>${q.title}</span><b>${q.progress||0}/${q.target}${q.ready?' ✓':''}</b></div>`).join('')||'<div class="muted-exp">No active quests. Speak with a village Quest Keeper.</div>';
 $('inventoryContent').innerHTML=`<div class="gear-layout">${gearCard(p.weapon,'Weapon')}${gearCard(p.armorGear,'Armor')}</div><h3 class="exp-heading">Trinkets • 3 slots</h3><div class="trinket-grid">${p.trinkets.map((t,i)=>gearCard(t,`Trinket ${i+1}`)).join('')}</div><div class="inventory-exp-grid"><section><h3>Forging Materials</h3>${mats}</section><section><h3>Quest Journal</h3>${quests}</section></div><h3 style="margin:22px 0 9px">Spellbook • ${p.unlocked.length}/${Object.keys(SPELLS).length} discovered</h3><div class="feature-grid" style="grid-template-columns:repeat(auto-fit,minmax(210px,1fr));margin-top:0">${spellHtml}</div>`;
};

const _baseRenderMinimap=renderMinimap;
renderMinimap=function(){
 const root=$('minimapGrid'),mini=$('minimap');if(W<760){root.style.gridTemplateColumns='';root.style.gridTemplateRows='';mini.style.width='';mini.style.height='';return _baseRenderMinimap()}root.innerHTML='';root.style.gridTemplateColumns='repeat(7,1fr)';root.style.gridTemplateRows='repeat(7,1fr)';mini.style.width='142px';mini.style.height='142px';for(let dy=-3;dy<=3;dy++)for(let dx=-3;dx<=3;dx++){const x=game.room.x+dx,y=game.room.y+dy,r=game.rooms[roomKey(x,y)],c=document.createElement('div');c.className='map-cell';if(r?.seen)c.classList.add('seen');if(r?.cleared)c.classList.add('clear');if(r?.town)c.classList.add('town');if(r?.boss)c.classList.add('boss');if(dx===0&&dy===0)c.classList.add('current');root.appendChild(c)}
};
const _baseUpdateHUD=updateHUD;
updateHUD=function(){_baseUpdateHUD();updateExpansionHUD();const r=game.roomData;if(r){$('roomSub').textContent+=` • Region ${r.regionTier||1}${r.challenge?` • ${r.challenge}`:''}`;if(r.town&&r.x!==0)$('roomState').textContent=`Village • Tier ${r.villageLevel||1}`}};
function updateExpansionHUD(){if(!game.player||!$('materialsPill'))return;ensureExpansionState();const total=Object.values(game.materials).reduce((a,b)=>a+Number(b||0),0);$('materialsPill').innerHTML=`⚒ <span>${total}</span> materials`;}

const _baseUpdate=update;
update=function(dt){_baseUpdate(dt);if(!running||paused||modalPause||roomTransition)return;ensureExpansionState();game.expansion.wardCooldown=Math.max(0,(game.expansion.wardCooldown||0)-dt);updateVillageLife(dt)};

function injectExpansionUI(){
 const style=document.createElement('style');style.id='arcaneExpansionStyles';style.textContent=`
 #materialsPill{position:absolute;left:max(12px,env(safe-area-inset-left));bottom:max(54px,calc(env(safe-area-inset-bottom) + 48px));padding:7px 10px;border-radius:999px;font-weight:900;font-size:11px;background:linear-gradient(180deg,rgba(12,19,32,.91),rgba(6,11,20,.88));border:1px solid var(--line);box-shadow:0 12px 32px rgba(0,0,0,.28)}
 .exp-dialogue{color:#bfd0e1;line-height:1.55;padding:12px 14px;border-left:3px solid #7bb7ef;background:rgba(255,255,255,.035);border-radius:8px}.exp-shop{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.exp-buy,.exp-recipe{border:1px solid rgba(255,255,255,.1);border-radius:14px;background:rgba(255,255,255,.045);padding:14px;color:#eaf4ff;text-align:left;cursor:pointer;display:flex;flex-direction:column;gap:6px}.exp-buy:hover,.exp-recipe:hover{background:rgba(111,176,236,.1);border-color:rgba(145,205,255,.28)}.exp-buy span,.exp-recipe span,.exp-card small{font-size:10px;color:#9db1c5;line-height:1.45}.exp-buy strong,.exp-recipe strong{color:#ffd77d}.blockish{width:100%}.exp-card{padding:13px;border-radius:14px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.08);display:flex;flex-direction:column;gap:8px}.exp-good{color:#86efb0}.quest-row,.material-row{display:flex;align-items:center;justify-content:space-between;gap:9px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.06);font-size:11px}.quest-row .btn{margin-left:auto}.exp-inline{display:flex;gap:8px;flex-wrap:wrap;margin-top:7px}.forge-materials{display:flex;flex-wrap:wrap;gap:7px;margin:10px 0 14px}.forge-materials span{padding:6px 9px;border-radius:999px;background:rgba(255,255,255,.05);font-size:10px}.forge-materials b{color:#fff;margin-left:4px}.forge-recipes{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.forge-recipes .exp-card{grid-column:1/-1}.affix-line{margin-top:6px;padding:6px 8px;border-radius:8px;background:rgba(125,171,225,.08);border:1px solid rgba(125,171,225,.12);font-size:9px;color:#c8dcf0;line-height:1.35}.trinket-desc{font-size:9px;color:#a8bfd4;margin:6px 0}.trinket-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.trinket-grid .gear-card{min-height:220px}.trinket-grid .gear-preview{height:78px;font-size:42px}.trinket-compare{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.trinket-loot{grid-template-columns:1.7fr 1fr!important}.trinket-loot>.gear-card{min-height:240px}.trinket-slot-choice{border:0;background:transparent;padding:0;color:inherit;text-align:left;cursor:pointer}.trinket-slot-choice:hover{transform:translateY(-2px)}.inventory-exp-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:16px}.inventory-exp-grid section{padding:13px;border-radius:14px;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.07)}.inventory-exp-grid h3,.exp-heading{margin:0 0 9px}.muted-exp{font-size:10px;color:#8fa5ba}.empty-gear{opacity:.68}
 @media(max-width:760px){.exp-shop,.forge-recipes,.trinket-grid,.inventory-exp-grid{grid-template-columns:1fr}.trinket-compare{grid-template-columns:1fr}.trinket-loot{grid-template-columns:1fr!important}#materialsPill{bottom:132px;font-size:9px}.forge-recipes .exp-card{grid-column:auto}}
 `;document.head.appendChild(style);
 const pill=document.createElement('div');pill.id='materialsPill';$('hud').appendChild(pill);
 const wrap=document.createElement('div');wrap.innerHTML=`
 <div class="overlay hidden" id="npcPanel"><div class="panel" style="max-width:760px"><div class="overlay-head"><div><h2 id="npcName">Villager</h2><p>Village life, stores and local work.</p></div><button class="btn secondary" data-exp-close="npcPanel">Close</button></div><div id="npcBody"></div></div></div>
 <div class="overlay hidden" id="forgeCraftPanel"><div class="panel" style="max-width:900px"><div class="overlay-head"><div><h2>Runeforge & Crafting</h2><p>Turn common enemy materials into uncommon opportunities for real gear.</p></div><button class="btn secondary" data-exp-close="forgeCraftPanel">Close</button></div><div class="forge-materials" id="forgeMaterials"></div><div class="forge-recipes" id="forgeRecipes"></div></div></div>
 <div class="overlay hidden" id="trinketSlotPanel"><div class="panel" style="max-width:980px"><div class="overlay-head"><div><h2>Choose a Trinket Slot</h2><p>You can wear exactly three trinkets. Choose what the new find replaces.</p></div></div><div id="trinketFound"></div><h3>Replace one</h3><div class="trinket-grid" id="trinketChoices"></div><div class="menu-actions" style="justify-content:flex-end;margin-top:12px"><button class="btn secondary" id="cancelTrinketSwap">Keep Current Trinkets</button></div></div></div>`;
 while(wrap.firstElementChild)document.body.appendChild(wrap.firstElementChild);document.querySelectorAll('[data-exp-close]').forEach(b=>b.onclick=()=>closeOverlay(b.dataset.expClose));$('cancelTrinketSwap').onclick=()=>{game.loot=null;closeOverlay('trinketSlotPanel')};
}

injectExpansionUI();ensureExpansionState();
$('equipLootBtn').onclick=equipLoot;$('mobileDodge').onclick=dodge;$('newRunBtn').onclick=startNewGame;
updateExpansionHUD();render();
