'use strict';

function hasUpgrade(spell,id){return (game.player.upgrades[spell]||[]).some(u=>u===id || UPGRADE_POOLS[spell]?.find(v=>v[0]===u)?.[4]===id)}
function spellMods(spell){const arr=game.player.upgrades[spell]||[];return {count:arr.length,power:1+arr.length*.08,cdr:Math.max(.72,1-arr.length*.025)}}
function spellAim(){
 if(aimStick.active&&Math.hypot(aimStick.x,aimStick.y)>.18)return screenToWorldDir(aimStick.x,aimStick.y);
 if(mouse.active){const ps=worldToScreen(game.player.x,game.player.y,18);return screenToWorldDir((mouse.x-ps.x)/TILE_W,(mouse.y-ps.y)/TILE_H)}
 const t=nearestEnemy(game.player,12);return t?norm(t.x-game.player.x,t.y-game.player.y):game.player.facing;
}
function aimPoint(range=6){const d=spellAim();return {x:clamp(game.player.x+d.x*range,.7,ROOM_W-.7),y:clamp(game.player.y+d.y*range,.7,ROOM_H-.7)}}
function castSpell(slot){
 const id=game.player.activeSpells[slot];if(!id||paused||modalPause)return;
 const s=SPELLS[id], st=game.player.spellState[id]||(game.player.spellState[id]={cd:0});if(st.cd>0)return;
 const mods=spellMods(id);st.cd=s.cooldown*mods.cdr;game.player.facing=spellAim();
 const fn=SPELL_CASTS[s.cast];if(fn)fn(id,s,mods);flashSpellSlot(slot);updateHUD();
}
function magicProjectile(opts){
 const p={owner:'player',x:opts.x??game.player.x,y:opts.y??game.player.y,z:opts.z??18,vx:opts.vx||0,vy:opts.vy||0,vz:opts.vz||0,r:opts.r||.16,damage:opts.damage||10,life:opts.life||2,maxLife:opts.life||2,color:opts.color||'#fff',color2:opts.color2||opts.color||'#fff',kind:opts.kind||'orb',pierce:opts.pierce||0,seek:opts.seek||0,splash:opts.splash||0,knock:opts.knock||0,trail:opts.trail||'spark',returning:opts.returning||false,phase:opts.phase||0,onHit:opts.onHit||null,tag:opts.tag||'',hit:new Set()};game.projectiles.push(p);return p;
}
function radialDamage(x,y,r,damage,tag='',knock=0){
 for(const e of [...game.enemies]){const d=Math.hypot(e.x-x,e.y-y);if(d<=r+e.r){damageEnemy(e,damage,tag);if(knock&&d){e.x+=((e.x-x)/d)*knock;e.y+=((e.y-y)/d)*knock}}}
}
function groundEffect(kind,x,y,r,life,color,damage=0,interval=.35,extra={}){const h={kind,x,y,r,life,maxLife:life,color,damage,interval,tick:0,...extra};game.hazards.push(h);return h}
function telegraph(kind,x,y,r,time,color,extra={}){const t={kind,x,y,r,time,maxTime:time,color,...extra};game.telegraphs.push(t);return t}
function fx(kind,x,y,life,color,extra={}){game.effects.push({kind,x,y,life,maxLife:life,color,...extra})}
function burst(x,y,color,count=12,power=1,z=10){for(let i=0;i<count;i++){const a=Math.random()*TAU,s=rnd(power,.2);game.particles.push({x,y,z,vx:Math.cos(a)*s,vy:Math.sin(a)*s,vz:rnd(2.5,-.1),life:rnd(.9,.3),maxLife:.9,size:rnd(4,1.5),color,soft:Math.random()<.45})}}

const SPELL_CASTS={
 firebolt(id,s,m){const d=spellAim();magicProjectile({vx:d.x*6.4,vy:d.y*6.4,r:.22,damage:s.damage*m.power,color:'#ff713d',color2:'#ffd36b',kind:'fireball',life:2.2,seek:hasUpgrade(id,'seek')?.75:0,splash:hasUpgrade(id,'huge')?1.65:.85,knock:hasUpgrade(id,'huge')?.7:.18,onHit:(e,p)=>{
   if(hasUpgrade(id,'burn'))groundEffect('fire',p.x,p.y,hasUpgrade(id,'huge')?1.5:1.05,3.4,'#ff6838',s.damage*.16,.33);
   if(hasUpgrade(id,'echo'))setTimeout(()=>{if(running){radialDamage(p.x,p.y,.82,s.damage*.52,'fire');fx('explosion',p.x,p.y,.35,'#ffb34f',{r:.9});burst(p.x,p.y,'#ff8a48',10,1.2)}},260);
   if(hasUpgrade(id,'split'))for(let i=-1;i<=1;i++){const a=Math.atan2(p.vy,p.vx)+i*.55;magicProjectile({x:p.x,y:p.y,z:10,vx:Math.cos(a)*5.3,vy:Math.sin(a)*5.3,r:.13,damage:s.damage*.42*m.power,color:'#ff924a',kind:'ember',life:1.15,splash:.28})}
  }});fx('castRing',game.player.x,game.player.y,.3,'#ff7549',{r:.7})},
 frostnova(id,s,m){let r=hasUpgrade(id,'ring')?4.8:3.1;fx('frostNova',game.player.x,game.player.y,.8,'#a9ecff',{r,ring:hasUpgrade(id,'ring')});radialDamage(game.player.x,game.player.y,r,s.damage*m.power,'frost');
  for(const e of game.enemies)if(dist(e,game.player)<r+e.r){e.slow=Math.max(e.slow||0,hasUpgrade(id,'freeze')?3.5:2.2);if(hasUpgrade(id,'freeze')&&e.hp<e.maxHp*.45&&!e.boss)e.stun=Math.max(e.stun||0,.8)}
  if(hasUpgrade(id,'armor'))game.player.shield=Math.max(game.player.shield,18+game.level*2);
  if(hasUpgrade(id,'echo'))setTimeout(()=>{if(running){fx('frostNova',game.player.x,game.player.y,.65,'#d8f7ff',{r:r*.8});radialDamage(game.player.x,game.player.y,r*.8,s.damage*.62*m.power,'frost')}},500);burst(game.player.x,game.player.y,'#b8f1ff',24,1.4)},
 thorns(id,s,m){const rings=hasUpgrade(id,'double')?2:1;for(let q=0;q<rings;q++)game.effects.push({kind:'thornRing',x:game.player.x,y:game.player.y,life:1,maxLife:1,color:'#7ce08a',r:0,damage:s.damage*m.power,spin:q?1:-1,returning:hasUpgrade(id,'return'),root:hasUpgrade(id,'root'),bleed:hasUpgrade(id,'bleed'),hit:new Set()});if(hasUpgrade(id,'wall'))groundEffect('thorns',game.player.x,game.player.y,2.75,4,'#62bd75',s.damage*.22,.4,{ring:true});burst(game.player.x,game.player.y,'#76dd8c',20,1.1)},
 missiles(id,s,m){let count=4+(hasUpgrade(id,'more')?3:0);for(let i=0;i<count;i++){const a=TAU*i/count+Math.random()*.2,orbit=hasUpgrade(id,'orbit')&&i%2===0;magicProjectile({x:game.player.x,y:game.player.y,z:18,vx:Math.cos(a)*2.2,vy:Math.sin(a)*2.2,r:.13,damage:s.damage*m.power*(hasUpgrade(id,'execute')?1.08:1),color:'#9bb4ff',color2:'#e0d7ff',kind:orbit?'orbitalMissile':'arcane',life:3.2,seek:2.8,splash:hasUpgrade(id,'burst')?.32:0,phase:a,tag:hasUpgrade(id,'chain')?'chain':''})}fx('castRing',game.player.x,game.player.y,.45,'#9f8cff',{r:1.05})},
 gust(id,s,m){const d=spellAim(),wide=hasUpgrade(id,'wide')?1.25:.76,range=hasUpgrade(id,'wide')?6.6:5;fx('gustCone',game.player.x,game.player.y,.65,'#bdeeff',{dir:d,range,width:wide});for(const e of game.enemies){const v=norm(e.x-game.player.x,e.y-game.player.y),dd=dist(e,game.player),dot=v.x*d.x+v.y*d.y;if(dd<range&&dot>Math.cos(wide)){damageEnemy(e,s.damage*m.power*(hasUpgrade(id,'blades')?1.55:1),'wind');e.x+=d.x*(hasUpgrade(id,'wide')?1.2:.8);e.y+=d.y*(hasUpgrade(id,'wide')?1.2:.8);if(hasUpgrade(id,'stun')&&(e.x<1||e.x>ROOM_W-1||e.y<1||e.y>ROOM_H-1))e.stun=1}}
  if(hasUpgrade(id,'tornado'))groundEffect('tornado',game.player.x+d.x*3,game.player.y+d.y*3,1.1,4.2,'#9fe1e8',s.damage*.25,.28,{moving:true});if(hasUpgrade(id,'tailwind'))game.player.tailwind=2.5;burst(game.player.x+d.x,game.player.y+d.y,'#d7faff',18,1.8)},
 ward(id){let cap=hasUpgrade(id,'long')?58:34;game.player.shield=Math.max(game.player.shield,cap+game.level*2);game.player.shieldTime=hasUpgrade(id,'long')?8:5;game.player.wardReflect=hasUpgrade(id,'reflect')?.35:0;if(hasUpgrade(id,'dash'))game.player.dodgeCd=0;if(hasUpgrade(id,'heal'))game.player.wardHeal=game.player.shieldTime;fx('ward',game.player.x,game.player.y,game.player.shieldTime,'#8fd8ff',{follow:true});burst(game.player.x,game.player.y,'#91dcff',14,.7)},
 chain(id,s,m){const first=nearestEnemy(game.player,10);if(!first)return;let current=first,seen=new Set(),jumps=4+(hasUpgrade(id,'more')?3:0),from={x:game.player.x,y:game.player.y};for(let j=0;j<jumps&&current;j++){seen.add(current);fx('lightning',from.x,from.y,.24,'#8ff3ff',{toX:current.x,toY:current.y,width:3});damageEnemy(current,s.damage*m.power*(1-j*.06),'lightning');if(hasUpgrade(id,'stun')&&Math.random()<.25&&!current.boss)current.stun=.55;if(hasUpgrade(id,'fork')){const fork=nearestEnemy(current,3.2,e=>!seen.has(e));if(fork){fx('lightning',current.x,current.y,.18,'#bdf7ff',{toX:fork.x,toY:fork.y,width:2});damageEnemy(fork,s.damage*.55*m.power,'lightning')}}from={x:current.x,y:current.y};current=nearestEnemy(current,4.5,e=>!seen.has(e))}if(hasUpgrade(id,'ground'))groundEffect('lightningField',from.x,from.y,1.35,3,'#73e7ff',s.damage*.2,.32);if(hasUpgrade(id,'repeat'))setTimeout(()=>{const n=nearestEnemy(game.player,10);if(n){fx('lightning',game.player.x,game.player.y,.2,'#a8f8ff',{toX:n.x,toY:n.y,width:2});damageEnemy(n,s.damage*.55*m.power,'lightning')}},320)},
 poison(id,s,m){const pt=aimPoint(4.2);groundEffect('poison',pt.x,pt.y,hasUpgrade(id,'grow')?1.7:1.35,6.5,'#77d85f',s.damage*m.power,.48,{moving:hasUpgrade(id,'move'),spore:hasUpgrade(id,'spore'),slow:hasUpgrade(id,'slow'),pop:hasUpgrade(id,'pop')});fx('bloom',pt.x,pt.y,.65,'#99ef73',{r:1.5});burst(pt.x,pt.y,'#a9ef78',18,.9)},
 chakram(id,s,m){const d=spellAim(),twins=hasUpgrade(id,'twins')?2:1;for(let i=0;i<twins;i++){const a=Math.atan2(d.y,d.x)+(twins===2?(i?-.2:.2):0),dd={x:Math.cos(a),y:Math.sin(a)};magicProjectile({vx:dd.x*6.3,vy:dd.y*6.3,r:.28,damage:s.damage*m.power,color:'#b9a1ff',color2:'#e9e0ff',kind:'chakram',life:2.6,pierce:20,returning:true,phase:a,tag:[hasUpgrade(id,'saw')?'saw':'',hasUpgrade(id,'bounce')?'bounce':''].join(' ')})}fx('castRing',game.player.x,game.player.y,.35,'#c3adff',{r:.8})},
 spirits(id,s,m){let count=3+(hasUpgrade(id,'more')?3:0);for(let i=0;i<count;i++)game.summons.push({kind:'wisp',x:game.player.x,y:game.player.y,z:20,angle:TAU*i/count,life:9,maxLife:9,damage:s.damage*m.power,heal:hasUpgrade(id,'heal'),bomb:hasUpgrade(id,'bomb'),chain:hasUpgrade(id,'chain'),guard:hasUpgrade(id,'guard'),shot:Math.random()*.5,color:i%2?'#b8fbff':'#d8bdff'});fx('summon',game.player.x,game.player.y,.7,'#bde9ff',{r:1.4})},
 quake(id,s,m){const d=spellAim(),angles=hasUpgrade(id,'three')?[-.25,0,.25]:[0];for(const off of angles){const a=Math.atan2(d.y,d.x)+off;game.effects.push({kind:'quake',x:game.player.x,y:game.player.y,dx:Math.cos(a),dy:Math.sin(a),life:1,maxLife:1,color:'#d0b694',damage:s.damage*m.power,width:hasUpgrade(id,'wide')?1.1:.6,pillars:hasUpgrade(id,'pillars'),stun:hasUpgrade(id,'stun'),hit:new Set()})}if(hasUpgrade(id,'return'))setTimeout(()=>{if(running){const d2={x:-d.x,y:-d.y};game.effects.push({kind:'quake',x:game.player.x+d.x*5,y:game.player.y+d.y*5,dx:d2.x,dy:d2.y,life:.8,maxLife:.8,color:'#e2c9a7',damage:s.damage*.58*m.power,width:.65,hit:new Set()})}},500);shake=Math.max(shake,5)},
 meteor(id,s,m){const pt=aimPoint(5.5),count=hasUpgrade(id,'three')?3:1;for(let i=0;i<count;i++){const x=pt.x+(count>1?rnd(2,-2):0),y=pt.y+(count>1?rnd(1.7,-1.7):0),delay=hasUpgrade(id,'fast')?.45:1.05;telegraph('circle',x,y,hasUpgrade(id,'three')?1.05:1.55,delay,'#ff8a55',{pulse:true});game.effects.push({kind:'meteor',x,y,life:delay+.35,maxLife:delay+.35,impactAt:.35,color:'#ff744b',damage:s.damage*m.power*(count>1?.68:1),r:hasUpgrade(id,'three')?1.1:1.6,crater:hasUpgrade(id,'crater'),fragments:hasUpgrade(id,'fragments'),pull:hasUpgrade(id,'pull'),landed:false})}},
 voidrift(id,s,m){const pt=aimPoint(4.5),twins=hasUpgrade(id,'twins')?2:1;for(let i=0;i<twins;i++){const x=pt.x+(i?2.5:0),y=pt.y+(i?-1.6:0);groundEffect('void',x,y,hasUpgrade(id,'slow')?2.25:1.7,6,'#9c59d9',s.damage*m.power,.3,{pull:hasUpgrade(id,'slow')?.65:.35,move:hasUpgrade(id,'move'),burst:hasUpgrade(id,'burst'),orbs:hasUpgrade(id,'orbs')})}fx('riftOpen',pt.x,pt.y,.7,'#b56cff',{r:2})},
 icelance(id,s,m){const d=spellAim(),shots=hasUpgrade(id,'triple')?[-.16,0,.16]:[0];for(const off of shots){const a=Math.atan2(d.y,d.x)+off;magicProjectile({vx:Math.cos(a)*11,vy:Math.sin(a)*11,r:.14,damage:s.damage*m.power*(shots.length>1?.72:1),color:'#a8ecff',color2:'#e7fbff',kind:'iceLance',life:1.25,pierce:6,splash:hasUpgrade(id,'explode')?.7:0,tag:hasUpgrade(id,'execute')?'iceExecute':'',onHit:(e,p)=>{e.slow=Math.max(e.slow||0,2);if(hasUpgrade(id,'trail'))groundEffect('iceShard',p.x,p.y,.35,2.4,'#a9eeff',s.damage*.12,.55)}})}fx('castLine',game.player.x,game.player.y,.25,'#bdefff',{dir:d,range:5})},
 soulflame(id,s,m){const t=nearestEnemy(game.player,9);if(!t)return;t.curse={life:6,damage:s.damage*m.power*.22,heal:hasUpgrade(id,'heal'),ghost:hasUpgrade(id,'ghost'),spread:hasUpgrade(id,'spread'),aura:hasUpgrade(id,'aura'),boss:hasUpgrade(id,'boss')};fx('soulLink',game.player.x,game.player.y,.5,'#cf68ff',{toX:t.x,toY:t.y});burst(t.x,t.y,'#bd5eff',12,.6)},
 tempest(id,s,m){const pt=aimPoint(4);groundEffect('tempest',pt.x,pt.y,hasUpgrade(id,'big')?3:2.15,hasUpgrade(id,'big')?8:6,'#7fdcff',s.damage*m.power,.58,{moving:hasUpgrade(id,'move'),fork:hasUpgrade(id,'fork'),deflect:hasUpgrade(id,'deflect'),final:hasUpgrade(id,'final')});fx('stormSpawn',pt.x,pt.y,.8,'#91e8ff',{r:2.5})},
 timestop(id){const pt=hasUpgrade(id,'follow')?{x:game.player.x,y:game.player.y}:aimPoint(3),r=hasUpgrade(id,'big')?4.5:3.1;groundEffect('time',pt.x,pt.y,r,5.2,'#7fb5ff',0,.1,{follow:hasUpgrade(id,'follow'),freeze:hasUpgrade(id,'freeze'),haste:hasUpgrade(id,'haste'),burst:hasUpgrade(id,'burst')});fx('timeBubble',pt.x,pt.y,5.2,'#8abaff',{r,follow:hasUpgrade(id,'follow')})},
 phoenix(id,s,m){const d=spellAim(),angles=hasUpgrade(id,'twins')?[-.2,.2]:[0];for(const off of angles){const a=Math.atan2(d.y,d.x)+off;game.effects.push({kind:'phoenix',x:game.player.x,y:game.player.y,dx:Math.cos(a),dy:Math.sin(a),life:3.2,maxLife:3.2,color:'#ff9c49',damage:s.damage*m.power*(angles.length>1?.72:1),trail:hasUpgrade(id,'trail'),heal:hasUpgrade(id,'heal'),explode:hasUpgrade(id,'explode'),circle:hasUpgrade(id,'circle'),hit:new Set()})}burst(game.player.x,game.player.y,'#ffc766',30,2)},
 starfall(id,s,m){const pt=aimPoint(3),count=hasUpgrade(id,'more')?18:11;game.effects.push({kind:'starfall',x:pt.x,y:pt.y,life:hasUpgrade(id,'more')?7:5,maxLife:hasUpgrade(id,'more')?7:5,color:'#c3ddff',damage:s.damage*m.power,count,spawn:0,seek:hasUpgrade(id,'seek'),nova:hasUpgrade(id,'nova'),guard:hasUpgrade(id,'guard'),final:hasUpgrade(id,'final'),done:0});fx('constellation',pt.x,pt.y,1.1,'#d7eaff',{r:3})},
 singularity(id,s,m){const pt=aimPoint(4),r=hasUpgrade(id,'big')?4.3:3;groundEffect('singularity',pt.x,pt.y,r,7,'#8e5cff',s.damage*m.power*.08,.22,{pull:hasUpgrade(id,'big')?1.15:.8,orbit:hasUpgrade(id,'orbit'),shards:hasUpgrade(id,'shards'),burstDamage:s.damage*m.power,reset:hasUpgrade(id,'reset')});if(hasUpgrade(id,'second'))groundEffect('singularity',ROOM_W-pt.x,ROOM_H-pt.y,r*.62,6,'#6b44b8',s.damage*m.power*.05,.28,{pull:.55,burstDamage:s.damage*m.power*.6});fx('riftOpen',pt.x,pt.y,1,'#9b61ff',{r})}
};

function updateSpellEntities(dt){
 for(const s of game.summons){s.life-=dt;s.angle+=dt*1.8;const rr=1.15+Math.sin(elapsed*2+s.angle)*.18;s.x=game.player.x+Math.cos(s.angle)*rr;s.y=game.player.y+Math.sin(s.angle)*rr;s.z=18+Math.sin(elapsed*4+s.angle)*5;s.shot-=dt;if(s.shot<=0){const t=nearestEnemy(s,6);if(t){const d=norm(t.x-s.x,t.y-s.y);magicProjectile({x:s.x,y:s.y,z:s.z,vx:d.x*7,vy:d.y*7,r:.09,damage:s.damage,color:s.color,kind:'wispBolt',life:1,seek:1.4,tag:s.chain?'chain':''});s.shot=.65+Math.random()*.35;if(s.heal&&Math.random()<.16)healPlayer(2)}}if(s.life<=0&&s.bomb){radialDamage(s.x,s.y,1.1,s.damage*.8,'spirit');fx('explosion',s.x,s.y,.3,s.color,{r:1.2})}}
 game.summons=game.summons.filter(s=>s.life>0);
 for(const h of game.hazards){h.life-=dt;h.tick-=dt;if(h.follow){h.x=game.player.x;h.y=game.player.y}if(h.moving){const t=nearestEnemy(h,7);if(t){const d=norm(t.x-h.x,t.y-h.y);h.x+=d.x*dt*.65;h.y+=d.y*dt*.65}}if(h.kind==='void'||h.kind==='singularity'){for(const e of game.enemies){const d=Math.hypot(e.x-h.x,e.y-h.y);if(d<h.r*1.55&&d>.05){const pull=(1-d/(h.r*1.7))*h.pull*dt;e.x+=(h.x-e.x)/d*pull;e.y+=(h.y-e.y)/d*pull;if(h.kind==='singularity'&&h.orbit){const tx=-(e.y-h.y)/d,ty=(e.x-h.x)/d;e.x+=tx*dt*.55;e.y+=ty*dt*.55}}}if(h.shards&&Math.random()<dt*2){const a=Math.random()*TAU;magicProjectile({x:h.x,y:h.y,z:9,vx:Math.cos(a)*5,vy:Math.sin(a)*5,r:.1,damage:h.damage*2.2,color:'#ae77ff',kind:'voidShard',life:1.4,pierce:1})}}
  if(h.kind==='time'){for(const e of game.enemies)if(dist(e,h)<h.r+e.r)e.timeSlow=h.freeze&&dist(e,h)<h.r*.45?.05:.23;if(h.haste&&dist(game.player,h)<h.r)game.player.haste=.15}
  if(h.kind==='tempest'&&h.deflect)for(const p of game.projectiles)if(p.owner==='enemy'&&dist(p,h)<h.r){const d=norm(p.x-h.x,p.y-h.y);p.vx=d.x*Math.hypot(p.vx,p.vy);p.vy=d.y*Math.hypot(p.vx,p.vy)}
  if(h.tick<=0&&h.damage){h.tick=h.interval;for(const e of game.enemies)if(dist(e,h)<h.r+e.r){damageEnemy(e,h.damage,h.kind);if(h.slow)e.slow=Math.max(e.slow||0,1.2)}if(h.kind==='tempest'){const t=nearestEnemy(h,h.r+1);if(t){fx('lightning',h.x+rnd(.7,-.7),h.y+rnd(.7,-.7),.22,'#91efff',{toX:t.x,toY:t.y,width:3});burst(t.x,t.y,'#a5efff',6,.45)}}if(h.spore){const t=nearestEnemy(h,h.r+3);if(t){const d=norm(t.x-h.x,t.y-h.y);magicProjectile({x:h.x,y:h.y,z:7,vx:d.x*4.5,vy:d.y*4.5,r:.09,damage:h.damage*.7,color:'#a7ed72',kind:'spore',life:1.2,seek:1})}}}
 }
 for(const h of game.hazards)if(h.life<=0){if(h.pop||h.burstDamage){const dmg=h.burstDamage||h.damage*3;radialDamage(h.x,h.y,h.r,dmg,h.kind);fx('explosion',h.x,h.y,.45,h.color,{r:h.r});burst(h.x,h.y,h.color,22,1.6);shake=Math.max(shake,4)}if(h.kind==='tempest'&&h.final){radialDamage(h.x,h.y,h.r*1.3,h.damage*2.8,'lightning');fx('shockRing',h.x,h.y,.55,'#c5f7ff',{r:h.r*1.4})}if(h.kind==='time'&&h.burst){radialDamage(h.x,h.y,h.r,28+game.level*2,'arcane');fx('shockRing',h.x,h.y,.45,'#9fc4ff',{r:h.r})}}
 game.hazards=game.hazards.filter(h=>h.life>0);
 updateComplexEffects(dt);
}

function updateComplexEffects(dt){
 for(const e of game.effects){e.life-=dt;
  if(e.kind==='meteor'&&!e.landed&&e.life<=e.impactAt){e.landed=true;radialDamage(e.x,e.y,e.r,e.damage,'fire',.6);fx('explosion',e.x,e.y,.45,'#ff8b54',{r:e.r*1.15});burst(e.x,e.y,'#ff9a5a',30,2.2);shake=Math.max(shake,9);if(e.crater)groundEffect('fire',e.x,e.y,e.r*.9,5,'#ff643a',e.damage*.12,.38);if(e.fragments)for(let i=0;i<10;i++){const a=TAU*i/10;magicProjectile({x:e.x,y:e.y,z:8,vx:Math.cos(a)*5,vy:Math.sin(a)*5,r:.08,damage:e.damage*.18,color:'#ffbb69',kind:'ember',life:1})}}
  if(e.kind==='quake'){const t=1-e.life/e.maxLife,head=t*7;for(const foe of game.enemies){if(e.hit.has(foe))continue;const rx=foe.x-e.x,ry=foe.y-e.y,along=rx*e.dx+ry*e.dy,side=Math.abs(rx*(-e.dy)+ry*e.dx);if(along>0&&along<head&&along>head-1.4&&side<e.width+foe.r){e.hit.add(foe);damageEnemy(foe,e.damage,'earth');if(e.stun&&!foe.boss)foe.stun=.7;if(e.pillars)fx('stonePillar',foe.x,foe.y,.7,'#c1aa8b',{r:.7})}}}
  if(e.kind==='thornRing'){const t=1-e.life/e.maxLife;e.r=(e.returning&&t>.55?1-(t-.55)/.45:t/.55)*4.2;for(const foe of game.enemies){if(e.hit.has(foe)&&!e.returning)continue;const dd=dist(foe,e);if(Math.abs(dd-e.r)<.42+foe.r){e.hit.add(foe);damageEnemy(foe,e.damage,'nature');if(e.root)foe.stun=Math.max(foe.stun||0,.45);if(e.bleed)foe.bleed={life:3,damage:e.damage*.12}}}}
  if(e.kind==='phoenix'){const age=e.maxLife-e.life;let px=e.x+e.dx*age*4.2,py=e.y+e.dy*age*4.2;if(age>1.55){const back=age-1.55;px=e.x+e.dx*(6.5-back*4.2);py=e.y+e.dy*(6.5-back*4.2)}e.cx=px;e.cy=py;if(e.trail&&Math.random()<dt*8)groundEffect('fire',px,py,.55,2.2,'#ff7c42',e.damage*.08,.45);for(const foe of game.enemies){const key=foe.id+'_'+Math.floor(age*2);if(dist(foe,{x:px,y:py})<.8+foe.r&&!e.hit.has(key)){e.hit.add(key);damageEnemy(foe,e.damage,'fire');if(e.explode)fx('explosion',foe.x,foe.y,.25,'#ffb45c',{r:.6})}}if(e.heal&&age>1.55&&!e.healed){e.healed=true;healPlayer(10+game.level)}}
  if(e.kind==='starfall'){e.spawn-=dt;if(e.spawn<=0&&e.done<e.count){e.spawn=.26;e.done++;let x=e.x+rnd(3.3,-3.3),y=e.y+rnd(2.6,-2.6);if(e.seek&&Math.random()<.75){const t=nearestEnemy(e,6);if(t){x=t.x+rnd(.7,-.7);y=t.y+rnd(.7,-.7)}}const final=e.final&&e.done===e.count;game.effects.push({kind:'fallingStar',x,y,life:.62,maxLife:.62,color:final?'#fff0a8':'#d3e6ff',damage:e.damage*(final?2.5:1),r:final?1.7:.72,nova:e.nova,landed:false})}}
  if(e.kind==='fallingStar'&&!e.landed&&e.life<.12){e.landed=true;radialDamage(e.x,e.y,e.r,e.damage,'star');fx('explosion',e.x,e.y,.3,e.color,{r:e.r});burst(e.x,e.y,e.color,e.r>1?28:10,e.r>1?2:1);if(e.nova)for(let i=0;i<6;i++){const a=i/6*TAU;magicProjectile({x:e.x,y:e.y,z:8,vx:Math.cos(a)*4.5,vy:Math.sin(a)*4.5,r:.07,damage:e.damage*.18,color:'#e6efff',kind:'starShard',life:1})}}
 }
 game.effects=game.effects.filter(e=>e.life>0);
}
