'use strict';

function showOverlay(id){$(id).classList.remove('hidden');modalPause=true}
function closeOverlay(id){$(id).classList.add('hidden');modalPause=false;if(game.pendingLevelUps>0)setTimeout(openLevelChoice,80)}
function choiceCard({rarity='Common',icon='✨',name,desc,tag='',owned=false},onClick){const b=document.createElement('button');b.className='card-choice';b.style.setProperty('--rar',rarityColors[rarity]);b.innerHTML=`${owned?'<span class="owned-mark">OWNED • EVOLVE</span>':''}<div class="rarity">${rarity}</div><div class="choice-icon">${icon}</div><div class="choice-name">${name}</div><div class="choice-desc">${desc}</div>${tag?`<span class="choice-tag">${tag}</span>`:''}`;b.onclick=onClick;return b}
function weightedSpellPool(){const arr=[];for(const [id,s] of Object.entries(SPELLS)){if(game.level<rarityMin[s.rarity])continue;let weight=s.rarity==='Common'?9:s.rarity==='Uncommon'?6:s.rarity==='Rare'?3.2:s.rarity==='Epic'?1.4:.55;if(game.player.unlocked.includes(id))weight*=1.45;for(let i=0;i<Math.max(1,Math.round(weight));i++)arr.push(id)}return arr}
function sampleUnique(pool,n){const out=[];let guard=0;while(out.length<n&&guard++<200&&pool.length){const v=pool[irnd(pool.length)];if(!out.includes(v))out.push(v)}return out}
function openLevelChoice(free=false){if(!game.player||modalPause)return;if(!free&&game.pendingLevelUps<=0)return;if(!free)game.pendingLevelUps--;modalPause=true;$('levelTitle').textContent=free?'Arcane Seer':'Level Up • '+game.level;const root=$('levelCards');root.innerHTML='';const ids=sampleUnique(weightedSpellPool(),3);for(const id of ids){const s=SPELLS[id],owned=game.player.unlocked.includes(id);root.appendChild(choiceCard({rarity:s.rarity,icon:s.icon,name:s.name,desc:s.desc,tag:owned?'Choose to evolve':'Unlock spell',owned},()=>selectSpellChoice(id)))}$('levelOverlay').classList.remove('hidden')}
function selectSpellChoice(id){$('levelOverlay').classList.add('hidden');if(game.player.unlocked.includes(id)){openUpgradeChoice(id);return}game.player.unlocked.push(id);if(game.player.activeSpells.length<3){game.player.activeSpells.push(id);toastMsg(`${SPELLS[id].name} unlocked.`);modalPause=false;saveGame();updateHUD();if(game.pendingLevelUps>0)setTimeout(openLevelChoice,100)}else{game.selectedSpell=id;openReplaceChoice(id)}}
function openUpgradeChoice(id){game.selectedSpell=id;modalPause=true;$('upgradeTitle').textContent=`Evolve ${SPELLS[id].icon} ${SPELLS[id].name}`;const current=game.player.upgrades[id]||[],pool=(UPGRADE_POOLS[id]||[]).filter(u=>!current.includes(u[0]));const pick=sampleUnique(pool.map(u=>u[0]),3),root=$('upgradeCards');root.innerHTML='';for(const uid of pick){const u=UPGRADE_POOLS[id].find(v=>v[0]===uid);root.appendChild(choiceCard({rarity:SPELLS[id].rarity,icon:u[2],name:u[1],desc:u[3],tag:'Behavior mutation'},()=>{(game.player.upgrades[id]||(game.player.upgrades[id]=[])).push(uid);$('upgradeOverlay').classList.add('hidden');modalPause=false;toastMsg(`${SPELLS[id].name}: ${u[1]}`);saveGame();updateHUD();if(game.pendingLevelUps>0)setTimeout(openLevelChoice,100)}))}if(!pick.length){root.appendChild(choiceCard({rarity:SPELLS[id].rarity,icon:'✦',name:'Arcane Mastery',desc:'This spell has every mutation. Gain +12% global spell potency instead.',tag:'Mastery'},()=>{$('upgradeOverlay').classList.add('hidden');modalPause=false;game.player.weapon.power*=1.12;saveGame();updateHUD()}))}$('upgradeOverlay').classList.remove('hidden')}
function openReplaceChoice(id){modalPause=true;const root=$('replaceCards');root.innerHTML='';game.player.activeSpells.forEach((old,i)=>{const s=SPELLS[old];root.appendChild(choiceCard({rarity:s.rarity,icon:s.icon,name:`Replace ${s.name}`,desc:`Put ${SPELLS[id].name} into active slot ${i+1}. ${s.name} remains unlocked in your spellbook.`,tag:`Slot ${i+1}`},()=>{game.player.activeSpells[i]=id;$('replaceOverlay').classList.add('hidden');modalPause=false;toastMsg(`${SPELLS[id].name} equipped.`);saveGame();updateHUD();if(game.pendingLevelUps>0)setTimeout(openLevelChoice,100)}))});$('replaceOverlay').classList.remove('hidden')}

function updateHUD(){if(!game.player)return;const p=game.player,room=game.roomData||getRoomData(game.room.x,game.room.y);$('heroLabel').textContent=`Wanderer • Lv ${game.level}`;$('hpText').textContent=`${Math.ceil(p.hp)} / ${Math.ceil(p.maxHp)}`;$('hpFill').style.width=(100*clamp(p.hp/p.maxHp,0,1))+'%';$('hpBarLabel').textContent=p.shield>0?`Shield ${Math.ceil(p.shield)}`:'';$('xpFill').style.width=(100*clamp(game.xp/game.xpNeed,0,1))+'%';$('weaponChip').textContent=`${p.weapon.icon} ${p.weapon.name}`;$('armorChip').textContent=`${p.armorGear.icon} ${p.armorGear.name}`;$('powerChip').textContent=`⚔ ${Math.round(weaponDamage())} Power`;$('dodgeChip').textContent=p.dodgeCd>0?`↯ ${p.dodgeCd.toFixed(1)}s`:'↯ Dodge Ready';$('goldText').textContent=game.gold;$('roomName').textContent=room.name;$('roomSub').textContent=`${biomePalette[room.biome].name} • ${game.room.x}, ${game.room.y} • Threat ${room.difficulty}`;const state=$('roomState');state.className='room-state '+(room.town?'town':room.cleared?'clear':'locked');state.textContent=room.town?'Sanctuary':room.cleared?'Roads Open':room.boss?'Boss Domain':room.elite?'Elite Encounter':'Doors Sealed';renderSpellBar();renderMinimap();const boss=game.enemies.find(e=>e.boss);$('bossHud').classList.toggle('show',!!boss);if(boss){$('bossName').textContent=boss.name;$('bossFill').style.width=(100*clamp(boss.hp/boss.maxHp,0,1))+'%'}}
function renderSpellBar(){const root=$('spells');root.innerHTML='';for(let i=0;i<3;i++){const id=game.player.activeSpells[i];if(!id){const b=document.createElement('button');b.className='spell-slot';b.innerHTML=`<span class="spell-key">${i+1}</span><span class="spell-icon">＋</span><span class="spell-name">Empty</span>`;root.appendChild(b);continue}const s=SPELLS[id],st=game.player.spellState[id]||(game.player.spellState[id]={cd:0}),max=s.cooldown*spellMods(id).cdr,ratio=max?clamp(st.cd/max,0,1):0,b=document.createElement('button');b.className='spell-slot';b.style.borderColor=colorAlpha(rarityColors[s.rarity],.38);b.innerHTML=`<span class="spell-key">${i+1}</span><span class="spell-icon">${s.icon}</span><span class="spell-name">${s.name}</span><i class="cooldown" style="transform:scaleY(${ratio})"></i><span class="cooldown-text">${st.cd>.05?st.cd.toFixed(1):''}</span>`;b.onclick=()=>castSpell(i);root.appendChild(b)}}
function flashSpellSlot(i){const b=$('spells').children[i];if(!b)return;b.animate([{transform:'translateY(0) scale(1)'},{transform:'translateY(-4px) scale(1.07)'},{transform:'translateY(0) scale(1)'}],{duration:220})}
function renderMinimap(){const root=$('minimapGrid');root.innerHTML='';for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){const x=game.room.x+dx,y=game.room.y+dy,r=game.rooms[roomKey(x,y)],c=document.createElement('div');c.className='map-cell';if(r?.seen)c.classList.add('seen');if(r?.cleared)c.classList.add('clear');if(r?.town)c.classList.add('town');if(r?.boss)c.classList.add('boss');if(dx===0&&dy===0)c.classList.add('current');root.appendChild(c)}}

function gearCard(item,label){if(!item)return '';const stats=item.slot==='weapon'?[['Power',Math.round(item.power*(item.damage||1))],['Attack',`${(1/(item.attack||1)).toFixed(2)}/s`],['Range',(item.range||0).toFixed(1)],['Forge',`+${item.forge||0}`]]:[['Bonus HP',`+${Math.round(item.hpBonus)}`],['HP scale',`${Math.round(item.hp*100)}%`],['Armor',`${Math.round(item.armorBonus*100)}%`],['Move',`${Math.round(item.move*100)}%`]];return `<div class="gear-card" style="border-color:${colorAlpha(rarityColors[item.rarity],.34)}"><div class="rarity" style="color:${rarityColors[item.rarity]}">${label} • ${item.rarity}</div><div class="gear-preview">${item.icon}</div><div class="choice-name">${item.name}</div><div class="stats">${stats.map(([a,b])=>`<div class="stat">${a}<b>${b}</b></div>`).join('')}</div></div>`}
function openLootOverlay(){if(!game.loot)return;const current=game.loot.slot==='weapon'?game.player.weapon:game.player.armorGear;$('lootCompare').innerHTML=gearCard(current,'Equipped')+gearCard(game.loot,'Found');showOverlay('lootOverlay')}
function renderInventory(){const p=game.player;let spellHtml=p.unlocked.map(id=>{const s=SPELLS[id],ups=p.upgrades[id]||[];return `<div class="feature" style="border-color:${colorAlpha(rarityColors[s.rarity],.25)}"><b>${s.icon} ${s.name} <span style="color:${rarityColors[s.rarity]};float:right">${s.rarity}</span></b><span>${s.desc}</span><div style="margin-top:8px;font-size:9px;color:#d9e7f5">${ups.length?ups.map(uid=>UPGRADE_POOLS[id]?.find(v=>v[0]===uid)?.[1]).filter(Boolean).join(' • '):'No mutations yet'}</div></div>`}).join('');$('inventoryContent').innerHTML=`<div class="gear-layout">${gearCard(p.weapon,'Weapon')}${gearCard(p.armorGear,'Armor')}</div><h3 style="margin:22px 0 9px">Spellbook • ${p.unlocked.length}/${Object.keys(SPELLS).length} discovered</h3><div class="feature-grid" style="grid-template-columns:repeat(auto-fit,minmax(210px,1fr));margin-top:0">${spellHtml}</div>`}
function openTownPanel(service){const heal=12+game.level*2,forge=28+(game.player.weapon.forge||0)*22,seer=55+game.level*4;$('healService').textContent=`Restore Health • ${heal} gold`;$('forgeService').textContent=`Forge +13% Power • ${forge} gold`;$('seerService').textContent=`Seek Spell • ${seer} gold`;$('townTitle').textContent=game.roomData.name+' Services';showOverlay('townPanel');if(service)toastMsg(`${capitalize(service)} ready.`)}
function serviceSpend(cost,fn){if(game.gold<cost){toastMsg('Not enough gold.');return}game.gold-=cost;fn();updateHUD();saveGame()}

function togglePause(){if(!running)return;if(modalPause&&!$('pauseOverlay').classList.contains('hidden')){closeOverlay('pauseOverlay');paused=false;return}if(modalPause)return;paused=true;showOverlay('pauseOverlay')}

$('newRunBtn').onclick=startNewGame;$('continueBtn').onclick=()=>{if(loadGame())beginWorld()};$('howBtn').onclick=()=>showOverlay('helpOverlay');$('lobbyBtn').onclick=() => location.href='/lobby/lobby.html';$('pauseLobbyBtn').onclick=() => location.href='/lobby/lobby.html';$('resumeBtn').onclick=()=>{closeOverlay('pauseOverlay');paused=false};$('restartBtn').onclick=()=>{if(confirm('Start a new Arcane Wilds journey? Your current run will be replaced.')){document.querySelectorAll('.overlay').forEach(o=>o.classList.add('hidden'));startNewGame()}};$('pauseBtn').onclick=togglePause;$('inventoryBtn').onclick=()=>{renderInventory();showOverlay('inventoryOverlay')};$('mobileDodge').onclick=dodge;$('mobileInteract').onclick=interact;$('equipLootBtn').onclick=equipLoot;$('leaveLootBtn').onclick=()=>{game.loot=null;closeOverlay('lootOverlay')};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeOverlay(b.dataset.close));
$('healService').onclick=()=>{const c=12+game.level*2;serviceSpend(c,()=>{game.player.hp=game.player.maxHp;burst(game.player.x,game.player.y,'#83e7ff',20,1);toastMsg('The well restores you.')})};$('forgeService').onclick=()=>{const c=28+(game.player.weapon.forge||0)*22;serviceSpend(c,()=>{game.player.weapon.forge=(game.player.weapon.forge||0)+1;burst(game.player.x,game.player.y,'#ffbf69',24,1.2);toastMsg('Weapon reforged.')})};$('seerService').onclick=()=>{const c=55+game.level*4;if(game.gold<c)return toastMsg('Not enough gold.');game.gold-=c;$('townPanel').classList.add('hidden');modalPause=false;updateHUD();saveGame();setTimeout(()=>openLevelChoice(true),80)};
bindStick('moveZone',moveStick,'moveKnob');bindStick('aimZone',aimStick,'aimKnob');

const hasSave=!!localStorage.getItem(SAVE_KEY);$('continueBtn').classList.toggle('hidden',!hasSave);
render();
