from pathlib import Path
import re

path = Path('game/turncraft.html')
text = path.read_text(encoding='utf-8')


def replace_once(old: str, new: str, label: str) -> None:
    global text
    if old not in text:
        raise SystemExit(f'Missing replacement target: {label}')
    text = text.replace(old, new, 1)


def regex_once(pattern: str, replacement: str, label: str) -> None:
    global text
    text2, count = re.subn(pattern, replacement, text, count=1, flags=re.S)
    if count != 1:
        raise SystemExit(f'Expected one regex target for {label}, got {count}')
    text = text2


replace_once(
    '<meta name="turncraft-build" content="expanded-ai-research-sentry-dropship-ravager-2026-07-19" />',
    '<meta name="turncraft-build" content="strategy-controls-doctrines-minimap-report-2026-08-02" />',
    'build metadata',
)

regex_once(
    r"function expansionPositions\(\)\{return \[.*?\n\]\}",
    """function expansionPositions(){return [
  {x:14,y:11,rotation:.35,naturalFor:0,rich:false},
  {x:28,y:11,rotation:2.78,naturalFor:1,rich:false},
  {x:21,y:17,rotation:-1.55,naturalFor:2,rich:false},
  {x:8,y:22,rotation:.2,naturalFor:null,rich:false},
  {x:34,y:22,rotation:2.95,naturalFor:null,rich:false},
  {x:21,y:7,rotation:1.55,naturalFor:null,rich:true}
]}""",
    'expansion positions',
)

regex_once(
    r"function createTerrain\(\)\{.*?\n\}
function startPositions",
    """function createTerrain(){terrain=[];for(let y=0;y<BOARD_H;y++)for(let x=0;x<BOARD_W;x++){let type='ground';const edge=Math.min(x,BOARD_W-1-x,y,BOARD_H-1-y),band=y<10?'highland':y>20?'lowland':'midland',noise=(Math.sin((x+mapSeed%17)*.42)+Math.cos((y+mapSeed%23)*.37)+Math.sin((x+y)*.19))/3;if(band==='highland')type=noise>.18?'sand':noise<-.35?'dust':'ruins';else if(band==='lowland')type=noise>.2?'grass':noise<-.34?'moss':'ground';else type=noise>.32?'ruins':noise<-.35?'moss':'ground';if(edge<2&&noise>.1)type='rock';terrain.push({x,y,type,blocked:type==='rock'})}
  const starts=startPositions(),sites=expansionPositions(),center={x:21,y:14},protectedPoints=[...starts,...sites,center];
  const ridges=[{x:4,y:15,rx:3,ry:2},{x:38,y:15,rx:3,ry:2},{x:15,y:23,rx:3,ry:2},{x:27,y:23,rx:3,ry:2},{x:21,y:2,rx:4,ry:1}];
  for(const ridge of ridges)for(let y=ridge.y-ridge.ry;y<=ridge.y+ridge.ry;y++)for(let x=ridge.x-ridge.rx;x<=ridge.x+ridge.rx;x++){const t=tileAt(x,y);if(!t||protectedPoints.some(p=>Math.hypot(p.x-x,p.y-y)<4.7))continue;const ellipse=((x-ridge.x)*(x-ridge.x))/(ridge.rx*ridge.rx)+((y-ridge.y)*(y-ridge.y))/(ridge.ry*ridge.ry);if(ellipse<=1){t.type=(x+y)%3===0?'crystal':'rock';t.blocked=true}}
  for(let i=0;i<7;i++){const cx=4+Math.floor(rand()*(BOARD_W-8)),cy=4+Math.floor(rand()*(BOARD_H-8));if(protectedPoints.some(p=>Math.hypot(p.x-cx,p.y-cy)<5.2))continue;const rx=1+Math.floor(rand()*2),ry=1+Math.floor(rand()*2),kind=rand()<.72?'rock':'crystal';for(let y=cy-ry;y<=cy+ry;y++)for(let x=cx-rx;x<=cx+rx;x++){const t=tileAt(x,y);if(!t)continue;const ellipse=((x-cx)*(x-cx))/(rx*rx)+((y-cy)*(y-cy))/(ry*ry);if(ellipse<=1&&rand()<.78){t.type=kind;t.blocked=true}}}
  for(const s of starts)paintTerrainCircle(s.x,s.y,4.6,'ground',false);
  for(const site of sites)paintTerrainCircle(site.x,site.y,3.5,'expansion',false);
  for(let i=0;i<starts.length;i++){const natural=sites.find(s=>s.naturalFor===i);carveCorridor(starts[i],natural,2,'lane');carveCorridor(natural,center,1,'lane')}
  carveCorridor(sites[5],center,1,'lane');carveCorridor(sites[3],sites[2],1,'lane');carveCorridor(sites[4],sites[2],1,'lane');carveCorridor(sites[3],center,1,'lane');carveCorridor(sites[4],center,1,'lane');
  for(let a=0;a<Math.PI*2;a+=Math.PI/10){const x=Math.round(center.x+Math.cos(a)*5),y=Math.round(center.y+Math.sin(a)*4);paintTerrainCircle(x,y,1.15,'ruins',false)}
  paintTerrainCircle(center.x,center.y,3.4,'ruins',false);for(const site of sites)paintTerrainCircle(site.x,site.y,2.5,'expansion',false)
}
function startPositions""",
    'terrain generator',
)

css = r'''
/* Turncraft strategic command, minimap, doctrine, alert, and report systems */
#battleAlerts{position:fixed;top:58px;left:50%;transform:translateX(-50%);z-index:16;width:min(760px,calc(100vw - 20px));display:flex;flex-direction:column;align-items:center;gap:3px;pointer-events:none}.battleAlert{pointer-events:auto;appearance:none;border:0;background:rgba(32,4,8,.88);color:#ff7785;border-left:4px solid #ff4357;border-radius:7px;padding:4px 9px;font-size:11px;font-weight:1000;box-shadow:0 5px 18px rgba(0,0,0,.4);cursor:pointer;animation:alertIn .18s ease}.battleAlert.severe{color:#fff;background:rgba(117,6,19,.94);font-size:12px}@keyframes alertIn{from{opacity:0;transform:translateY(-5px)}}
#controlGroups{position:fixed;top:60px;right:12px;z-index:15;display:flex;gap:4px}.controlGroupChip{appearance:none;border:1px solid rgba(105,184,255,.36);background:rgba(5,12,24,.88);color:#dceeff;border-radius:9px;min-width:34px;height:31px;padding:2px 6px;font-size:9px;font-weight:1000;line-height:1}.controlGroupChip b{display:block;font-size:12px}.controlGroupChip.assigned{border-color:#69b8ff;background:rgba(35,103,158,.88)}
#minimapDock{display:block!important;position:fixed!important;right:12px!important;bottom:286px!important;z-index:12!important;width:224px!important;padding:7px!important}.miniCollapse{appearance:none;border:0;background:rgba(255,255,255,.08);color:#fff;border-radius:7px;padding:2px 6px;font-weight:1000;cursor:pointer}#minimapDock.collapsed{width:auto!important}#minimapDock.collapsed #minimap,#minimapDock.collapsed #miniLeader{display:none!important}#minimap{display:block!important;width:210px!important;height:138px!important}#miniLeader{display:inline!important}
#doctrineBtn{appearance:none;border:1px solid rgba(255,209,102,.48);background:rgba(255,209,102,.12);color:#fff1bd;border-radius:10px;padding:7px 9px;font-size:9px;font-weight:1000;cursor:pointer}#doctrineOverlay{position:fixed;inset:0;z-index:31;display:none;align-items:center;justify-content:center;padding:14px;background:rgba(1,4,10,.84)}#doctrineOverlay.open{display:flex}#doctrineCard{width:min(760px,calc(100vw - 24px));max-height:calc(100dvh - 24px);overflow:auto;padding:18px;border-radius:22px;background:linear-gradient(180deg,#152642,#070c17);border:1px solid rgba(255,255,255,.2)}#doctrineChoices{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:12px}.doctrineChoice{appearance:none;text-align:left;color:#fff;border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.055);border-radius:15px;padding:12px;cursor:pointer}.doctrineChoice:hover:not(:disabled){border-color:#ffd166;background:rgba(255,209,102,.1)}.doctrineChoice:disabled{opacity:.45}.doctrineChoice b{display:block;font-size:14px}.doctrineChoice small{display:block;color:#a9bdd5;font-size:10px;line-height:1.42;margin-top:5px}.doctrineCost{color:#ffe19a!important;font-weight:1000}#closeDoctrine{width:100%;margin-top:12px}
#postMatchReport{margin:14px 0 4px;text-align:left}.reportSummary{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-bottom:9px}.reportStat{padding:8px;border-radius:11px;background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.1);text-align:center}.reportStat b{display:block;font-size:17px}.reportStat small{color:#9fb4cd;font-size:9px}.reportTable{width:100%;border-collapse:collapse;font-size:10px}.reportTable th,.reportTable td{padding:6px 5px;border-bottom:1px solid rgba(255,255,255,.08);text-align:right}.reportTable th:first-child,.reportTable td:first-child{text-align:left}.reportNote{font-size:10px;color:#a9bdd5;line-height:1.4;margin-top:8px}
@media(max-width:900px){#minimapDock{right:7px!important;bottom:218px!important;width:154px!important;padding:5px!important}#minimap{width:142px!important;height:96px!important}#miniHeader{font-size:8px!important}#controlGroups{top:47px;right:6px}.controlGroupChip{min-width:30px;height:28px;padding:1px 4px}#battleAlerts{top:44px}#doctrineChoices{grid-template-columns:1fr}}
@media(max-width:620px){#minimapDock{bottom:193px!important;width:126px!important}#minimap{width:114px!important;height:78px!important}#battleAlerts{top:41px}.battleAlert{font-size:9px;padding:3px 7px}#controlGroups{top:40px}.controlGroupChip{min-width:27px;height:25px;font-size:7px}.controlGroupChip b{font-size:10px}.reportSummary{grid-template-columns:repeat(2,1fr)}}
'''
replace_once('</style>', css + '\n</style>', 'strategy css')

replace_once(
    '<canvas id="minimap" hidden></canvas><span id="miniLeader" hidden></span>',
    '<div id="minimapDock" class="glass"><div id="miniHeader"><span>Battle Map</span><span id="miniLeader">3 factions alive</span><button id="miniCollapse" class="miniCollapse" aria-label="Collapse minimap">−</button></div><canvas id="minimap"></canvas></div>',
    'minimap markup',
)
replace_once('<div id="toast"></div>', '<div id="battleAlerts" aria-live="assertive"></div><div id="controlGroups" aria-label="Control groups"></div><div id="toast"></div>', 'alerts and control groups markup')
replace_once('<p id="endText">The opposing command bases have fallen.</p>', '<p id="endText">The opposing command bases have fallen.</p><div id="postMatchReport"></div>', 'post-match report markup')

js = r'''

// ---------- Strategic command expansion ----------
const CONTROL_GROUP_COUNT=4,controlGroupSlots=Array.from({length:CONTROL_GROUP_COUNT},()=>[]),commandMarkers=[];
const DOCTRINES={
  frontier:[
    {id:'mechanized',name:'Mechanized Command',icon:'▥',cost:[225,125],desc:'Armored and mechanical units gain 12% health and 10% damage. Factories train 12% faster.'},
    {id:'orbital',name:'Orbital Command',icon:'△',cost:[225,125],desc:'Flying units move and attack 10% faster. Scans and transport abilities recharge 15% faster.'},
    {id:'fortress',name:'Fortress Command',icon:'▰',cost:[225,125],desc:'Structures gain 18% health, defensive weapons deal 12% more damage, and repairs restore more.'}
  ],
  ascendant:[
    {id:'barrier',name:'Barrier Doctrine',icon:'◈',cost:[225,125],desc:'All shields increase 16%, shield regeneration begins sooner, and barrier support is stronger.'},
    {id:'psionic',name:'Psionic Doctrine',icon:'Ψ',cost:[225,125],desc:'Psionic units deal 12% more damage and active abilities recharge 12% faster.'},
    {id:'celestial',name:'Celestial Fleet',icon:'✹',cost:[225,125],desc:'Flying units gain 14% health, 10% damage, and train 10% faster.'}
  ],
  brood:[
    {id:'swarm',name:'Endless Swarm',icon:'●',cost:[225,125],desc:'Light biological units train or morph 14% faster and Zerglings cost 10 fewer minerals.'},
    {id:'creep',name:'Creep Dominion',icon:'≋',cost:[225,125],desc:'Brood regeneration on creep rises 25%, creep vision expands, and movement on creep improves.'},
    {id:'primal',name:'Primal Evolution',icon:'♜',cost:[225,125],desc:'Armored, massive, and advanced Brood units gain 12% health and 12% damage.'}
  ]
};
function safeNum(v){return Number.isFinite(Number(v))?Number(v):0}
function ensureMatchStats(p){if(!p)return null;p.matchStats=p.matchStats||{minerals:0,gas:0,unitsProduced:0,structuresBuilt:0,unitsLost:0,structuresLost:0,unitKills:0,structuresDestroyed:0,damageDealt:0,researchCompleted:0,peakArmy:0,killsByType:{}};p.doctrineId=p.doctrineId||null;return p.matchStats}
function doctrineForFaction(f){const p=players[f];return (DOCTRINES[p?.factionId]||[]).find(d=>d.id===p?.doctrineId)||null}
function doctrineReady(f){const p=players[f],tech=playerStructures(f).filter(s=>!STRUCTURES[s.type]?.base&&!STRUCTURES[s.type]?.supply&&!STRUCTURES[s.type]?.gas);return !!p&&!p.doctrineId&&tech.length>=2}
function chooseDoctrine(f,id,free=false){const p=players[f],choice=(DOCTRINES[p?.factionId]||[]).find(d=>d.id===id);if(!p||!choice||p.doctrineId||!doctrineReady(f))return false;if(!free&&!canAfford(f,choice.cost))return false;if(!free)spend(f,choice.cost);p.doctrineId=id;for(const e of entities.filter(e=>e.faction===f&&e.alive!==false))applyDoctrineStats(e);if(f===PLAYER){renderDoctrineUI();pushBattleAlert(`${choice.icon} ${choice.name} adopted`,null,null,'info')}markDirty();return true}
function applyDoctrineStats(e){if(!e||e.faction<0)return e;const id=players[e.faction]?.doctrineId;if(!id||e.doctrineApplied===id)return e;const d=defOf(e),oldHp=Math.max(1,e.maxHp||d?.hp||1),oldShield=Math.max(0,e.maxShield||d?.shield||0),hpRatio=clamp((e.hp||oldHp)/oldHp,0,1),shieldRatio=oldShield?clamp((e.shield||0)/oldShield,0,1):0;let hpMult=1,shieldMult=1;if(id==='mechanized'&&(hasTag(e,'mechanical')||hasTag(e,'armored')))hpMult=1.12;if(id==='fortress'&&e.kind==='structure')hpMult=1.18;if(id==='celestial'&&isFlying(e))hpMult=1.14;if(id==='barrier'&&(e.maxShield||d?.shield))shieldMult=1.16;if(id==='primal'&&(hasTag(e,'armored')||hasTag(e,'massive')||['ravager','lurker','defiler','ultralisk'].includes(e.type)))hpMult=1.12;e.maxHp=Math.round(oldHp*hpMult);e.hp=Math.max(1,Math.min(e.maxHp,e.maxHp*hpRatio));e.maxShield=Math.round(oldShield*shieldMult);e.shield=Math.min(e.maxShield,e.maxShield*shieldRatio);e.doctrineApplied=id;return e}
function doctrineDamageMultiplier(attacker){const id=players[attacker?.faction]?.doctrineId;if(id==='mechanized'&&(hasTag(attacker,'mechanical')||hasTag(attacker,'armored')))return 1.1;if(id==='fortress'&&attacker?.kind==='structure')return 1.12;if(id==='psionic'&&hasTag(attacker,'psionic'))return 1.12;if(id==='celestial'&&isFlying(attacker))return 1.1;if(id==='primal'&&(hasTag(attacker,'armored')||hasTag(attacker,'massive')||['ravager','lurker','defiler','ultralisk'].includes(attacker?.type)))return 1.12;return 1}
function doctrineProductionMultiplier(f,type){const id=players[f]?.doctrineId;if(id==='mechanized'&&['hellion','siegeTank','goliath'].includes(type))return .88;if(id==='celestial'&&UNITS[type]?.tags?.includes('flying'))return .9;if(id==='swarm'&&UNITS[type]?.tags?.includes('light')&&UNITS[type]?.tags?.includes('biological'))return .86;return 1}
function doctrineAbilityMultiplier(e){const id=players[e?.faction]?.doctrineId;if(id==='orbital'&&(isFlying(e)||e?.type==='dropship'))return .85;if(id==='psionic'&&hasTag(e,'psionic'))return .88;return 1}
function showCommandMarker(x,y,kind='move'){commandMarkers.push({x:Number(x),y:Number(y),kind,startAt:nowMs(),endAt:nowMs()+1800})}
function drawCommandMarkers(){const t=nowMs(),z=TILE*cam.zoom;for(const marker of commandMarkers){if(marker.endAt<=t)continue;const s=worldToScreen(marker.x,marker.y),p=clamp((t-marker.startAt)/Math.max(1,marker.endAt-marker.startAt),0,1),alpha=1-p,r=z*(.22+.18*p);ctx.save();ctx.globalAlpha=alpha;ctx.lineWidth=Math.max(2,z*.055);ctx.strokeStyle=marker.kind==='attackMove'?'#ff5365':marker.kind==='rally'?'#ffd166':'#69b8ff';ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=12;if(marker.kind==='rally'){ctx.beginPath();ctx.moveTo(s.x+z*.43,s.y+z*.8);ctx.lineTo(s.x+z*.43,s.y+z*.2);ctx.lineTo(s.x+z*.76,s.y+z*.34);ctx.lineTo(s.x+z*.43,s.y+z*.47);ctx.stroke()}else{ctx.beginPath();ctx.arc(s.x+z/2,s.y+z/2,r,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(s.x+z/2-r*.65,s.y+z/2);ctx.lineTo(s.x+z/2+r*.65,s.y+z/2);ctx.moveTo(s.x+z/2,s.y+z/2-r*.65);ctx.lineTo(s.x+z/2,s.y+z/2+r*.65);ctx.stroke()}ctx.restore()}for(let i=commandMarkers.length-1;i>=0;i--)if(commandMarkers[i].endAt<=t)commandMarkers.splice(i,1)}
function issueAttackMoveOrder(e,x,y){if(!e||e.kind!=='unit'||e.garrisonedIn||e.siegeMode)return false;e.targetId=null;e.lastKnownTargetX=null;e.lastKnownTargetY=null;e.attackMode=true;e.attackMoveDestination={x:clamp(Number(x),0,BOARD_W-1),y:clamp(Number(y),0,BOARD_H-1)};e.moveDestination={...e.attackMoveDestination};e.destinationStalls=0;e.order='attackMove';if(nowMs()>=e.moveReadyAt)stepTowardDestination(e);markDirty();return true}
function attackMoveGroup(ids,x,y,slot){const units=(ids||[]).map(entityById).filter(e=>e&&e.faction===slot&&e.kind==='unit'&&!e.garrisonedIn&&!e.siegeMode),targets=formationTargets(Number(x),Number(y),units.length);let ordered=0;for(let i=0;i<units.length;i++)if(issueAttackMoveOrder(units[i],targets[i]?.x??x,targets[i]?.y??y))ordered++;return ordered>0}
function setStructureRally(e,x,y){if(!e||e.kind!=='structure'||e.alive===false)return false;const d=STRUCTURES[e.type];if(!d?.produces?.length&&!d?.larvaEvery&&!d?.base)return false;e.rallyPoint={x:clamp(Number(x),0,BOARD_W-1),y:clamp(Number(y),0,BOARD_H-1)};showCommandMarker(e.rallyPoint.x,e.rallyPoint.y,'rally');toast(`${d.name} rally point set. New troops will move as close as possible.`,1900);markDirty();refreshUI(true);return true}
function nearestAttackMoveEnemy(e){return entities.filter(t=>t.alive!==false&&!t.garrisonedIn&&t.faction!==e.faction&&t.faction>=0&&!players[t.faction]?.eliminated&&tileVisibleToFaction(e.faction,t.x,t.y)&&dist(e,t)<=Math.max(6,attackRange(e)+2)).sort((a,b)=>dist(e,a)-dist(e,b)||a.id-b.id)[0]||null}
function updateAttackMoveOrders(){for(const e of entities){if(e.alive===false||e.kind!=='unit'||!e.attackMoveDestination||players[e.faction]?.eliminated)continue;let target=entityById(e.targetId);if(target&&target.alive!==false&&target.faction!==e.faction){if(canTarget(e,target)){fireAt(e,target);continue}if(nowMs()>=e.moveReadyAt)aiStepToward(e,target.x,target.y,true);continue}target=nearestAttackMoveEnemy(e);if(target){e.targetId=target.id;e.order='attackMove';continue}e.targetId=null;e.moveDestination={...e.attackMoveDestination};if(e.x===e.attackMoveDestination.x&&e.y===e.attackMoveDestination.y){e.attackMoveDestination=null;clearMoveDestination(e);e.attackMode=false;e.order='idle'}else if(nowMs()>=e.moveReadyAt)stepTowardDestination(e)}}
function pushBattleAlert(text,x=null,y=null,severity='normal'){const host=document.getElementById('battleAlerts');if(!host)return;const key=`${text}|${Math.round(x||0)}|${Math.round(y||0)}`,stamp=Number(host.dataset[key]||0);if(nowMs()-stamp<4200)return;host.dataset[key]=String(nowMs());const b=document.createElement('button');b.className='battleAlert'+(severity==='severe'?' severe':'');b.textContent=text;b.onclick=()=>{if(Number.isFinite(x)&&Number.isFinite(y))centerOn(x,y);b.remove()};host.prepend(b);while(host.children.length>3)host.lastElementChild.remove();setTimeout(()=>b.remove(),severity==='severe'?6500:4800)}
function renderControlGroups(){const host=document.getElementById('controlGroups');if(!host)return;host.innerHTML='';for(let i=0;i<CONTROL_GROUP_COUNT;i++){const b=document.createElement('button'),ids=controlGroupSlots[i].filter(id=>entityById(id)?.alive!==false);controlGroupSlots[i]=ids;b.className='controlGroupChip'+(ids.length?' assigned':'');b.innerHTML=`<b>${i+1}</b>${ids.length||'—'}`;let hold=null;b.onpointerdown=()=>{hold=setTimeout(()=>{assignControlGroup(i);hold=null},520)};b.onpointerup=()=>{if(hold){clearTimeout(hold);recallControlGroup(i)}};b.onpointercancel=()=>{if(hold)clearTimeout(hold)};host.appendChild(b)}}
function assignControlGroup(i){const ids=selectedEntities().filter(ownEntity).map(e=>e.id);if(!ids.length){toast('Select your units or structures before assigning a control group.',1800);return}controlGroupSlots[i]=ids;renderControlGroups();toast(`Control group ${i+1} assigned: ${ids.length} selected.`,1500)}
function recallControlGroup(i){const list=controlGroupSlots[i].map(entityById).filter(e=>e&&e.alive!==false&&e.faction===PLAYER);if(!list.length){toast(`Control group ${i+1} is empty. Hold its chip to assign the current selection.`,1700);return}selectEntities(list);const x=list.reduce((s,e)=>s+e.x,0)/list.length,y=list.reduce((s,e)=>s+e.y,0)/list.length;centerOn(x,y)}
function createDoctrineUI(){if(document.getElementById('doctrineOverlay'))return;const btn=document.createElement('button');btn.id='doctrineBtn';btn.textContent='Doctrine';btn.onclick=()=>document.getElementById('doctrineOverlay').classList.add('open');document.getElementById('utilityButtons')?.appendChild(btn);const wrap=document.createElement('div');wrap.id='doctrineOverlay';wrap.setAttribute('aria-hidden','true');wrap.innerHTML='<div id="doctrineCard"><h2>Strategic Doctrine</h2><p style="color:#b8cce2;font-size:12px;line-height:1.45">After establishing two technology structures, commit to one permanent match doctrine. The choice specializes your army instead of merely increasing every statistic.</p><div id="doctrineChoices"></div><button id="closeDoctrine" class="hudBtn">Return to Battle</button></div>';document.body.appendChild(wrap);wrap.onclick=e=>{if(e.target===wrap)wrap.classList.remove('open')};document.getElementById('closeDoctrine').onclick=()=>wrap.classList.remove('open')}
function renderDoctrineUI(){createDoctrineUI();const p=players[PLAYER],btn=document.getElementById('doctrineBtn'),host=document.getElementById('doctrineChoices');if(!p||!btn||!host)return;const chosen=doctrineForFaction(PLAYER);btn.textContent=chosen?`${chosen.icon} ${chosen.name}`:doctrineReady(PLAYER)?'Doctrine Ready':'Doctrine';btn.disabled=!!chosen;host.innerHTML='';for(const d of DOCTRINES[p.factionId]||[]){const b=document.createElement('button');b.className='doctrineChoice';b.disabled=!!chosen||!doctrineReady(PLAYER)||!canAfford(PLAYER,d.cost);b.innerHTML=`<b>${d.icon} ${d.name}</b><small>${d.desc}</small><small class="doctrineCost">◆ ${d.cost[0]} · ◈ ${d.cost[1]}</small>`;b.onclick=()=>{sendCommand({type:'doctrine',doctrineId:d.id});document.getElementById('doctrineOverlay').classList.remove('open')};host.appendChild(b)}}
function formatDuration(ms){const total=Math.max(0,Math.floor(ms/1000));return `${Math.floor(total/60)}:${String(total%60).padStart(2,'0')}`}
function renderPostMatchReport(winner){const host=document.getElementById('postMatchReport');if(!host)return;const mine=players[PLAYER],stats=ensureMatchStats(mine),duration=nowMs()-safeNum(modeState?.matchStartedAt||matchStartedAt),objective=safeNum(modeState?.scores?.[PLAYER]);const rows=players.map(p=>{const s=ensureMatchStats(p);return `<tr><td>${factionOf(p.idx).icon} ${p.name}</td><td>${s.unitKills+s.structuresDestroyed}</td><td>${s.unitsProduced}</td><td>${Math.round(s.minerals+s.gas)}</td><td>${Math.round(s.damageDealt)}</td><td>${s.researchCompleted}</td></tr>`}).join('');const topKills=Object.entries(stats.killsByType||{}).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([type,n])=>`${UNITS[type]?.name||STRUCTURES[type]?.name||type} ${n}`).join(' · ')||'No confirmed kills';host.innerHTML=`<div class="reportSummary"><div class="reportStat"><b>${formatDuration(duration)}</b><small>Match Time</small></div><div class="reportStat"><b>${stats.peakArmy}</b><small>Peak Army</small></div><div class="reportStat"><b>${stats.unitKills+stats.structuresDestroyed}</b><small>Enemies Destroyed</small></div><div class="reportStat"><b>${stats.unitsProduced}</b><small>Units Produced</small></div><div class="reportStat"><b>${Math.round(stats.minerals+stats.gas)}</b><small>Resources Gathered</small></div><div class="reportStat"><b>${objective}</b><small>Objective Score</small></div></div><table class="reportTable"><thead><tr><th>Commander</th><th>Kills</th><th>Units</th><th>Resources</th><th>Damage</th><th>Research</th></tr></thead><tbody>${rows}</tbody></table><div class="reportNote"><b>Your doctrine:</b> ${doctrineForFaction(PLAYER)?.name||'None'} · <b>Most effective:</b> ${topKills} · <b>Losses:</b> ${stats.unitsLost} units and ${stats.structuresLost} structures.</div>`}
let matchStartedAt=0,lastAlertScan=0;
const baseMakePlayer=makePlayer;makePlayer=function(...args){const p=baseMakePlayer(...args);ensureMatchStats(p);return p};
const baseCreateGameStrategic=createGame;createGame=function(slotConfig){const out=baseCreateGameStrategic(slotConfig);matchStartedAt=nowMs();if(modeState)modeState.matchStartedAt=matchStartedAt;controlGroupSlots.forEach((_,i)=>controlGroupSlots[i]=[]);renderControlGroups();renderDoctrineUI();return out};
const baseAddEntityStrategic=addEntity;addEntity=function(kind,type,faction,x,y,opts={}){const e=baseAddEntityStrategic(kind,type,faction,x,y,opts);applyDoctrineStats(e);if(gameStarted&&kind==='structure'&&opts.complete===false)ensureMatchStats(players[faction]);return e};
const baseDamageAgainstStrategic=damageAgainst;damageAgainst=function(attacker,target){return Math.round(baseDamageAgainstStrategic(attacker,target)*doctrineDamageMultiplier(attacker))};
const baseEffectiveMoveCdStrategic=effectiveMoveCd;effectiveMoveCd=function(e){let value=baseEffectiveMoveCdStrategic(e),id=players[e?.faction]?.doctrineId;if(id==='orbital'&&isFlying(e))value*=.9;if(id==='celestial'&&isFlying(e))value*=.9;if(id==='creep'&&players[e?.faction]?.factionId==='brood'&&isCreepTile(e.faction,e.x,e.y))value*=.88;return value};
const baseEffectiveAttackCdStrategic=effectiveAttackCd;effectiveAttackCd=function(e){let value=baseEffectiveAttackCdStrategic(e),id=players[e?.faction]?.doctrineId;if(id==='orbital'&&isFlying(e))value*=.9;if(id==='celestial'&&isFlying(e))value*=.9;return value};
const baseEffectiveAbilityCdStrategic=effectiveAbilityCd;effectiveAbilityCd=function(id,e=null){return baseEffectiveAbilityCdStrategic(id,e)*doctrineAbilityMultiplier(e)};
const baseBroodRegenRateStrategic=broodRegenRate;broodRegenRate=function(e){let value=baseBroodRegenRateStrategic(e);if(players[e?.faction]?.doctrineId==='creep'&&isCreepTile(e.faction,e.x,e.y))value*=1.25;return value};
const baseVisionRadiusStrategic=visionRadius;visionRadius=function(e){let value=baseVisionRadiusStrategic(e);if(players[e?.faction]?.doctrineId==='creep'&&players[e.faction]?.factionId==='brood'&&isCreepTile(e.faction,e.x,e.y))value+=1;return value};
const baseQueueUnitStrategic=queueUnit;queueUnit=function(structure,type){const before=structure?.queue?.length||0,ok=baseQueueUnitStrategic(structure,type);if(ok&&structure.queue.length>before){const item=structure.queue[structure.queue.length-1],mult=doctrineProductionMultiplier(structure.faction,type);item.finishAt=item.startAt+(item.finishAt-item.startAt)*mult;if(players[structure.faction]?.doctrineId==='swarm'&&type==='zergling'){const refundAmount=Math.min(10,UNITS[type].cost[0]);players[structure.faction].minerals+=refundAmount;item.cost=[item.cost[0]-refundAmount,item.cost[1]]}}return ok};
function recordProduced(f,type){const s=ensureMatchStats(players[f]);if(!s)return;s.unitsProduced++;s.peakArmy=Math.max(s.peakArmy,playerUnits(f).filter(u=>!isWorker(u)).length);}
const baseSpawnProducedUnit=spawnProducedUnit;
spawnProducedUnit=function(structure,type){const before=nextEntityId,ok=baseSpawnProducedUnit(structure,type);if(ok){const unit=entities.find(e=>e.id===before);if(unit){recordProduced(unit.faction,unit.type);applyDoctrineStats(unit);if(structure.rallyPoint)issueMoveOrder(unit,structure.rallyPoint.x,structure.rallyPoint.y)}}return ok};
const baseUpdateProductionForRally=updateProduction;
updateProduction=function(dt){const cocoons=new Map(entities.filter(e=>e.alive!==false&&e.kind==='cocoon').map(e=>[e.id,e.sourceId]));baseUpdateProductionForRally(dt);for(const [id,sourceId] of cocoons){const unit=entityById(id),source=entityById(sourceId);if(unit?.kind==='unit'&&!unit.rallyApplied){unit.rallyApplied=true;recordProduced(unit.faction,unit.type);applyDoctrineStats(unit);if(source?.rallyPoint)issueMoveOrder(unit,source.rallyPoint.x,source.rallyPoint.y)}}};
const baseMorphLarvaStrategic=morphLarva;morphLarva=function(larva,type){const ok=baseMorphLarvaStrategic(larva,type);if(ok&&larva.morphEnd){larva.morphEnd=nowMs()+(larva.morphEnd-nowMs())*doctrineProductionMultiplier(larva.faction,type)}return ok};
const baseCompleteConstructionStrategic=completeConstruction;completeConstruction=function(e){baseCompleteConstructionStrategic(e);applyDoctrineStats(e);const s=ensureMatchStats(players[e.faction]);if(s)s.structuresBuilt++};
const baseCompleteResearchStrategic=completeResearch;completeResearch=function(f,id){const before=researchLevel(f,id),out=baseCompleteResearchStrategic(f,id);if(researchLevel(f,id)>before){const s=ensureMatchStats(players[f]);if(s)s.researchCompleted++}return out};
const baseUpdateMiningStrategic=updateMining;updateMining=function(){const before=players.map(p=>({m:safeNum(p.minerals),g:safeNum(p.gas)}));baseUpdateMiningStrategic();players.forEach((p,i)=>{const s=ensureMatchStats(p);s.minerals+=Math.max(0,p.minerals-before[i].m);s.gas+=Math.max(0,p.gas-before[i].g);s.peakArmy=Math.max(s.peakArmy,playerUnits(i).filter(u=>!isWorker(u)).length)})};
const baseApplyDamageStrategic=applyDamage;applyDamage=function(target,amount,attacker=null){const hpBefore=safeNum(target?.hp)+safeNum(target?.shield);baseApplyDamageStrategic(target,amount,attacker);const dealt=Math.max(0,hpBefore-(safeNum(target?.hp)+safeNum(target?.shield)));if(attacker&&players[attacker.faction])ensureMatchStats(players[attacker.faction]).damageDealt+=dealt;if(target?.faction===PLAYER&&attacker?.faction!==PLAYER&&nowMs()-lastAlertScan>1100){lastAlertScan=nowMs();const label=isBase(target)?'COMMAND BASE UNDER ATTACK':isWorker(target)?'Workers under attack':target.kind==='structure'?`${STRUCTURES[target.type]?.name||'Structure'} under attack`:'Army taking fire';pushBattleAlert(label,target.x,target.y,isBase(target)?'severe':'normal')}};
const baseKillEntityStrategic=killEntity;killEntity=function(e,attacker=null){if(e?.alive===false)return;const wasUnit=e.kind==='unit',wasStructure=e.kind==='structure',type=e.type,f=e.faction;baseKillEntityStrategic(e,attacker);const victim=ensureMatchStats(players[f]);if(victim){if(wasUnit)victim.unitsLost++;else if(wasStructure)victim.structuresLost++}const killer=ensureMatchStats(players[attacker?.faction]);if(killer&&attacker?.faction!==f){if(wasUnit)killer.unitKills++;else if(wasStructure)killer.structuresDestroyed++;killer.killsByType[type]=(killer.killsByType[type]||0)+1}};
const baseUpdatePersistentOrdersStrategic=updatePersistentOrders;updatePersistentOrders=function(){baseUpdatePersistentOrdersStrategic();updateAttackMoveOrders()};
const baseApplyCommand=applyCommand;applyCommand=function(c){if(!gameStarted)return;if(c.type==='attackMove'){const e=entityById(c.entityId);if(e?.faction===c.slot)issueAttackMoveOrder(e,c.x,c.y);if(c.slot===PLAYER)showCommandMarker(c.x,c.y,'attackMove');refreshUI(true);return}if(c.type==='groupAttackMove'){attackMoveGroup(c.entityIds,c.x,c.y,c.slot);if(c.slot===PLAYER)showCommandMarker(c.x,c.y,'attackMove');refreshUI(true);return}if(c.type==='setRally'){const e=entityById(c.entityId);if(e?.faction===c.slot)setStructureRally(e,c.x,c.y);return}if(c.type==='doctrine'){chooseDoctrine(c.slot,c.doctrineId,true);return}const affected=c.entityIds?.map(entityById).filter(Boolean)||[entityById(c.entityId)].filter(Boolean);if(['move','groupMove'].includes(c.type))for(const e of affected){e.attackMoveDestination=null;e.attackMode=false}const out=baseApplyCommand(c);if(c.slot===PLAYER&&c.type==='move')showCommandMarker(c.x,c.y,'move');if(c.slot===PLAYER&&c.type==='groupMove')showCommandMarker(c.x,c.y,'move');if(['stop','groupStop','hold','groupHold'].includes(c.type))for(const e of affected){e.attackMoveDestination=null;e.attackMode=false}return out};
const baseAiThinkStrategic=aiThink;aiThink=function(f,cfg){if(!players[f]?.doctrineId&&doctrineReady(f)){const choices=DOCTRINES[players[f].factionId]||[],pick=players[f].factionId==='frontier'?(aiVisibleEnemies(f).some(isFlying)?'orbital':countType(f,'bunker')>1?'fortress':'mechanized'):players[f].factionId==='ascendant'?(playerUnits(f).filter(isFlying).length>=3?'celestial':playerUnits(f).filter(u=>hasTag(u,'psionic')).length>=2?'psionic':'barrier'):(playerUnits(f).filter(u=>['ultralisk','ravager','lurker'].includes(u.type)).length>=2?'primal':playerStructures(f).length>5?'creep':'swarm');chooseDoctrine(f,choices.find(d=>d.id===pick)?.id||choices[0]?.id,true)}return baseAiThinkStrategic(f,cfg)};
const baseDrawStrategic=draw;draw=function(){baseDrawStrategic();drawCommandMarkers()};
const baseRefreshUIStrategic=refreshUI;refreshUI=function(force=false){const out=baseRefreshUIStrategic(force);renderControlGroups();renderDoctrineUI();return out};
const baseFinishMatchStrategic=finishMatch;finishMatch=function(winner,reason=''){baseFinishMatchStrategic(winner,reason);renderPostMatchReport(winner)};
function tryStrategicHold(sx,sy){if(!gameStarted||paused||interactionMode)return false;const t=screenToTile(sx,sy);if(!inBounds(t.x,t.y))return false;const list=selectedEntities().filter(ownEntity),units=list.filter(e=>e.kind==='unit'),structure=list.length===1&&list[0].kind==='structure'?list[0]:null;if(units.length){sendCommand({type:units.length>1?'groupAttackMove':'attackMove',entityIds:units.length>1?units.map(e=>e.id):undefined,entityId:units.length===1?units[0].id:undefined,x:t.x,y:t.y});return true}if(structure&&(STRUCTURES[structure.type]?.produces?.length||STRUCTURES[structure.type]?.larvaEvery||STRUCTURES[structure.type]?.base)){sendCommand({type:'setRally',entityId:structure.id,x:t.x,y:t.y});return true}return false}
createDoctrineUI();renderControlGroups();const miniDock=document.getElementById('minimapDock'),miniCollapseBtn=document.getElementById('miniCollapse');if(miniCollapseBtn)miniCollapseBtn.onclick=()=>{miniDock.classList.toggle('collapsed');miniCollapseBtn.textContent=miniDock.classList.contains('collapsed')?'+':'−';resize()};
const strategicKeyHandler=e=>{if(!gameStarted||e.repeat||e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;const n=Number(e.key);if(n>=1&&n<=CONTROL_GROUP_COUNT){e.preventDefault();if(e.ctrlKey||e.metaKey)assignControlGroup(n-1);else recallControlGroup(n-1)}};window.addEventListener('keydown',strategicKeyHandler);
const basePointerDown=canvas.onpointerdown;
let strategicHoldTimer=null,strategicHoldTriggered=false,strategicHoldStart=null;
canvas.addEventListener('pointerdown',e=>{strategicHoldTriggered=false;strategicHoldStart={x:e.clientX,y:e.clientY,id:e.pointerId};if(e.button===0)strategicHoldTimer=setTimeout(()=>{if(!strategicHoldStart||strategicHoldStart.id!==e.pointerId||pointerMoved||activePointers.size>1)return;if(tryStrategicHold(strategicHoldStart.x,strategicHoldStart.y)){strategicHoldTriggered=true;clearSelectionHold();selectionBox=null;dragging=false;canvas.classList.remove('dragging');if(navigator.vibrate)navigator.vibrate(35)}},560)},true);
canvas.addEventListener('pointermove',e=>{if(strategicHoldStart&&strategicHoldStart.id===e.pointerId&&Math.hypot(e.clientX-strategicHoldStart.x,e.clientY-strategicHoldStart.y)>9){clearTimeout(strategicHoldTimer);strategicHoldTimer=null}},true);
canvas.addEventListener('pointerup',e=>{clearTimeout(strategicHoldTimer);strategicHoldTimer=null;strategicHoldStart=null;if(strategicHoldTriggered){strategicHoldTriggered=false;e.stopImmediatePropagation();e.preventDefault()}},true);
canvas.addEventListener('pointercancel',()=>{clearTimeout(strategicHoldTimer);strategicHoldTimer=null;strategicHoldStart=null;strategicHoldTriggered=false},true);
'''

replace_once('// ---------- Main loop ----------', js + '\n// ---------- Main loop ----------', 'strategic JavaScript injection')

text = text.replace('mine.unitKills+safenum(mine.structuresDestroyed)', 'safeNum(mine.unitKills)+safeNum(mine.structuresDestroyed)')
path.write_text(text, encoding='utf-8')
print(f'Patched {path} ({len(text):,} characters)')
