(function(){
'use strict';
const $=id=>document.getElementById(id), SAVE='ats-crown-save-v1', LEGACY='ats-crown-legacy-v1', SETTINGS='ats-crown-settings-v1';
const screens=['menu','guide','pause','settings','death','legacy','overview','build','bootError'];
let game=null, screen='menu', running=false, lastTime=0, accumulator=0, hudTimer=0, autosaveTimer=0, overviewTimer=0, deathShown=false, settingsReturn='pause', guideReturn='menu';
let buildSettlementId=null, pendingMenuNotice=null;
let settings={enabled:true,volume:.45,quality:'high',reducedMotion:false}, histories=[], saved=null, storageAvailable=true,saveWarned=false;
const keys=new Set(),pointer={x:innerWidth*.7,y:innerHeight*.5,active:false,aiming:false},touchMove={x:0,y:0},joy={id:null,x:0,y:0},fmt=n=>Math.floor(n||0).toLocaleString();
const renderer=new ATSRenderer($('gameCanvas')), audio=new ATSAudio();window.ATS={renderer,audio,get game(){return game},get screen(){return screen},get performance(){return game?.performance.snapshot()},debugPerformance(enabled=true){debugPerf=enabled;if(game)game.performance.enabled=enabled;perfPanel.hidden=!enabled}};
const army=new ATSArmyUI({getGame:()=>game,getScreen:()=>screen,renderer,command:cmd=>{if(['charge','spreadCharge'].includes(cmd)&&matchMedia('(pointer:coarse)').matches){pointer.aiming=cmd}else game.command(cmd,currentAim())},find:()=>toggleSettlementFinder(),build:()=>openBuild(),resetInput:()=>{pointer.active=false;pointer.aiming=false}});window.ATS.army=army;
let debugPerf=new URLSearchParams(location.search).has('perf');const perfPanel=document.createElement('pre');perfPanel.id='performanceMonitor';perfPanel.hidden=!debugPerf;perfPanel.style.cssText='position:fixed;right:12px;bottom:12px;z-index:90;margin:0;padding:10px;background:rgba(4,16,22,.9);color:#b7dccb;border:1px solid #3b665c;pointer-events:none;font:11px/1.4 monospace';document.body.append(perfPanel);
function read(key,fallback){try{let raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{storageAvailable=false;return false}}
settings={...settings,...read(SETTINGS,{})};histories=read(LEGACY,[]);if(!Array.isArray(histories))histories=[];saved=read(SAVE,null);if(saved?.ended||!saved?.king||saved.king.hp<=0)saved=null;
audio.setSettings(settings);renderer.quality=settings.quality;renderer.reducedMotion=settings.reducedMotion;
function show(id){const wasBuild=screen==='build';for(const s of screens)$(s).hidden=s!==id;screen=id;running=id==='play';$('hud').hidden=!(id==='play'||id==='pause'||id==='overview'||id==='build'||id==='settings'&&game);$('hud').inert=id!=='play';$('commandPanel').hidden=true;$('commandToggle').setAttribute('aria-expanded','false');keys.clear();army.cancel();pointer.active=false;pointer.aiming=false;touchMove.x=touchMove.y=0;joy.id=null;$('joystickKnob').style.transform='translate(0px,0px)';accumulator=0;audio.pause(!running);if(id!=='build')buildSettlementId=null;updateMenu();if(id==='overview')updateOverview();if(id==='legacy')renderLegacy();if(pendingMenuNotice&&id!=='play'){const notice=pendingMenuNotice;pendingMenuNotice=null;menuFeedback(notice.text,notice.color)}const target=$(id)?.querySelector('button:not(:disabled),input');if(id!=='play')requestAnimationFrame(()=>target?.focus({preventScroll:true}));else if(wasBuild)requestAnimationFrame(()=>($('buildButton').hidden?$('commandToggle'):$('buildButton')).focus({preventScroll:true}))}
function menuFeedback(text,color='gold'){
 const panel=$(screen)?.querySelector('.dialog,.menu-content');if(!panel){pendingMenuNotice={text,color};return}let message=panel.querySelector('.menu-feedback');if(!message){message=document.createElement('p');message.className='menu-feedback';message.setAttribute('role','status');panel.append(message)}message.textContent=text;message.dataset.color=color;
}
function toast(text,color='gold',category='routine'){
 if(category==='menu'){menuFeedback(text,color);return}if(category!=='villageAttack')return;
 const area=$('toastArea'),el=document.createElement('div');el.className='toast';el.style.borderLeft='2px solid '+({red:'#e47c6b',green:'#83c8b3',gold:'#cfb46e'}[color]||color);el.textContent=text;area.append(el);while(area.children.length>4)area.firstChild.remove();setTimeout(()=>el.remove(),5500);
}
const hooks={toast,sound:(...args)=>audio.play(...args),death:g=>{deathShown=false;try{localStorage.removeItem(SAVE)}catch{}saved=null;recordLegacy(g)}};
function updateMenu(){$('continueRun').disabled=!saved;$('highScore').textContent=fmt(Math.max(0,...histories.map(h=>h.score)))}
function startNew(){
 const seed=$('seedInput').value.trim().slice(0,50)||Math.random().toString(36).slice(2,10).toUpperCase();audio.unlock();
 try{game=new ATSGame(seed,$('difficultySelect').value,hooks);renderer.camera.x=game.king.x;renderer.camera.y=game.king.y;renderer.camera.zoom=1;renderer.camera.armyFocus=null;renderer.findSettlements=false;$('findSettlementButton').setAttribute('aria-pressed','false');deathShown=false;$('toastArea').replaceChildren();show('play');saveGame(false)}catch(e){handleError(e)}
}
function loadGame(data=saved){audio.unlock();try{validateSave(data);game=ATSGame.fromJSON(data,hooks);renderer.camera.x=game.king.x;renderer.camera.y=game.king.y;deathShown=false;$('toastArea').replaceChildren();show('play');return true}catch(e){toast('Could not load this run: '+e.message,'red','menu');return false}}
function validateSave(d){if(!d||d.version!==1||!d.king||!Number.isFinite(d.king.x)||!Number.isFinite(d.king.y)||!Number.isFinite(d.king.hp)||d.king.hp<=0||d.ended)throw new Error('The file does not contain a living run.');if(!Number.isFinite(d.time)||d.time<0||!Array.isArray(d.apes)||d.apes.length>3000||!Array.isArray(d.humans)||d.humans.length>3000||!Array.isArray(d.settlements)||!d.world)throw new Error('The save data is incomplete.');if(d.apes.filter(a=>a.hp>0).length>MAX_APE_POPULATION)throw new Error('The saved population exceeds '+MAX_APE_POPULATION.toLocaleString()+'.');for(const list of [d.apes,d.humans,d.settlements,d.vehicles||[],d.helis||[]])for(const a of list)if(!Number.isFinite(a.x)||!Number.isFinite(a.y))throw new Error('A saved position is invalid.')}
function saveGame(announce=true){if(!game||game.ended)return false;try{const data=game.serialize();if(!write(SAVE,data)){if(announce||!saveWarned)toast('Device storage is unavailable. Export a save file from Pause.','red','menu');saveWarned=true;return false}saved=data;saveWarned=false;if(announce)toast('Your living run is saved on this device.','green','menu');updateMenu();return true}catch(e){if(announce)toast('Save failed. Export a save file to keep this run.','red','menu');return false}}
function recordLegacy(g){const h={score:g.score,title:g.title,seed:g.seed,difficulty:g.difficulty,time:g.time,stats:{...g.stats},date:new Date().toISOString()};histories.unshift(h);histories.sort((a,b)=>b.score-a.score);histories=histories.slice(0,12);write(LEGACY,histories);updateMenu()}
function renderLegacy(){const list=$('legacyList');list.replaceChildren();if(!histories.length){list.textContent='Every kingdom begins with one ape. Your legacy awaits.';return}for(const h of histories){const row=document.createElement('div');row.className='legacy-row';const title=document.createElement('span');title.textContent=h.title;const score=document.createElement('strong');score.textContent=fmt(h.score);const details=document.createElement('small');details.textContent='Seed '+h.seed+' · '+Math.floor(h.time/60)+'m · '+h.stats.freed+' freed · '+h.difficulty;row.append(title,score,details);list.append(row)}}
function deathScreen(){if(deathShown||!game)return;deathShown=true;show('death');$('legacyTitle').textContent=game.title;$('legacyScore').textContent=fmt(game.score);const stats=$('deathStats');stats.replaceChildren();const lines=[['Apes freed',game.stats.freed],['Apes born',game.stats.born],['Largest traveling horde',game.stats.largestHorde],['Settlements founded',game.stats.settlements],['Settlements surviving',game.settlements.filter(s=>s.population>0).length],['Humans defeated',game.stats.humans],['Bases liberated',game.stats.bases],['Structures destroyed',game.stats.structures],['Days survived',game.day],['Highest human threat',ATSTierNames[game.stats.highestThreat-1]],['Seed',game.seed]];for(const [label,value]of lines){const row=document.createElement('div');row.style.display='flex';row.style.justifyContent='space-between';row.style.gap='20px';const a=document.createElement('span');a.textContent=label;const b=document.createElement('strong');b.textContent=String(value);b.style.color='#cfb46e';row.append(a,b);stats.append(row)}}
function updateHud(){if(!game)return;army.update();const hp=Math.max(0,game.king.hp);$('hpFill').style.width=(hp/game.king.maxHp*100)+'%';$('hpFill').style.background=hp<40?'#e37b6b':'';$('hpText').textContent=Math.ceil(hp)+' / '+game.king.maxHp;$('hordeCount').textContent=game.followers.length;$('populationCount').textContent='Population '+fmt(game.population)+' / '+fmt(MAX_APE_POPULATION);$('foodCount').textContent=fmt(game.food);$('threatText').textContent=ATSTierNames[game.tier-1];$('dayText').textContent='NIGHT '+game.day;$('regionText').textContent=game.world.districtAt(game.king.x,game.king.y).name;$('exposureFill').style.width=(game.exposure*100)+'%';$('exposureText').textContent=game.exposure>.5?'IN THE LIGHT':game.time-game.lastContact<12?'BEING HUNTED':'IN THE SHADOWS';$('exposureText').style.color=game.exposure>.5?'#e37b6b':'#9facaa';
 $('buildButton').hidden=screen!=='play'||game.ended||!game.colonies.lodgeAt(game.king);
}
function openBuild(){
 if(screen!=='play'||!game||game.ended)return;const settlement=game.colonies.lodgeAt(game.king);if(!settlement)return;buildSettlementId=settlement.id;$('buildFeedback').textContent='';saveGame(false);show('build');updateBuild();$('closeBuild').focus({preventScroll:true});
}
function updateBuild(){
 if(screen!=='build'||!game)return;const s=game.settlement(buildSettlementId),near=game.colonies.lodgeAt(game.king);
 if(game.ended||!s||near?.id!==s.id){show('play');return}game.colonies.init(s);const options=game.colonies.catalog(s),byKind=new Map(options.map(item=>[item.kind,item]));
 $('buildTitle').textContent=s.name+' · Main hut';const slots=game.colonies.commissioningSlots(s);$('buildResources').textContent=fmt(s.wood)+' timber · '+fmt(s.food)+' village food · '+fmt(s.builders)+' builders · '+fmt(s.population)+' residents · '+fmt(slots.active)+' / '+fmt(slots.limit)+' commissions';
 const catalog=$('buildCatalog');catalog.replaceChildren();for(const item of options){const card=document.createElement('article');card.className='build-card';const heading=document.createElement('h3');heading.textContent=item.label;const description=document.createElement('p');description.textContent=item.description;const cost=document.createElement('div');cost.className='build-cost';cost.textContent=fmt(item.cost.wood)+' timber'+(item.cost.food?' + '+fmt(item.cost.food)+' food':'')+' · '+fmt(item.totalWork)+' work';const slots=document.createElement('div');slots.className='build-slots';slots.textContent=fmt(item.built)+' built · '+fmt(item.queued)+' queued · '+fmt(item.limit)+' slots';const button=document.createElement('button');button.className='button';button.dataset.structure=item.kind;button.textContent=item.available?'Commission '+item.label:item.reason||'Unavailable';button.disabled=!item.available;button.addEventListener('click',()=>{if(screen!=='build'||!game)return;const result=game.colonies.commission(s.id,item.kind);if(result.ok){saveGame(false);updateBuild();$('buildFeedback').textContent=item.label+' commissioned. Builders will begin when the village is safe.';$('buildFeedback').dataset.color='green'}else{updateBuild();$('buildFeedback').textContent=result.reason||'This structure cannot be commissioned.';$('buildFeedback').dataset.color='red'}});card.append(heading,description,cost,slots,button);catalog.append(card)}
 const projects=$('buildQueue');projects.replaceChildren();for(const p of s.projects||[]){if(p.kind==='lumber')continue;const row=document.createElement('li'),label=byKind.get(p.commissionKind||p.kind)?.label||({barrier:'Palisade',storage:'Food stores',workShelter:'Work shelter',repairBarrier:'Repair defenses',repairHut:'Repair hut',rebuildHut:'Rebuild hut',lodge:'Lodge upgrade'}[p.kind]||p.kind),progress=Math.round((p.progress||0)*100),state=p.waiting?'Queued'+(progress?' ('+progress+'%)':''):p.treeIds?.length?'Clearing ground':progress?'Building '+progress+'%':'Queued';row.textContent=label+' · '+state+(p.commissioned?' · Commissioned':'');projects.append(row)}if(!projects.children.length){const row=document.createElement('li');row.textContent='No building projects waiting.';projects.append(row)}
 const completed=$('buildCompleted');completed.replaceChildren();for(const entry of (s.commissions||[]).filter(p=>p.status==='complete').slice(-8).reverse()){const row=document.createElement('li');row.textContent=byKind.get(entry.kind)?.label||entry.kind;completed.append(row)}if(!completed.children.length){const row=document.createElement('li');row.textContent='Completed commissions will appear here.';completed.append(row)}
 $('buildTraining').textContent='Staffed training facilities gradually strengthen adult residents through three levels. Each level adds 12 maximum health and 8% strike damage. Recruit them after training to take their strength into battle.';
}
function updateOverview(){
 if(!game)return;renderer.drawMap(game,$('mapCanvas'));const site=game.colonies.evaluate(game.king.x,game.king.y);$('overviewStats').textContent='Population '+fmt(game.population)+' / '+fmt(MAX_APE_POPULATION)+' · Traveling '+game.followers.length+' · Legacy '+fmt(game.score)+' · Seed '+game.seed;
 $('siteAssessment').textContent=site.region+' · '+site.biome+' · '+site.berries+' food patches · '+site.wood+' trees · '+(site.water?'water nearby':'no nearby water')+' · '+(site.risk?'human activity nearby':'quiet surroundings')+' · natural capacity '+site.capacity;
 const list=$('settlementList');list.replaceChildren();for(const settlement of game.settlements){
  game.colonies.init(settlement);const s=settlement,row=document.createElement('div');row.className='settlement-row';const head=document.createElement('strong');head.textContent=(s.known?'✕ ':'')+s.name+' · Level '+s.level;head.style.color=s.known?'#e37b6b':'#cfb46e';
  const detail=document.createElement('p');detail.textContent=s.population+'/'+s.housing+' housed · '+s.huts.filter(h=>h.hp>0).length+' huts ('+s.huts.filter(h=>h.hp<=0).length+' ruined) · '+s.scouts+' scouts · '+s.children+' young · '+fmt(s.food)+' food ('+(s.foodDelta>=0?'+':'')+(s.foodDelta||0).toFixed(1)+'/s) · '+fmt(s.wood)+' timber · '+fmt(s.defense)+' defense';
  const project=document.createElement('div');project.textContent=s.status+' · Building: '+s.project+' · '+Math.round(s.buildProgress)+' work';const label=document.createElement('label');label.textContent='Priority ';const select=document.createElement('select');select.setAttribute('aria-label',s.name+' work priority');
  for(const [value,text]of[['balanced','Balanced growth'],['forage','Food security'],['fortify','Defend and repair']]){const option=document.createElement('option');option.value=value;option.textContent=text;option.selected=s.policy===value;select.append(option)}select.addEventListener('change',()=>{game.colonies.action(s.id,select.value);saveGame(false)});label.append(select);
  const actions=document.createElement('div');actions.className='settlement-actions';for(const [action,text]of[['supply','Deliver up to 30 food'],['recruit','Recruit adults']]){const button=document.createElement('button');button.className='button';button.textContent=text;button.addEventListener('click',()=>{const result=game.colonies.action(s.id,action);saveGame(false);updateOverview();if(!result)menuFeedback(Math.hypot(game.king.x-s.x,game.king.y-s.y)>s.radius+110?'Visit '+s.name+' to move supplies or recruit its apes.':action==='supply'?'Gather food before delivering supplies.':'No adults are ready to recruit.','red')});actions.append(button)}
  row.append(head,detail,project,label,actions);list.append(row)
 }if(!game.settlements.length)list.textContent='Rescue apes and settle with Z. Water, woodland and food patches support a lasting home.';
}
function applySettings(){settings={enabled:$('soundToggle').checked,volume:Number($('volumeInput').value),quality:$('qualitySelect').value,reducedMotion:$('reducedMotion').checked};audio.setSettings(settings);renderer.quality=settings.quality;renderer.reducedMotion=settings.reducedMotion;write(SETTINGS,settings)}
function fillSettings(){$('soundToggle').checked=settings.enabled;$('volumeInput').value=settings.volume;$('qualitySelect').value=settings.quality;$('reducedMotion').checked=settings.reducedMotion}
function handleError(e){console.error(e);running=false;audio.pause(true);keys.clear();$('errorMessage').textContent='The world paused safely. '+(e?.message||'An unexpected error occurred.')+(saved?' You can return to your latest living checkpoint.':' Return to the menu to begin another run.');$('errorResume').textContent=saved?'Load latest checkpoint':'Return to menu';show('bootError')}
$('newRun').addEventListener('click',startNew);$('continueRun').addEventListener('click',()=>loadGame());$('howToPlay').addEventListener('click',()=>{guideReturn='menu';show('guide')});$('backGuide').addEventListener('click',()=>show(guideReturn));$('legacyButton').addEventListener('click',()=>show('legacy'));$('backLegacy').addEventListener('click',()=>show('menu'));
$('pauseButton').addEventListener('click',()=>{if(game&&!game.ended){saveGame(false);show('pause')}});$('resumeRun').addEventListener('click',()=>show('play'));$('saveRun').addEventListener('click',()=>saveGame());$('quitRun').addEventListener('click',()=>{saveGame(false);show('menu')});$('settingsButton').addEventListener('click',()=>{settingsReturn='pause';fillSettings();show('settings')});$('backSettings').addEventListener('click',()=>show(settingsReturn));for(const id of ['soundToggle','volumeInput','qualitySelect','reducedMotion'])$(id).addEventListener('input',applySettings);
$('deathNew').addEventListener('click',startNew);$('deathMenu').addEventListener('click',()=>show('menu'));$('mapButton').addEventListener('click',()=>show(screen==='overview'?'play':'overview'));$('closeOverview').addEventListener('click',()=>show('play'));$('errorResume').addEventListener('click',()=>{if(saved)loadGame();else show('menu')});
$('buildButton').addEventListener('click',openBuild);$('closeBuild').addEventListener('click',()=>show('play'));
function toggleSettlementFinder(){if(!game||screen!=='play')return;renderer.findSettlements=!renderer.findSettlements;$('findSettlementButton').setAttribute('aria-pressed',String(renderer.findSettlements));if(renderer.findSettlements)toast(game.settlements.length?'Edge arrows lead to every settlement.':'Found a settlement with Z; its arrow will appear here.')}
$('findSettlementButton').addEventListener('click',toggleSettlementFinder);
$('exportSave').addEventListener('click',()=>{if(!game||game.ended)return;const blob=new Blob([JSON.stringify(game.serialize())],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Apes_Together_Strong_'+game.seed.replace(/[^a-z0-9_-]/gi,'_')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('Save file exported.','green','menu')});
$('importSave').addEventListener('click',()=>$('importInput').click());$('importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw new Error('This save file is too large.');const data=JSON.parse(await file.text());validateSave(data);if(loadGame(data))saveGame(false)}catch(err){toast('Import failed: '+err.message,'red','menu')}e.target.value=''});
$('commandToggle').addEventListener('click',()=>{$('commandPanel').hidden=!$('commandPanel').hidden;$('commandToggle').setAttribute('aria-expanded',String(!$('commandPanel').hidden))});document.querySelectorAll('[data-command]').forEach(btn=>btn.addEventListener('click',()=>{if(!game||screen!=='play')return;const cmd=btn.dataset.command;if(['charge','spreadCharge'].includes(cmd)&&matchMedia('(pointer:coarse)').matches){pointer.aiming=cmd}else{pointer.aiming=false;game.command(cmd,currentAim())}$('commandPanel').hidden=true;$('commandToggle').setAttribute('aria-expanded','false')}));
function currentAim(){if(!game)return {x:1,y:0};const p=renderer.unproject(pointer.x,pointer.y),origin=game.siege?.selected.length?game.siege.center():game.king;let x=p.x-origin.x,y=p.y-origin.y;return Math.hypot(x,y)>5?{x,y}:game.aim}
window.addEventListener('keydown',e=>{
 if(screen==='build'&&e.key==='Tab'){const focusable=[...$('build').querySelectorAll('button:not(:disabled),input,select')],first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}return}
 if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)&&e.key!=='Escape')return;
 if(document.activeElement?.tagName==='BUTTON'&&['Enter',' '].includes(e.key))return;
 if(screen==='play'&&army.key(e)){pointer.active=false;return}
 if(screen==='play'&&e.ctrlKey&&!e.metaKey&&['control','w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase())){e.preventDefault();keys.add(e.key.toLowerCase());return}
 if(e.ctrlKey||e.metaKey||e.altKey)return;
 const key=e.key.toLowerCase();if(key==='f3'){e.preventDefault();window.ATS.debugPerformance(!debugPerf);return}if(screen==='play'&&[' ','tab','arrowup','arrowdown','arrowleft','arrowright'].includes(key))e.preventDefault();if(e.repeat){if(screen==='play')keys.add(key);return}
 if(key==='escape'){if(screen==='play'){saveGame(false);show('pause')}else if(['pause','overview','build'].includes(screen))show('play');else if(screen==='settings')show(settingsReturn);else if(screen==='guide')show(guideReturn);else if(screen==='legacy')show('menu');return}
 if((key==='tab'||key==='m')&&game&&!game.ended&&['play','overview'].includes(screen)){show(screen==='play'?'overview':'play');return}
 if(screen!=='play'||!game)return;if(key==='v'){toggleSettlementFinder();return}if(key==='b'){openBuild();return}keys.add(key);const map={q:'call',e:'charge',x:'spreadCharge',t:'attackNearest',r:'recall',f:'hold',z:e.shiftKey?'settleAll':'settle',c:'patrol'};if(map[key]){pointer.aiming=false;game.command(map[key],currentAim())}
});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
$('gameCanvas').addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY;army.move(e)});$('gameCanvas').addEventListener('pointerdown',e=>{if(screen!=='play'||e.button!==0&&e.button!==2)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);document.activeElement?.blur();audio.unlock();pointer.x=e.clientX;pointer.y=e.clientY;if(!pointer.aiming&&army.down(e)){pointer.active=false;return}if(e.button===2)return;if(pointer.aiming){game.command(pointer.aiming,currentAim());pointer.aiming=false;return}if(e.pointerType==='touch'){game.aim=currentAim();game.attack(game.aim)}else{pointer.active=true;game.aim=currentAim();game.attack(game.aim)}});window.addEventListener('pointerup',e=>{if(screen==='play')army.up(e);pointer.active=false});window.addEventListener('pointercancel',()=>{army.cancel();pointer.active=false});$('gameCanvas').addEventListener('contextmenu',e=>e.preventDefault());$('gameCanvas').addEventListener('wheel',e=>{if(screen==='play'){e.preventDefault();renderer.camera.zoom=Math.max(.38,Math.min(1.65,renderer.camera.zoom-e.deltaY*.0005))}},{passive:false});
const joyEl=$('joystick');joyEl.addEventListener('pointerdown',e=>{if(screen!=='play')return;e.preventDefault();joy.id=e.pointerId;joy.x=e.clientX;joy.y=e.clientY;joyEl.setPointerCapture(e.pointerId);audio.unlock()});joyEl.addEventListener('pointermove',e=>{if(joy.id!==e.pointerId)return;let dx=e.clientX-joy.x,dy=e.clientY-joy.y,len=Math.hypot(dx,dy),max=36;if(len>max){dx=dx/len*max;dy=dy/len*max}touchMove.x=dx/max;touchMove.y=dy/max;$('joystickKnob').style.transform='translate('+dx+'px,'+dy+'px)'});const resetJoy=()=>{joy.id=null;touchMove.x=touchMove.y=0;$('joystickKnob').style.transform='translate(0px,0px)'};joyEl.addEventListener('pointerup',resetJoy);joyEl.addEventListener('pointercancel',resetJoy);$('attackButton').addEventListener('pointerdown',e=>{if(screen!=='play')return;e.preventDefault();pointer.active=true;game.attack(game.aim);audio.unlock()});$('attackButton').addEventListener('pointerup',()=>pointer.active=false);$('attackButton').addEventListener('pointercancel',()=>pointer.active=false);
window.addEventListener('blur',()=>{army.cancel();pointer.aiming=false;keys.clear();pointer.active=false;resetJoy();if(screen==='play'&&game&&!game.ended){saveGame(false);show('pause')}});document.addEventListener('visibilitychange',()=>{lastTime=0;accumulator=0;audio.pause(document.hidden||!running);if(document.hidden){army.cancel();pointer.active=false;pointer.aiming=false;keys.clear();resetJoy()}if(document.hidden&&screen==='play'&&game&&!game.ended){saveGame(false);show('pause')}});window.addEventListener('beforeunload',()=>saveGame(false));window.addEventListener('resize',()=>{renderer.resize();if(screen==='overview')updateOverview()});
function input(){
 let sx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+touchMove.x,sy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+touchMove.y;
 let x=sx/.8+sy/.42,y=sy/.42-sx/.8,d=Math.hypot(x,y);if(d>1){x/=d;y/=d}const coarse=matchMedia('(pointer:coarse)').matches;if(coarse&&d>.04)game.aim={x,y};return {x,y,sneak:keys.has('control'),sprint:keys.has('shift'),attack:!game.siege?.selected.length&&(pointer.active||keys.has(' ')),aim:coarse?game.aim:currentAim()};
}
function frame(timestamp){
 const frameInterval=lastTime?Math.max(0,timestamp-lastTime):1000/60,dt=Math.min(.05,frameInterval/1000);lastTime=timestamp;
 if(document.hidden){accumulator=0;requestAnimationFrame(frame);return}
 const frameStart=performance.now();let simulationMs=0,renderMs=0,navigationMs=0;
 try{
 if(running&&game){const simStart=performance.now();accumulator+=dt;let steps=0;while(accumulator>=1/60&&steps<3){game.update(1/60,input());navigationMs+=game.performance.navigationMs;accumulator-=1/60;steps++}if(steps===3)accumulator=0;simulationMs=performance.now()-simStart;
 audio.update({king:game.king,world:game.world,humans:game.humans,threat:game.tier,helicopterActive:game.helis.length>0},dt);autosaveTimer+=dt;if(autosaveTimer>15&&!game.ended){autosaveTimer=0;saveGame(false)}if(game.ended&&game.deathTimer>2.4)deathScreen()}
 const renderStart=performance.now();
 if(screen==='build'&&game?.ended)deathScreen();
 if(screen==='bootError'){}else if(game&&['play','pause','overview','build','settings','death'].includes(screen))renderer.draw(game,screen==='play'?dt:0);else renderer.drawMenu(timestamp/1000);
 renderMs=performance.now()-renderStart;
 hudTimer+=dt;if(hudTimer>.12){hudTimer=0;updateHud();if(debugPerf&&game){const p=game.performance.snapshot(),f=n=>Number(n||0).toFixed(1);perfPanel.textContent='Frame '+f(p.frameMs)+' ms · Sim '+f(p.simulationMs)+' · Render '+f(p.renderMs)+' · Nav '+f(p.navigationMs)+'\nApes '+p.simulatedApes+'/'+p.activeApes+' · Humans '+p.simulatedHumans+'/'+p.activeHumans+' · Visible '+(p.visibleActors||0)+'\nA* '+p.aStarSearches+' · Cache '+p.navigationCacheHits+' · Queue '+p.navigationQueue+' · Think '+p.aiThinks+' · LOS '+p.losTests+'\nBullets '+p.projectiles+' · Effects '+p.effects+' · Slow frames '+p.slowFrames+' · Quality '+p.qualityLevel}}
 if(game){game.performance.enabled=debugPerf;game.performance.frame(Math.max(frameInterval,performance.now()-frameStart),simulationMs,renderMs,dt,running);game.performance.navigationMs=navigationMs}
 }catch(e){handleError(e)}requestAnimationFrame(frame);
}
fillSettings();updateMenu();renderer.resize();requestAnimationFrame(frame);
})();
