(function(){
'use strict';
const $=id=>document.getElementById(id), SAVE='ats-crown-save-v1', LEGACY='ats-crown-legacy-v1', SETTINGS='ats-crown-settings-v1';
const screens=['menu','guide','pause','settings','death','legacy','overview','bootError'];
let game=null, screen='menu', running=false, lastTime=0, accumulator=0, hudTimer=0, autosaveTimer=0, overviewTimer=0, deathShown=false, settingsReturn='pause', guideReturn='menu';
let settings={enabled:true,volume:.45,quality:'high',reducedMotion:false}, histories=[], saved=null, storageAvailable=true,saveWarned=false;
const keys=new Set(),pointer={x:innerWidth*.7,y:innerHeight*.5,active:false,aiming:false},touchMove={x:0,y:0},joy={id:null,x:0,y:0},fmt=n=>Math.floor(n||0).toLocaleString();
const renderer=new ATSRenderer($('gameCanvas')), audio=new ATSAudio();window.ATS={renderer,audio,get game(){return game},get screen(){return screen}};
function read(key,fallback){try{let raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{storageAvailable=false;return false}}
settings={...settings,...read(SETTINGS,{})};histories=read(LEGACY,[]);if(!Array.isArray(histories))histories=[];saved=read(SAVE,null);if(saved?.ended||!saved?.king||saved.king.hp<=0)saved=null;
audio.setSettings(settings);renderer.quality=settings.quality;renderer.reducedMotion=settings.reducedMotion;
function show(id){for(const s of screens)$(s).hidden=s!==id;screen=id;running=id==='play';$('hud').hidden=!(id==='play'||id==='pause'||id==='overview'||id==='settings'&&game);$('commandPanel').hidden=true;keys.clear();pointer.active=false;touchMove.x=touchMove.y=0;$('joystickKnob').style.transform='translate(0px,0px)';accumulator=0;audio.pause(!running);updateMenu();if(id==='overview')updateOverview();if(id==='legacy')renderLegacy();const target=$(id)?.querySelector('button:not(:disabled),input');if(id!=='play')requestAnimationFrame(()=>target?.focus({preventScroll:true}))}
function toast(text,color='gold'){
 const area=$('toastArea'),el=document.createElement('div');el.className='toast';el.style.borderLeft='2px solid '+({red:'#e47c6b',green:'#83c8b3',gold:'#cfb46e'}[color]||color);el.textContent=text;area.append(el);while(area.children.length>4)area.firstChild.remove();setTimeout(()=>el.remove(),5500);
}
const hooks={toast,sound:(...args)=>audio.play(...args),death:g=>{deathShown=false;try{localStorage.removeItem(SAVE)}catch{}saved=null;recordLegacy(g)}};
function updateMenu(){$('continueRun').disabled=!saved;$('highScore').textContent=fmt(Math.max(0,...histories.map(h=>h.score)))}
function startNew(){
 const seed=$('seedInput').value.trim().slice(0,50)||Math.random().toString(36).slice(2,10).toUpperCase();audio.unlock();
 try{game=new ATSGame(seed,$('difficultySelect').value,hooks);renderer.camera.x=game.king.x;renderer.camera.y=game.king.y;renderer.camera.zoom=1;deathShown=false;show('play');saveGame(false);toast(matchMedia('(pointer:coarse)').matches?'Use the left stick. Strike the nearby cage, then choose Call.':'Move with WASD. Strike the nearby cage, then press Q.');$('objectiveHint').textContent='A cage rattles in the eastern shadows.'}catch(e){handleError(e)}
}
function loadGame(data=saved){audio.unlock();try{validateSave(data);game=ATSGame.fromJSON(data,hooks);renderer.camera.x=game.king.x;renderer.camera.y=game.king.y;deathShown=false;show('play');toast('The crown returns. Your tribe remembers.');return true}catch(e){toast('Could not load this run: '+e.message,'red');return false}}
function validateSave(d){if(!d||d.version!==1||!d.king||!Number.isFinite(d.king.x)||!Number.isFinite(d.king.y)||!Number.isFinite(d.king.hp)||d.king.hp<=0||d.ended)throw new Error('The file does not contain a living run.');if(!Number.isFinite(d.time)||d.time<0||!Array.isArray(d.apes)||d.apes.length>3000||!Array.isArray(d.humans)||d.humans.length>3000||!Array.isArray(d.settlements)||!d.world)throw new Error('The save data is incomplete.');for(const list of [d.apes,d.humans,d.settlements,d.vehicles||[],d.helis||[]])for(const a of list)if(!Number.isFinite(a.x)||!Number.isFinite(a.y))throw new Error('A saved position is invalid.')}
function saveGame(announce=true){if(!game||game.ended)return false;try{const data=game.serialize();if(!write(SAVE,data)){if(announce||!saveWarned)toast('Device storage is unavailable. Export a save file from Pause.','red');saveWarned=true;return false}saved=data;saveWarned=false;if(announce)toast('Your living run is saved on this device.','green');updateMenu();return true}catch(e){if(announce)toast('Save failed. Export a save file to keep this run.','red');return false}}
function recordLegacy(g){const h={score:g.score,title:g.title,seed:g.seed,difficulty:g.difficulty,time:g.time,stats:{...g.stats},date:new Date().toISOString()};histories.unshift(h);histories.sort((a,b)=>b.score-a.score);histories=histories.slice(0,12);write(LEGACY,histories);updateMenu()}
function renderLegacy(){const list=$('legacyList');list.replaceChildren();if(!histories.length){list.textContent='Every kingdom begins with one ape. Your legacy awaits.';return}for(const h of histories){const row=document.createElement('div');row.className='legacy-row';const title=document.createElement('span');title.textContent=h.title;const score=document.createElement('strong');score.textContent=fmt(h.score);const details=document.createElement('small');details.textContent='Seed '+h.seed+' · '+Math.floor(h.time/60)+'m · '+h.stats.freed+' freed · '+h.difficulty;row.append(title,score,details);list.append(row)}}
function deathScreen(){if(deathShown||!game)return;deathShown=true;show('death');$('legacyTitle').textContent=game.title;$('legacyScore').textContent=fmt(game.score);const stats=$('deathStats');stats.replaceChildren();const lines=[['Apes freed',game.stats.freed],['Apes born',game.stats.born],['Largest traveling horde',game.stats.largestHorde],['Settlements founded',game.stats.settlements],['Settlements surviving',game.settlements.filter(s=>s.population>0).length],['Humans defeated',game.stats.humans],['Bases liberated',game.stats.bases],['Structures destroyed',game.stats.structures],['Days survived',game.day],['Highest human threat',ATSTierNames[game.stats.highestThreat-1]],['Seed',game.seed]];for(const [label,value]of lines){const row=document.createElement('div');row.style.display='flex';row.style.justifyContent='space-between';row.style.gap='20px';const a=document.createElement('span');a.textContent=label;const b=document.createElement('strong');b.textContent=String(value);b.style.color='#cfb46e';row.append(a,b);stats.append(row)}}
function updateHud(){if(!game)return;const hp=Math.max(0,game.king.hp);$('hpFill').style.width=(hp/game.king.maxHp*100)+'%';$('hpFill').style.background=hp<40?'#e37b6b':'';$('hpText').textContent=Math.ceil(hp)+' / '+game.king.maxHp;$('hordeCount').textContent=game.followers.length;$('foodCount').textContent=fmt(game.food);$('threatText').textContent=ATSTierNames[game.tier-1];$('dayText').textContent='NIGHT '+game.day;$('regionText').textContent=game.world.districtAt(game.king.x,game.king.y).name;$('exposureFill').style.width=(game.exposure*100)+'%';$('exposureText').textContent=game.exposure>.5?'IN THE LIGHT':game.time-game.lastContact<12?'BEING HUNTED':'IN THE SHADOWS';$('exposureText').style.color=game.exposure>.5?'#e37b6b':'#9facaa';
 const objs=game.world.getObjects(game.king.x,game.king.y,105),cage=objs.find(o=>o.type==='cage'&&!o.dead);const free=game.apes.filter(a=>a.state==='free'&&Math.hypot(a.x-game.king.x,a.y-game.king.y)<280);const settle=game.settlements.find(s=>s.population>0&&Math.hypot(s.x-game.king.x,s.y-game.king.y)<s.radius+90);
 if(cage)$('contextHint').textContent='Strike the cage · Click / Space';else if(free.length)$('contextHint').textContent='Free apes nearby · Q to Call';else if(settle)$('contextHint').textContent=settle.name+' · Z settle · C scouts · Q recruit';else if(game.exposure>.4)$('contextHint').textContent='Break line of sight. The forest is your shelter.';else $('contextHint').textContent='Q Call · E Charge · R Recall · F Hold';
 let nearest=game.world.getObjects(game.king.x,game.king.y,600).filter(o=>o.type==='cage'&&!o.dead).sort((a,b)=>Math.hypot(a.x-game.king.x,a.y-game.king.y)-Math.hypot(b.x-game.king.x,b.y-game.king.y))[0];if(nearest){let p=renderer.project(nearest.x,nearest.y),k=renderer.project(game.king.x,game.king.y),angle=Math.atan2(p.y-k.y,p.x-k.x),arrows=['→','↘','↓','↙','←','↖','↑','↗'],ix=(Math.round(angle/(Math.PI/4))+8)%8;$('objectiveHint').textContent=arrows[ix]+' Captive calls · '+Math.round(Math.hypot(nearest.x-game.king.x,nearest.y-game.king.y)/10)+' paces';}else $('objectiveHint').textContent=game.followers.length>8?'Strength gathers. Find safe woodland for a settlement.':'Explore the dark. Listen for the captive calls.';
}
function updateOverview(){
 if(!game)return;renderer.drawMap(game,$('mapCanvas'));const site=game.colonies.evaluate(game.king.x,game.king.y);$('overviewStats').textContent='Population '+game.population+' · Traveling '+game.followers.length+' · Legacy '+fmt(game.score)+' · Seed '+game.seed;
 $('siteAssessment').textContent=site.region+' · '+site.biome+' · '+site.berries+' food patches · '+site.wood+' trees · '+(site.water?'water nearby':'no nearby water')+' · '+(site.risk?'human activity nearby':'quiet surroundings')+' · natural capacity '+site.capacity;
 const list=$('settlementList');list.replaceChildren();for(const settlement of game.settlements){game.colonies.init(settlement);const s=settlement,row=document.createElement('div');row.className='settlement-row';const head=document.createElement('strong');head.textContent=(s.known?'✕ ':'')+s.name+' · Level '+s.level;head.style.color=s.known?'#e37b6b':'#cfb46e';const detail=document.createElement('p');detail.textContent=s.population+'/'+s.housing+' housed · '+s.scouts+' scouts · '+s.children+' young · '+fmt(s.food)+' food ('+(s.foodDelta>=0?'+':'')+(s.foodDelta||0).toFixed(1)+'/s) · '+fmt(s.wood)+' timber · '+fmt(s.defense)+' defense';const project=document.createElement('div');project.textContent=s.status+' · Building: '+s.project+' · '+Math.round(s.buildProgress)+' work';const label=document.createElement('label');label.textContent='Priority ';const select=document.createElement('select');select.setAttribute('aria-label',s.name+' work priority');for(const [value,text]of[['balanced','Balanced growth'],['forage','Food security'],['fortify','Defend and repair']]){const option=document.createElement('option');option.value=value;option.textContent=text;option.selected=s.policy===value;select.append(option)}select.addEventListener('change',()=>{game.colonies.action(s.id,select.value);saveGame(false)});label.append(select);const actions=document.createElement('div');actions.className='settlement-actions';for(const [action,text]of[['supply','Deliver up to 30 food'],['recruit','Recruit adults']]){const button=document.createElement('button');button.className='button';button.textContent=text;button.addEventListener('click',()=>{game.colonies.action(s.id,action);saveGame(false);updateOverview()});actions.append(button)}row.append(head,detail,project,label,actions);list.append(row)}if(!game.settlements.length)list.textContent='Rescue apes and settle with Z. Water, woodland and food patches support a lasting home.';
}
function applySettings(){settings={enabled:$('soundToggle').checked,volume:Number($('volumeInput').value),quality:$('qualitySelect').value,reducedMotion:$('reducedMotion').checked};audio.setSettings(settings);renderer.quality=settings.quality;renderer.reducedMotion=settings.reducedMotion;write(SETTINGS,settings)}
function fillSettings(){$('soundToggle').checked=settings.enabled;$('volumeInput').value=settings.volume;$('qualitySelect').value=settings.quality;$('reducedMotion').checked=settings.reducedMotion}
function handleError(e){console.error(e);running=false;audio.pause(true);keys.clear();$('errorMessage').textContent='The world paused safely. '+(e?.message||'An unexpected error occurred.')+(saved?' You can return to your latest living checkpoint.':' Return to the menu to begin another run.');$('errorResume').textContent=saved?'Load latest checkpoint':'Return to menu';show('bootError')}
$('newRun').addEventListener('click',startNew);$('continueRun').addEventListener('click',()=>loadGame());$('howToPlay').addEventListener('click',()=>{guideReturn='menu';show('guide')});$('backGuide').addEventListener('click',()=>show(guideReturn));$('legacyButton').addEventListener('click',()=>show('legacy'));$('backLegacy').addEventListener('click',()=>show('menu'));
$('pauseButton').addEventListener('click',()=>{if(game&&!game.ended){saveGame(false);show('pause')}});$('resumeRun').addEventListener('click',()=>show('play'));$('saveRun').addEventListener('click',()=>saveGame());$('quitRun').addEventListener('click',()=>{saveGame(false);show('menu')});$('settingsButton').addEventListener('click',()=>{settingsReturn='pause';fillSettings();show('settings')});$('backSettings').addEventListener('click',()=>show(settingsReturn));for(const id of ['soundToggle','volumeInput','qualitySelect','reducedMotion'])$(id).addEventListener('input',applySettings);
$('deathNew').addEventListener('click',startNew);$('deathMenu').addEventListener('click',()=>show('menu'));$('mapButton').addEventListener('click',()=>show(screen==='overview'?'play':'overview'));$('closeOverview').addEventListener('click',()=>show('play'));$('errorResume').addEventListener('click',()=>{if(saved)loadGame();else show('menu')});
$('exportSave').addEventListener('click',()=>{if(!game||game.ended)return;const blob=new Blob([JSON.stringify(game.serialize())],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Apes_Together_Strong_'+game.seed.replace(/[^a-z0-9_-]/gi,'_')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('Save file exported.','green')});
$('importSave').addEventListener('click',()=>$('importInput').click());$('importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw new Error('This save file is too large.');const data=JSON.parse(await file.text());validateSave(data);if(loadGame(data))saveGame(false)}catch(err){toast('Import failed: '+err.message,'red')}e.target.value=''});
$('commandToggle').addEventListener('click',()=>{$('commandPanel').hidden=!$('commandPanel').hidden;$('commandToggle').setAttribute('aria-expanded',String(!$('commandPanel').hidden))});document.querySelectorAll('[data-command]').forEach(btn=>btn.addEventListener('click',()=>{if(!game||screen!=='play')return;const cmd=btn.dataset.command;if(cmd==='charge'&&matchMedia('(pointer:coarse)').matches){pointer.aiming=true;toast('Touch the ground to send the charge.')}else game.command(cmd,currentAim());$('commandPanel').hidden=true}));
function currentAim(){if(!game)return {x:1,y:0};const p=renderer.unproject(pointer.x,pointer.y);let x=p.x-game.king.x,y=p.y-game.king.y;return Math.hypot(x,y)>5?{x,y}:game.aim}
window.addEventListener('keydown',e=>{
 if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)&&e.key!=='Escape')return;
 const key=e.key.toLowerCase();if([' ','tab','arrowup','arrowdown','arrowleft','arrowright'].includes(key))e.preventDefault();if(e.repeat){keys.add(key);return}
 if(key==='escape'){if(screen==='play'){saveGame(false);show('pause')}else if(['pause','overview'].includes(screen))show('play');else if(screen==='settings')show(settingsReturn);else if(screen==='guide')show(guideReturn);else if(screen==='legacy')show('menu');return}
 if((key==='tab'||key==='m')&&game&&!game.ended&&['play','overview'].includes(screen)){show(screen==='play'?'overview':'play');return}
 if(screen!=='play'||!game)return;keys.add(key);const map={q:'call',e:'charge',r:'recall',f:'hold',z:e.shiftKey?'settleAll':'settle',c:'patrol'};if(map[key])game.command(map[key],currentAim());
});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
$('gameCanvas').addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY});$('gameCanvas').addEventListener('pointerdown',e=>{if(screen!=='play')return;e.preventDefault();audio.unlock();pointer.x=e.clientX;pointer.y=e.clientY;if(pointer.aiming){game.command('charge',currentAim());pointer.aiming=false;return}if(e.pointerType==='touch'){game.aim=currentAim();game.attack(game.aim)}else{pointer.active=true;game.aim=currentAim();game.attack(game.aim)}});window.addEventListener('pointerup',()=>pointer.active=false);window.addEventListener('pointercancel',()=>pointer.active=false);$('gameCanvas').addEventListener('contextmenu',e=>e.preventDefault());$('gameCanvas').addEventListener('wheel',e=>{if(screen==='play'){e.preventDefault();renderer.camera.zoom=Math.max(.6,Math.min(1.65,renderer.camera.zoom-e.deltaY*.0005))}},{passive:false});
const joyEl=$('joystick');joyEl.addEventListener('pointerdown',e=>{if(screen!=='play')return;e.preventDefault();joy.id=e.pointerId;joy.x=e.clientX;joy.y=e.clientY;joyEl.setPointerCapture(e.pointerId);audio.unlock()});joyEl.addEventListener('pointermove',e=>{if(joy.id!==e.pointerId)return;let dx=e.clientX-joy.x,dy=e.clientY-joy.y,len=Math.hypot(dx,dy),max=36;if(len>max){dx=dx/len*max;dy=dy/len*max}touchMove.x=dx/max;touchMove.y=dy/max;$('joystickKnob').style.transform='translate('+dx+'px,'+dy+'px)'});const resetJoy=()=>{joy.id=null;touchMove.x=touchMove.y=0;$('joystickKnob').style.transform='translate(0px,0px)'};joyEl.addEventListener('pointerup',resetJoy);joyEl.addEventListener('pointercancel',resetJoy);$('attackButton').addEventListener('pointerdown',e=>{if(screen!=='play')return;e.preventDefault();pointer.active=true;game.attack(game.aim);audio.unlock()});$('attackButton').addEventListener('pointerup',()=>pointer.active=false);$('attackButton').addEventListener('pointercancel',()=>pointer.active=false);
window.addEventListener('blur',()=>{keys.clear();pointer.active=false;resetJoy();if(screen==='play'&&game&&!game.ended){saveGame(false);show('pause')}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&screen==='play'&&game&&!game.ended){saveGame(false);show('pause')}});window.addEventListener('beforeunload',()=>saveGame(false));window.addEventListener('resize',()=>{renderer.resize();if(screen==='overview')updateOverview()});
function input(){
 let sx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+touchMove.x,sy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+touchMove.y;
 let x=sx/.8+sy/.42,y=sy/.42-sx/.8,d=Math.hypot(x,y);if(d>1){x/=d;y/=d}const coarse=matchMedia('(pointer:coarse)').matches;if(coarse&&d>.04)game.aim={x,y};return {x,y,sneak:keys.has('control'),sprint:keys.has('shift'),attack:pointer.active||keys.has(' '),aim:coarse?game.aim:currentAim()};
}
function frame(timestamp){
 const dt=Math.min(.05,Math.max(0,(timestamp-(lastTime||timestamp))/1000));lastTime=timestamp;
 try{
 if(running&&game){accumulator+=dt;let steps=0;while(accumulator>=1/60&&steps<4){game.update(1/60,input());accumulator-=1/60;steps++}if(steps===4)accumulator=0;audio.update({...game,threat:game.tier,helicopterActive:game.helis.length>0},dt);autosaveTimer+=dt;if(autosaveTimer>15&&!game.ended){autosaveTimer=0;saveGame(false)}if(game.ended&&game.deathTimer>2.4)deathScreen()}
 if(screen==='bootError'){}else if(game&&['play','pause','overview','settings','death'].includes(screen))renderer.draw(game,screen==='play'?dt:0);else renderer.drawMenu(timestamp/1000);
 hudTimer+=dt;if(hudTimer>.12){hudTimer=0;updateHud()}
 }catch(e){handleError(e)}requestAnimationFrame(frame);
}
fillSettings();updateMenu();renderer.resize();requestAnimationFrame(frame);
})();
