/* Overview controls deliberately reuse the existing paused kingdom screen. */
(() => {
'use strict';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n};
const title=a=>a.champion?.name||a.veteran?.name||'Veteran '+a.species;
function select(label,values,current,onChange){const wrap=el('label',label,'champion-field'),input=el('select');input.setAttribute('aria-label',label);for(const [id,name]of Object.entries(values)){const o=el('option',name);o.value=id;o.selected=id===current;input.append(o)}if(onChange)input.addEventListener('change',()=>onChange(input.value));wrap.append(input);return{wrap,input}}
function button(label,fn){const b=el('button',label,'button');b.type='button';b.addEventListener('click',fn);return b}
class ChampionsUI{
 constructor(root,options){this.root=root;this.getGame=options.getGame;this.onChange=options.onChange||(()=>{});this.map=options.mapCanvas;this.pendingDestination=null;this.root.classList.add('champions-panel');if(!document.getElementById('championsStyles')){const style=el('style');style.id='championsStyles';style.textContent='.champions-panel{margin-top:24px;border-top:1px solid var(--edge,#35514c);padding-top:20px}.champions-panel h3{color:var(--gold,#d9bd83);font-size:18px;margin:0 0 8px}.champions-panel p{font-size:12px;line-height:1.6;margin:6px 0 12px}.champion-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,270px),1fr));gap:12px}.champion-card{background:#0d2528;border:1px solid #36504d;border-radius:6px;padding:14px}.champion-card strong{color:#ead8a1;font-size:14px}.champion-card small{display:block;color:#a9bcb0;font-size:11px;line-height:1.65;margin:5px 0}.champion-form{display:flex;flex-wrap:wrap;gap:10px;align-items:end;margin:12px 0}.champion-field{display:flex;flex:1 1 120px;flex-direction:column;gap:5px;font-size:11px;color:#a9bcb0;min-width:0}.champion-field select{width:100%;max-width:100%;min-height:36px;background:#102e30;color:#eee2c5;border:1px solid #49635b;border-radius:4px;padding:6px;font:inherit}.champion-controls{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.champion-controls .button{font-size:10px;padding:8px 10px;min-height:34px}.champion-roster{max-height:310px;overflow:auto;margin:14px 0}.champion-roster summary{cursor:pointer;color:#d9bd83;font-size:13px;margin-bottom:10px}.champion-notice{color:#dfc188;min-height:20px}.champion-card progress{width:100%;height:5px;accent-color:#b6cc92}.champion-badge{display:inline-block;background:#28423f;padding:2px 7px;border-radius:9px;color:#d9dcb5;font-size:10px;margin-left:6px}.champion-map-pick{outline:2px solid #e3c073;cursor:crosshair}';document.head.append(style)}if(this.map)this.map.addEventListener('click',e=>this.place(e));}
 static mount(root,options){return new ChampionsUI(root,options)}
 changed(){this.onChange();this.update()}
 place(e){if(!this.pendingDestination||!this.map)return;const g=this.getGame();if(!g)return;const rect=this.map.getBoundingClientRect(),v=window.ATSChampionMapView?.(g,this.map);if(!v)return;const p={x:(e.clientX-rect.left-v.ox)/v.scale,y:(e.clientY-rect.top-v.oy)/v.scale},cell=g.world.revealCellSize||192,key=Math.floor(p.x/cell)+','+Math.floor(p.y/cell);if(!g.world.discovered?.has(key)){g.champions.status='Choose explored ground on the map.';this.update();return}g.champions.configure(this.pendingDestination,{destination:p});this.pendingDestination=null;this.map.classList.remove('champion-map-pick');this.changed()}
 update(){const g=this.getGame();if(!g)return;const c=g.champions,wasOpen=this.root.querySelector('details')?.open;this.root.replaceChildren();this.root.append(el('h3','Champions & divisions'),el('p','Rescue rare champions from fortified prisons. Veterans earn command through training or five victories. Set a division order here, then return to the battle.'));
  const roster=c.roster(),details=el('details',null,'champion-roster');details.open=wasOpen??false;details.append(el('summary',roster.length+' champions & veterans · '+roster.filter(a=>a.recoveryRemaining>0).length+' recovering'));const cards=el('div',null,'champion-grid');for(const a of roster.slice(0,72)){const card=el('div',null,'champion-card'),head=el('strong',title(a)),classInfo=window.ATSChampionClasses?.[a.champion?.archetype];card.append(head,el('small',a.species+' · '+(a.champion?'Champion':a.veteran?.role||'Trained veteran')+' · '+(a.recoveryRemaining?'Recovering '+Math.ceil(a.recoveryRemaining)+'s':a.settlementId?'Stationed at '+(g.settlement(a.settlementId)?.name||'home'):a.divisionId?'Leading / serving '+(c.divisions[a.divisionId]?.name||'division'):'Traveling')));if(classInfo)card.append(el('small',a.champion.item+((a.champion.gearLevel||0)?' +'+a.champion.gearLevel:'')+' · '+a.champion.passive),el('small',classInfo.description));const hp=el('progress');hp.max=a.maxHp;hp.value=a.hp;hp.setAttribute('aria-label',title(a)+' health '+Math.ceil(a.hp)+' of '+a.maxHp);card.append(hp);const actions=el('div',null,'champion-controls');if(a.settlementId)actions.append(button('Return to army',()=>{c.recall(a.id);this.changed()}));else{const near=g.settlements.filter(s=>Math.hypot(a.x-s.x,a.y-s.y)<(s.radius||140)+180).sort((x,y)=>Math.hypot(a.x-x.x,a.y-x.y)-Math.hypot(a.x-y.x,a.y-y.y))[0];if(near)actions.append(button('Station at '+near.name,()=>{c.station(a.id,near.id);this.changed()}))}if(a.recoveryRemaining)card.append(el('small','Recovery needs a safe settlement. Escort them home and use Station, or settle the group.'));card.append(actions);cards.append(card)}if(!roster.length)cards.append(el('p','No elites rescued yet. Blacksite cells can hold champions and injured legends.'));details.append(cards);this.root.append(details);
  const form=el('div',null,'champion-form'),division=select('Division',Object.fromEntries(ATSDivisions.map(d=>[d.id,d.name])),'vanguard'),commanders=Object.fromEntries(roster.filter(a=>c.eligible(a)).map(a=>[a.id,title(a)+' · '+a.species])),leader=select('Commander',Object.keys(commanders).length?commanders:{'':'No commander ready'},Object.keys(commanders)[0]),scope=select('Followers',{unassigned:'Unassigned followers',selected:'Current army selection',species:'Commander’s species'},'unassigned'),size=select('Maximum strength',{'32':'32 apes','64':'64 apes','128':'128 apes','256':'256 apes'},'64');form.append(division.wrap,leader.wrap,scope.wrap,size.wrap);const create=button('Form division',()=>{const commander=g.apesById.get(leader.input.value);if(!commander)return;const selected=scope.input.value==='selected'?new Set(g.siege.selectedMembers().map(a=>a.id)):null;const members=g.followers.filter(a=>a.id!==commander.id&&!a.recoveryRemaining&&(scope.input.value==='unassigned'?!a.divisionId:scope.input.value==='species'?a.species===commander.species:selected.has(a.id))).sort((a,b)=>Math.hypot(a.x-commander.x,a.y-commander.y)-Math.hypot(b.x-commander.x,b.y-commander.y)).slice(0,Number(size.input.value)-1);c.assign(division.input.value,commander.id,members.map(a=>a.id));this.changed()});create.disabled=!Object.keys(commanders).length;form.append(create);this.root.append(form);
  const grid=el('div',null,'champion-grid');for(const t of ATSDivisions){const d=c.divisions[t.id];if(!d)continue;const card=el('div',null,'champion-card');card.style.borderLeft='3px solid '+t.color;const a=g.apesById.get(d.commanderId);card.append(el('strong',d.name+' · '+d.memberIds.length),el('small',(a?title(a):'Commander fallen')+' · '+(d.suspended?'Standing by':d.fallingBack?'Falling back: '+d.reason:ATSDivisionOptions.stances[d.stance])));const fields=el('div',null,'champion-form');for(const [label,key,values]of[['Stance','stance',ATSDivisionOptions.stances],['Fallback','fallback',ATSDivisionOptions.fallbacks],['Target priority','priority',ATSDivisionOptions.priorities],['Formation','formation',ATSDivisionOptions.formations]])fields.append(select(label,values,d[key],v=>{c.configure(d.id,{[key]:v});this.changed()}).wrap);
   const destinations={'king':'King’s current position'};for(const s of g.settlements)destinations['settlement:'+s.id]=s.name;for(const s of g.world.sites.values()){const cell=g.world.revealCellSize||192;if(s.known||g.world.discovered?.has(Math.floor(s.x/cell)+','+Math.floor(s.y/cell)))destinations['site:'+s.id]=(s.cleared?'Liberated: ':'Objective: ')+s.name}fields.append(select('Send to',{'':'Choose destination',...destinations},'',value=>{const p=value==='king'?g.king:value.startsWith('settlement:')?g.settlement(value.slice(11)):g.world.sites.get(value.slice(5));if(p){c.configure(d.id,{destination:p,...(value.startsWith('settlement:')?{settlementId:p.id}:{})});this.changed()}}).wrap);card.append(fields,el('small','Destination '+Math.round(d.destination.x)+', '+Math.round(d.destination.y)+(d.stance==='defendSettlement'?' · '+(g.settlement(d.settlementId)?.name||'Choose a settlement to defend'):'')));const controls=el('div',null,'champion-controls');if(this.map)controls.append(button(this.pendingDestination===d.id?'Click explored map…':'Set destination on map',()=>{this.pendingDestination=d.id;this.map.classList.add('champion-map-pick');this.map.scrollIntoView({block:'center',behavior:'smooth'});this.update()}));controls.append(button(d.suspended||d.fallingBack?'Resume orders':'Regroup at king',()=>{c.configure(d.id,d.suspended||d.fallingBack?{}:{destination:g.king,stance:'defendKing'});this.changed()}),button('Disband',()=>{c.disband(d.id);this.changed()}));card.append(controls);grid.append(card)}if(!Object.keys(c.divisions).length)grid.append(el('p','Assign a commander and followers to create your first division. Direct army commands put divisions on standby.'));this.root.append(grid);if(c.records.length){const names=c.records.slice(-3).map(r=>r.name).join(', ');this.root.append(el('p','Remembered: '+names))}const notice=el('p',this.pendingDestination?'Choose explored ground on the map for '+(c.divisions[this.pendingDestination]?.name||'the division')+'.':c.status,'champion-notice');notice.setAttribute('role','status');this.root.append(notice);
 }
}
window.ATSChampionsUI=ChampionsUI;
})();
