/* Rare, persistent individuals and six shared division planners. No per-unit
   world scans: division targets refresh twice a second and auras once a second. */
(() => {
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),point=a=>({x:a.x,y:a.y});
const finite=p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y),FOLLOW=new Set(['follow','charge','hold']);
const DEVICES=new Set(['radio','alarm','powerRelay','generator','gateControl','prisonControl','lockControl','depot','fuelDepot','fuel']);
const FORTS=new Set(['wall','gate','riotGate','humanBarricade','heavyBarricade','fieldBarricade']);
const NAMES=['Ash','Koda','Flint','Moss','Sable','River','Ember','Bramble','Tala','Cedar','Storm','Dawn'];
const CLASSES={
 gorilla:[['wallbreaker','Wallbreaker','Gate maul','Breach instinct','Deals 65% more damage to gates and walls.'],['bulwark','Bulwark','Reinforced log shield','Sheltering presence','Nearby allies take 12% less damage.'],['tankBuster','Tank Buster','Iron chain wraps','Armored hunter','Deals 55% more vehicle damage from its flank or rear.'],['jailerCrusher','Jailer Crusher','Plate shoulder harness','Unshackled','Deals 60% more damage to towers, cells and emplacements.']],
 orangutan:[['masterBuilder','Master Builder','Builder tool rig','Patient craft','Stationed builders increase construction by 20%.'],['rescueBearer','Rescue Bearer','Rope pack','Leave none behind','Nearby wounded and freed captives travel faster.'],['siegeHauler','Siege Hauler','Heavy hauling straps','Heavy labor','Stronger shield logs and 35% more structural damage.'],['greatForager','Great Forager','Supply basket rig','Forest memory','Stationed foragers increase food yield by 20%.']],
 chimpanzee:[['saboteur','Saboteur','Wire cutters','Precise hands','Deals 75% more damage to alarms, power and controls.'],['climberCaptain','Climber Captain','Climbing wraps','Follow my lead','Nearby climbers ascend 25% faster.'],['shockRaider','Shock Raider','Scavenged guard baton','Shock assault','Strikes 20% faster and excels on wall tops.'],['gateRunner','Gate Runner','Demolition satchel','Open the way','Deals double damage to gate controls and 40% more to gates.']],
 gibbon:[['skyRunner','Sky Runner','Light hook kit','Sure footing','Climbs 40% faster and moves 15% faster.'],['scoutMaster','Scout Master','Signal ribbon harness','Far sight','Reveals terrain and detects nearby threats earlier.'],['silentInfiltrator','Silent Infiltrator','Stealth wraps','Quiet step','Harder to see beyond close range when alone.'],['signalHunter','Signal Hunter','Climbing sling','Watch the watchers','Extra damage to alarms, towers and officers.']],
 mandrill:[['warcaller','Warcaller','Signal drum harness','Voice of freedom','Rally lasts longer, reaches farther and recovers sooner.'],['guardCaptain','Guard Captain','Carved battle staff','Stand together','Nearby allies take 12% less damage.'],['pursuitLeader','Pursuit Leader','Command sash','Unbroken pursuit','Nearby followers move 12% faster.'],['settlementWarden','Settlement Warden','War mantle','Homeward oath','Stationed wardens improve defense by 25%.']],
 capuchin:[['slingerAce','Slinger Ace','Scavenged sling pouch','Steady aim','Thrown stones deal 65% more damage.'],['alarmSpoiler','Alarm Spoiler','Signal jammer kit','Disruptor','Extra damage to exposed devices and spotters.'],['skirmisher','Skirmisher','Stone satchel','Darting step','Throws more often and moves while recovering.'],['supplyThief','Supply Thief','Utility belt','Resourceful','Destroying a stocked depot recovers extra supplies.']]
};
const ARCHETYPES={};for(const [species,rows]of Object.entries(CLASSES))ARCHETYPES[species]=Object.freeze(rows.map(([id,label,item,passive,description])=>Object.freeze({id,label,item,passive,description,species})));
Object.freeze(ARCHETYPES);const ALL=Object.values(ARCHETYPES).flat(),BY_ID=new Map(ALL.map(c=>[c.id,c]));
const DIVISIONS=Object.freeze([{id:'vanguard',name:'Vanguard',color:'#e9b66c'},{id:'climbers',name:'Climbers',color:'#b8d992'},{id:'saboteurs',name:'Saboteurs',color:'#92d5d0'},{id:'shieldLine',name:'Shield Line',color:'#9fbae5'},{id:'reserve',name:'Reserve',color:'#dab1df'},{id:'defenders',name:'Defenders',color:'#e3b3a0'}]);
const OPTIONS=Object.freeze({stances:{assault:'Assault',hold:'Hold',skirmish:'Skirmish',sabotage:'Sabotage',rescue:'Rescue',defendKing:'Defend King',defendSettlement:'Defend Settlement',climbBreach:'Climb and Breach'},fallbacks:{wounded:'Fall back when wounded',outnumbered:'Fall back if outnumbered',commander:'Fall back if commander falls',never:'Hold at all costs'},priorities:{auto:'Stance objectives',infantry:'Infantry',officers:'Officers / spotters',vehicles:'Vehicles',devices:'Alarms / power / controls',gates:'Gates / walls',captives:'Captive cells'},formations:{wedge:'Wedge',line:'Line',column:'Column',spread:'Spread',shield:'Shield wall'}});
const classOf=a=>BY_ID.get(a?.champion?.archetype),typeOf=a=>a?.champion?.archetype;
class Champions{
 constructor(g){this.g=g;this.divisions={};this.members=new Map();this.routes=new Map();this.nextPlan=0;this.nextAura=0;this.lastTick=g.time;this.status='';this.records=[];this.plannerStats={groups:0,candidates:0};}
 roster(){return this.g.apes.filter(a=>a.hp>0&&(a.champion||a.veteran||a.trainingLevel>=2))}
 eligible(a){return !!a&&a.hp>0&&FOLLOW.has(a.state)&&!a.recoveryRemaining&&(!!a.champion||!!a.veteran||a.trainingLevel>=2)}
 promote(a,options={}){
  if(!a||a.hp<=0||a.state==='young'||!ARCHETYPES[a.species])return null;
  if(a.champion)return a;
  if(this.g.apes.filter(p=>p.hp>0&&p.champion).length>=24){this.veteran(a,options);return null}
  const list=ARCHETYPES[a.species],chosen=list.find(c=>c.id===options.archetype)||list[ATSUtil.hash(this.g.seed+'|champion|'+(options.sourceId||a.id))%list.length];
  const bonus={gorilla:120,orangutan:105,chimpanzee:65,gibbon:55,mandrill:85,capuchin:50}[a.species];
  a.champion={version:1,archetype:chosen.id,name:String(options.name||NAMES[ATSUtil.hash(a.id+'|name')%NAMES.length]+' '+chosen.label).slice(0,72),item:chosen.item,passive:chosen.passive,sourceId:options.sourceId||null,rescuedAt:this.g.time,gearLevel:0,healthBonus:bonus};
  a.maxHp+=bonus;a.hp=Math.min(a.maxHp,a.hp+bonus*.65);a.championHealthApplied=bonus;
  if(chosen.id==='bulwark')a.shield={hp:260,maxHp:260,champion:true};
  if(options.injured){a.recoveryRemaining=90;a.hp=Math.min(a.hp,a.maxHp*.3)}
  a.championKills=a.championKills||0;this.g.notify(a.champion.name+' joins the liberation campaign.'+(options.injured?' Escort them to a safe settlement to recover.':''),'gold');return a;
 }
 veteran(a,options={}){if(!a||a.hp<=0||a.state==='young')return null;if(!a.veteran){a.veteran={role:['builderElder','scoutVeteran','family','warcaller','survivor'].includes(options.role)?options.role:'survivor',name:String(options.name||'Veteran '+NAMES[ATSUtil.hash(a.id)%NAMES.length]).slice(0,72)};this.g.applyTraining(a,Math.max(2,a.trainingLevel||0));}if(options.injured){a.recoveryRemaining=Math.max(a.recoveryRemaining||0,55);a.hp=Math.min(a.hp,a.maxHp*.35)}return a}
 recover(a,dt,multiplier=1){if(!a||a.hp<=0||!(a.recoveryRemaining>0)||!Number.isFinite(dt)||dt<=0)return false;a.recoveryRemaining=Math.max(0,a.recoveryRemaining-dt*clamp(multiplier,0,4));a.hp=Math.min(a.maxHp,a.hp+dt*multiplier*2);if(!a.recoveryRemaining){delete a.recoveryRemaining;const text=(a.champion?.name||a.veteran?.name||'A wounded survivor')+' has recovered.',home=a.settlementId?this.g.settlement(a.settlementId):null;if(home&&this.g.kingdom?.event)this.g.kingdom.event(home,'champion-recovery',text,'green',0);else this.g.notify(text,'green');return true}return false}
 station(id,settlementId){const a=this.g.apesById.get(id),s=this.g.settlement(settlementId);if(!a||a.hp<=0||!s||!(a.champion||a.veteran)||distance(a,s)>(s.radius||140)+180){this.status='Escort the elite to this settlement before stationing them.';return false}this.removeMember(id);this.g.tactics?.clearOrder(a);a.state='settled';a.settlementId=s.id;this.g.refreshSettlements();this.status='Stationed at '+s.name;return true}
 recall(id){const a=this.g.apesById.get(id);if(!a||a.hp<=0)return false;this.removeMember(id);a.state='follow';a.settlementId=null;this.g.refreshSettlements();return true}
 reforge(id){const a=this.g.apesById.get(id);if(!a?.champion||a.hp<=0||a.state!=='settled'||!a.settlementId||(a.champion.gearLevel||0)>=2)return false;a.champion.gearLevel=(a.champion.gearLevel||0)+1;if(a.shield){a.shield.maxHp+=50;a.shield.hp=a.shield.maxHp}this.status=a.champion.name+' · gear improved';return true}
 settlementBonus(s){const out={build:1,food:1,recovery:1,defense:1,growth:1,scout:1};for(const a of this.g.settlementMembers.get(s.id)||[]){if(a.hp<=0||a.recoveryRemaining||a.kingdomMission||distance(a,s)>(s.radius||160)+70)continue;const t=typeOf(a),r=a.veteran?.role;if(t==='masterBuilder'||r==='builderElder')out.build+=.2;if(t==='greatForager')out.food+=.2;if(t==='rescueBearer')out.recovery+=.25;if(t==='settlementWarden'||r==='warcaller')out.defense+=.25;if(t==='scoutMaster'||r==='scoutVeteran')out.scout+=.25;if(r==='family')out.growth+=.2;}for(const k in out)out[k]=Math.min(1.75,out[k]);return out}
 removeMember(id){const d=this.members.get(id);if(d){d.memberIds=d.memberIds.filter(n=>n!==id);if(d.commanderId===id)d.suspended=true;this.members.delete(id)}const a=this.g.apesById.get(id);if(a){delete a.divisionId;delete a.divisionSlot;delete a._divisionTarget}}
 assign(id,commanderId,memberIds){const template=DIVISIONS.find(d=>d.id===id),leader=this.g.apesById.get(commanderId);if(!template||!this.eligible(leader)){this.status='Choose a recovered champion or trained veteran who is traveling with the army.';return false}const ids=[...new Set([commanderId,...(Array.isArray(memberIds)?memberIds:[])])].filter(n=>{const a=this.g.apesById.get(n);return a&&a.hp>0&&FOLLOW.has(a.state)&&!a.recoveryRemaining}).slice(0,256);this.disband(id);for(const n of ids)this.removeMember(n);const d={id,name:template.name,commanderId,memberIds:ids,stance:id==='defenders'?'defendKing':id==='saboteurs'?'sabotage':id==='climbers'?'climbBreach':'hold',fallback:'wounded',priority:'auto',formation:id==='shieldLine'?'shield':'wedge',destination:point(leader),initialCount:ids.length,suspended:false};this.divisions[id]=d;ids.forEach((n,i)=>{const a=this.g.apesById.get(n);this.g.tactics?.clearOrder(a);a.divisionId=id;a.divisionSlot=i;this.members.set(n,d)});this.nextPlan=0;this.status=d.name+' formed · '+ids.length+' apes';return d}
 configure(id,values={}){const d=this.divisions[id];if(!d)return false;for(const [key,options]of[['stance',OPTIONS.stances],['fallback',OPTIONS.fallbacks],['priority',OPTIONS.priorities],['formation',OPTIONS.formations]])if(values[key]&&Object.hasOwn(options,values[key]))d[key]=values[key];if(finite(values.destination))d.destination={x:clamp(values.destination.x,-1e7,1e7),y:clamp(values.destination.y,-1e7,1e7)};if(values.settlementId&&this.g.settlement(values.settlementId))d.settlementId=values.settlementId;d.suspended=false;delete d.fallingBack;delete d.target;this.nextPlan=0;this.status=d.name+' · '+OPTIONS.stances[d.stance];return true}
 disband(id){const d=this.divisions[id];if(!d)return false;for(const n of d.memberIds){this.members.delete(n);const a=this.g.apesById.get(n);if(a){delete a.divisionId;delete a.divisionSlot;delete a._divisionTarget;this.g.tactics?.clearOrder(a);if(FOLLOW.has(a.state))a.state='follow'}}delete this.divisions[id];return true}
 suspendAll(){for(const d of Object.values(this.divisions)){d.suspended=true;delete d.target}this.status='Divisions standing by after direct army command.'}
 anchor(d){if(d.fallingBack||d.stance==='defendKing')return this.g.king;if(d.stance==='defendSettlement')return this.g.settlement(d.settlementId)||d.destination;return d.destination}
 formation(d,a){const center=this.anchor(d),leader=this.g.apesById.get(d.commanderId),heading=d.heading??(leader?Math.atan2(center.y-leader.y,center.x-leader.x):0),i=a.divisionSlot||0;if(i===0)return point(center);let side,back;const columns=d.formation==='column'?3:d.formation==='spread'?10:d.formation==='line'||d.formation==='shield'?12:8,spacing=d.formation==='spread'?43:d.formation==='shield'?25:32;if(d.formation==='wedge'){const row=Math.floor(Math.sqrt(i));side=(i-row*row-row)*30;back=row*32}else{side=((i-1)%columns-(Math.min(columns,d.memberIds.length-1)-1)/2)*spacing;back=(Math.floor((i-1)/columns)+1)*spacing}return{x:center.x-Math.sin(heading)*side-Math.cos(heading)*back,y:center.y+Math.cos(heading)*side-Math.sin(heading)*back}}
 chooseTarget(d,leader){const g=this.g,anchor=this.anchor(d),defensive=['hold','defendKing','defendSettlement'].includes(d.stance),origin=defensive?anchor:leader,range=defensive?185:340;
  const candidates=[];for(const t of g.humanGrid.nearest(origin.x,origin.y,range,12))candidates.push({t,kind:'human'});for(const t of g.vehicleGrid.nearest(origin.x,origin.y,range,4))candidates.push({t,kind:'vehicle'});
  if(!defensive)for(const t of g.world.getObjects(origin.x,origin.y,range).filter(t=>t.hp>0&&!t.dead&&t.faction!=='ape'&&t.team!=='ape'&&!['tree','rock','berry','apeBuilding','stairs','house'].includes(t.type)).slice(0,36)){if(t.type==='cage'&&!(t.count??t.prisoners??0))continue;if(t.type==='gate'&&!t.solid)continue;candidates.push({t,kind:'object'})}
  this.plannerStats.candidates+=candidates.length;let best=null,bestScore=Infinity;const locked=t=>t.type==='cage'&&g.prisons&&!g.prisons.unlocked(t),needsUnlock=candidates.some(c=>locked(c.t));
  const priority=d.priority==='auto'?d.stance==='sabotage'?'devices':d.stance==='rescue'?'captives':d.stance==='climbBreach'?'gates':'infantry':d.priority;
  for(const c of candidates){const t=c.t;if(locked(t)||c.kind==='object'&&g.siege&&!g.siege.known(t)||c.kind!=='object'&&g.lineVisible(leader,t)===false)continue;const preferred=priority==='infantry'&&c.kind==='human'||priority==='vehicles'&&c.kind==='vehicle'||priority==='officers'&&['officer','spotter','sniper'].includes(t.role)||priority==='devices'&&DEVICES.has(t.type)||priority==='gates'&&FORTS.has(t.type)||priority==='captives'&&(t.type==='cage'||needsUnlock&&['prisonControl','generator'].includes(t.type));const score=distance(leader,t)-(preferred?240:0);if(score<bestScore){bestScore=score;best={id:t.id,kind:c.kind}}}return best;
 }
 plan(){const g=this.g;this.plannerStats={groups:0,candidates:0};for(const d of Object.values(this.divisions)){if(d.suspended)continue;this.plannerStats.groups++;const leader=g.apesById.get(d.commanderId);d.memberIds=d.memberIds.filter(id=>{const a=g.apesById.get(id);if(a?.hp>0&&FOLLOW.has(a.state))return true;this.members.delete(id);if(a){delete a.divisionId;delete a.divisionSlot}return false});if(!d.memberIds.length){d.suspended=true;continue}const live=d.memberIds.map(id=>g.apesById.get(id)),health=live.reduce((n,a)=>n+a.hp/a.maxHp,0)/live.length;
   if((!leader||leader.hp<=0||!FOLLOW.has(leader.state))&&d.fallback!=='never'){d.fallingBack=true;d.reason='Commander unavailable'}else if(d.fallback==='wounded'&&(health<.4||leader?.hp/leader?.maxHp<.28)){d.fallingBack=true;d.reason='Wounded'}else if(d.fallback==='outnumbered'&&leader&&(d.memberIds.length<d.initialCount*.55||g.humanGrid.nearest(leader.x,leader.y,250,48).length>d.memberIds.length*1.7)){d.fallingBack=true;d.reason='Outnumbered'}
   if(d.fallingBack){delete d.target;continue}d.target=this.chooseTarget(d,leader?.hp>0?leader:live[0]);
  }
 }
 resolve(ref){return !ref?null:ref.kind==='human'?this.g.humansById.get(ref.id):ref.kind==='vehicle'?this.g.vehicles.find(a=>a.id===ref.id):this.g.world.objects.get(ref.id)}
 travel(d,a,goal,dt,target=null){const g=this.g,order={...point(goal),type:'move',...(target?{targetId:target.id,targetKind:d.target?.kind}:{})},key=d.id+':'+a.species+':'+(target?.id||Math.floor(goal.x/96)+','+Math.floor(goal.y/96))+':'+g.world.navRevision;
  let route=a._divisionRoute;if(!route||route.key!==key){const shared=key+':'+Math.floor(a.x/256)+','+Math.floor(a.y/256);let steps=this.routes.get(shared);if(!steps){steps=g.siege?.routeFor(a,order)||[point(goal)];this.routes.set(shared,steps);if(this.routes.size>128)this.routes.delete(this.routes.keys().next().value)}route=a._divisionRoute={key,steps,index:0}}
  let p=route.steps[route.index];if(!p)p=goal;const gate=p.gateId?g.world.objects.get(p.gateId):null;if(gate?.hp>0&&gate.solid){if(g.siege?.attack(a,gate,'object',dt))return;g.move(a,gate.x-a.x,gate.y-a.y,a.speed,dt);return}
  if(p.action){const wall=g.world.objects.get(p.wallId);if(!wall||wall.dead){route.index++;return}if(distance(a,wall)<Math.max(wall.w||20,wall.h||20)/2+42){if(g.siege?.startTransition(a,wall,p,p.action==='climb'))route.index++;return}}
  if(p.blocked){d.reason='Route blocked — choose another approach';return}const last=route.index>=route.steps.length-1;if(last&&!p.action&&!p.gateId)p=goal;if(distance(a,p)<(last?20:9)){route.index++;return}a.target=point(p);g.move(a,p.x-a.x,p.y-a.y,a.speed*(d.fallingBack?1.22:d.stance==='assault'?1.12:1),dt);
 }
 updateApe(a,dt){const d=this.members.get(a.id);if(!d||d.suspended||!FOLLOW.has(a.state)||a.hp<=0)return false;const g=this.g;if(a.siegeTransition){g.siege.transition(a,dt);return true}if(a.wallClimb){g.tactics?.updateClimb(a,dt);return true}if(a.onWallId){g.siege?.detach(a);return true}g.siege?.releaseThrow(a);g.siege?.updateRally(a);const leader=g.apesById.get(d.commanderId);if((!leader||leader.hp<=0)&&d.fallback!=='never')d.fallingBack=true;
  const target=this.resolve(d.target),defensive=['hold','defendKing','defendSettlement'].includes(d.stance),anchor=this.anchor(d);a.state='hold';
  if(!d.fallingBack&&target?.hp>0&&!target.dead&&(!defensive||distance(target,anchor)<210)){
   const range=d.target.kind==='object'?g.objectDistance(a,target):distance(a,target);if(d.stance==='skirmish'&&range<85&&d.target.kind==='human'){g.move(a,a.x-target.x,a.y-target.y,a.speed*1.1,dt);if(a.species==='capuchin')g.siege?.throwAt(a,target,'human');return true}
   if(g.siege?.attack(a,target,d.target.kind,dt))return true;
   if(d.stance==='climbBreach'&&target.type==='wall'&&g.tactics?.tryClimb(a,anchor.x-a.x,anchor.y-a.y,target))return true;
   if(!defensive||distance(a,anchor)<180){this.travel(d,a,target,dt,target);return true}
  }
  let goal=this.formation(d,a);if(d.stance==='rescue'&&!d.target&&!d.fallingBack&&g.time>=(d.nextEscort||0)){d.nextEscort=g.time+1;const freed=g.apeGrid.nearest(a.x,a.y,180,24,p=>p.state==='free'),cohorts=(g.prisons?.active||[]).flatMap(s=>s.prison?.cohorts||[]).filter(c=>c.count>0&&distance(c,a)<210);for(const captive of freed){captive.state='follow';captive.retreatUntil=g.time+12}if(freed.length||cohorts.length){d.fallingBack=true;d.reason='Escorting rescued captives';goal=this.formation(d,a)}}
  if(distance(a,goal)>20)this.travel(d,a,goal,dt);return true;
 }
 tick(){const g=this.g;if(g.ended)return;const elapsed=clamp(g.time-this.lastTick,0,2);this.lastTick=g.time;if(g.time>=this.nextPlan){this.nextPlan=g.time+.5;this.plan()}
  if(g.time<this.nextAura)return;const dt=this.nextAura?1:elapsed;this.nextAura=g.time+1;
  for(const a of g.apes){if(a.hp<=0||!(a.champion||a.veteran))continue;const t=typeOf(a),s=a.settlementId?g.settlement(a.settlementId):null;if(a.recoveryRemaining&&!a.kingdomMission&&s&&!s.attack&&distance(a,s)<(s.radius||160)+70&&g.time-(a.lastHit??-100)>8)this.recover(a,dt,(s.specialization==='sanctuary'?2:1)*this.settlementBonus(s).recovery);
   if(a.recoveryRemaining)continue;
   if(t==='scoutMaster'||a.veteran?.role==='scoutVeteran'){g.world.reveal(a.x,a.y,380);const h=g.humanGrid.nearest(a.x,a.y,420,1)[0];if(h&&g.time>(a.nextChampionWarn||0)){a.nextChampionWarn=g.time+25;g.notify((a.champion?.name||'Veteran scout')+' spots human movement nearby.','gold');g.rescueFocus.push({x:h.x,y:h.y,hp:1,until:g.time+8})}}
   if(['bulwark','guardCaptain','pursuitLeader','climberCaptain','rescueBearer'].includes(t)){for(const p of g.apeGrid.nearest(a.x,a.y,150,48,p=>p.hp>0)){if(t==='bulwark'||t==='guardCaptain')p._championGuardUntil=g.time+1.2;if(t==='pursuitLeader')p._championHasteUntil=g.time+1.2;if(t==='climberCaptain')p._championClimbUntil=g.time+1.2;if(t==='rescueBearer'&&(p.recoveryRemaining||p.state==='free'||p.rescuedFrom))p._championCarryUntil=g.time+1.2}}
  }
 }
 leadership(a){const d=this.members.get(a.id);if(!d||d.suspended||d.fallingBack)return null;const leader=this.g.apesById.get(d.commanderId);return leader?.hp>0&&!leader.recoveryRemaining&&distance(a,leader)<210?leader:null}
 serialize(){return{version:1,divisions:Object.values(this.divisions).map(d=>({id:d.id,commanderId:d.commanderId,memberIds:d.memberIds.slice(),stance:d.stance,fallback:d.fallback,priority:d.priority,formation:d.formation,destination:d.destination,settlementId:d.settlementId,initialCount:d.initialCount,suspended:d.suspended,fallingBack:d.fallingBack,reason:d.reason})),records:this.records.slice(-24)}}
 restore(data){this.divisions={};this.members.clear();for(const a of this.g.apes){delete a.divisionId;delete a.divisionSlot;if(a.champion&&!classOf(a))delete a.champion;if(a.champion){a.champion.gearLevel=clamp(Math.floor(Number(a.champion.gearLevel)||0),0,2);a.recoveryRemaining=clamp(Number(a.recoveryRemaining)||0,0,120)}}if(data?.version!==1)return;for(const saved of (Array.isArray(data.divisions)?data.divisions:[]).slice(0,6)){const template=DIVISIONS.find(d=>d.id===saved?.id);if(!template||!finite(saved.destination)||!Array.isArray(saved.memberIds))continue;const ids=[...new Set(saved.memberIds)].filter(id=>{const a=this.g.apesById.get(id);return a?.hp>0&&FOLLOW.has(a.state)&&!this.members.has(id)}).slice(0,256);if(!ids.length)continue;const d={id:template.id,name:template.name,commanderId:String(saved.commanderId||''),memberIds:ids,stance:'hold',fallback:'wounded',priority:'auto',formation:'wedge',destination:point(saved.destination)};this.divisions[d.id]=d;this.configure(d.id,saved);d.initialCount=clamp(Number(saved.initialCount)||ids.length,1,256);d.suspended=!!saved.suspended;d.fallingBack=!!saved.fallingBack;d.reason=String(saved.reason||'').slice(0,80);ids.forEach((id,i)=>{const a=this.g.apesById.get(id);a.divisionId=d.id;a.divisionSlot=i;this.members.set(id,d);if(!d.suspended)this.g.tactics?.clearOrder(a)})}this.records=(Array.isArray(data.records)?data.records:[]).filter(r=>r&&typeof r.name==='string').slice(-24);this.status='';}
}
const P=ATSGame.prototype;
Object.defineProperty(P,'champions',{configurable:true,get(){if(!this._champions)this._champions=new Champions(this);return this._champions}});
const tick=ATSSiege.prototype.tick;ATSSiege.prototype.tick=function(dt){this.g.champions.tick();return tick.call(this,dt)};
const update=ATSSiege.prototype.updateApe;ATSSiege.prototype.updateApe=function(a,dt){if(this.g.champions.updateApe(a,dt))return true;return update.call(this,a,dt)};
const balance=ATSSiege.prototype.balance;ATSSiege.prototype.balance=function(a,force=false){const change=a.id!=='king'&&a.state!=='young'&&(!a.speciesBalanceVersion||force),ratio=clamp(a.hp/Math.max(1,a.maxHp||120),0,1),bonus=a.champion?.healthBonus||0;balance.call(this,a,force);if(change&&bonus){a.maxHp+=bonus;a.hp=a.maxHp*ratio;a.championHealthApplied=bonus}};
const damage=P.apeDamage;P.apeDamage=function(a,base){let n=damage.call(this,a,base);if(a.champion)n*=1.2+(a.champion.gearLevel||0)*.05;if(typeOf(a)==='slingerAce'&&base<=8)n*=1.65;if(typeOf(a)==='shockRaider'&&(a.onWallId||a.elevation))n*=1.25;if(this.champions.leadership(a))n*=1.1;if(a.recoveryRemaining)n*=.6;return n};
const hurt=P.hurt;P.hurt=function(a,n,source){const t=typeOf(source);if(t==='tankBuster'&&(a.vehicleClass||a.id?.startsWith('vehicle'))&&Math.cos(Math.atan2(source.y-a.y,source.x-a.x)-(a.dir||0))<.5)n*=1.55;if((t==='signalHunter'||t==='alarmSpoiler')&&['officer','spotter','sniper'].includes(a.role))n*=1.45;if(a.species){if(a._championGuardUntil>this.time)n*=.88;const leader=this.champions.leadership(a);if(leader?.species==='gorilla'||leader?.species==='mandrill')n*=.92;if(typeOf(a)==='bulwark')n*=.92}const before=a.hp,result=hurt.call(this,a,n,source);if(before>0&&a.hp<=0){if(a.champion){this.champions.records.push({name:a.champion.name,species:a.species,at:this.time});this.notify(a.champion.name+' has fallen.','red')}if(source?.species&&source.id!=='king'&&a.id?.startsWith('human')){source.championKills=(source.championKills||0)+1;if(source.championKills===5&&!source.veteran&&!source.champion)this.champions.veteran(source)}}return result};
const objectDamage=P.damageObject;P.damageObject=function(o,n,a){const t=typeOf(a);if(t==='wallbreaker'&&FORTS.has(o.type))n*=1.65;if(t==='jailerCrusher'&&['tower','gatlingNest','mortarNest','cage','holdingBlock','riotGate'].includes(o.type))n*=1.6;if(t==='siegeHauler')n*=1.35;if(t==='saboteur'&&DEVICES.has(o.type))n*=1.75;if(t==='gateRunner')n*=o.type==='gateControl'?2:o.type==='gate'||o.type==='riotGate'?1.4:1;if((t==='signalHunter'||t==='alarmSpoiler')&&(DEVICES.has(o.type)||o.type==='tower'))n*=1.6;const before=o.hp,result=objectDamage.call(this,o,n,a);if(t==='supplyThief'&&before>0&&o.hp<=0&&['depot','fuelDepot','fuel'].includes(o.type)){this.food+=12;this.effect('text',o.x,o.y,{text:'+12 supplies',color:'#d4cc85',life:1.5})}return result};
const move=P.move;P.move=function(a,dx,dy,speed,dt,...args){if(a.species&&a.id!=='king'){if(a.recoveryRemaining)speed*=.65;if(typeOf(a)==='skyRunner')speed*=1.15;if(a._championCarryUntil>this.time)speed*=1.3;else if(a._championHasteUntil>this.time)speed*=1.12;const leader=this.champions.leadership(a);if(leader)speed*=distance(a,leader)>100?1.2:1.06}return move.call(this,a,dx,dy,speed,dt,...args)};
const apeUpdate=P.updateApe;P.updateApe=function(a,dt){if(typeOf(a)==='shockRaider')a.attackCD=Math.max(0,a.attackCD-dt*.2);return apeUpdate.call(this,a,dt)};
const actorTier=P.actorTier;P.actorTier=function(a){const d=this._champions?.members.get(a.id);if(d&&!d.suspended)return distance(a,this.king)<1200?0:1;return actorTier.call(this,a)};
const transition=ATSSiege.prototype.transition;ATSSiege.prototype.transition=function(a,dt){const t=typeOf(a);return transition.call(this,a,dt*(t==='skyRunner'?1.4:t==='climberCaptain'||a._championClimbUntil>this.g.time?1.25:1))};
const climb=ATSApeTactics.prototype.updateClimb;ATSApeTactics.prototype.updateClimb=function(a,dt){return climb.call(this,a,dt*(typeOf(a)==='skyRunner'?1.4:typeOf(a)==='climberCaptain'||a._championClimbUntil>this.g.time?1.25:1))};
const rally=ATSSiege.prototype.updateRally;ATSSiege.prototype.updateRally=function(a){const casting=!!a.rallyCast,ready=this.rallyReady;rally.call(this,a);if(casting&&!a.rallyCast&&this.rallyReady>ready&&typeOf(a)==='warcaller'){this.rallyReady=this.g.time+23;for(const p of this.g.apeGrid.nearest(a.x,a.y,235,96))p.rallyUntil=this.g.time+10;this.g.effect('wave',a.x,a.y,{color:'#e9c773',range:235,life:1.2})}};
const throwAt=ATSSiege.prototype.throwAt;ATSSiege.prototype.throwAt=function(a,t,kind){const prior=a.nextThrowAt,result=throwAt.call(this,a,t,kind);if(typeOf(a)==='skirmisher'&&a.nextThrowAt!==prior)a.nextThrowAt=this.g.time+.95;return result};
const capuchin=ATSSiege.prototype.capuchin;ATSSiege.prototype.capuchin=function(a,dt){const result=capuchin.call(this,a,dt);if(result&&typeOf(a)==='skirmisher'&&!a.throwWindup&&a.state!=='hold'&&!a.moving){const side=(ATSUtil.hash(a.id)%2?1:-1),angle=(a.dir||0)+side*Math.PI/2;this.g.move(a,Math.cos(angle)*40,Math.sin(angle)*40,a.speed*.5,dt)}return result};
const prepareShields=ATSSiege.prototype.prepareShields;ATSSiege.prototype.prepareShields=function(){const result=prepareShields.call(this);if(result)for(const a of this.selectedMembers())if(typeOf(a)==='siegeHauler'&&a.shield&&!a.shield.hauler){a.shield.hp+=70;a.shield.maxHp+=70;a.shield.hauler=true}return result};
const lineVisible=P.lineVisible;P.lineVisible=function(a,b,critical=false){if(!critical&&a?.id?.startsWith('human')&&typeOf(b)==='silentInfiltrator'&&distance(a,b)>150&&this.apeGrid.nearest(b.x,b.y,80,2,p=>p.id!==b.id).length===0)return false;return lineVisible.call(this,a,b,critical)};
const command=P.command;P.command=function(cmd,...args){const elites=cmd==='patrol'?this.apes.filter(a=>a.champion).map(a=>({a,state:a.state,hp:a.hp,maxHp:a.maxHp})):[];const result=command.call(this,cmd,...args);if(result&&['call','follow','recall','charge','hold','spreadCharge','attackNearest','retreat'].includes(cmd))this.champions.suspendAll();for(const old of elites)if(old.state!=='scout'&&old.a.state==='scout'){old.a.maxHp=old.maxHp+25;old.a.hp=old.hp}return result};
const issue=ATSSiege.prototype.issue;ATSSiege.prototype.issue=function(species,orders,append=false){const result=issue.call(this,species,orders,append);if(result)for(const s of species)for(const id of this.groups[s]?.members||[])this.g.champions.removeMember(id);return result};
const serialize=P.serialize;P.serialize=function(){const d=serialize.call(this);d.champions=this.champions.serialize();return d};
const restore=ATSGame.fromJSON;ATSGame.fromJSON=function(d,hooks={}){const g=restore.call(this,d,hooks);g.champions.restore(d.champions);return g};
window.ATSChampions=Champions;window.ATSChampionArchetypes=ARCHETYPES;window.ATSChampionClasses=Object.freeze(Object.fromEntries(BY_ID));window.ATSDivisions=DIVISIONS;window.ATSDivisionOptions=OPTIONS;
})();
