/* The workshop menu can live in the existing paused kingdom overview. */
(() => {
'use strict';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n},button=(text,fn)=>{const b=el('button',text,'button');b.type='button';b.addEventListener('click',fn);return b};
class EquipmentUI{
 constructor(root,options){this.root=root;this.getGame=options.getGame;this.onChange=options.onChange||(()=>{});this.selected=null;root.classList.add('equipment-panel');if(!document.getElementById('equipmentStyles')){const style=el('style');style.id='equipmentStyles';style.textContent='.equipment-panel{margin-top:24px;border-top:1px solid #405b51;padding-top:20px}.equipment-panel h3{margin:0 0 8px;color:#e7c47e;font-size:18px}.equipment-panel p{font-size:12px;line-height:1.6;color:#b7c9b8}.equipment-toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:14px 0}.equipment-toolbar label{font-size:12px;color:#b7c9b8}.equipment-toolbar select{display:block;width:100%;min-width:220px;max-width:100%;margin-top:5px;border:1px solid #516b58;border-radius:4px;background:#102d2c;color:#ead8ae;padding:9px}.equipment-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr));gap:12px}.equipment-card{background:#112b29;border:1px solid #456047;border-radius:7px;padding:15px;min-width:0}.equipment-card strong{display:block;color:#e5c68b;font-size:14px}.equipment-card small{display:block;color:#a8bdab;font-size:11px;line-height:1.6;margin:7px 0}.equipment-card .button{font-size:11px;min-height:35px}.equipment-card .button:disabled{opacity:.48;cursor:not-allowed}.equipment-symbol{font-size:26px;line-height:1.4;color:#e5c68b}.equipment-queue{margin:16px 0;display:grid;gap:8px}.equipment-job{border:1px solid #4d5a43;background:#162d29;border-radius:5px;padding:10px;font-size:12px;color:#d5dcb9}.equipment-job progress{width:100%;height:7px;accent-color:#d8b769;display:block;margin:8px 0}.equipment-job .button{float:right;font-size:10px;padding:4px 8px}.equipment-notice{min-height:20px;color:#edc982!important}.equipment-stock{color:#d7cca0;font-size:12px}';document.head.append(style)}}
 static mount(root,options){return new EquipmentUI(root,options)}
 changed(){this.onChange();this.update()}
 update(){const g=this.getGame();if(!g)return;const e=g.equipment,workshops=e.workshops(),near=e.nearby();if(!workshops.some(p=>p.w.id===this.selected))this.selected=near?.w.id||workshops[0]?.w.id||null;const current=workshops.find(p=>p.w.id===this.selected);this.root.replaceChildren();this.root.append(el('h3','Workshops & royal armor'),el('p','Visit a completed workshop with the King to spend that village’s timber and food. Artisans equip one individual at a time. Recruits travel to the workshop; the King must remain nearby while his armor is fitted. Work pauses during raids.'));
  const toolbar=el('div',null,'equipment-toolbar'),label=el('label','Workshop'),select=el('select');select.setAttribute('aria-label','Workshop to visit');for(const p of workshops){const option=el('option',p.s.name+' · '+Math.round(Math.hypot(g.king.x-p.w.x,g.king.y-p.w.y))+' paces');option.value=p.w.id;option.selected=p.w.id===this.selected;select.append(option)}select.addEventListener('change',()=>{this.selected=select.value;this.update()});label.append(select);toolbar.append(label);if(current)toolbar.append(el('span',Math.floor(current.s.wood)+' timber · '+Math.floor(current.s.food)+' food','equipment-stock'));this.root.append(toolbar);
  if(!current)this.root.append(el('p','Commission a workshop from a settlement’s great lodge, then visit it to arm your army.'));
  const grid=el('div',null,'equipment-grid');for(const spec of e.catalog(current?.s.id,current?.w.id)){const card=el('div',null,'equipment-card');card.append(el('div',{spear:'➶',cuffs:'▣',torch:'♨',armor:'♜'}[spec.kind],'equipment-symbol'),el('strong',spec.label),el('small',spec.description),el('small',spec.wood+' timber + '+spec.food+' food · '+spec.seconds+' seconds'));if(spec.kind!=='armor')card.append(el('small',spec.equipped+' equipped · '+spec.pending+' queued · '+spec.limit+' slots this tier'));card.append(el('small',spec.reason||'Ready at this workshop.'));const buy=button(spec.kind==='armor'?'Commission royal armor':'Equip one '+(spec.kind==='cuffs'?'gorilla':spec.kind==='spear'?'capuchin':'climber'),()=>{e.purchase(current.s.id,current.w.id,spec.kind);this.changed()});buy.disabled=!spec.available;card.append(buy);grid.append(card)}this.root.append(grid);
  if(e.armorLevel===3)this.root.append(el('p','Jungle sovereign armor complete: 500 maximum health · 22% damage protection · 70% stronger attacks.'));else if(e.armor)this.root.append(el('p','Worn by the King: '+e.armor.label+' · '+Math.ceil(g.king.hp)+' / '+g.king.maxHp+' health.'));
  const queue=el('div',null,'equipment-queue');queue.append(el('strong','Artisan queue · '+e.queue.length+' / 8 orders'));e.queue.forEach((job,index)=>{const a=e.actor(job),spec=job.kind==='armor'?ATSKingArmor[job.armorLevel-1]:ATSEquipmentGear[job.kind],row=el('div',null,'equipment-job'),cancel=button('Cancel',()=>{e.cancel(job.id);this.changed()});row.append(cancel,el('span',(index+1)+'. '+spec.label+' · '+(a?.id==='king'?'King':a?.champion?.name||a?.species||'Recipient lost')));const progress=el('progress');progress.max=job.duration;progress.value=job.progress;progress.setAttribute('aria-label',spec.label+' '+Math.round(job.progress/job.duration*100)+' percent complete');row.append(progress,el('small',index?'Queued — waits for the prior individual':e.state(job)+' · '+Math.max(0,Math.ceil(job.duration-job.progress))+'s remaining'));queue.append(row)});if(!e.queue.length)queue.append(el('p','No gear in production. Continue playing after placing an order.'));this.root.append(queue);const status=el('p',e.status,'equipment-notice');status.setAttribute('role','status');this.root.append(status);
 }
}
window.ATSEquipmentUI=EquipmentUI;
})();
