/* A single shared artisan queue equips real individuals. Crowds retain cached
   sprites; only the small torch roster contributes additional moving lights. */
(() => {
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const GEAR=Object.freeze({
 spear:Object.freeze({label:'Throwing spears',tier:1,wood:28,food:24,seconds:18,species:['capuchin'],limits:[0,16,48],description:'Equip one capuchin with visible thrown spears that deal 130% more ranged damage.'}),
 cuffs:Object.freeze({label:'Wooden fist cuffs',tier:1,wood:36,food:30,seconds:22,species:['gorilla'],limits:[0,16,48],description:'Fit one gorilla with hardwood cuffs for 35% stronger strikes.'}),
 torch:Object.freeze({label:'Raider torch',tier:1,wood:24,food:28,seconds:16,species:['gibbon','chimpanzee','capuchin'],limits:[0,8,24],description:'Arm one climber with fire: 65% more building damage and a pool of light, but humans can spot the bearer from any direction.'})
});
const ARMOR=Object.freeze([
 Object.freeze({level:1,label:'Barkguard armor',tier:1,wood:100,food:120,seconds:25,maxHp:240,damage:1.18,reduction:.08}),
 Object.freeze({level:2,label:'Ironwood war harness',tier:2,wood:200,food:240,seconds:35,maxHp:350,damage:1.4,reduction:.15}),
 Object.freeze({level:3,label:'Jungle sovereign armor',tier:2,wood:360,food:420,seconds:50,maxHp:500,damage:1.7,reduction:.22})
]);
const activeWorkshop=o=>o&&o.kind==='workShelter'&&o.hp>0&&!o.dead&&(o.stage??4)===4;
class Equipment{
 constructor(g){this.g=g;this.queue=[];this.serial=0;this.status='';this.torchIds=new Set();this.nextMaintenance=0;this.stats={activeWorkers:0,torchLights:0};}
 get tier(){return clamp(Math.floor(this.g.progression?.tier??(this.g.population>=200?2:this.g.population>=100?1:0)),0,2)}
 get armorLevel(){return clamp(Math.floor(this.g.king.equipment?.armorLevel||0),0,3)}
 get armor(){return ARMOR[this.armorLevel-1]||null}
 workshop(settlementId,workshopId){const s=this.g.settlement(settlementId);if(!s)return null;const w=(s.structures||[]).find(o=>o.id===workshopId&&activeWorkshop(o));return w?{s,w}:null}
 workshops(){const out=[];for(const s of this.g.settlements)for(const w of s.structures||[])if(activeWorkshop(w))out.push({s,w});return out}
 nearby(){let nearest=null,range=100;for(const p of this.workshops()){const d=distance(this.g.king,p.w);if(d<=range){range=d;nearest=p}}return nearest}
 workshopAt(){const p=this.nearby();return p?{settlement:p.s,workshop:p.w}:null}
 gearCount(kind){let count=0;for(const a of this.g.apes)if(a.hp>0&&a.equipment?.[kind])count++;return count}
 eligible(a,kind,s){const spec=GEAR[kind];return !!a&&a.hp>0&&a.state!=='young'&&spec?.species.includes(a.species)&&!a.equipment?.[kind]&&!a.recoveryRemaining&&!a.kingdomMission&&!a.siegeTransition&&!a.wallClimb&&!a.onWallId&&!this.queue.some(j=>j.actorId===a.id)&&distance(a,s)<(s.radius||160)+200&&!(kind==='spear'&&a.equipment?.torch||kind==='torch'&&a.equipment?.spear)}
 candidate(kind,s){const spec=GEAR[kind];if(!spec)return null;let best=null,score=Infinity;for(const a of this.g.apes){if(!this.eligible(a,kind,s))continue;const d=distance(a,s)+spec.species.indexOf(a.species)*400;if(d<score){score=d;best=a}}return best}
 catalog(settlementId,workshopId){const p=this.workshop(settlementId,workshopId),s=p?.s,near=!!p&&distance(this.g.king,p.w)<=100,baseReason=!p?'Build a completed workshop first.':!near?'Bring the King within 100 paces of this workshop.':s.attack?'The village must be safe before commissioning gear.':this.queue.length>=8?'The artisan queue is full (8 orders).':'';
  const entries=Object.entries(GEAR).map(([kind,spec])=>{const equipped=this.gearCount(kind),pending=this.queue.filter(j=>j.kind===kind).length,limit=spec.limits[this.tier],a=s?this.candidate(kind,s):null,reason=this.tier<spec.tier?'Unlocks at 100 apes — King of the Jungle.':baseReason||((equipped+pending>=limit)?'All '+limit+' gear slots are in use.':!a?'Bring an unequipped adult '+spec.species.join(' / ')+' to this village.':s.wood<spec.wood?'Not enough village timber.':s.food<spec.food?'Not enough village food.':'');return{kind,...spec,equipped,pending,limit,actorId:a?.id,available:!reason,reason}});
  const spec=ARMOR[this.armorLevel];if(spec){const pending=this.queue.some(j=>j.kind==='armor'),reason=this.tier<spec.tier?'Unlocks at '+(spec.tier===2?'200 apes — Warlord.':'100 apes — King of the Jungle.'):baseReason||(pending?'The King already has an armor order in the queue.':s.wood<spec.wood?'Not enough village timber.':s.food<spec.food?'Not enough village food.':'');entries.push({kind:'armor',...spec,description:spec.maxHp+' maximum health, '+Math.round(spec.reduction*100)+'% damage protection and '+Math.round((spec.damage-1)*100)+'% stronger attacks. Existing wounds remain.',available:!reason,reason})}return entries;
 }
 purchase(settlementId,workshopId,kind){const entry=this.catalog(settlementId,workshopId).find(e=>e.kind===kind);if(!entry?.available){this.status=entry?.reason||'That upgrade is unavailable.';return{ok:false,reason:this.status}}const {s}=this.workshop(settlementId,workshopId);s.wood-=entry.wood;s.food-=entry.food;const job={id:'equipment-'+ ++this.serial,settlementId,workshopId,kind,actorId:kind==='armor'?'king':entry.actorId,armorLevel:kind==='armor'?entry.level:0,progress:0,duration:entry.seconds,cost:{wood:entry.wood,food:entry.food},createdAt:this.g.time};this.queue.push(job);this.status=entry.label+' ordered. One individual is equipped at a time.';return{ok:true,jobId:job.id,reason:this.status}}
 cancel(id){const index=this.queue.findIndex(j=>j.id===id);if(index<0)return false;const job=this.queue[index],s=this.g.settlement(job.settlementId),remaining=1-clamp(job.progress/job.duration,0,1);if(s){s.wood+=Math.floor(job.cost.wood*remaining);s.food+=Math.floor(job.cost.food*remaining)}this.queue.splice(index,1);this.status='Order cancelled; unused timber and food returned to the village.';return true}
 actor(job){return job?.actorId==='king'?this.g.king:this.g.apesById.get(job?.actorId)}
 state(job=this.queue[0]){if(!job)return'Idle';const p=this.workshop(job.settlementId,job.workshopId),a=this.actor(job);if(!a||a.hp<=0)return'Paused — recipient lost; cancel to recover unused supplies';if(!p)return'Paused — workshop destroyed; cancel to recover unused supplies';if(p.s.attack)return'Paused — village under attack';if(distance(a,p.w)>90)return a.id==='king'?'Waiting for the King at the workshop':'Recipient traveling to workshop';if(a.siegeTransition||a.wallClimb||a.onWallId||a.recoveryRemaining||a.kingdomMission||this.g.time-(a.lastHit??-100)<3)return'Paused — recipient cannot work yet';return'Equipping'}
 updateApe(a,dt){const job=this.queue[0];if(!job||job.actorId!==a.id||a.hp<=0)return false;const p=this.workshop(job.settlementId,job.workshopId);if(!p||p.s.attack||a.siegeTransition||a.wallClimb||a.onWallId||this.g.time-(a.lastHit??-100)<3)return false;if(distance(a,p.w)>75){const x=p.w.x+58,y=p.w.y+16;this.g.move(a,x-a.x,y-a.y,(a.speed||90)*.85,dt)}else{a.moving=false;a.dir=Math.atan2(p.w.y-a.y,p.w.x-a.x)}return true}
 finish(job){const a=this.actor(job);if(!a||a.hp<=0)return;const gear=a.equipment||(a.equipment={});if(job.kind==='armor'){if(job.armorLevel!==this.armorLevel+1)return;const spec=ARMOR[job.armorLevel-1],deficit=Math.max(0,a.maxHp-a.hp);gear.armorLevel=spec.level;a.maxHp=spec.maxHp;a.hp=Math.max(1,spec.maxHp-deficit);this.status=spec.label+' fitted — '+spec.maxHp+' maximum health.'}else{gear[job.kind]=true;if(job.kind==='torch')this.torchIds.add(a.id);this.status=GEAR[job.kind].label+' ready for '+a.species+'.'}this.g._lightsAt=-1;this.g.notify(this.status,'gold');this.g.effect?.('wave',a.x,a.y,{color:'#e8bb70',range:55,life:.6});}
 tick(dt){if(this.g.ended||!(dt>0))return;this.stats.activeWorkers=0;const job=this.queue[0];if(job&&this.state(job)==='Equipping'){this.stats.activeWorkers=1;job.progress=Math.min(job.duration,job.progress+Math.min(dt,1));if(job.progress>=job.duration){this.finish(job);this.queue.shift()}}if(this.g.time>=this.nextMaintenance){this.nextMaintenance=this.g.time+1;for(const id of this.torchIds){const a=this.g.apesById.get(id);if(!a||a.hp<=0||!a.equipment?.torch)this.torchIds.delete(id)}}}
 lights(){const out=[];for(const id of this.torchIds){const a=this.g.apesById.get(id);if(a?.hp>0&&distance(a,this.g.king)<1050){out.push({id:'torch:'+id,x:a.x,y:a.y,dir:0,range:115,angle:Math.PI,kind:'flare',equipmentTorch:true,active:true});if(out.length===24)break}}this.stats.torchLights=out.length;return out}
 serialize(){return{version:1,serial:this.serial,queue:this.queue.map(j=>({...j,cost:{...j.cost}}))}}
 restore(data){this.queue=[];this.torchIds.clear();for(const a of this.g.apes){const saved=a.equipment;if(!saved)continue;a.equipment={};for(const [kind,spec]of Object.entries(GEAR))if(saved[kind]&&spec.species.includes(a.species))a.equipment[kind]=true;if(a.equipment.spear&&a.equipment.torch)delete a.equipment.torch;if(a.equipment.torch&&a.hp>0){if(this.torchIds.size<24)this.torchIds.add(a.id);else delete a.equipment.torch}}
  const king=this.g.king,level=this.armorLevel;if(level){king.equipment={armorLevel:level};king.maxHp=ARMOR[level-1].maxHp;king.hp=clamp(king.hp,1,king.maxHp)}this.serial=Math.max(0,Math.floor(Number(data?.serial)||0));if(data?.version!==1)return;const assigned=new Set();for(const saved of(Array.isArray(data.queue)?data.queue:[]).slice(0,8)){const armorLevel=Number(saved?.armorLevel),spec=saved?.kind==='armor'?ARMOR[armorLevel-1]:GEAR[saved?.kind];if(!spec||assigned.has(saved.actorId)||!this.g.settlement(saved.settlementId))continue;const a=saved.actorId==='king'?king:this.g.apesById.get(saved.actorId);if(!a||a.hp<=0||saved.kind==='armor'&&(a.id!=='king'||armorLevel!==level+1)||saved.kind!=='armor'&&(!spec.species.includes(a.species)||a.equipment?.[saved.kind]))continue;assigned.add(saved.actorId);this.queue.push({id:'equipment-'+ ++this.serial,kind:saved.kind,actorId:a.id,settlementId:saved.settlementId,workshopId:String(saved.workshopId||''),armorLevel:saved.kind==='armor'?armorLevel:0,duration:spec.seconds,progress:clamp(Number(saved.progress)||0,0,spec.seconds),cost:{wood:spec.wood,food:spec.food},createdAt:Number(saved.createdAt)||this.g.time})}this.status='';
 }
}
const P=ATSGame.prototype;
Object.defineProperty(P,'equipment',{configurable:true,get(){if(!this._equipment)this._equipment=new Equipment(this);return this._equipment}});
const tick=ATSSiege.prototype.tick;ATSSiege.prototype.tick=function(dt){this.g.equipment.tick(dt);return tick.call(this,dt)};
const update=ATSSiege.prototype.updateApe;ATSSiege.prototype.updateApe=function(a,dt){if(this.g.equipment.updateApe(a,dt))return true;return update.call(this,a,dt)};
const damage=P.apeDamage;P.apeDamage=function(a,base){return damage.call(this,a,base)*(a.equipment?.cuffs?1.35:1)};
const hurt=P.hurt;P.hurt=function(a,n,source){const armor=this.equipment.armor;if(armor){if(a.id==='king')n*=1-armor.reduction;if(source?.id==='king')n*=armor.damage}return hurt.call(this,a,n,source)};
const objectDamage=P.damageObject;P.damageObject=function(o,n,a){if(a?.id==='king')n*=this.equipment.armor?.damage||1;else if(a?.equipment?.torch&&!['tree','rock','berry'].includes(o.type)&&o.team!=='ape'&&o.faction!=='ape'){n*=1.65;if(this.time>=(a._torchSparkAt||0)){a._torchSparkAt=this.time+.4;this.effect('smash',o.x,o.y,{life:.3,color:'#f0a34b'})}}return objectDamage.call(this,o,n,a)};
const release=ATSSiege.prototype.releaseThrow;ATSSiege.prototype.releaseThrow=function(a){const length=this.stones.length,result=release.call(this,a);if(a.equipment?.spear&&this.stones.length>length){const p=this.stones[this.stones.length-1];p.equipmentType='spear';p.damage*=2.3;p.duration=Math.max(.2,p.duration*.8)}return result};
const lights=P.getLights;P.getLights=function(){const result=lights.call(this);if(this._equipment){let write=0;for(let i=0;i<result.length;i++)if(!result[i].equipmentTorch)result[write++]=result[i];result.length=write;if(this.equipment.torchIds.size)result.push(...this.equipment.lights())}this.lightCache=result;return result};
// Self-lit raiders are conspicuous even outside a guard's narrow flashlight
// cone. The normal line-of-sight budget and existing sensing range still apply.
const perceive=P.perceive;P.perceive=function(h,light){const result=perceive.call(this,h,light);if(result?.seen||result?.pending||!this._equipment?.torchIds.size)return result;const range=light.range*(this.weatherInfo?.().sight||1);let checks=0;for(const id of this.equipment.torchIds){const a=this.apesById.get(id);if(!a||a.hp<=0||distance(h,a)>range)continue;if(++checks>4)break;const clear=this.lineVisible(h,a);if(clear===null)return{pending:true};if(clear)return{seen:a}}return result};
const serialize=P.serialize;P.serialize=function(){const d=serialize.call(this);d.equipment=this.equipment.serialize();return d};
const restore=ATSGame.fromJSON;ATSGame.fromJSON=function(d,hooks={}){const g=restore.call(this,d,hooks);g.equipment.restore(d.equipment);return g};
window.ATSEquipment=Equipment;window.ATSEquipmentGear=GEAR;window.ATSKingArmor=ARMOR;
})();
