/* Overview controls use the same actions as the simulation and save immediately. */
(function(){
'use strict';
let styled=false;
function mountRow(game,s,row,{onChange=()=>{},feedback=()=>{}}={}){
 const kingdom=game.kingdom;kingdom.ensure(s);
 if(!styled){const style=document.createElement('style');style.textContent='.kingdom-controls{margin-top:12px;padding-top:10px;border-top:1px solid #40574c}.kingdom-controls label{display:inline-flex;flex-wrap:wrap;align-items:center;gap:6px;margin:0 10px 8px 0}.kingdom-controls select{max-width:100%;min-height:36px}.kingdom-actions{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0}.kingdom-actions button{min-height:38px;font-size:11px;padding:7px 10px}.kingdom-detail{font-size:12px;color:#b9ceb8;line-height:1.5}.kingdom-events{font-size:11px;margin:8px 0;padding-left:18px;color:#d0c9a8}.kingdom-missions{font-size:12px;color:#d8b875}';document.head.append(style);styled=true}
 const root=document.createElement('section');root.className='kingdom-controls';root.setAttribute('aria-label',s.name+' kingdom controls');
 const choose=(label,values,current,action)=>{const holder=document.createElement('label');holder.textContent=label+' ';const select=document.createElement('select');select.setAttribute('aria-label',s.name+' '+label.toLowerCase());for(const [value,text]of values){const option=document.createElement('option');option.value=value;option.textContent=text;option.selected=current===value;select.append(option)}select.addEventListener('change',()=>{const result=action(select.value);if(!result.ok)feedback(result.reason);onChange()});holder.append(select);root.append(holder);return select};
 choose('Specialization',Object.entries(ATSKingdomFocus).map(([key,value])=>[key,value.label]),s.specialization,value=>kingdom.specialize(s.id,value));
 choose('Defense posture',[['balanced','Balanced defense'],['fortified','Hold entrances · stronger defense'],['mobile','Mobile reserve · faster patrols']],s.defensePosture,value=>kingdom.posture(s.id,value));
 const description=document.createElement('p');description.className='kingdom-detail';description.textContent=ATSKingdomFocus[s.specialization].description+(s.moraleUntil>game.time?' Celebration: faster growth and construction for '+Math.ceil(s.moraleUntil-game.time)+'s.':'')+(s.rallyPoint?' Kingdom rally point.':'');root.append(description);
 const actions=document.createElement('div');actions.className='kingdom-actions';const button=(label,action)=>{const b=document.createElement('button');b.type='button';b.className='button';b.textContent=label;b.addEventListener('click',()=>{const result=action();if(!result.ok)feedback(result.reason);onChange()});actions.append(b);return b};
 button('Request defenders',()=>kingdom.requestReinforcements(s.id));button('Evacuate noncombatants',()=>kingdom.evacuate(s.id));const rally=button(s.rallyPoint?'Rally point selected':'Set rally point',()=>kingdom.rally(s.id));rally.setAttribute('aria-pressed',String(!!s.rallyPoint));root.append(actions);
 const send=document.createElement('div');send.className='kingdom-actions';const label=document.createElement('label');label.textContent='Supply destination ';const destination=document.createElement('select');destination.setAttribute('aria-label',s.name+' supply destination');for(const target of [{id:'king',name:'Traveling army'},...game.settlements.filter(other=>other.id!==s.id&&other.population>0)]){const option=document.createElement('option');option.value=target.id;option.textContent=target.name;destination.append(option)}label.append(destination);send.append(label);const supply=document.createElement('button');supply.type='button';supply.className='button';supply.textContent='Send supply group';supply.addEventListener('click',()=>{const result=kingdom.sendSupplies(s.id,destination.value);if(!result.ok)feedback(result.reason);onChange()});send.append(supply);root.append(send);
 if(s.specialization==='workshop'||s.gearKits||s.siegeMaterials){const stock=document.createElement('p');stock.className='kingdom-detail';stock.textContent=s.gearKits+' gear kits · '+s.siegeMaterials+' siege materials · crafting '+Math.floor(s.craftProgress)+'/45s (12 timber + 6 food per batch).';root.append(stock);button('Refit stationed champion',()=>kingdom.refit(s.id));button('Issue reinforced log shields',()=>kingdom.issueShields(s.id))}
 const missions=s.kingdomMissions.filter(m=>m.status==='traveling');if(missions.length){const active=document.createElement('p');active.className='kingdom-missions';active.textContent=missions.map(m=>m.members.length+' '+m.kind+' travelers · '+(m.returning?'returning home':m.targetId==='king'?'to the King':'to '+(game.settlement(m.targetId)?.name||'settlement'))).join(' | ');root.append(active)}
 if(s.kingdomEvents.length){const events=document.createElement('ul');events.className='kingdom-events';events.setAttribute('aria-label',s.name+' recent events');for(const event of s.kingdomEvents.slice(-3).reverse()){const item=document.createElement('li');item.textContent=event.text;events.append(item)}root.append(events)}
 row.append(root);
}
window.ATSKingdomUI={mountRow};
})();
