/* Organic settlements: limited forage, housing, work priorities and defenses. */
(function(){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
class Settlements {
 constructor(game){this.game=game}
 evaluate(x,y){const w=this.game.world,t=w.terrain(x,y),objects=w.getObjects(x,y,390),trees=objects.filter(o=>o.type==='tree'&&!o.dead).length,berries=objects.filter(o=>o.type==='berry').length,region=w.districtAt(x,y);let water=false;for(let i=0;i<8;i++){const a=i*Math.PI/4;if(w.terrain(x+Math.cos(a)*210,y+Math.sin(a)*210).water)water=true}const risk=w.getSites(x,y,700).filter(s=>!s.cleared&&s.guards>0).length;return {fertility:region.fertility,wood:trees,berries,water,cover:clamp(trees/16,.1,1),capacity:Math.round(12+berries*5+(water?12:0)+region.fertility*10),risk,biome:t.biome,region:region.name}}
 init(s){if(s.economyVersion!==2){s.economyVersion=2;s.policy=s.policy||'balanced';s.wood=s.wood??8;s.housing=Math.max(6,Math.ceil((s.population||5)/6)*6);s.gardens=s.gardens||0;s.defense=s.defense||0;s.maxDefense=s.maxDefense||0;s.buildProgress=0;s.safety=s.safety??1;s.suitability=this.evaluate(s.x,s.y);s.foodDelta=0;s.project='Shelters';s.status='Establishing camp';s.supplyTimer=0;s.investedLevel=s.level||1}
 // Old saves retain their actual housing. New work creates persistent physical
 // huts; neither refreshing residents nor loading a save restores lost homes.
 if(s.structuresVersion!==1){s.structuresVersion=1;s.huts=[];let remaining=Math.max(0,(s.housing||6)-6);while(remaining>0){const capacity=Math.min(12,remaining);this.addHut(s,capacity,true);remaining-=capacity}}s.huts=s.huts||[];this.updateHousing(s);s.birthTimer=s.birthTimer||0}
 addHut(s,capacity=12,preserveHousing=false){let slot=s.huts.length,offset=slot,ring=0,count=8;while(offset>=count){offset-=count;ring++;count=8+ring*4}const radius=140+ring*70,angle=offset/count*Math.PI*2+ring*.31+.2,w=this.game.world;let plot=null;
 // A bounded deterministic search keeps a new home out of rivers, trunks and
 // other hut plots. Existing save housing still migrates even in crowded woods.
 for(let i=0;i<32;i++){const a=angle+(i%8)*Math.PI/4,r=radius+Math.floor(i/8)*35,x=s.x+Math.cos(a)*r,y=s.y+Math.sin(a)*r;if(w.terrain(x,y).water||s.huts.some(h=>Math.hypot(h.x-x,h.y-y)<64)||w.blocked(x,y,24))continue;plot={x,y};break}if(!plot){if(!preserveHousing)return null;plot={x:s.x+Math.cos(angle)*radius,y:s.y+Math.sin(angle)*radius}}const hut={id:s.id+'-hut-'+slot,slot,...plot,maxHp:100,hp:100,capacity};s.huts.push(hut);this.updateHousing(s);return hut}
 updateHousing(s){s.housing=6+(s.huts||[]).reduce((sum,h)=>sum+(h.hp>0?h.capacity||12:0),0)}
 footprint(s){this.init(s);let radius=90+Math.min(10,s.level||1)*12;for(const h of s.huts)radius=Math.max(radius,Math.hypot(h.x-s.x,h.y-s.y)+38);return radius}
 damageHut(s,h,damage,source){if(h.hp<=0||!(damage>0))return false;h.hp=Math.max(0,h.hp-damage);h.lastHit=this.game.time;this.game.effect?.('hit',h.x,h.y,{life:.3,color:'#c8ac79'});if(h.hp===0){h.destroyedAt=this.game.time;this.updateHousing(s);this.game.sound?.('smash',.65,h.x);this.game.effect?.('smoke',h.x,h.y,{life:2});this.game.notify(s.name+' loses a hut — '+(h.capacity||12)+' housing destroyed.','red')}return true}
 damageNearby(x,y,radius,damage,source){if(!(radius>0&&damage>0))return;for(const s of this.game.settlements){if(Math.hypot(s.x-x,s.y-y)>(s.radius||this.footprint(s))+radius)continue;this.init(s);for(const h of s.huts){const d=Math.hypot(h.x-x,h.y-y);if(h.hp>0&&d<radius)this.damageHut(s,h,damage*(1-d/radius*.65),source)}}}
 siege(s,raiders){const g=this.game;let budget=64;for(const h of raiders){if(!budget||h.hp<=0||h.state==='patrol'||h.raidTarget&&h.raidTarget!==s.id||g.time<(h._hutAttackAt||0))continue;let target=null,distance=175;for(const hut of s.huts){const d=Math.hypot(h.x-hut.x,h.y-hut.y);if(hut.hp>0&&d<distance&&g.world.lineClear(h.x,h.y,hut.x,hut.y)){target=hut;distance=d}}if(!target)continue;budget--;h._hutAttackAt=g.time+1.8;h.structureTarget=target.id;h.dir=Math.atan2(target.y-h.y,target.x-h.x);h.attackTimer=.14;h.animation={kind:'recoil',start:g.time,duration:.2};g.effect?.('muzzle',h.x,h.y,{life:.12});g.effect?.('siegeShot',h.x,h.y,{targetX:target.x,targetY:target.y,life:.15});g.sound?.('gun',.3,h.x);this.damageHut(s,target,h.role==='heavy'?15:h.role==='engineer'?20:10,h)}}
 action(id,action){const g=this.game,s=g.settlement(id);if(!s)return false;this.init(s);if(['balanced','forage','fortify'].includes(action)){s.policy=action;g.notify(s.name+' prioritizes '+({balanced:'balanced growth',forage:'food security',fortify:'defense'}[action])+'.');return true}if(Math.hypot(g.king.x-s.x,g.king.y-s.y)>s.radius+110){g.notify('Visit this settlement to move supplies or recruit its apes.','red');return false}
 if(action==='supply'){const amount=Math.min(30,g.food);if(amount<1){g.notify('Gather berries or seize human supplies first.');return false}g.food-=amount;s.food+=amount;g.notify(Math.floor(amount)+' food delivered to '+s.name+'.','green');return true}
 if(action==='recruit'){for(const a of g.apes)if(a.settlementId===id&&a.state!=='young'&&a.hp>0){a.state='follow';a.settlementId=null}g.refreshSettlements();g.notify('The adults of '+s.name+' rally to your crown.');return true}return false}
 tick(s){const g=this.game;this.init(s);s.radius=this.footprint(s);const nearby=g.humanGrid.near(s.x,s.y,s.radius+120);this.siege(s,nearby);if(!s.population)return;s.age++;const adults=(g.settlementMembers.get(s.id)||g.apes).filter(a=>a.hp>0&&a.settlementId===s.id&&a.state!=='young'&&a.state!=='scout');const policy=s.policy,forageRatio=policy==='forage'?.65:policy==='fortify'?.3:.45;const foragers=Math.max(adults.length?1:0,Math.floor(adults.length*forageRatio)),builders=Math.max(adults.length>=4?1:0,Math.floor(adults.length*(policy==='fortify'?.45:.25)));s.foragers=foragers;s.builders=builders;s.guards=Math.max(0,adults.length-foragers-builders);
 adults.forEach((a,i)=>{a.job=i<foragers?'forager':i<foragers+builders?'builder':'guardian'});
 s.attack=nearby.some(h=>h.hp>0&&h.state!=='patrol');s.safety=clamp(s.safety+(s.attack?-.045:.007),0,1);
 const before=s.food,nodes=g.world.getObjects(s.x,s.y,s.radius*2.4).filter(o=>o.type==='berry');let available=0;for(const b of nodes){b.food=Math.min(b.count||30,(b.food||0)+.025*s.suitability.fertility);if(b.food>.5)b.dead=false;available+=b.food||0}
 const demand=foragers*.32*(s.attack?.25:1),harvest=Math.min(available,demand);let remaining=harvest;for(const b of nodes){const take=Math.min(remaining,b.food||0);b.food-=take;remaining-=take;if(b.food<=0)b.dead=true;if(remaining<=0)break}
 const gardenYield=s.gardens*.6*s.suitability.fertility*(s.suitability.water?1.15:1);s.food=Math.max(0,s.food+harvest+gardenYield-s.population*.06);s.food=Math.min(s.food,s.housing*10+80);s.foodDelta=s.food-before;s.wood+=builders*.18*Math.min(1,s.suitability.wood/12);s.wood=Math.min(s.wood,150+s.level*15);
 const populationGoal=Math.min(10,1+Math.floor(s.population/12)),housingReserve=Math.max(8,Math.ceil(s.population*.25)),capacity=s.suitability.capacity+s.gardens*16+s.level*10;
 const ruined=s.huts.find(h=>h.hp<=0),wounded=s.huts.find(h=>h.hp>0&&h.hp<h.maxHp);
 s.project=ruined?'Rebuild hut':s.housing<s.population+housingReserve?'Shelters':wounded?'Repair huts':policy==='fortify'&&s.maxDefense<60+s.level*30?'Palisade':(s.food<s.population*3||capacity<=s.population)&&s.gardens<Math.ceil(s.population/8)?'Gardens':s.level<populationGoal?'Great lodge':s.maxDefense>0&&s.defense<s.maxDefense?'Repair defenses':'Food stores';
 if(s.buildProject!==s.project){s.buildProject=s.project;s.buildProgress=0}
 const timber=s.project==='Great lodge'?10:s.project==='Repair huts'?4:6,cost={Shelters:18,'Rebuild hut':24,'Repair huts':16,Palisade:35,Gardens:22,'Great lodge':35,'Repair defenses':18,'Food stores':35}[s.project];
 if(!s.attack&&builders&&s.wood>=timber){s.buildProgress+=builders*1.25;if(s.buildProgress>=cost){s.constructionBlocked=s.project==='Shelters'&&!this.addHut(s);if(s.constructionBlocked)s.buildProgress=cost;else{s.buildProgress-=cost;s.wood-=timber;if(s.project==='Rebuild hut'){ruined.hp=ruined.maxHp;delete ruined.destroyedAt;this.updateHousing(s)}else if(s.project==='Repair huts')wounded.hp=Math.min(wounded.maxHp,wounded.hp+45);else if(s.project==='Gardens')s.gardens++;else if(s.project==='Palisade'){s.maxDefense+=35;s.defense=Math.min(s.maxDefense,s.defense+35)}else if(s.project==='Repair defenses')s.defense=Math.min(s.maxDefense,s.defense+30);else if(s.project==='Great lodge'){s.level++;g.notify(s.name+' finishes lodge level '+s.level+'.','green')}else if(s.project==='Food stores')s.food+=16;s.radius=this.footprint(s)}}}
 // Each eight adults support a family; larger communities can raise several young at once.
 const parents=adults.length+(s.scouts||0),space=Math.min(s.housing,capacity)-s.population;
 const canRaise=parents>=4&&space>=1&&s.food>s.population*1.5&&s.safety>.7&&!s.attack;
 const population=g.population,cap=window.MAX_APE_POPULATION;
 if(population>=cap){s.birthTimer=Math.min(30,s.birthTimer);if(canRaise&&!s.capNotified){s.capNotified=true;g.notify('Population limit reached — '+cap.toLocaleString()+' apes. Families wait for space.')}}else{s.capNotified=false;if(canRaise)s.birthTimer+=parents/8}
 if(canRaise&&s.birthTimer>=30&&population<cap){const births=Math.min(Math.floor(s.birthTimer/30),Math.floor(space),cap-population,Math.floor((s.food-s.population*1.5)/6));for(let i=0;i<births;i++){const angle=(g.stats.born+i)*2.399;g.makeApe(s.x+Math.cos(angle)*25,s.y+Math.sin(angle)*25,'young',s.id,true)}if(births>0){s.birthTimer-=births*30;s.food-=births*6;g.stats.born+=births;g.sound('birth',.45,s.x);if(g.stats.born===births)g.notify('A new generation is born in '+s.name+'.','green')}}
 if(s.food<1){s.starveTimer++;if(s.starveTimer===15)g.notify(s.name+' needs food. Forage or deliver supplies.','red');if(s.starveTimer>40)for(const a of adults)g.hurt(a,.6,{x:s.x,y:s.y})}else{s.starveTimer=0;for(const a of adults)if(!s.attack)a.hp=Math.min(a.maxHp,a.hp+.16)}
 s.status=s.attack?'Under attack':s.constructionBlocked?'Need open ground':s.food<s.population?'Food shortage':s.population>=s.housing?'Crowded':s.safety<.5?'Recovering':s.foodDelta<0?'Drawing on stores':'Thriving';
 if(s.attack){const raiders=g.humanGrid.near(s.x,s.y,s.radius);s.food=Math.max(0,s.food-raiders.length*.18);s.defense=Math.max(0,s.defense-raiders.length*.15);if(g.time>s.nextWarn){s.nextWarn=g.time+25;g.notify('Distant roars — '+s.name+' is under attack!','red')}}
 if(s.known&&g.time-s.lastRaid>95&&Math.random()<.025){const base=[...g.world.sites.values()].filter(x=>!x.cleared&&x.strength>0&&Math.hypot(x.x-s.x,x.y-s.y)<3200).sort((a,b)=>Math.hypot(a.x-s.x,a.y-s.y)-Math.hypot(b.x-s.x,b.y-s.y))[0];if(base&&g.spawnRaid(base,s,true)){s.lastRaid=g.time;g.notify((s.scouts?'Scouts warn: a raid is approaching ':'Human forces march toward ')+s.name+'.','red')}}
 g.stats.largestSettlement=Math.max(g.stats.largestSettlement,s.population);
 }
 absorb(a,damage){const s=this.game.settlement(a.settlementId);if(!s||s.defense<=0||Math.hypot(a.x-s.x,a.y-s.y)>=s.radius)return damage;const absorbed=Math.min(s.defense,damage*.25);s.defense-=absorbed;return damage-absorbed}
}
window.ATSSettlements=Settlements;
})();
