/* Organic settlements: limited forage, housing, work priorities and defenses. */
(function(){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
class Settlements {
 constructor(game){this.game=game}
 evaluate(x,y){const w=this.game.world,t=w.terrain(x,y),objects=w.getObjects(x,y,390),trees=objects.filter(o=>o.type==='tree'&&!o.dead).length,berries=objects.filter(o=>o.type==='berry').length,region=w.districtAt(x,y);let water=false;for(let i=0;i<8;i++){const a=i*Math.PI/4;if(w.terrain(x+Math.cos(a)*210,y+Math.sin(a)*210).water)water=true}const risk=w.getSites(x,y,700).filter(s=>!s.cleared&&s.guards>0).length;return {fertility:region.fertility,wood:trees,berries,water,cover:clamp(trees/16,.1,1),capacity:Math.round(12+berries*5+(water?12:0)+region.fertility*10),risk,biome:t.biome,region:region.name}}
 init(s){if(s.economyVersion===2)return;s.economyVersion=2;s.policy=s.policy||'balanced';s.wood=s.wood??8;s.housing=Math.max(6,Math.ceil((s.population||5)/6)*6);s.gardens=s.gardens||0;s.defense=s.defense||0;s.maxDefense=s.maxDefense||0;s.buildProgress=0;s.safety=s.safety??1;s.suitability=this.evaluate(s.x,s.y);s.foodDelta=0;s.project='Shelters';s.status='Establishing camp';s.supplyTimer=0;s.investedLevel=s.level||1}
 action(id,action){const g=this.game,s=g.settlements.find(x=>x.id===id);if(!s)return false;this.init(s);if(['balanced','forage','fortify'].includes(action)){s.policy=action;g.notify(s.name+' prioritizes '+({balanced:'balanced growth',forage:'food security',fortify:'defense'}[action])+'.');return true}if(Math.hypot(g.king.x-s.x,g.king.y-s.y)>s.radius+110){g.notify('Visit this settlement to move supplies or recruit its apes.','red');return false}
 if(action==='supply'){const amount=Math.min(30,g.food);if(amount<1){g.notify('Gather berries or seize human supplies first.');return false}g.food-=amount;s.food+=amount;g.notify(Math.floor(amount)+' food delivered to '+s.name+'.','green');return true}
 if(action==='recruit'){for(const a of g.apes)if(a.settlementId===id&&a.state!=='young'&&a.hp>0){a.state='follow';a.settlementId=null}g.refreshSettlements();g.notify('The adults of '+s.name+' rally to your crown.');return true}return false}
 tick(s){const g=this.game;this.init(s);if(!s.population)return;s.age++;const adults=g.apes.filter(a=>a.hp>0&&a.settlementId===s.id&&a.state!=='young'&&a.state!=='scout');const policy=s.policy,forageRatio=policy==='forage'?.65:policy==='fortify'?.3:.45;const foragers=Math.max(adults.length?1:0,Math.floor(adults.length*forageRatio)),builders=Math.floor(adults.length*(policy==='fortify'?.45:.25));s.foragers=foragers;s.builders=builders;s.guards=Math.max(0,adults.length-foragers-builders);
 adults.forEach((a,i)=>{a.job=i<foragers?'forager':i<foragers+builders?'builder':'guardian'});
 s.attack=g.humans.some(h=>h.hp>0&&Math.hypot(h.x-s.x,h.y-s.y)<s.radius+120&&h.state!=='patrol');s.safety=clamp(s.safety+(s.attack?-.045:.007),0,1);
 const before=s.food,nodes=g.world.getObjects(s.x,s.y,s.radius*2.4).filter(o=>o.type==='berry');let available=0;for(const b of nodes){b.food=Math.min(b.count||30,(b.food||0)+.025*s.suitability.fertility);if(b.food>.5)b.dead=false;available+=b.food||0}
 const demand=foragers*.24*(s.attack?.25:1),harvest=Math.min(available,demand);let remaining=harvest;for(const b of nodes){const take=Math.min(remaining,b.food||0);b.food-=take;remaining-=take;if(b.food<=0)b.dead=true;if(remaining<=0)break}
 const gardenYield=s.gardens*.21*s.suitability.fertility*(s.suitability.water?1.15:1);s.food=Math.max(0,s.food+harvest+gardenYield-s.population*.06);s.food=Math.min(s.food,s.housing*10+80);s.foodDelta=s.food-before;s.wood+=builders*.065*Math.min(1,s.suitability.wood/12);s.wood=Math.min(s.wood,150+s.level*15);
 const populationGoal=Math.min(10,1+Math.floor(Math.sqrt(s.population)/1.7));s.project=s.housing<s.population+4?'Shelters':policy==='fortify'&&s.maxDefense<60+s.level*30?'Palisade':s.food<s.population*3&&s.gardens<Math.ceil(s.population/8)?'Gardens':s.level<populationGoal?'Great lodge':s.maxDefense>0&&s.defense<s.maxDefense?'Repair defenses':'Food stores';
 if(!s.attack&&builders&&s.wood>=6){s.buildProgress+=builders*.5;const cost={Shelters:25,Palisade:45,Gardens:35,'Great lodge':85,'Repair defenses':25,'Food stores':55}[s.project];if(s.buildProgress>=cost){s.buildProgress=0;s.wood-=s.project==='Great lodge'?Math.min(s.wood,18):6;if(s.project==='Shelters')s.housing+=6;else if(s.project==='Gardens')s.gardens++;else if(s.project==='Palisade'){s.maxDefense+=35;s.defense=Math.min(s.maxDefense,s.defense+35)}else if(s.project==='Repair defenses')s.defense=Math.min(s.maxDefense,s.defense+30);else if(s.project==='Great lodge'){s.level++;g.notify(s.name+' finishes lodge level '+s.level+'.','green')}else s.food+=8}}
 s.birthTimer+=(s.population>=4&&s.population<s.housing&&s.population<s.suitability.capacity+s.gardens*8&&s.food>s.population*2&&s.safety>.7&&!s.attack)?1:0;
 if(s.birthTimer>Math.max(35,110/(1+s.population/22))&&g.population<600){s.birthTimer=0;s.food=Math.max(0,s.food-8);g.makeApe(s.x+15,s.y+15,'young',s.id,true);g.stats.born++;g.sound('birth',.45,s.x);if(g.stats.born===1)g.notify('A new generation is born in '+s.name+'.','green')}
 if(s.food<1){s.starveTimer++;if(s.starveTimer===15)g.notify(s.name+' needs food. Forage or deliver supplies.','red');if(s.starveTimer>40)for(const a of adults)g.hurt(a,.6,{x:s.x,y:s.y})}else{s.starveTimer=0;for(const a of adults)if(!s.attack)a.hp=Math.min(a.maxHp,a.hp+.16)}
 s.status=s.attack?'Under attack':s.food<s.population?'Food shortage':s.population>=s.housing?'Crowded':s.safety<.5?'Recovering':s.foodDelta<0?'Drawing on stores':'Thriving';
 if(s.attack){const raiders=g.humans.filter(h=>h.hp>0&&Math.hypot(h.x-s.x,h.y-s.y)<s.radius);s.food=Math.max(0,s.food-raiders.length*.18);s.defense=Math.max(0,s.defense-raiders.length*.15);if(g.time>s.nextWarn){s.nextWarn=g.time+25;g.notify('Distant roars — '+s.name+' is under attack!','red')}}
 if(s.known&&g.time-s.lastRaid>95&&Math.random()<.025){const base=[...g.world.sites.values()].filter(x=>!x.cleared&&x.strength>0&&Math.hypot(x.x-s.x,x.y-s.y)<3200).sort((a,b)=>Math.hypot(a.x-s.x,a.y-s.y)-Math.hypot(b.x-s.x,b.y-s.y))[0];if(base&&g.spawnRaid(base,s,true)){s.lastRaid=g.time;g.notify((s.scouts?'Scouts warn: a raid is approaching ':'Human forces march toward ')+s.name+'.','red')}}
 g.stats.largestSettlement=Math.max(g.stats.largestSettlement,s.population);
 }
 absorb(a,damage){const s=this.game.settlements.find(s=>s.id===a.settlementId&&s.defense>0&&Math.hypot(a.x-s.x,a.y-s.y)<s.radius);if(!s)return damage;const absorbed=Math.min(s.defense,damage*.25);s.defense-=absorbed;return damage-absorbed}
}
window.ATSSettlements=Settlements;
})();
