/* Small desktop hotkey pictures; touch keeps comfortably sized hit targets. */
(() => {
'use strict';
const COMMANDS=[['call','q','Call / follow'],['charge','','Directional charge'],['nearestTarget','e','Nearest target · hold E for humans'],['nearestHuman','','Attack nearest humans'],['recall','r','Retreat / regroup'],['hold','f','Hold position'],['spreadCharge','x','Spread charge'],['attackNearest','t','Defend against nearest enemies'],['target','g','Target / route'],['finish','p','Finish with attack · right-click a final point'],['unit','i','Pick individual apes'],['shield','h','Shield advance'],['sabotage','j','Sabotage'],['climb','k','Climb wall'],['rally','l','Rally Roar'],['logs','u','Prepare log shields'],['regroup','y','Regroup here'],['defend','n','Defend position'],['settle','z','Found settlement'],['patrol','c','Settlement scouts'],['finder','v','Find settlements'],['build','b','Village buildings']];
const COLORS={gorilla:'#9ca9a8',orangutan:'#c88a58',chimpanzee:'#b4b48e',gibbon:'#ddd4ac',capuchin:'#c5aa79',mandrill:'#89b8c3'};
function icon(canvas,kind){const c=canvas.getContext('2d');canvas.width=40;canvas.height=40;c.scale(2,2);c.strokeStyle='#dedbb5';c.fillStyle='#dedbb5';c.lineWidth=1.5;c.lineCap='round';c.lineJoin='round';const line=(...p)=>{c.beginPath();c.moveTo(p[0],p[1]);for(let i=2;i<p.length;i+=2)c.lineTo(p[i],p[i+1]);c.stroke()},circle=(x,y,r)=>{c.beginPath();c.arc(x,y,r,0,7);c.stroke()};
 if(['charge','target','regroup','recall'].includes(kind)){const back=kind==='recall';c.save();if(back){c.translate(20,0);c.scale(-1,1)}line(3,10,17,10,12,5);line(17,10,12,15);if(kind==='target'){circle(10,10,7)}c.restore()}
 else if(kind==='hold'){line(6,4,6,16);line(14,4,14,16)}
 else if(kind==='shield'||kind==='logs'){line(4,4,10,2,16,4,15,12,10,17,5,12,4,4);if(kind==='logs')line(6,8,14,8);else line(10,14,10,6,7,9)}
 else if(kind==='climb'){line(5,2,5,18);line(15,2,15,18);for(let y=5;y<18;y+=4)line(5,y,15,y)}
 else if(kind==='sabotage'){circle(7,7,4);line(10,10,17,17);line(4,3,7,7,3,5)}
 else if(kind==='spreadCharge'||kind==='attackNearest'||kind==='nearestTarget'||kind==='nearestHuman'){line(10,16,10,4,7,7);line(10,4,13,7);line(9,12,3,6,3,10);line(11,12,17,6,17,10)}
 else if(kind==='call'||kind==='rally'){circle(6,10,3);line(9,8,13,5,13,15,9,12);c.beginPath();c.arc(11,10,7,-.7,.7);c.stroke();if(kind==='rally')line(4,3,6,1,8,3)}
 else if(kind==='settle'||kind==='build'||kind==='finder'){line(3,9,10,3,17,9);line(5,8,5,17,15,17,15,8);line(9,17,9,12,12,12,12,17);if(kind==='finder')circle(10,10,9)}
 else if(kind==='patrol'){circle(7,8,4);circle(14,8,4);line(5,12,4,16);line(16,12,17,16)}
 else if(kind==='defend'||kind==='finish'){circle(10,10,7);line(10,1,10,5);line(10,15,10,19);line(1,10,5,10);line(15,10,19,10)}
 else if(kind==='go'){line(5,3,16,10,5,17,5,3)}
 else if(kind==='undo'){line(8,5,3,9,8,13);line(3,9,12,9,16,14)}
 else if(kind==='clear'){line(5,5,15,15);line(15,5,5,15)}
 else if(kind==='append'){line(4,10,16,10);line(10,4,10,16)}
 else if(kind==='retry'){c.beginPath();c.arc(10,10,7,.2,5.2);c.stroke();line(12,2,15,4,12,6)}
 else if(kind==='skip'){line(4,4,12,10,4,16,4,4);line(15,4,15,16)}
 else if(kind==='unit'){circle(10,6,4);line(4,17,4,14,10,11,16,14,16,17)}
 else if(kind==='all'){for(const x of[5,10,15])circle(x,8,2);line(3,15,17,15)}
}
class ArmyUI{
 constructor({getGame,getScreen,renderer,command,find,build,resetInput=()=>{}}){this.getGame=getGame;this.getScreen=getScreen;this.renderer=renderer;this.command=command;this.find=find;this.build=build;this.resetInput=resetInput;this.mode=null;this.pointer=null;this.touches=new Map();this.pinch=null;this.signature='';
  const style=document.createElement('style');style.textContent=`
  #armyDock{position:absolute;bottom:12px;left:50%;transform:translateX(-50%);z-index:6;max-width:calc(100vw - 36px);display:flex;flex-direction:column;align-items:center;gap:5px;pointer-events:auto}
  #armyDock .army-row{display:flex;gap:3px;justify-content:center;align-items:center;flex-wrap:wrap;max-width:100%;padding:4px;background:rgba(5,22,26,.94);border:1px solid #38574e;border-radius:6px}
  #armyDock button{position:relative;display:flex;align-items:center;justify-content:center;width:30px;height:34px;min-height:0;padding:2px;border-radius:3px;border:1px solid transparent;background:#183730;color:#e8ddb0;letter-spacing:0}
  #armyDock button:hover,#armyDock button:focus-visible{border-color:#d5c183;background:#2c4c3a}#armyDock button[aria-pressed=true]{background:#4a6244;border-color:#d8cb8b}#armyDock button:disabled{opacity:.35}#armyDock canvas{width:20px;height:20px;pointer-events:none;margin-top:-5px}#armyDock kbd{position:absolute;bottom:1px;right:3px;font:8px/1 system-ui;color:#d2cdae;pointer-events:none}#armyDock .army-count{position:absolute;top:1px;right:2px;font:8px/1 system-ui;color:#f4dea2;pointer-events:none}#armyDock .species-button{width:36px;height:38px}#armyDock .species-button canvas{width:30px;height:29px}
  #armyDock .army-route-steps{display:flex;gap:3px;flex-wrap:wrap;justify-content:center}#armyDock button[hidden]{display:none}#armyDock button.army-cancel{width:58px}#armyDock .army-cancel canvas{width:15px;height:15px}#armyDock .army-cancel .cancel-label{font:9px system-ui;margin-top:-5px}#armyDock .army-step{width:26px;height:26px;font-size:10px}#armyDock .army-step.active{border-color:#bdd098}#armyDock .army-step.blocked{border-color:#ee9479}#armyDock .army-step.draft{border-style:dashed;border-color:#8eab86}#armyDock .army-step span{font:10px/1 system-ui}#armyDock .army-route[hidden]{display:none}#armyDock .army-presets{position:absolute;left:0;bottom:50px;display:none}#armyDock.expanded .army-presets{display:flex}.command-wrap{display:none!important}
  #armyStatus{position:absolute;width:1px;height:1px;clip-path:inset(50%);overflow:hidden}#armyInspect{display:none;position:absolute;bottom:100%;left:50%;transform:translateX(-50%);padding:7px 10px;margin-bottom:6px;white-space:nowrap;background:#122c2a;border:1px solid #657756;border-radius:4px;font:11px/1.4 system-ui;color:#e4d9b2;pointer-events:none}#armyDock:focus-within #armyInspect[data-open],#armyInspect[data-open]{display:block}
  @media(pointer:fine) and (min-width:801px){.command-wrap{display:none!important}.hud-bottom{bottom:20px}#armyDock{max-width:calc(100vw - 380px)}}
  @media(pointer:coarse),(max-width:800px){#armyDock{bottom:8px;max-width:calc(100vw - 16px);width:100%}#armyDock button{width:42px;height:44px}#armyDock .species-button{width:42px;height:44px}#armyDock .army-row{padding:2px;gap:2px}#armyDock .army-commands{max-width:330px;display:none}#armyDock.expanded .army-commands{display:flex}#armyDock .army-route{max-width:330px}#armyDock .army-step{width:40px;height:44px}#armyDock kbd{display:none}#armyDock .army-count{font-size:10px}.hud-bottom{bottom:auto!important;top:100px;left:12px!important}.exposure-panel{width:130px}.exposure-title{font-size:7px}#armyDock .army-presets{position:static}#armyDock.expanded{bottom:8px}#armyDock .army-mobile{display:flex}.command-wrap{bottom:62px!important}#joystick{bottom:130px}#attackButton{bottom:134px}}
  @media(pointer:fine) and (min-width:801px){#armyDock .army-mobile{display:none}}
  `;document.head.append(style);this.root=document.createElement('div');this.root.id='armyDock';this.root.setAttribute('aria-label','Army species and commands');document.getElementById('hud').append(this.root);
  this.speciesRow=this.row('army-species');this.routeRow=this.row('army-route');this.commands=this.row('army-commands');this.status=document.createElement('div');this.status.id='armyStatus';this.status.setAttribute('role','status');this.status.setAttribute('aria-live','polite');this.root.append(this.status);this.inspect=document.createElement('div');this.inspect.id='armyInspect';this.root.append(this.inspect);
  this.speciesButtons={};ATSSiegeSpecies.forEach((s,i)=>{const b=this.button(this.speciesRow,s,String(i+1),s[0].toUpperCase()+s.slice(1),e=>this.select(s,e.shiftKey));b.classList.add('species-button');b.dataset.species=s;const count=document.createElement('span');count.className='army-count';b.append(count);this.speciesButtons[s]=b;const canvas=b.querySelector('canvas');canvas.width=60;canvas.height=58;const c=canvas.getContext('2d');c.translate(30,51);c.scale(.67,.67);renderer.drawApeMini(c,0,0,1,{id:'button-'+s,species:s,coatVariant:1,hp:100,maxHp:100,age:200,state:'follow'});});
  this.presetsRow=this.row('army-presets');for(let i=0;i<4;i++){let held=false,timer;const b=this.button(this.presetsRow,'all','^'+(i+1),'Group '+(i+1)+' · tap to recall, Shift-click or hold to save',e=>{if(held){held=false;return}const s=this.siege;if(e.shiftKey||!s.presets[i]?.length)s.presets[i]=s.selected.slice();else{s.select(s.presets[i]);this.mode='route'}this.update(true)});b.dataset.preset=String(i);b.querySelector('canvas').remove();const label=document.createElement('span');label.textContent=String.fromCharCode(65+i);b.prepend(label);b.addEventListener('pointerdown',()=>{held=false;timer=setTimeout(()=>{if(this.siege){this.siege.presets[i]=this.siege.selected.slice();held=true;this.update(true)}},650)});for(const event of ['pointerup','pointercancel','pointerleave'])b.addEventListener(event,()=>clearTimeout(timer));}
  this.button(this.speciesRow,'all','0','All followers',()=>{this.siege.select(ATSSiegeSpecies);this.mode='route';this.update(true)});
  const expand=this.button(this.speciesRow,'target','','Army commands',()=>this.root.classList.toggle('expanded'));expand.classList.add('army-expand');
  for(const [cmd,key,label]of COMMANDS)this.button(this.commands,cmd,key,label,()=>this.action(cmd));
  this.routeSteps=document.createElement('div');this.routeSteps.className='army-route-steps';this.routeRow.append(this.routeSteps);
  this.routeButtons={};for(const [kind,key,label,fn]of[
   ['go','↵','Go: replace remaining orders',()=>this.siege.dispatch(false)],
   ['append','⇧↵','Append after running orders',()=>this.siege.dispatch(true)],
   ['undo','⌫','Undo draft waypoint',()=>{for(const id of this.siege.selected)this.siege.drafts[id]?.pop()}],
   ['clear','O','Cancel planning and return to King; issued orders continue',()=>this.cancelPlanning()],
   ['retry','','Retry blocked route',()=>this.siege.retry()],['skip','','Skip blocked step',()=>this.siege.skip()]])this.routeButtons[kind]=this.button(this.routeRow,kind,key,label,fn);
  const cancel=this.routeButtons.clear;cancel.classList.add('army-cancel');const label=document.createElement('span');label.className='cancel-label';label.textContent='Cancel';cancel.append(label);
  this.root.addEventListener('pointerdown',e=>{this.cancel();this.resetInput();e.stopPropagation()});this.update(true);
 }
 get siege(){return this.getGame()?.siege}
 row(cls){const row=document.createElement('div');row.className='army-row '+cls;this.root.append(row);return row}
 button(parent,kind,key,label,fn){const b=document.createElement('button');b.type='button';b.dataset.armyCommand=kind;b.setAttribute('aria-label',label+(key?' ('+key.toUpperCase()+')':''));b.title=label+(key?' ['+key.toUpperCase()+']':'');const picture=document.createElement('canvas');picture.setAttribute('aria-hidden','true');icon(picture,kind);const k=document.createElement('kbd');k.textContent=key.toUpperCase();b.append(picture,k);b.addEventListener('click',e=>{if(this.getScreen()==='play'&&this.siege){fn(e);this.update(true)}});b.addEventListener('mouseenter',()=>this.hint(b.title));b.addEventListener('focus',()=>this.hint(b.title));b.addEventListener('mouseleave',()=>this.hint(''));b.addEventListener('blur',()=>this.hint(''));parent.append(b);return b}
 hint(text){this.inspect.textContent=text;if(text)this.inspect.setAttribute('data-open','');else this.inspect.removeAttribute('data-open')}
 select(s,add=false){if(!this.siege)return;this.renderer.camera.armyFocus=null;const selected=this.siege.selected;if(add&&selected.includes(s))this.siege.selected=selected.filter(x=>x!==s);else if(!add&&selected.length===1&&selected[0]===s)this.siege.select([]);else this.siege.select(s,add);this.mode=this.siege.selected.length?'route':null;this.update(true)}
 action(cmd){const g=this.getGame(),s=g?.siege;if(!s)return;this.hint('');if(cmd==='finder'){this.find();return}if(cmd==='build'){this.build();return}
  if(['target','sabotage','climb','shield','defend','regroup','unit','finish'].includes(cmd)){if(!s.selected.length)s.select(ATSSiegeSpecies);this.mode=cmd==='target'?'route':cmd;this.root.classList.remove('expanded');return}
  if(cmd==='rally'){s.rally();return}if(cmd==='logs'){s.prepareShields();return}
  this.command(cmd);if(cmd==='charge'||cmd==='spreadCharge')this.root.classList.remove('expanded');
 }
 key(e){const s=this.siege;if(!s||this.getScreen()!=='play')return false;const k=/^Digit[0-6]$/.test(e.code)?e.code.slice(-1):e.key.toLowerCase();
  if(e.ctrlKey&&!e.metaKey&&/^[1-4]$/.test(k)){if(e.repeat){e.preventDefault();return true}e.preventDefault();const i=Number(k)-1;if(e.shiftKey)s.presets[i]=s.selected.slice();else{s.select(s.presets[i]||[]);this.mode=s.selected.length?'route':null}this.update(true);return true}
  if(e.ctrlKey||e.metaKey||e.altKey)return false;
  const handled=/^[0-6]$/.test(k)||['o','enter','backspace','delete'].includes(k)||COMMANDS.some(c=>c[1]===k);if(e.repeat&&handled){e.preventDefault();return true}
  if(/^[0-6]$/.test(k)){e.preventDefault();if(k==='0'){s.select(ATSSiegeSpecies);this.mode='route'}else this.select(ATSSiegeSpecies[Number(k)-1],e.shiftKey);this.update(true);return true}
  if(k==='o'){e.preventDefault();this.cancelPlanning();this.update(true);return true}
  if(k==='enter'&&s.selected.length){e.preventDefault();s.dispatch(e.shiftKey);this.update(true);return true}
  if(k==='backspace'&&s.selected.length){e.preventDefault();for(const id of s.selected)s.drafts[id]?.pop();this.update(true);return true}
  if(k==='delete'&&s.selected.length){e.preventDefault();for(const id of s.selected)s.drafts[id]=[];this.update(true);return true}
  const c=COMMANDS.find(c=>c[1]===k);if(c&&!e.repeat){e.preventDefault();this.action(c[0]==='settle'&&e.shiftKey?'settleAll':c[0]);this.update(true);return true}return false;
 }
 down(e){if(e.button!=null&&e.button!==0&&e.button!==2)return false;if(e.button===2&&!this.siege?.selected.length)return false;if(e.altKey){this.mode='unit';if(!this.siege?.selected.length)this.siege.select(ATSSiegeSpecies)}if(!this.siege?.selected.length)return false;this.touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.touches.size===2){const [a,b]=[...this.touches.values()];this.pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:this.renderer.camera.zoom};this.pointer=null;return true}if(this.touches.size>1){this.pointer=null;return true}this.pointer={id:e.pointerId,finish:e.button===2,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY};return true}
 move(e){if(!this.touches.has(e.pointerId))return false;this.touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pinch&&this.touches.size>=2){const [a,b]=[...this.touches.values()];this.renderer.camera.zoom=Math.max(.38,Math.min(1.65,this.pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,this.pinch.distance)));return true}const p=this.pointer;if(!p||p.id!==e.pointerId)return true;if(p.drag||Math.hypot(e.clientX-p.x,e.clientY-p.y)>8)p.drag=true;if(p.drag){const old=this.renderer.unproject(p.lastX,p.lastY),next=this.renderer.unproject(e.clientX,e.clientY),cam=this.renderer.camera,king=this.getGame().king;cam.x+=old.x-next.x;cam.y+=old.y-next.y;const d=Math.hypot(cam.x-king.x,cam.y-king.y);if(d>700){cam.x=king.x+(cam.x-king.x)*700/d;cam.y=king.y+(cam.y-king.y)*700/d}cam.armyFocus={x:cam.x,y:cam.y}}p.lastX=e.clientX;p.lastY=e.clientY;return true}

 up(e){this.touches.delete(e.pointerId);if(this.pinch){if(!this.touches.size)this.pinch=null;this.pointer=null;return true}if(!this.pointer||e.pointerId!==this.pointer.id)return false;const p=this.pointer;this.pointer=null;const rect=this.renderer.canvas.getBoundingClientRect();if(p.drag||e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom||document.elementFromPoint(e.clientX,e.clientY)!==this.renderer.canvas||Math.hypot(e.clientX-p.x,e.clientY-p.y)>8)return true;if(p.finish||this.mode==='finish'){this.finishAt(this.renderer.unproject(e.clientX,e.clientY));return true}const s=this.siege,target=['route','sabotage','climb'].includes(this.mode)?this.targetAt(e.clientX,e.clientY):this.renderer.unproject(e.clientX,e.clientY);if(this.mode==='unit'){const candidates=this.getGame().apes.filter(a=>s.eligible(a)).map(a=>({a,p:this.renderer.project(a.x,a.y,(a.elevation||0)+22)})).sort((a,b)=>Math.hypot(a.p.x-e.clientX,a.p.y-e.clientY)-Math.hypot(b.p.x-e.clientX,b.p.y-e.clientY));const pick=candidates[0];if(pick&&Math.hypot(pick.p.x-e.clientX,pick.p.y-e.clientY)<40){s.selectUnits([pick.a.id],e.shiftKey);this.mode='route'}this.update(true);return true}s.draft(target,this.mode==='route'?undefined:this.mode);this.update(true);return true}
 finishAt(point){const s=this.siege;if(!s?.selected.length)return;for(const id of s.selected){const draft=s.drafts[id]||[];s.drafts[id]=draft.filter(o=>o.type!=='attackArea')}if(s.draft(point,'attackArea'))s.dispatch(false);this.mode='route';this.update(true)}
 cancelPlanning(){const s=this.siege;if(s){for(const id of s.selected)s.drafts[id]=[];s.select([]);s.status=''}this.mode=null;this.cancel();this.resetInput();this.renderer.camera.armyFocus=null;this.root.classList.remove('expanded');this.hint('')}
 cancel(){this.pointer=null;this.touches.clear();this.pinch=null}
 targetAt(x,y){const g=this.getGame(),s=this.siege,p=this.renderer.unproject(x,y),zoom=this.renderer.camera.zoom,choices=[];
  for(const o of g.world.getObjects(p.x,p.y,220)){if(o.dead||!o.hp||!s.known(o)||['tree','rock','berry','stairs'].includes(o.type))continue;const q=this.renderer.project(o.x,o.y,o.type==='gateControl'?22:(o.visualHeight||o.height||30)*.55),radius=o.type==='gateControl'?Math.max(13,22*zoom):Math.max(15,Math.min(65,((o.w||o.r*2||24)+(o.h||o.r*2||24))*.3*zoom)),d=Math.hypot(x-q.x,y-q.y);if(d<radius)choices.push({o,score:d/radius+(o.type==='gateControl'?-.4:0)})}
  for(const h of g.humanGrid.near(p.x,p.y,220)){if(h.hp<=0)continue;const q=this.renderer.project(h.x,h.y,(h.elevation||0)+25),d=Math.hypot(x-q.x,y-q.y);if(d<Math.max(13,20*zoom)&&s.visibleTarget(h))choices.push({o:h,score:d/20-.2})}choices.sort((a,b)=>a.score-b.score);return choices.length?{x:choices[0].o.x,y:choices[0].o.y}:p;
 }
 update(force=false){const s=this.siege;if(!s)return;const counts={};for(const a of this.getGame().apes)if(s.eligible(a))counts[a.species]=(counts[a.species]||0)+1;
  for(const [id,b]of Object.entries(this.speciesButtons)){b.querySelector('.army-count').textContent=counts[id]||0;b.setAttribute('aria-pressed',String(s.selected.includes(id)));b.title=id+' · '+(counts[id]||0)+' · '+s.statusOf(id)}
  this.root.querySelector('[data-army-command=rally]').disabled=!s.selected.includes('mandrill')||this.getGame().time<s.rallyReady;this.routeRow.hidden=!s.selected.length;const active=s.selected[0],group=s.groups[active],draft=s.drafts[active]||[],signature=JSON.stringify([s.selected,group?.orders,group?.blocked,draft,this.mode,s.status]);if(!force&&signature===this.signature)return;this.signature=signature;this.routeSteps.replaceChildren();
  const orders=[...(group?.orders||[]),...draft];orders.forEach((o,i)=>{const b=document.createElement('button');b.type='button';b.className='army-step '+(i>=(group?.orders.length||0)?'draft':group?.blocked?'blocked':'active');b.innerHTML='<span>'+String(i+1)+'</span>';b.title=o.type+(o.targetId?' · target':'')+(i>=(group?.orders.length||0)?' · click to remove draft':' · running');b.setAttribute('aria-label',b.title);b.addEventListener('click',()=>{if(i>=(group?.orders.length||0))for(const id of s.selected)s.drafts[id]?.splice(i-(s.groups[id]?.orders.length||0),1);this.update(true)});this.routeSteps.append(b)});
  const hasDraft=s.selected.some(id=>s.drafts[id]?.length);this.routeButtons.go.disabled=this.routeButtons.append.disabled=this.routeButtons.undo.disabled=!hasDraft;this.routeButtons.retry.hidden=this.routeButtons.skip.hidden=!group?.blocked;
  const msg=s.status||(group?.blocked?'Order blocked: '+group.blocked:'');if(this.status.textContent!==msg)this.status.textContent=msg;
  this.root.querySelector('[data-army-command=rally]').disabled=!s.selected.includes('mandrill')||this.getGame().time<s.rallyReady;
 }
}
window.ATSArmyUI=ArmyUI;
})();
