(() => {
'use strict';
const P=ATSRenderer.prototype,baseApe=P.drawApe,baseSprite=P.drawApeSprite,baseHuman=P.drawHuman,baseHumanSprite=P.drawHumanSprite,baseObject=P.drawObject,baseGate=P.drawGate,baseWall=P.drawWall;
const line=(c,x,y,u,v,color,width=1)=>{c.beginPath();c.moveTo(x,y);c.lineTo(u,v);c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.stroke()},poly=(c,points,fill,stroke)=>{c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.lineWidth=1;c.stroke()}},ellipse=(c,x,y,w,h,color)=>{c.beginPath();c.ellipse(x,y,w,h,0,0,Math.PI*2);c.fillStyle=color;c.fill()};
P.siegeApeDetails=function(c,a){
 if(a.shield?.hp>0){const ratio=a.shield.hp/a.shield.maxHp,flip=Math.cos(a.dir||0)<0?-1:1;c.save();c.scale(flip,1);c.translate(10,-24);line(c,-18,-6,20,5,'#57432d',14);line(c,-18,-9,20,2,'#a18a55',5);ellipse(c,20,5,6,8,'#c7af77');ellipse(c,20,5,3,5,'#7a623b');line(c,-12,-5,13,1,'#d0ac69',1);if(ratio<.65){line(c,-5,-10,-8,-3,'#312b24',2);line(c,-8,-3,1,1,'#312b24',2)}if(ratio<.3){line(c,10,-4,7,4,'#2c241e',3);line(c,7,4,14,9,'#2c241e',2)}c.restore()}
 if(a.rallyUntil>this.time){c.save();c.strokeStyle='#e5c484';c.lineWidth=1.5;c.beginPath();c.ellipse(0,5,19,7,0,0,Math.PI*2);c.stroke();c.restore()}
};
P.drawApe=function(c,a,king,exposure){c.save();if(a.siegeTransition&&!a.onWallId)c.translate(0,-(a.elevation||0));baseApe.call(this,c,a,king,exposure);if(!king){if(a.onWallId)c.translate(0,-(a.elevation||0));this.siegeApeDetails(c,a)}c.restore()};
P.drawApeSprite=function(c,a){if(a.siegeTransition||a.elevation||a.rallyCast)return this.drawApe(c,a,false);const result=baseSprite.call(this,c,a);if(result!==false)this.siegeApeDetails(c,a);return result};
P.drawHuman=function(c,h){c.save();c.translate(0,-(h.elevation||0));baseHuman.call(this,c,h);c.restore()};
P.drawHumanSprite=function(c,h){if(h.elevation||h.siegeTransition)return this.drawHuman(c,h);return baseHumanSprite.call(this,c,h)};
P.drawGate=function(c,o){if(o.gateState!=='open'&&!o.forcedOpen)return baseGate.call(this,c,o);const hw=(o.w||143)/2,h=o.visualHeight||70,opening=this.reducedMotion?1:Math.min(1,Math.max(0,(this.time-(o.openedAt||0))*2));
 for(const side of[-1,1]){const x=side*hw*.8,y=side*hw*.42;line(c,x,y,x,y-h,'#8c9c91',8);line(c,x,y-h,x+side*(20+opening*30),y-h+15,'#748a80',6);line(c,x+side*(20+opening*30),y-h+15,x+side*(20+opening*30),y+15,'#516b63',5)}
};
P.drawWall=function(c,o){baseWall.call(this,c,o);if(o.dead||!o.walkable)return;const z=o.walkHeight||o.visualHeight||70,hw=(o.w||30)/2,hh=(o.h||30)/2,pt=(x,y)=>[(x-y)*.8,(x+y)*.42-z];poly(c,[pt(-hw,-hh),pt(hw,-hh),pt(hw,hh),pt(-hw,hh)],'#687e77','#a0afa0');if(o.climbAccess){const side=(o.w||0)<(o.h||0)?1:-1;for(let i=0;i<3;i++){const x=(i-1)*7;line(c,x,0,x+side*5,-z,'#769368',2);for(let j=15;j<z;j+=18)line(c,x,-j,x+6,-j-6,'#95b777',2)}}};
P.drawObject=function(c,o){if(o.type==='gate'&&(o.gateState==='open'||o.forcedOpen)){this.drawGate(c,o);return}if(o.type==='gateControl'){if(!o.discovered)return;if(o.dead){poly(c,[[-14,0],[0,-8],[15,0],[0,7]],'#6b6550');line(c,-8,-3,8,3,'#b6a273',3);return}poly(c,[[-13,-4],[-13,-27],[12,-22],[12,3]],'#5d7065','#a1ae8f');ellipse(c,0,-22,11,10,'#a8a886');ellipse(c,0,-22,5,5,'#445850');line(c,-12,-25,14,-17,'#c5b585',3);line(c,14,-17,14,-10,'#c5b585',3);if(o.hp<o.maxHp)this.health(c,o.hp/o.maxHp,-42,27,'#d9bd83');return}
 if(o.type==='stairs'){if(o.dead)return;const dx=(o.topX-o.x),dy=(o.topY-o.y),height=o.height||70,steps=9;for(let i=0;i<steps;i++){const f=i/steps,next=(i+1)/steps,side=12,ax=(dx*f-dy*f)*.8,ay=(dx*f+dy*f)*.42-height*f,bx=(dx*next-dy*next)*.8,by=(dx*next+dy*next)*.42-height*next;poly(c,[[ax-side,ay],[ax+side,ay+5],[bx+side,by+5],[bx-side,by]],i%2?'#6b7d75':'#84938a','#415952')}return}baseObject.call(this,c,o)};
P.drawSiege=function(game){const siege=game.siege;if(!siege)return;const c=this.ctx,z=this.camera.zoom;
 for(const b of siege.stones){const p=this.project(b.x,b.y,b.z||b.z0);if(this.visible(p,20)){ellipse(c,p.x,p.y,3*z,2.3*z,'#d8c49c');const ground=this.project(b.x,b.y);ellipse(c,ground.x,ground.y,2*z,z,'rgba(5,12,10,.4)')}}
 if(!siege.selected.length)return;c.save();
 for(const a of siege.selectedMembers()){const p=this.project(a.x,a.y,a.elevation||a.wallClimbHeight||0);if(!this.visible(p,35))continue;c.beginPath();c.ellipse(p.x,p.y+4*z,19*z,7*z,0,0,Math.PI*2);c.strokeStyle='#d6dba1';c.lineWidth=1;c.stroke()}
 const seen=new Set();for(const species of siege.selected){const group=siege.groups[species],orders=[...(group?.orders||[]),...(siege.drafts[species]||[])],members=siege.members([species]);if(!orders.length||!members.length)continue;let prev=this.project(members[0].x,members[0].y);orders.forEach((o,i)=>{const key=o.id+':'+i;if(seen.has(key))return;seen.add(key);const p=this.project(o.x,o.y);c.setLineDash([4,5]);line(c,prev.x,prev.y,p.x,p.y,group?.blocked?'#e4a875':'#d7ce92',1.4);c.setLineDash([]);if(this.visible(p,24)){c.beginPath();c.arc(p.x,p.y,12,0,Math.PI*2);c.fillStyle='#102b2a';c.fill();c.strokeStyle=['attack','sabotage','assault'].includes(o.type)?'#e6a279':'#d7ce92';c.lineWidth=2;c.stroke();c.font='700 10px system-ui';c.textAlign='center';c.fillStyle='#f3e5b8';c.fillText(String(i+1),p.x,p.y+3)}prev=p})}
 for(const o of game.world.getObjects(game.king.x,game.king.y,game.viewRadius||900)){if(o.dead||!siege.known(o)||!o.climbAccess&&o.type!=='gateControl')continue;const p=this.project(o.x,o.y,(o.visualHeight||o.height||20)+10);if(!this.visible(p,20))continue;if(o.climbAccess){line(c,p.x-5,p.y+7,p.x-5,p.y-7,'#b4d58d',1.5);line(c,p.x+5,p.y+7,p.x+5,p.y-7,'#b4d58d',1.5);for(let y=-5;y<=5;y+=5)line(c,p.x-5,p.y+y,p.x+5,p.y+y,'#b4d58d',1)}else{c.beginPath();c.arc(p.x,p.y,6,0,Math.PI*2);c.strokeStyle='#e2c384';c.stroke();line(c,p.x-3,p.y,p.x+3,p.y,'#e2c384',2)}}
 c.restore();};
})();
