import test from 'node:test';
import assert from 'node:assert/strict';
import {RULES,Maze,makeMaze,runKey,fresh,living,trapWindow,placementError,chooseSpawn,stepEnemies,distance,LatestWriter,hazardAt,remotePosition,energy} from '../game/stoney-relic/core.mjs';
const state=(seed=42)=>({seed,w:21,h:21,cellSize:4,runId:'round-1',phase:'play',startAt:1000,endAt:301000,crown:null,carrierId:null,dmEnergyBase:50,dmEnergyStamp:1000});
const player=(point,now=5000,more={})=>({...point,uid:'p',name:'Runner',role:'player',ready:true,runId:'round-1',alive:true,deadUntil:0,updatedAt:now,...more});
const trap=(point,more={})=>({...point,type:'demon',placedAt:1000,ttlMs:300000,runId:'round-1',...more});
test('seeded maze stays deterministic and all cells are reachable',()=>{
  for(let seed=0;seed<50;seed++){
    const m=new Maze(state(seed));assert.deepEqual(makeMaze(21,21,seed),makeMaze(21,21,seed));
    assert.equal([...m.distances(m.entry)].filter(x=>x>=0).length,441);
    assert.equal(m.graph.reduce((n,x)=>n+x.length,0),880);
  }
});
test('every pathfinding edge is physically traversable; no wall tunnelling',()=>{
  const m=new Maze(state());
  for(let i=0;i<m.cells.length;i++)for(const j of m.graph[i])assert.equal(m.clear(m.center(i),m.center(j),.34),true);
  let checked=0;
  for(let i=0;i<m.cells.length;i++)if(i%21<20&&!m.graph[i].includes(i+1)){
    const a=m.center(i),b=m.center(i+1);assert.equal(m.clear(a,b),false);
    assert.ok(distance(m.move(a,b.x-a.x,b.z-a.z),b)>.5);checked++;
  }
  assert.ok(checked>100);
});
test('entrance remains open but room and maze outer walls constrain players',()=>{
  const m=new Maze(state()),a=m.spawn('p'),b=m.center(m.entry);
  assert.ok(m.clear(a,b,.34));assert.ok(m.inRoom(a));assert.ok(!m.inRoom(b));
  assert.ok(m.blocked(999,999));assert.ok(m.blocked(NaN,0));
  assert.equal(m.move(a,0,100).z<m.maxZ+9,true);
});
test('setup traps never arm or expire before the actual early/late Ready event',()=>{
  const t=trap({x:0,z:0},{ttlMs:10000,placedAt:2000});
  assert.deepEqual(trapWindow(t,{...state(),phase:'setup',startAt:null,setupDeadline:32000}),{armedAt:Infinity,expiresAt:Infinity});
  assert.deepEqual(trapWindow(t,{...state(),startAt:9000}),{armedAt:9000,expiresAt:19000});
  assert.deepEqual(trapWindow({...t,armedAt:14200},{...state(),startAt:9000}),{armedAt:14200,expiresAt:24200});
});
test('presence excludes dead, stale, wrong-round and explicitly disconnected players',()=>{
  const p=player({x:0,z:0});assert.ok(living(p,5000,state()));
  for(const change of [{alive:false},{updatedAt:1},{online:false},{runId:'old'}])assert.equal(living({...p,...change},20000,state()),false);
  assert.equal(fresh({...p,serverAt:{seconds:20,nanoseconds:0}},20001),true);
});
test('spawn director respects living players, crown, entrance, spacing and limits',()=>{
  const s=state(),m=new Maze(s),players=new Map([['p',player(m.center(100))]]),traps=new Map();
  s.crown=m.center(200);const p=chooseSpawn('demon',s,m,players,traps,5000);assert.ok(p);
  assert.equal(placementError('demon',p,s,m,players,traps,5000),'');
  assert.match(placementError('demon',m.center(100),s,m,players,traps,5000),/close|entrance/);
  assert.match(placementError('demon',s.crown,s,m,players,traps,5000),/crown|entrance|close/);
  assert.match(placementError('demon',m.center(m.entry),s,m,players,traps,5000),/entrance/);
  traps.set('one',trap(p));assert.match(placementError('fire',p,s,m,players,traps,5000),/space/);
  assert.match(placementError('crown',p,s,m,players,traps,5000),/cannot be moved/);
});
test('smart crown placement has a bounded journey and is reachable',()=>{
  const s={...state(),phase:'setup'},m=new Maze(s),p=chooseSpawn('crown',s,m,new Map(),new Map(),5000);
  assert.ok(p);assert.ok(m.distances(m.entry)[m.cell(p)]>=3);assert.ok(Math.abs(m.distances(m.entry)[m.cell(p)]-55)<2);
});
test('energy is capped and is not generated by a backwards clock',()=>{
  assert.equal(energy(state(),2000),56);assert.equal(energy(state(),999),50);assert.equal(energy(state(),100000),100);
});
test('demons actually pursue through corridors and never cross walls',()=>{
  const s=state(),m=new Maze(s),from=100,to=m.graph[from][0],target=m.center(to),p=player(target);
  const traps=new Map([['d',trap(m.center(from))]]),players=new Map([['p',p]]);let enemies={};
  for(let frame=0;frame<120;frame++){
    const now=5000+frame*50;p.updatedAt=now;
    const prev=enemies.d;enemies=stepEnemies(m,s,traps,players,enemies,.05,now);
    assert.ok(!m.blocked(enemies.d.x,enemies.d.z,.25));
    if(prev)assert.ok(distance(prev,enemies.d)<=2.65*.05+.001);
  }
  assert.ok(distance(enemies.d,target)<1);assert.equal(enemies.d.targetId,'p');
});
test('stale/dead players are not enemy targets, and expired enemies disappear',()=>{
  const s=state(),m=new Maze(s),t=trap(m.center(100)),traps=new Map([['d',t]]);
  const players=new Map([['dead',player(m.center(101),5000,{alive:false})],['stale',player(m.center(102),1)]]);
  let e=stepEnemies(m,s,traps,players,{},.05,50000);assert.equal(e.d.targetId,'');
  assert.deepEqual(stepEnemies(m,s,traps,players,e,.05,400000),{});
});
test('spawn warning and respawn protection prevent instant kills',()=>{
  const s=state(),m=new Maze(s),p=player(m.center(100),5000),t=trap(p,{type:'fire',armedAt:6000}),traps=new Map([['fire',t]]);
  assert.equal(hazardAt(p,p,s,traps,{},m,5000),null);
  assert.equal(hazardAt({...p,protectedUntil:8000},p,s,traps,{},m,7000),null);
  assert.equal(hazardAt({...p,updatedAt:7000},p,s,traps,{},m,7000).type,'fire');
});
test('remote motion prediction is capped and cannot cross a wall',()=>{
  const m=new Maze(state()),p={...m.center(100),vx:5.4,vz:0,updatedAt:1000};
  assert.ok(distance(p,remotePosition(p,100000,m))<=5.4*.35+.001);
  assert.ok(!m.blocked(remotePosition(p,100000,m).x,remotePosition(p,100000,m).z));
});
test('latest-only writer coalesces frames with one outstanding request',async()=>{
  let now=0,resolve;const writes=[];
  const w=new LatestWriter(v=>{writes.push(v);return new Promise(r=>resolve=r);},{now:()=>now});
  w.offer({x:0,z:0,yaw:0});const first=w.flush();await Promise.resolve();
  for(let x=1;x<=100;x++){w.offer({x,z:0,yaw:0});w.flush(true);}
  assert.equal(writes.length,1);resolve();await first;now=1000;
  const second=w.flush();await Promise.resolve();assert.equal(writes.length,2);assert.equal(writes[1].x,100);resolve();await second;
});
test('failed writes do not advance the acknowledged baseline and retry newest data',async()=>{
  let now=0,fail=true;const writes=[];
  const w=new LatestWriter(async v=>{writes.push(v);if(fail)throw new Error('offline');},{now:()=>now});
  w.offer({x:1,z:0,yaw:0});assert.equal(await w.flush(),false);assert.equal(w.last,null);
  w.offer({x:20,z:0,yaw:0});now=100;assert.equal(await w.flush(true),false);assert.equal(writes.length,1);
  now=5000;fail=false;assert.equal(await w.flush(),true);assert.equal(w.last.x,20);
});
test('idle heartbeats are bounded and disposal stops future writes',async()=>{
  let now=0,count=0;const w=new LatestWriter(async()=>count++,{now:()=>now});
  w.offer({x:1,z:1,yaw:0});await w.flush();now=1000;await w.flush();assert.equal(count,1);
  now=2600;await w.flush();assert.equal(count,2);w.close();now=6000;await w.flush(true);assert.equal(count,2);
});
