import test from 'node:test';
import assert from 'node:assert/strict';
import {RULES,COST,TTL,roundKey,makeMaze,center,cellAt,spawnPoint,blocked,move,Navigation,isOnline,trapWindow,placementProblem,suggestSpawn,defaultCrown,EnemyDirector,LatestWriter,canPickup,canEscape} from '../game/stoney/core.mjs';
import {StoneyRoom} from '../game/stoney/network.mjs';
const copy=v=>v==null?v:structuredClone(v);
const state=(now=100000)=>({seed:42,w:9,h:9,cellSize:4,phase:'play',setupDeadline:now-10000,startAt:now-1000,endAt:now+300000,dmEnergyBase:100,dmEnergyStamp:now,crown:null});
const live=(uid,p,now=100000)=>({uid,name:uid,...p,alive:true,online:true,updatedAt:now,stoneyRole:'player',shieldUntil:0});
function merge(a,b){const out={...a};for(const[k,v]of Object.entries(b))out[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(out[k]||{},v):copy(v);return out;}
/** Transactional in-memory driver: enforces reads-before-writes and atomic commits. Not a Firebase emulator. */
class MemoryStore {
 constructor(){this.now=100000;this.docs=new Map();this.listeners=new Set();this.tail=Promise.resolve();this.failCommit=false;this.commitCount=0;}
 driver(uid){const db=this;return{uid,time:()=>db.now,get:async p=>copy(db.docs.get(p)||null),set:async(p,v)=>{db.commit([[p,merge(db.docs.get(p)||{},v)]]);},transaction:fn=>{const operation=db.tail.then(async()=>{const writes=[];let writing=false;const result=await fn({get:async p=>{assert.equal(writing,false,'Firestore transactions cannot read after writing');return copy(db.docs.get(p)||null);},set:(p,v)=>{writing=true;writes.push([p,merge(db.docs.get(p)||{},v)]);},update:(p,v)=>{writing=true;assert.ok(db.docs.has(p),`missing update ${p}`);const next=copy(db.docs.get(p));for(const[k,x]of Object.entries(v)){const parts=k.split('.');let obj=next;for(const part of parts.slice(0,-1))obj=obj[part]??={};obj[parts.at(-1)]=copy(x);}writes.push([p,next]);},delete:p=>{writing=true;writes.push([p,null]);}});if(db.failCommit&&writes.length){db.failCommit=false;throw new Error('simulated commit failure');}db.commit(writes);return result;});db.tail=operation.catch(()=>{});return operation;},listenDoc:(p,cb,error)=>db.listen(p,false,cb,error),listenCollection:(p,cb,error)=>db.listen(p,true,cb,error)};}
 listen(path,collection,cb,error){const listener={path,collection,cb,error};this.listeners.add(listener);queueMicrotask(()=>{if(!this.listeners.has(listener))return;if(collection)cb([...this.docs].filter(([p])=>p.startsWith(path+'/')&&p.split('/').length===path.split('/').length+1).map(([p,data])=>({id:p.split('/').at(-1),type:'added',data:copy(data)})),{fromCache:false,hasPendingWrites:false});else cb(copy(this.docs.get(path)||null),{fromCache:false,hasPendingWrites:false});});return()=>this.listeners.delete(listener);}
 commit(writes){if(!writes.length)return;const changes=writes.map(([path,value])=>({path,value,type:value==null?'removed':this.docs.has(path)?'modified':'added'}));for(const c of changes){if(c.value==null)this.docs.delete(c.path);else this.docs.set(c.path,copy(c.value));}this.commitCount++;for(const l of this.listeners){const relevant=changes.filter(c=>l.collection?c.path.startsWith(l.path+'/')&&c.path.split('/').length===l.path.split('/').length+1:c.path===l.path);if(relevant.length)queueMicrotask(()=>{if(!this.listeners.has(l))return;l.cb(l.collection?relevant.map(c=>({id:c.path.split('/').at(-1),type:c.type,data:copy(c.value)})):copy(relevant.at(-1).value),{fromCache:false,hasPendingWrites:false});});}}
 async settle(){for(let i=0;i<8;i++){await this.tail;await new Promise(r=>setImmediate(r));}}
 async room(uid,role='player',skew=0){const room=new StoneyRoom(this.driver(uid),{id:'test',name:uid,role,now:()=>this.now+skew,visible:()=>true});await room.start();await this.settle();room.tick();await this.settle();return room;}
}
async function pose(db,room,p){room.setPose(p);const self=room.me();await room.d.set(room.posePath,{...p,uid:room.uid,sessionId:room.session,round:room.joined,life:self.life,online:true,active:true,updatedAt:db.now,serverAt:db.now});room.lastAck=db.now;await db.settle();}
async function fixture(){const db=new MemoryStore(),dm=await db.room('dm','dm'),a=await db.room('a'),b=await db.room('b');await pose(db,dm,spawnPoint(dm.maze));await pose(db,a,spawnPoint(dm.maze));await pose(db,b,spawnPoint(dm.maze));db.now+=1000;for(const r of [dm,a,b])r.lastAck=db.now;return{db,dm,a,b};}

test('seeded mazes are deterministic, connected, and reciprocal across 30 seeds',()=>{for(let seed=1;seed<=30;seed++){const m=makeMaze(21,21,seed);assert.deepEqual(m.cells,makeMaze(21,21,seed).cells);assert.equal([...new Navigation(m).field(0)].filter(v=>v<0).length,0);for(let i=0;i<m.cells.length;i++)for(const j of m.neighbors[i])assert.ok(m.neighbors[j].includes(i));}});
test('entrance is passable, room spawn is safe, and large movement cannot tunnel through a wall',()=>{const m=makeMaze(9,9,42),entry=center(m,m.entrance.y*m.w+m.entrance.x);for(let z=entry.z;z<m.h*m.size/2+9;z+=.1)assert.equal(blocked(m,{x:entry.x,z}),false);assert.equal(blocked(m,spawnPoint(m,'a')),false);const p=center(m,0),next=move(m,p,0,-100);assert.ok(next.z>p.z-2);assert.equal(blocked(m,next),false);});
test('BFS next steps always use open maze edges',()=>{const m=makeMaze(21,21,8),nav=new Navigation(m);for(let i=0;i<m.cells.length;i++){const n=nav.next(i,200);assert.ok(n===i||m.neighbors[i].includes(n));}});
test('server timestamps determine presence, dead and stale players are not spawn obstacles',()=>{const now=100000,m=makeMaze(9,9,42),s=state(now),p=center(m,0);assert.equal(isOnline({online:true,updatedAt:999999,serverAt:now-500},now),true);assert.equal(isOnline({updatedAt:now-16000},now),false);assert.match(placementProblem(m,s,p,[live('a',p,now)],[],now,'ghost'),/Too close/);assert.equal(placementProblem(m,s,p,[{...live('a',p,now),alive:false}],[],now,'ghost'),'');});
test('safe-spawn planner respects crown, players, entrance, overlapping traps, and caps',()=>{const m=makeMaze(21,21,42),s=state(),p=live('a',center(m,10));s.crown=defaultCrown(m);const next=suggestSpawn(m,s,[p],[],100000,'ghost');assert.ok(next);assert.equal(placementProblem(m,s,next,[p],[],100000,'ghost'),'');assert.match(placementProblem(m,s,next,[p],[{...next,type:'fire',placedAt:100000}],100000,'ghost'),/stacking/);assert.match(placementProblem(m,s,s.crown,[],[],100000,'ghost'),/crown/);assert.match(placementProblem(m,s,center(m,m.entrance.y*m.w+m.entrance.x),[],[],100000,'ghost'),/entrance/);assert.equal(cellAt(m,s.crown)>=0,true);});
test('setup and live spawns arm after the shared warning, with TTL measured from arming',()=>{const s={setupDeadline:130000,startAt:110000};assert.deepEqual(trapWindow({placedAt:100000,telegraphMs:1300,type:'fire',ttlMs:10000},s),{armedAt:111300,expiresAt:121300});assert.deepEqual(trapWindow({placedAt:115000,telegraphMs:1300,type:'fire',ttlMs:10000},s),{armedAt:116300,expiresAt:126300});});
test('enemy director chases through open corridors without crossing walls',()=>{const m=makeMaze(9,9,42),s=state(),start=center(m,0),goal=m.neighbors[0][0],player=live('a',center(m,goal));const trap={id:'g',type:'ghost',...start,placedAt:98000,ttlMs:300000};const ai=new EnemyDirector(m);for(let i=0;i<120;i++){player.updatedAt=100000+i*50;ai.step([trap],s,[player],100000+i*50,.05);assert.equal(blocked(m,ai.enemies.get('g'),.3),false);}assert.equal(ai.enemies.get('g').targetId,'a');assert.ok(Math.hypot(ai.enemies.get('g').x-start.x,ai.enemies.get('g').z-start.z)>1);});
test('shielded, dead, disconnected players and setup phase do not take enemy damage',()=>{const m=makeMaze(9,9,42),s=state(),p=center(m,0),ai=new EnemyDirector(m),trap={id:'fire',type:'fire',...p,placedAt:98000,ttlMs:10000};for(const extra of [{shieldUntil:110000},{alive:false},{updatedAt:1},{online:false}])assert.deepEqual(ai.step([trap],s,[{...live('a',p),...extra}],100000,.05),[]);assert.deepEqual(ai.step([trap],{...s,phase:'setup'},[live('a',p)],100000,.05),[]);assert.deepEqual(ai.step([trap],s,[live('a',p)],100000,.05),['a']);});
test('enemy memory expires and shared snapshots restore without a positional reset',()=>{const m=makeMaze(9,9,42),s=state(),p=center(m,0),trap={id:'g',type:'ghost',...p,placedAt:98000,ttlMs:300000},ai=new EnemyDirector(m);ai.step([trap],s,[live('a',p)],100000,.05);const snapshot=ai.snapshot(),newHost=new EnemyDirector(m);newHost.restore(snapshot);assert.equal(newHost.enemies.get('g').x,snapshot[0].x);newHost.step([trap],s,[],104000,.05);assert.equal(newHost.enemies.get('g').targetId,'');});
test('demon warns before its charge',()=>{const m=makeMaze(9,9,42),s=state(),p=center(m,0),ai=new EnemyDirector(m);ai.step([{id:'d',type:'demon',...p,placedAt:98000,ttlMs:300000}],s,[live('a',{x:p.x+.9,z:p.z})],100000,.05);assert.equal(ai.enemies.get('d').mode,'windup');assert.equal(ai.enemies.get('d').windupUntil,100650);});
test('latest writer allows one in-flight write and coalesces intermediate positions',async()=>{let release;const sent=[],w=new LatestWriter(v=>{sent.push(v);return new Promise(r=>release=r);});w.offer(1);const first=w.flush();w.offer(2);w.offer(3);assert.equal(await w.flush(),false);release();await first;const second=w.flush();assert.deepEqual(sent,[1,3]);release();await second;});
test('failed writes do not advance acknowledgment, retry backs off, and closed writers stay closed',async()=>{let now=100,fail=true;const ack=[],w=new LatestWriter(async()=>{if(fail)throw Error('offline');},{now:()=>now,onAck:v=>ack.push(v)});w.offer({x:1});assert.equal(await w.flush(),false);assert.deepEqual(ack,[]);fail=false;assert.equal(await w.flush(),false);now+=501;assert.equal(await w.flush(),true);assert.equal(ack.length,1);w.close();w.offer({x:2});assert.equal(await w.flush(),false);});
test('pickup and escape require current living carrier and an unexpired round',()=>{const m=makeMaze(9,9,42),s=state(),p=live('a',center(m,0));s.crown={x:p.x,z:p.z};assert.equal(!!canPickup(s,p,100000),true);assert.equal(!!canPickup(s,{...p,alive:false},100000),false);s.carrierId='b';assert.equal(canEscape(m,s,{...p,...spawnPoint(m)},100000),false);s.carrierId='a';assert.equal(canEscape(m,s,{...p,...spawnPoint(m)},100000),true);assert.equal(canEscape(m,{...s,endAt:99999},{...p,...spawnPoint(m)},100000),false);});

test('clock calibration precedes setup deadlines and registration survives reload',async()=>{const db=new MemoryStore(),dm=await db.room('dm','dm',600000);assert.equal(dm.state.setupDeadline,db.now+30000);const a=await db.room('a');const p=center(a.maze,5);await pose(db,a,p);const again=await db.room('a');assert.equal(again.me().x,p.x);assert.equal(a.locked,true);assert.equal(again.me().sessionId,again.session);for(const r of [dm,a,again])r.close();assert.equal(db.listeners.size,0);});
test('new DM role cannot be taken by a different UID',async()=>{const db=new MemoryStore(),dm=await db.room('dm','dm');await assert.rejects(db.room('impostor','dm'),/assigned Dungeon Master/);dm.close();});
test('cache-only subscriptions and terminal listener errors cannot appear playable',async()=>{const{db,dm,a,b}=await fixture();assert.equal(a.playable(),true);a.readsReady.delete('world');assert.equal(a.playable(),false);const l=[...db.listeners].find(l=>l.path===a.syncPath&&!l.collection);l.error(Error('listener ended'));assert.equal(dm.healthy(),false);for(const r of [dm,a,b])r.close();});
test('spawn and energy are atomic, failure does not spend energy, and mode cannot mutate in flight',async()=>{const{db,dm,a,b}=await fixture();db.now+=20000;for(const r of[dm,a,b])r.lastAck=db.now;await pose(db,dm,spawnPoint(dm.maze));const p=suggestSpawn(dm.maze,dm.state,dm.players(),[],db.now,'ghost');db.failCommit=true;assert.equal(await dm.place('ghost',p),false);assert.equal(db.docs.get(dm.base).stoney.dmEnergyBase,0);assert.equal([...db.docs.keys()].filter(p=>p.includes('/traps/')).length,0);db.now+=1000;dm.lastAck=db.now;assert.equal(await dm.place('ghost',p),true);await db.settle();const t=[...dm.traps.values()][0];assert.equal(t.type,'ghost');assert.equal(t.ttlMs,TTL.ghost);assert.equal(db.docs.get(dm.base).stoney.dmEnergyBase,50);for(const r of[dm,a,b])r.close();});
test('simultaneous crown pickups have exactly one owner, globally marked as discovered',async()=>{const{db,dm,a,b}=await fixture();await dm.ready();await db.settle();const crown=dm.state.crown;await pose(db,a,crown);await pose(db,b,crown);await Promise.all([a.pickup(),b.pickup()]);await db.settle();assert.equal(dm.state.carrierId,'a');assert.equal(a.state.carrierId,b.state.carrierId);assert.equal(dm.state.crownDiscovered,true);for(const r of[dm,a,b])r.close();});
test('stale pose from prior life cannot overwrite respawn state or position',async()=>{const{db,dm,a,b}=await fixture();await dm.ready();await db.settle();const p=center(a.maze,1);await pose(db,a,p);await a.d.set(a.playerPath,{alive:false,deadUntil:db.now-1});await db.settle();await a.respawn();await db.settle();const self=a.me();assert.equal(self.life,1);assert.equal(self.alive,true);assert.equal(self.shieldUntil,db.now+RULES.shield);await a.d.set(a.posePath,{...p,life:0});await db.settle();const seen=b.players().find(p=>p.uid==='a');assert.equal(seen.x,spawnPoint(a.maze,'a').x);assert.equal(seen.z,spawnPoint(a.maze,'a').z);assert.equal(seen.alive,true);for(const r of[dm,a,b])r.close();});
test('host lease is unique, takeover restores enemies, and stale host cannot publish',async()=>{const{db,dm,a,b}=await fixture();await dm.claimHost();await db.settle();assert.equal(dm.isHost(),true);const original=db.docs.get(dm.syncPath);dm.closed=true;db.now+=7000;for(const r of[a,b])await pose(db,r,spawnPoint(r.maze));await Promise.all([a.claimHost(),b.claimHost()]);await db.settle();assert.equal(a.isHost(),true);assert.equal(b.isHost(),false);const epoch=db.docs.get(a.syncPath).epoch;assert.ok(epoch>original.epoch);dm.closed=false;await dm.publish();await db.settle();assert.equal(db.docs.get(a.syncPath).owner,'a');assert.equal(db.docs.get(a.syncPath).epoch,epoch);for(const r of[dm,a,b])r.close();});
test('host timeout ends the round without any new lobby write',async()=>{const{db,dm,a,b}=await fixture();await dm.ready();await db.settle();db.now=dm.state.endAt+1;for(const r of[dm,a,b])await pose(db,r,spawnPoint(r.maze));await Promise.all([dm,a,b].map(r=>r.claimHost()));await db.settle();await [dm,a,b].find(r=>r.isHost()).maintain();await db.settle();assert.equal(a.state.phase,'ended');assert.equal(b.state.winner,'dm');for(const r of[dm,a,b])r.close();});
test('disconnected carrier drops crown where last seen and it remains recoverable',async()=>{const{db,dm,a,b}=await fixture();await dm.ready();await db.settle();await pose(db,a,dm.state.crown);await a.pickup();await db.settle();db.now+=21000;await pose(db,dm,spawnPoint(dm.maze));await pose(db,b,spawnPoint(dm.maze));await Promise.all([dm,b].map(r=>r.claimHost()));await db.settle();await [dm,b].find(r=>r.isHost()).maintain();await db.settle();assert.equal(b.state.carrierId,null);assert.deepEqual(b.state.crown,dm.state.crown);assert.equal(b.state.crownDiscovered,true);for(const r of[dm,a,b])r.close();});
test('offline reconnect rebuilds maps and listener cleanup is complete',async()=>{const{db,dm,a,b}=await fixture();a.setOffline(true);assert.equal(a.playable(),false);await a.d.set(`${a.base}/players/gone`,{name:'gone',protocol:2,stoneyRound:a.joined,updatedAt:db.now});await db.settle();a.setOffline(false);await db.settle();assert.ok(a.statuses.has('gone'));a.setOffline(true);db.commit([[`${a.base}/players/gone`,null]]);a.setOffline(false);await db.settle();assert.equal(a.statuses.has('gone'),false);for(const r of[dm,a,b])r.close();assert.equal(db.listeners.size,0);});
test('authoritative enemy contact commits death and crown drop together',async()=>{const{db,dm,a,b}=await fixture();await dm.ready();await db.settle();const p=dm.state.crown;await pose(db,a,p);await a.d.set(a.playerPath,{shieldUntil:0});await db.settle();await a.pickup();await db.settle();await dm.claimHost();await db.settle();dm.director.enemies.set('contact',{id:'contact',type:'ghost',...p,targetId:'a',mode:'hunt',lastSeen:db.now,goal:cellAt(dm.maze,p),windupUntil:0,chargeUntil:0,cooldownUntil:0});dm.pendingHits.add('a');await dm.publish();await db.settle();assert.equal(a.me().alive,false);assert.equal(a.me().deadUntil,db.now+RULES.respawn);assert.equal(a.state.carrierId,null);assert.deepEqual(a.state.crown,p);for(const r of[dm,a,b])r.close();});
test('an old cached session cannot lock the newly connected tab',async()=>{const db=new MemoryStore(),dm=await db.room('dm','dm');const self=copy(dm.me()),listener=[...db.listeners].find(l=>l.path===`${dm.base}/players`);listener.cb([{id:'dm',type:'modified',data:{...self,sessionId:'stale-cache'}}],{fromCache:true,hasPendingWrites:false});assert.equal(!!dm.locked,false);assert.equal(dm.playable(),false);listener.cb([{id:'dm',type:'modified',data:self}],{fromCache:false,hasPendingWrites:false});assert.equal(dm.playable(),true);dm.close();});
test('moving pose documents are not transaction dependencies during safe placement',async()=>{const{db,dm,a,b}=await fixture();db.now+=20000;await pose(db,dm,spawnPoint(dm.maze));const pathLog=[],baseTransaction=dm.d.transaction;dm.d.transaction=fn=>baseTransaction(tx=>fn({...tx,get:async path=>{pathLog.push(path);return tx.get(path);}}));const p=suggestSpawn(dm.maze,dm.state,dm.players(),[],db.now,'ghost');assert.equal(await dm.place('ghost',p),true);assert.equal(pathLog.some(p=>p.includes('/stoneyPoses/')),false);for(const r of[dm,a,b])r.close();});

test('automatic crown placement leaves time for searching and escaping',()=>{for(let seed=1;seed<=40;seed++){const m=makeMaze(21,21,seed),d=new Navigation(m).field(m.entrance.y*m.w+m.entrance.x)[cellAt(m,defaultCrown(m))];assert.ok(d>0);assert.ok(d*m.size*2/3.9<=RULES.duration/1000*.45);}});
