import test from 'node:test';
import assert from 'node:assert/strict';
import {TEAMS,resolveVoice,parseSchedule,feedQueue,playable,cycle,RadioPlayer} from './core.mjs';
const game={id:'1',away:'DET',home:'GB',date:'2026-09-13T17:00:00Z',state:'in'};
const games=[game,{id:'2',away:'BUF',home:'KC',date:game.date,state:'in'},{id:'3',away:'NYG',home:'DAL',date:game.date,state:'in'}];
const now=Date.now();
const feed=(id,kind='flagship',overrides={})=>({id,name:id,kind,team:'DET',access:'direct',authorized:true,gameAudio:true,gameIds:['1'],streamUrl:'https://authorized.example/live.mp3',sourceUrl:'https://authorized.example/rights',verifiedAt:new Date(now).toISOString(),availableFrom:new Date(now-1000).toISOString(),availableUntil:new Date(now+60000).toISOString(),...overrides});
test('all 32 teams and natural Lions requests resolve',()=>{assert.equal(TEAMS.length,32);for(const phrase of ['Lions','Detroit','Play Detroit Lions game','Put on Detroit','Detroit Green Bay','Switch to the Lions','DET'])assert.equal(resolveVoice(phrase,games,game).game.id,'1');});
test('ambiguous cities, opponent pairs and feed commands',()=>{assert.equal(resolveVoice('New York',games).message,'Giants or Jets?');assert.equal(resolveVoice('New York Dallas',games).game.id,'3');assert.equal(resolveVoice('Chiefs Bills',games).game.id,'2');assert.equal(resolveVoice('Green Bay broadcast',games,game).role,'home');assert.equal(resolveVoice('away broadcast',games,game).role,'away');assert.equal(resolveVoice('next station',games).kind,'nextStation');assert.equal(resolveVoice('Patriots',games).kind,'unknown');});
test('rotation wraps only selected games',()=>{assert.equal(cycle(['1','3'],'1',1),'3');assert.equal(cycle(['1','3'],'3',1),'1');assert.equal(cycle(['1','3'],'1',-1),'3');assert.equal(cycle([],null,1),null);});
test('direct playback requires game authorization, source and current window',()=>{const f=feed('a');assert.ok(playable(f,game,now));for(const change of [{authorized:false},{gameAudio:false},{gameIds:['2']},{access:'subscription'},{streamUrl:'http://example.com'},{sourceUrl:null},{availableUntil:'2020-01-01'},{availableFrom:'2099-01-01'}])assert.equal(playable({...f,...change},game,now),false);});
test('fallback excludes opposing team and prefers flagship then affiliates then national',()=>{const f=[feed('national','national',{team:null}),feed('affiliate','affiliate'),feed('flagship'),feed('opponent','flagship',{team:'GB'})];assert.deepEqual(feedQueue(f,game,'DET',null,null,now).map(f=>f.id),['flagship','affiliate','national']);assert.equal(feedQueue(f,game,'DET','affiliate',null,now)[0].id,'affiliate');assert.equal(feedQueue(f,game,'DET',null,'home',now)[0].id,'opponent');});
test('schedule parser rejects invalid responses and normalizes team codes',()=>{assert.throws(()=>parseSchedule({}));assert.deepEqual(parseSchedule({events:[]}),[]);const event={id:'x',date:game.date,status:{type:{state:'pre'}},competitions:[{competitors:[{homeAway:'home',team:{abbreviation:'WSH'}},{homeAway:'away',team:{abbreviation:'JAC'}}]}]};assert.equal(parseSchedule({events:[event]})[0].home,'WAS');assert.equal(parseSchedule({events:[event]})[0].away,'JAX');});
class FakeAudio extends EventTarget{constructor(){super();this.paused=true;this.calls=0;}play(){this.calls++;this.paused=false;return Promise.resolve();}pause(){this.paused=true;}load(){}removeAttribute(){}emit(name){this.dispatchEvent(new Event(name));}}
test('tap starts audio synchronously; rapid switch ignores stale errors and stops old audio',()=>{const created=[],states=[];const p=new RadioPlayer(()=>{const a=new FakeAudio();created.push(a);return a;},s=>states.push(s));p.select([feed('a')]);assert.equal(created[0].calls,1);p.select([feed('b')]);assert.equal(created[0].paused,true);created[0].emit('error');assert.equal(created.length,2);created[1].emit('playing');assert.equal(states.at(-1),'playing');p.stop();});
test('stream failure falls forward once and exhausts without a loop',()=>{const created=[],states=[];const p=new RadioPlayer(()=>{const a=new FakeAudio();created.push(a);return a;},s=>states.push(s));p.select([feed('a'),feed('b')]);created[0].emit('error');created[0].emit('error');assert.equal(created.length,2);created[1].emit('error');assert.equal(states.at(-1),'unavailable');p.stop();});
test('autoplay denial is not mistaken for a broken station',async()=>{const states=[];const p=new RadioPlayer(()=>{const a=new FakeAudio();a.play=()=>Promise.reject(Object.assign(new Error(),{name:'NotAllowedError'}));return a;},s=>states.push(s));p.select([feed('a'),feed('b')]);await Promise.resolve();assert.equal(states.at(-1),'blocked');assert.equal(p.index,0);p.stop();});
test('pausing prevents a late stall from starting another feed',()=>{const created=[];const p=new RadioPlayer(()=>{const a=new FakeAudio();created.push(a);return a;},()=>{});p.select([feed('a'),feed('b')]);p.pause();created[0].emit('error');created[0].emit('waiting');assert.equal(created.length,1);p.resume();assert.equal(created.length,2);p.stop();});
