import { BUILDINGS, FORMATIONS, REGIONS, RESOURCES, UNITS } from './data.mjs';
import { ART } from './asset-manifest.mjs';
import { PLAYER, buildCheck, findPath, kingdom, recruitCheck, recruitmentCost, settlements, treaty } from './core.mjs';
import { buildingLevel, buildingSpec, constructionSpec, productionPlan, storageCapacity, tileProduction, wallMaximum } from './economy.mjs';
import { economicRelationship } from './living.mjs';
import { publicEconomy, tradeInfrastructure, tradeRoute } from './trade.mjs';
import { STRATEGY_GOALS } from './strategy.mjs';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cost=c=>Object.entries(c).map(([r,n])=>`${n} ${r}`).join(' · ');
export const art=(url,alt,cls='catalog-art')=>`<img class="${cls}" src="${url}" alt="${esc(alt)}" loading="lazy">`;
export const systemTitle=id=>art(ART.titles[id],id.replaceAll('_',' '),'system-art');
export function buildingInspection(s,t){
  let html=`<p class="fine">${esc(REGIONS[t.region]?.name)} · ${esc(REGIONS[t.region]?.description)}</p>`;
  const output=tileProduction(t,t.owner);
  html+=Object.keys(BUILDINGS).filter(id=>buildingLevel(t,id)).map(id=>{const level=buildingLevel(t,id),b=BUILDINGS[id],spec=buildingSpec(id,level),next=constructionSpec(t,id);return `<article class="realm-card inspection">${art(ART.structures[id][level],spec.name)}<div><strong>${esc(spec.name)} · Level ${level}</strong>${Object.keys(b.yield||{}).length?`<p class="fine">${Object.keys(b.yield).map(r=>`+${output[r]} ${r}/turn`).join(' · ')}</p>`:''}${b.recipe?`<p class="fine">Per production batch: ${cost(b.recipe.input)} → ${cost(b.recipe.output)}. Level ${level}.</p>`:''}${id==='wall'?`<p class="fine">Integrity ${t.walls}/${wallMaximum(t)}</p>`:''}${next?`<p class="fine">${next.repair?'Repair':esc(next.name)} · ${next.turns} turns · ${cost(next.cost)}</p>`:'<p class="fine">Maximum level</p>'}</div></article>`;}).join('');
  if(t.project){const p=t.project,spec=buildingSpec(p.type,p.level);html+=`<div class="realm-card inspection">${art(ART.construction[Math.min(2,Math.floor((1-p.remaining/p.total)*3))],'Under construction')}<div><strong>${esc(spec.name)} underway${p.repair?' · Repair':''}</strong><p>Turn ${p.total-p.remaining}/${p.total} · ${p.remaining} remaining</p><progress max="${p.total}" value="${p.total-p.remaining}"></progress><p class="fine">The completed tier stays active during an upgrade.</p></div></div>`;}
  const stalls=productionPlan(s,t.owner||PLAYER).stalls.filter(x=>x.tile===t.id);for(const x of stalls)html+=`<p class="negative">${esc(BUILDINGS[x.type].name)} paused: needs ${cost(x.input)} per turn.</p>`;
  return html;
}
export function constructionBrowser(s,t){
 return `${systemTitle('construction')}<p class="fine">Select a project to start. Materials and one order are paid now. Upgrades activate after their final turn.</p>`+['Economy','Trade','Military','Defense','Government','Great Projects'].map(category=>`<details class="catalog-group" ${category==='Economy'?'open':''}><summary>${category}</summary>${category==='Great Projects'?systemTitle('great_projects'):''}<div class="build-list">${Object.entries(BUILDINGS).filter(([,b])=>b.category===category).map(([id,b])=>{const spec=constructionSpec(t,id),level=spec?.level||buildingLevel(t,id)||1,why=buildCheck(s,PLAYER,t.id,id);return `<button class="build-card" data-build="${id}" ${why?'disabled':''} title="${esc(why||b.description)}">${art(ART.structures[id][level],spec?.name||b.name)}<span class="build-title">${esc(spec?.name||b.name)} ${spec?.repair?'· Repair':`· ${level}`}</span><span class="build-cost">${spec?`${cost(spec.cost)} · ${spec.turns} turns`:'Complete'}</span><span class="build-desc">${esc(why||benefits(id,level))}</span></button>`;}).join('')}</div></details>`).join('');
}
function benefits(id,level){const b=BUILDINGS[id];if(b.recipe)return `Manufactures ${cost(b.recipe.output)} per batch by consuming ${cost(b.recipe.input)}.`;if(b.yield)return `Production scales with level${['farm','mine','quarry','lumber','ranch'].includes(id)?' and deposit quality':''}. ${cost(b.yield)} base.`;const unlock=Object.values(UNITS).filter(u=>u.requires[id]===level&&!u.legacy).map(u=>u.name);return unlock.length?`Unlocks ${unlock.join(', ')}.`:id==='storehouse'?`+${level*400} storage per resource.`:id==='fort'||id==='wall'?'Stronger garrison and fortifications; sieges must breach them.':id==='road'?'Faster travel; contiguous roads increase trade capacity and remove transport fees.':id==='greatGranary'?'2,400 extra food storage; halves famine attrition.':id==='greatStable'?'Horse production and a morale boost when recruiting mounted troops.':id==='siegeFoundry'?'Reduces advanced siege recruitment material costs by 20%.':id==='envoyOffice'?`Shared dispatches and ambassadors; upper tiers add ${(level-1)*2} envoy movement.`:id==='watchtower'?`Controls nearby ground, stops adjacent enemies, and adds ${level*15}% tower defense.`:b.description;}
export function musterBrowser(s,t){return `${systemTitle('army')}<div class="build-list">${Object.entries(UNITS).filter(([,u])=>!u.legacy).map(([id,u])=>{const why=recruitCheck(s,PLAYER,t.id,id),bonus=u.family==='infantry'?Math.max(0,Math.min(kingdom(s,PLAYER).population-u.count-20,buildingLevel(t,'barracks')-1)):0;return `<button class="build-card" data-recruit="${id}" ${why?'disabled':''}>${art(ART.units[id],u.name)}<span class="build-title">${u.count+bonus} ${u.name}</span><span class="build-cost">${cost(recruitmentCost(t,id))}</span><span class="build-desc">${esc(why||u.description)}</span></button>`;}).join('')}</div>`;}
export function formationControl(a){return `<label>Formation<select data-formation="${a.id}">${Object.entries(FORMATIONS).map(([id,f])=>`<option value="${id}" ${a.formation===id?'selected':''}>${f.name}</option>`).join('')}</select></label><p class="fine">${esc(FORMATIONS[a.formation]?.description)} Morale ${Math.round(a.morale*100)}% · Retreats ${a.retreats||0}</p>`;}
export function tradePanel(s,selected=null){
  const pending=s.commerce.offers.filter(o=>o.status==='pending'&&o.expires>=s.turn),infra=tradeInfrastructure(s,PLAYER);
  let html=`${systemTitle('trade')}<p class="fine">${s.treaties.filter(t=>t.type==='recurring'&&t.parties.includes(PLAYER)&&t.expires>s.turn).length}/${infra.capacity} contracts. Outpost level ${infra.level}. Exact foreign stores remain private.</p>`;
  html+=pending.map(o=>{const i=o.intent,route=tradeRoute(s,PLAYER,o.from),r=kingdom(s,o.from).relations[PLAYER];return `<article class="trade-dispatch"><strong>${esc(kingdom(s,o.from).name)} · Trade Dispatch</strong><p>${esc(o.reason)}</p><p>You send <b>${i.giveAmount} ${i.giveResource}</b><br>You receive <b>${i.receiveAmount} ${i.receiveResource}</b></p><p class="fine">${i.type==='RECURRING'?`${i.duration} turns, per-turn exchange`:'Immediate exchange'} · ${esc(route.status)} · Trust ${r.trust} · Expires T${o.expires}</p><div class="button-row"><button data-trade-review="${o.id}">Accept · Review terms</button><button data-trade-counter="${o.id}">Counter</button><button data-trade-decline="${o.id}">Decline</button><button data-talk="${o.from}">Open Negotiation</button></div></article>`;}).join('');
  const contracts=s.treaties.filter(t=>t.type==='recurring'&&t.parties.includes(PLAYER)&&t.expires>s.turn);
  html+=contracts.map(t=>{const other=t.parties.find(id=>id!==PLAYER),route=tradeRoute(s,PLAYER,other),i=t.intent,relation=economicRelationship(s,PLAYER,other),from=route.path.length?s.tiles[route.path[0]]?.name:'No connection',to=route.path.length?s.tiles[route.path.at(-1)]?.name:kingdom(s,other).name;return `<div class="realm-card"><strong>${esc(from||'Outpost')} ↔ ${esc(to||kingdom(s,other).name)}</strong><p>Exports ${i.giveAmount} ${i.giveResource} → Imports ${i.receiveAmount} ${i.receiveResource} / turn</p><p class="fine">${esc(t.routeStatus||route.status)} · ${t.expires-s.turn} turns left · Transport ${i.tradeKind==='preferential'?0:route.fee||0} gold/turn · Supplier dependence ${relation.dependency}%</p>${t.disrupted?'<p class="negative">Disrupted. After three missed turns this contract ends.</p>':''}</div>`;}).join('');
  if(!pending.length&&!contracts.length)html+='<p class="fine">No incoming proposals or active supply contracts. Markets and outposts attract useful trade as shortages develop.</p>';
  return html;
}
export function commercialConnections(s,t){
 if(t.owner!==PLAYER||!['city','town','tradeOutpost'].includes(t.building))return '';
 const base=['city','town'].includes(t.building)?t:settlements(s,PLAYER)[0];if(!base)return '';
 return `<div class="section-label">COMMERCIAL CONNECTIONS</div>`+settlements(s).filter(other=>other.id!==base.id&&(other.owner===PLAYER||treaty(s,PLAYER,other.owner,'trade'))).map(other=>{
   const path=findPath(s,base.id,other.id,PLAYER,true);if(!path.length)return '';
   const level=Math.min(buildingLevel(base,'road'),...path.map(id=>buildingLevel(s.tiles[id],'road'))),income=(other.owner===PLAYER?6:10)+buildingLevel(base,'market')*2+buildingLevel(base,'merchantGuild')*3+(level-1)*4;
   return `<article class="realm-card"><strong>${esc(base.name)} ↔ ${esc(other.name)}</strong><p class="fine">${level===3?'Royal Highway':'Connected road'} · ${income} gold / turn · ${path.length} hexes</p>${other.owner===PLAYER&&level<3?`<button data-highway-from="${base.id}" data-highway-to="${other.id}">Review Royal Highway project</button>`:''}</article>`;
 }).join('');
}
export function economySummary(s){const p=productionPlan(s,PLAYER);return `${systemTitle('treasury')}<div class="stat-grid">${RESOURCES.map(r=>`<span>${r} storage</span><b>${kingdom(s,PLAYER).resources[r]} / ${storageCapacity(s,PLAYER,r)}</b>`).join('')}</div>${p.stalls.length?`<p class="negative">${p.stalls.length} workshops lack manufacturing inputs.</p>`:''}`;}
export function foreignEconomy(s,id){const e=publicEconomy(s,id);return `<p class="fine">${esc(e.specialty)}<br>Seeking: ${e.imports.join(', ')||'No major shortages'} · Offering: ${e.exports.join(', ')||'No major surplus'}</p>`;}
export function rivalTurnReports(s){
 const rounds=(s.strategy?.history||[]).slice().reverse();
 const place=id=>esc(s.tiles[id]?.name||id),action=a=>{
  if(a.kind==='build'||a.kind==='complete')return `${a.kind==='build'?'Started':'Completed'} ${esc(buildingSpec(a.building,a.level).name)} at ${place(a.tile)}.`;
  if(a.kind==='recruit')return `Recruited ${a.count} ${esc(UNITS[a.unit].name)} at ${place(a.tile)}.`;
  if(a.kind==='march')return a.arrivedAt===null?`An army ordered toward ${place(a.tile)} was lost.`:a.arrivedAt&&a.arrivedAt!==a.from?`Marched from ${place(a.from)} to ${place(a.arrivedAt)}${a.arrivedAt===a.tile?'':`, toward ${place(a.tile)}`}.`:`Ordered toward ${place(a.tile)}; the army held or fought at ${place(a.from)}.`;
  if(a.kind==='hold')return `Held position at ${place(a.tile)}.`;
  if(a.kind==='merge')return `Combined armies at ${place(a.tile)}.`;
  if(a.kind==='tax')return `Set ${esc(a.policy)} taxes.`;
  return `${a.kind==='war'?'Declared war on':'Agreed to peace with'} ${esc(kingdom(s,a.house).name)}.`;
 };
 return `<section aria-label="Rival turns"><div class="section-label">RIVAL TURNS</div><p class="fine">End Turn gives every surviving rival one turn. Houses pay for their own projects and troops, then all armies move and every realm collects production.</p>${rounds.length?rounds.map((round,i)=>`<details class="battle-report" ${i===0?'open':''}><summary>Round ${round.turn} · ${round.houses.filter(h=>h.goal!=='ELIMINATED').length} rival councils acted</summary>${round.houses.map(h=>`<details class="realm-card" data-rival-turn="${h.owner}"><summary>${esc(kingdom(s,h.owner).name)} · ${esc(STRATEGY_GOALS[h.goal])}</summary><p class="fine">${esc(h.reason)} ${h.orders} construction / recruitment orders used.</p>${h.actions.length?`<ul>${h.actions.map(a=>`<li>${action(a)}</li>`).join('')}</ul>`:''}${h.omitted?'<p class="fine">Additional army activity is visible on the map.</p>':''}</details>`).join('')}</details>`).join(''):'<p class="fine">The first rival turn report appears after you end round 1.</p>'}</section>`;
}
export function battleReports(s){
 const events=s.militaryEvents.filter(e=>[e.attacker,e.defender].includes(PLAYER)).slice(-12).reverse();
 return `${systemTitle('battle')}${events.length?events.map(e=>`<details class="battle-report"><summary>T${e.turn} · ${esc(s.tiles[e.tile]?.name||e.tile)} · ${e.winner?esc(kingdom(s,e.winner).name)+' victory':e.breach?'Breach opened':'Siege'}</summary>${e.composition?`<div class="report-scroll"><table><thead><tr><th>Troops</th><th>${esc(kingdom(s,e.attacker).name)}</th><th>${esc(kingdom(s,e.defender).name)}</th></tr></thead><tbody>${Object.entries(UNITS).filter(([id])=>e.composition.some(a=>a[id])).map(([id,u])=>`<tr><td>${u.name}</td>${[0,1].map(i=>`<td>${e.composition[i][id]||0} · lost ${e.casualties[i][id]||0}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:''}${(e.phases||[]).map(p=>`<p><strong>${esc(p.name)}</strong><br>${p.notes.map(esc).join(' ')}${p.loss?` <small>Losses: ${p.loss.join(' / ')}</small>`:''}</p>`).join('')}${e.retreat?`<p>Retreat: ${esc(kingdom(s,e.retreatOwner||e.defender).name)} to ${esc(e.retreat)}.</p>`:''}</details>`).join(''):'<p class="fine">Battle phases and casualties will appear here after a clash.</p>'}`;
}
