import { knowledgeView } from './fog.mjs';
import { alive, atWar, kingdom, settlements, treaty } from './core.mjs';
import { localHouseId } from './house-control.mjs';
import { OPERATION_ROLES, ongoingOperation, operationMember } from './cooperation-state.mjs';
import { operationPledges, operationProgress, publicMobilizations } from './operations.mjs';
import { visibleOperations } from './espionage.mjs';
import { strategicLocation } from './strategic-geography.mjs';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const house=(s,id)=>esc(kingdom(s,id)?.name||id);
const place=(s,id)=>esc(s.tiles[id]?.name||id);
function decisionButtons(id,attr,member='') {
  return `<div class="button-row">${['accept','decline',...(member?[]:['counter'])].map(choice=>`<button data-${attr}="${esc(id)}" data-decision="${choice}" ${member?`data-member="${esc(member)}"`:''}>${choice==='counter'?'Counteroffer':choice==='accept'?'Accept':'Decline'}</button>`).join('')}</div>`;
}
function operationCard(s,o,viewer) {
  const own=operationMember(o,viewer),pledges=operationPledges(s,o);
  return `<article class="realm-card operation-card"><span class="eyebrow">${esc(o.status)}</span><h3>${esc(o.name)}</h3><p>Target: ${house(s,o.target)} · <button data-goto="${esc(o.targetTile)}">${place(s,o.targetTile)}</button></p><p>Attack window: <strong>T${o.attackStart}–${o.attackEnd}</strong>${o.launchedTurn?` · Launched T${o.launchedTurn}`:''}</p><p class="fine">${esc(o.reason)}</p><label>Exposure: ${o.exposure}%<progress max="100" value="${o.exposure}" aria-label="Operation exposure"></progress></label><p class="fine">${o.exposureReasons.map(esc).join(' · ')||'Private preparation'}</p>${own?.status==='invited'?`<p>Your court has been invited. Acceptance creates binding commitments.</p>${decisionButtons(o.id,'operation-answer')}`:''}${o.participants.map(p=>{
    const progress=operationProgress(s,o,p),tasks=pledges.filter(x=>x.debtor===p.house);
    return `<section class="operation-role"><strong>${house(s,p.house)} · ${esc(OPERATION_ROLES[p.role])}</strong><p class="fine">${esc(p.status)}${p.status==='accepted'&&o.status==='Preparing'?` · ${progress.ready?'Prepared':'Preparing'}`:''} · Rally ${place(s,p.rally)} (${esc(p.rally)})</p><p class="fine">At rally: ${progress.troops}/${p.requiredTroops} troops · ${progress.siege}/${p.requiredSiege} siege · Food ${p.food?`${progress.supplyReady?'delivered':'owed'} ${p.food}`:'none'}</p>${p.status==='counter'?`<p>Counteroffer: ${p.counterTroops} troops.</p>${o.owner===viewer?decisionButtons(o.id,'operation-answer',p.house):''}`:''}<ul>${tasks.map(t=>`<li>${esc(t.operationTask)}: <b class="${esc(t.status)}">${esc(t.status)}</b> · due T${t.deadline}${t.operationTask==='siege'?` · ${t.produced}/${p.requiredSiege} recruited`:''}</li>`).join('')}</ul>${p.house===viewer&&tasks.some(t=>t.operationTask==='supply'&&t.status==='pending'&&!t.delivered)?`<button data-operation-supply="${esc(o.id)}">Deliver ${p.food} food</button>`:''}</section>`;
  }).join('')}${ongoingOperation(o)&&own?.status==='accepted'?`<p class="fine">Your armies follow your orders. Rally your forces, then attack during the shared window. Leaving breaks outstanding commitments.</p><button class="danger" data-operation-leave="${esc(o.id)}">${o.owner===viewer?'Abandon operation':'Withdraw from operation'}</button>`:''}</article>`;
}
function createForm(s,viewer) {
  const allies=s.kingdoms.filter(k=>k.id!==viewer&&alive(s,k.id)&&treaty(s,viewer,k.id,'alliance')&&!atWar(s,viewer,k.id));
  const targets=Object.values(s.tiles).map(t=>t.knownCapital?{...t,owner:t.knownCapital}:t).filter(t=>t.owner&&t.owner!==viewer&&t.building&&!treaty(s,viewer,t.owner,'alliance'));
  if(!allies.length||!targets.length)return '<p class="fine">Form an alliance to plan a shared operation.</p>';
  const row=(k,leader=false)=>`<fieldset data-operation-house="${esc(k.id)}"><legend>${leader?house(s,k.id):`<label><input type="checkbox" name="include"> ${house(s,k.id)}</label>`}</legend><label>Role<select name="role" ${leader?'disabled':''}>${Object.entries(OPERATION_ROLES).filter(([id])=>!leader||id==='assault').map(([id,name])=>`<option value="${id}" ${!leader&&id==='flank'?'selected':''}>${name}</option>`).join('')}</select></label><label>Rally point<select name="rally">${settlements(s).filter(t=>t.owner===k.id||!leader&&t.owner===viewer).map(t=>`<option value="${esc(t.id)}" ${t.owner===k.id&&t.capital===k.id?'selected':''}>${place(s,t.id)} · ${house(s,t.owner)}</option>`).join('')}</select></label><div class="form-row"><label>Troops<input name="troops" type="number" min="0" max="500" value="${leader?30:20}" required></label><label>New siege<input name="siege" type="number" min="0" max="20" value="0" required></label><label>Food<input name="food" type="number" min="0" max="250" value="0" ${leader?'readonly':''} required></label></div></fieldset>`;
  return `<details><summary class="section-label">PLAN AN OPERATION</summary><form id="operation-form"><label>Operation name<input name="operationName" maxlength="60" value="Operation Iron Gate" required></label><label>Objective<select name="objective">${targets.map(t=>{const why=strategicLocation(s,t,viewer).reasons;return `<option value="${esc(t.id)}">${place(s,t.id)} · ${house(s,t.owner)}${why.length?` · ${esc(why.join(', '))}`:''}</option>`;}).join('')}</select></label><div class="form-row"><label>Attack from turn<input name="attackStart" type="number" min="${s.turn+1}" max="${s.turn+20}" value="${s.turn+4}" required></label><label>Through turn<input name="attackEnd" type="number" min="${s.turn+1}" max="${s.turn+24}" value="${s.turn+7}" required></label></div>${row(kingdom(s,viewer),true)}${allies.map(k=>row(k)).join('')}<p class="fine">Select at least one ally. Suppliers need 0 troops and 10–250 food. Defenders rally in your territory. Siege requirements include new recruitment after acceptance. Allies can accept, decline, or counter with fewer troops.</p><button type="submit" class="full">Propose operation</button></form></details>`;
}
export function warRoomPanel(s) {s=knowledgeView(s,localHouseId(s));
  const viewer=localHouseId(s),operations=(s.cooperation?.operations||[]).filter(o=>o.owner===viewer||['invited','accepted','counter'].includes(operationMember(o,viewer)?.status));
  const negotiations=(s.cooperation?.proposals||[]).filter(p=>[p.from,p.to].includes(viewer)&&['pending','counter'].includes(p.status));
  return `<span class="eyebrow">STRATEGIC COUNCIL</span><h2>War Room</h2><p class="fine">Private operations, binding commitments, and dated intelligence. Preparations create exposure; counterintelligence reduces disclosure.</p>${createForm(s,viewer)}<div class="section-label">DIPLOMATIC PROPOSALS</div>${negotiations.map(p=>`<article class="realm-card"><strong>${house(s,p.from)} → ${house(s,p.to)} · ${esc(p.kind)}</strong><p>${esc(p.reason)}</p><p class="fine">${p.duration} turns · ${esc(p.status)} · expires T${p.expires}</p><p class="fine">${esc(p.response)}</p>${viewer===(p.status==='counter'?p.from:p.to)?decisionButtons(p.id,'cooperation-answer',p.status==='counter'?viewer:''):'<p class="fine">Awaiting the other court.</p>'}</article>`).join('')||'<p class="fine">No pending negotiations.</p>'}<div class="section-label">YOUR OPERATIONS</div>${operations.slice().reverse().map(o=>operationCard(s,o,viewer)).join('')||'<p class="fine">No shared operations yet.</p>'}<div class="section-label">OBSERVED MOBILIZATIONS</div>${publicMobilizations(s,viewer).map(x=>`<p class="fine">${esc(x.text)}</p>`).join('')||'<p class="fine">No large movements observed near your frontier.</p>'}<div class="section-label">DISCOVERED OPERATIONS</div>${visibleOperations(s,viewer).map(r=>`<article class="realm-card"><strong>Observed T${r.turn} · ${['','Partial','Detailed','Extensive'][r.detail]} intelligence</strong><p>${esc(r.text)}</p>${r.snapshot.roles?`<ul>${r.snapshot.roles.map(p=>`<li>${house(s,p.house)}: ${esc(OPERATION_ROLES[p.role])} · rally ${place(s,p.rally)}</li>`).join('')}</ul>`:''}<p class="fine">This report is a snapshot. Plans may have changed since this observation.</p></article>`).join('')||'<p class="fine">No enemy operation has been discovered.</p>'}`;
}
