import {RULES,finite,distance,move,roundKey} from './core.mjs';
import {createView} from './view.mjs';
import {$,connect,notify,wireLifecycle,updateHUD} from './ui.mjs';
const coarse=matchMedia('(pointer:coarse)').matches,keys=new Set(),input={mx:0,my:0,lx:0,ly:0,sprint:false,jump:false};
const me={x:0,z:0,y:RULES.playerHeight,yaw:0,pitch:0,vx:0,vz:0,vy:0};let room,view,frame,timer,lastFrame=performance.now(),lastHUD=0,lastLife='',closed=false;
if(coarse)$('teamPanel').open=false;
function reset(){keys.clear();Object.assign(input,{mx:0,my:0,lx:0,ly:0,sprint:false,jump:false});for(const id of ['moveKnob','lookKnob'])$(id).style.transform='translate(0,0)';$('sprintBtn').classList.remove('active');me.vx=me.vz=0;}
function lock(){if(!coarse){document.activeElement?.blur?.();try{Promise.resolve($('scene').requestPointerLock?.()).catch(e=>notify(e.message));}catch(e){notify(e.message);}}}
$('lockBtn').addEventListener('click',lock);$('scene').addEventListener('click',()=>{if(room?.state?.phase==='play')lock();});
const down=e=>{if(e.target.closest?.('button,summary,input'))return;const key=e.key.toLowerCase();if(['w','a','s','d','shift',' ','arrowup','arrowdown','arrowleft','arrowright'].includes(key)){e.preventDefault();keys.add(key);if(key===' ')input.jump=true;}},up=e=>keys.delete(e.key.toLowerCase());
const mouse=e=>{if(document.pointerLockElement!==$('scene')||!room?.playable())return;me.yaw-=e.movementX*.0022;me.pitch=Math.max(-1.35,Math.min(1.35,me.pitch-e.movementY*.0022));};
window.addEventListener('keydown',down);window.addEventListener('keyup',up);document.addEventListener('mousemove',mouse);window.addEventListener('blur',reset);document.addEventListener('pointerlockchange',reset);
function joystick(stick,knob,xKey,yKey){let pointer=null;const update=e=>{const r=stick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.35,len=Math.hypot(dx,dy),scale=Math.min(1,max/Math.max(1,len));input[xKey]=dx*scale/max;input[yKey]=dy*scale/max;knob.style.transform=`translate(${dx*scale}px,${dy*scale}px)`;};stick.addEventListener('pointerdown',e=>{if(pointer!==null)return;e.preventDefault();pointer=e.pointerId;stick.setPointerCapture(pointer);update(e);});stick.addEventListener('pointermove',e=>{if(e.pointerId===pointer)update(e);});const end=e=>{if(e.pointerId!==pointer)return;pointer=null;input[xKey]=input[yKey]=0;knob.style.transform='translate(0,0)';};for(const event of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(event,end);}
joystick($('moveStick'),$('moveKnob'),'mx','my');joystick($('lookStick'),$('lookKnob'),'lx','ly');
$('sprintBtn').addEventListener('pointerdown',e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);input.sprint=true;e.currentTarget.classList.add('active');});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('sprintBtn').addEventListener(event,()=>{input.sprint=false;$('sprintBtn').classList.remove('active');});$('jumpBtn').addEventListener('pointerdown',e=>{e.preventDefault();input.jump=true;});
$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen?.();}catch(e){notify(e.message);}});
function syncSelf(){const self=room?.me();if(!self||!room.joined)return;const life=`${room.joined}:${self.sessionId}:${self.life}`;if(lastLife!==life){lastLife=life;Object.assign(me,{x:finite(room.pose?.x,self.x),z:finite(room.pose?.z,self.z),y:RULES.playerHeight,yaw:finite(room.pose?.yaw),pitch:0,vx:0,vz:0,vy:0});reset();}if(self.alive===false){me.vx=me.vz=0;}$('dead').style.opacity=self.alive===false?'1':'0';}
function overlay(){const s=room.state,p=room.me();$('lockBtn').hidden=true;if(!s){$('centerMsg').hidden=false;$('centerTitle').textContent='Waiting for the Dungeon Master';$('centerSub').textContent='The dungeon opens when the DM is ready or the setup timer ends.';return;}
  if(!room.playable()){$('centerMsg').hidden=false;$('centerTitle').textContent='Synchronizing the dungeon';$('centerSub').textContent=room.net;return;}
  if(s.phase==='setup'){$('centerMsg').hidden=false;$('centerTitle').textContent='The dungeon is being prepared';$('centerSub').textContent='Your team will enter together. Name markers show teammates, and gold marks the crown carrier.';}
  else if(s.phase==='ended'){$('centerMsg').hidden=false;$('centerTitle').textContent=s.winner==='players'?'🏆 Your team escaped!':'The Dungeon Master wins';$('centerSub').textContent=s.winner==='players'?`${s.winnerName||'A teammate'} brought the crown to the entrance.`:'The five-minute timer ran out. Return to the lobby to play another round.';}
  else if(p?.alive===false){$('centerMsg').hidden=false;$('centerTitle').textContent=`Caught — respawning in ${Math.ceil(Math.max(0,p.deadUntil-room.now())/1000)}s`;$('centerSub').textContent='The team can still recover the crown. You will return safely at the entrance.';}
  else if(!coarse&&document.pointerLockElement!==$('scene')){$('centerMsg').hidden=false;$('centerTitle').textContent='Ready to explore';$('centerSub').textContent='Click to look around. WASD moves, Shift sprints, and Space jumps. Press Esc to release the mouse.';$('lockBtn').hidden=false;}
  else $('centerMsg').hidden=true;
}
function animate(now){if(closed)return;const dt=Math.min(.05,Math.max(0,(now-lastFrame)/1000));lastFrame=now;
  if(room&&view&&room.maze){syncSelf();const self=room.me(),canMove=room.state.phase==='play'&&self?.alive!==false&&room.playable()&&(coarse||document.pointerLockElement===$('scene'));
    if(canMove){let x=coarse?input.mx:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),z=coarse?-input.my:(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0);const len=Math.hypot(x,z);if(len>1){x/=len;z/=len;}if(coarse){me.yaw-=input.lx*2.8*dt;me.pitch=Math.max(-1.35,Math.min(1.35,me.pitch-input.ly*2.2*dt));}const speed=keys.has('shift')||input.sprint?5.4:3.9,sy=Math.sin(me.yaw),cy=Math.cos(me.yaw),k=1-Math.exp(-18*dt);me.vx+=((x*cy-z*sy)*speed-me.vx)*k;me.vz+=((-x*sy-z*cy)*speed-me.vz)*k;const p=move(room.maze,me,me.vx*dt,me.vz*dt);me.x=p.x;me.z=p.z;if(input.jump&&me.y<=RULES.playerHeight+.001)me.vy=3.6;input.jump=false;me.vy-=10.5*dt;me.y=Math.max(RULES.playerHeight,me.y+me.vy*dt);if(me.y===RULES.playerHeight)me.vy=0;}
    else{me.vx=me.vz=0;input.jump=false;}
    room.setPose({x:me.x,z:me.z,yaw:me.yaw,vx:me.vx,vz:me.vz});view.render(room,me,dt);
    if(now-lastHUD>120){lastHUD=now;updateHUD(room,me);overlay();if(room.state.phase==='play'&&self){if(self.alive===false&&room.now()>=finite(self.deadUntil))room.respawn();else if(self.alive!==false){if(room.state.carrierId===room.uid&&me.z>room.maze.h*room.maze.size/2+1.8)room.escape();else if(room.state.crown&&!room.state.carrierId&&distance(me,room.state.crown)<1.6)room.pickup();}}}
  }
  frame=requestAnimationFrame(animate);
}
const resize=()=>view?.resize();window.addEventListener('resize',resize);
async function boot(){try{view=await createView($('scene'),$('markers'));room=await connect('player',syncSelf);syncSelf();timer=setInterval(()=>room.tick(.05),50);wireLifecycle(room,()=>{closed=true;clearInterval(timer);cancelAnimationFrame(frame);window.removeEventListener('resize',resize);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',reset);document.removeEventListener('mousemove',mouse);document.removeEventListener('pointerlockchange',reset);view.close();},reset);frame=requestAnimationFrame(animate);}catch(e){console.error(e);room?.close();view?.close();$('centerMsg').hidden=false;$('centerTitle').textContent='Unable to open the dungeon';$('centerSub').textContent=e.message;}}
boot();
