/* Render every new weapon, species gait and warning through the shipped build. */
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../../apes-together-strong.html')).href);await page.locator('#newRun').click();await page.waitForFunction(()=>ATS.game?.time>.1);await page.keyboard.press('Escape');
 const images=await page.evaluate(()=>{
  const r=ATS.renderer,c=document.createElement('canvas');c.width=1440;c.height=1060;const ctx=c.getContext('2d');ctx.fillStyle='#102526';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#ebddb3';ctx.font='600 28px system-ui';ctx.fillText('SAVE THE APE  /  FORTRESS ARSENAL',48,58);ctx.font='14px system-ui';ctx.fillStyle='#a5bdb0';ctx.fillText('Species movement, infantry specialists and the new fortress weapons — actual game artwork',48,86);r.quality='high';r.detailLevel=0;r.reducedMotion=false;r.camera.zoom=1;r.time=10;r.actorSpriteBudget=100;
  for(let i=0;i<6;i++){const species=ATSSiegeSpecies[i],x=120+i*236;ctx.fillStyle='#193735';ctx.fillRect(x-98,120,204,298);ctx.fillStyle='#dccc9e';ctx.font='600 15px system-ui';ctx.textAlign='center';ctx.fillText(species[0].toUpperCase()+species.slice(1),x,148);for(let f=0;f<2;f++){ctx.save();ctx.translate(x,265+f*130);ctx.scale(1.35,1.35);r.drawApe(ctx,{id:species,species,age:200,hp:100,maxHp:100,moving:true,phase:f*Math.PI/2,dir:0},false);ctx.restore()}}
  const variants=['repeater','bombard','cyclone'];for(let i=0;i<3;i++){ctx.save();ctx.translate(260+i*458,636);ctx.scale(1.7,1.7);r.drawVehicle(ctx,{id:variants[i],variant:variants[i],vehicleClass:'tank',kind:'tank',hp:100,maxHp:100,dir:0,turretDir:.15,moving:true,phase:0});ctx.restore();ctx.fillStyle='#dccc9e';ctx.font='600 17px system-ui';ctx.textAlign='center';ctx.fillText(ATSVehicleVariants[variants[i]].label,260+i*458,716)}
  for(let i=0;i<4;i++){const role=['breacher','spotter','bombardier','rotary'][i];ctx.save();ctx.translate(105+i*181,891);ctx.scale(1.6,1.6);r.drawHuman(ctx,{id:role,role,kind:ATSHumanRoles[role].weapon,dir:0,hp:100,maxHp:100,state:'patrol',moving:true});ctx.restore();ctx.fillStyle='#dccc9e';ctx.font='13px system-ui';ctx.fillText(ATSHumanRoles[role].label,105+i*181,930)}
  for(let i=0;i<3;i++){const type=['gatlingNest','mortarNest','powerRelay'][i];ctx.save();ctx.translate(850+i*220,894);ctx.scale(1.65,1.65);r.drawObject(ctx,{id:type,type,hp:100,maxHp:100,mountDir:0,dir:0,powered:true});ctx.restore();ctx.fillStyle='#dccc9e';ctx.font='13px system-ui';ctx.fillText(['Gatling nest','Mortar nest','Power relay'][i],850+i*220,930)}
  ctx.textAlign='left';ctx.fillStyle='#8ca799';ctx.font='14px system-ui';ctx.fillText('O / Cancel returns to King controls. Right-click ends a route with an area attack.',48,1015);
  const sample=document.createElement('canvas');sample.width=120;sample.height=130;const sc=sample.getContext('2d');function pose(time,reduced){sc.clearRect(0,0,120,130);r.time=time;r.reducedMotion=reduced;sc.save();sc.translate(60,115);r.drawApe(sc,{id:'gait',species:'gibbon',age:200,hp:100,maxHp:100,moving:true,phase:0,dir:0},false);sc.restore();return sample.toDataURL()}
  const motion=[pose(1,false),pose(1.2,false)],reduced=[pose(1,true),pose(1.2,true)];r.reducedMotion=false;
  return{sheet:c.toDataURL(),motion:motion[0]!==motion[1],reduced:reduced[0]===reduced[1]};
 });assert.ok(images.motion);assert.ok(images.reduced);
 if(process.env.QA_ARTIFACT_DIR){fs.mkdirSync(process.env.QA_ARTIFACT_DIR,{recursive:true});fs.writeFileSync(path.join(process.env.QA_ARTIFACT_DIR,'arsenal-artwork.png'),Buffer.from(images.sheet.split(',')[1],'base64'))}
 await page.evaluate(()=>{const g=ATS.game;g.world.objects.clear();g.world._spatial.clear();g.world.sites.clear();g.world.ensure=()=>{};g.world.stream=()=>{};g.spawnSites=()=>{};g.humans=[];g.vehicles=[];g.apes=[];g.king.x=0;g.king.y=360;g.king.hp=g.king.maxHp=10000;g.nextDirectorAt=g.nextConvoyAt=g.heliTimer=1e9;g.time=100;g.world._buildSite({objects:[],sites:[]},{id:'arsenal-2',x:0,y:-300,type:'regionalCommand',military:true,tier:5,guards:100,count:100,radius:620,extentX:500,extentY:430,layout:0});g.world.reveal(0,-300,1800);const site=g.world.sites.get('arsenal-2');site.known=true;for(const id of site.objects){const o=g.world.objects.get(id);if(o.type==='gateControl')o.discovered=true}for(let i=0;i<24;i++){const a=g.makeApe(-300+i%8*38,280+Math.floor(i/8)*42,'hold');a.species=ATSSiegeSpecies[i%6];g.siege.balance(a,true)}for(const [i,variant]of ['repeater','bombard','cyclone'].entries()){const v={id:'vehicle-art-'+i,x:260+i*135,y:140-i*80,variant,kind:'tank',vehicleClass:'tank',dir:1.8,turretDir:1.8};g.forces.initVehicle(v);g.vehicles.push(v)}g.syncIndexes();g.apeGrid.rebuild([g.king,...g.apes]);g.humanGrid.rebuild([]);g.vehicleGrid.rebuild(g.vehicles);g.siege.select(['gorilla','gibbon']);g.siege.draft({x:-370,y:90},'move');g.siege.draft({x:-350,y:-180},'move');g.siege.draft({x:-250,y:-230},'attackArea');g.performance.beginStep(g);g.forces.tick(0);ATS.renderer.camera.zoom=.7;ATS.renderer.camera.armyFocus={x:0,y:0};ATS.renderer.camera.x=0;ATS.renderer.camera.y=0;ATS.army.update(true)});
 await page.keyboard.press('Escape');await page.waitForTimeout(120);if(process.env.QA_ARTIFACT_DIR)await page.screenshot({path:path.join(process.env.QA_ARTIFACT_DIR,'arsenal-battlefield.png')});assert.deepEqual(errors,[]);console.log('PASS: all species, moving/reduced-motion poses, specialist art, three tank turrets, powered defenses and real fortress battlefield render without browser errors.');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
