'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {loadEngine}=require('./performance-harness.cjs');
function arena(){const c=loadEngine();if(!c.ATSChampions)vm.runInContext(fs.readFileSync(path.join(__dirname,'../champions.js'),'utf8'),c);const g=new c.ATSGame('CHAMPION-TEST');g.world.objects.clear();g.world._spatial.clear();g.world.sites.clear();g.world.ensure=()=>{};g.world.getSites=()=>[];g.world.terrain=()=>({biome:'forest',water:false});g.world.waterBlocked=()=>false;g.world.lineClear=()=>true;g.world.discovered.clear();g.spawnSites=()=>{};g.nextDirectorAt=g.nextConvoyAt=g.heliTimer=1e9;return{g,c}}
function ape(g,species='gorilla',x=0,y=0){const a=g.makeApe(x,y,'follow');a.species=species;g.siege.balance(a,true);a.attackCD=0;return a}
function grids(g){g.syncIndexes();g.apeGrid.rebuild([g.king,...g.apes]);g.humanGrid.rebuild(g.humans);g.vehicleGrid.rebuild(g.vehicles);g.navigation.beginFrame(g.time);g.performance.beginStep(g)}
function object(g,data){const o={id:'test-'+g.nextId++,x:100,y:0,hp:1000,maxHp:1000,solid:true,faction:'human',r:15,...data};g.world.objects.set(o.id,o);g.world._indexObject(o);return o}

test('all six species have four distinct elite archetypes, persistent gear and a hard rarity cap',()=>{const {g,c}=arena();assert.equal(Object.keys(c.ATSChampionArchetypes).length,6);for(const [species,classes]of Object.entries(c.ATSChampionArchetypes)){assert.equal(classes.length,4);for(const kind of classes){const a=ape(g,species),hp=a.maxHp;assert.equal(g.champions.promote(a,{archetype:kind.id}),a);assert.equal(a.champion.archetype,kind.id);assert.ok(a.maxHp>hp);assert.ok(a.champion.item&&a.champion.passive);g.champions.promote(a);assert.equal(a.maxHp,hp+a.champion.healthBonus)}}const excess=ape(g);assert.equal(g.champions.promote(excess),null);assert.ok(excess.veteran);assert.equal(g.champions.roster().filter(a=>a.champion).length,24)});

test('wounded champion recovery requires a safe settlement and sanctuary accelerates it',()=>{const {g}=arena(),a=ape(g);g.champions.promote(a,{archetype:'bulwark',injured:true});const max=a.maxHp;assert.equal(a.recoveryRemaining,90);assert.equal(g.champions.eligible(a),false);g.time=2;grids(g);g.champions.tick();assert.equal(a.recoveryRemaining,90);g.command('settle');const s=g.settlements[0];s.specialization='sanctuary';s.attack=false;g.time=3;grids(g);g.champions.tick();assert.equal(a.recoveryRemaining,88);s.attack=true;g.time=4;g.champions.tick();assert.equal(a.recoveryRemaining,88);s.attack=false;g.champions.recover(a,44,2);assert.equal(a.recoveryRemaining,undefined);assert.equal(a.maxHp,max);assert.equal(g.champions.recall(a.id),true);assert.equal(g.champions.eligible(a),true)});

test('class bonuses affect gates, exposed devices, tank flanks, stones and local protection',()=>{const {g}=arena(),wall=object(g,{type:'wall'}),radio=object(g,{type:'radio',x:200}),a=ape(g);g.champions.promote(a,{archetype:'wallbreaker'});g.damageObject(wall,20,a);assert.equal(wall.hp,967);const sab=ape(g,'chimpanzee');g.champions.promote(sab,{archetype:'saboteur'});g.damageObject(radio,20,sab);assert.equal(radio.hp,965);const slinger=ape(g,'capuchin');g.champions.promote(slinger,{archetype:'slingerAce'});assert.ok(g.apeDamage(slinger,6)>11);const tankBuster=ape(g,'gorilla',-20,0);g.champions.promote(tankBuster,{archetype:'tankBuster'});const tank={id:'vehicle-test',x:0,y:0,hp:1000,maxHp:1000,dir:0,vehicleClass:'tank'};g.forces.vehicleDamage=(a,n)=>n;g.hurt(tank,20,tankBuster);assert.equal(tank.hp,969);const guard=ape(g);g.champions.promote(guard,{archetype:'bulwark'});const friend=ape(g);grids(g);g.time=2;g.champions.tick();const before=friend.hp;g.hurt(friend,20,{type:'bullet',x:100,y:0});assert.ok(Math.abs(before-friend.hp-17.6)<1e-6)});

test('division assigns unique members and moves them toward real destinations in formation',()=>{const {g}=arena(),a=ape(g,'gorilla',0,0),b=ape(g,'chimpanzee',0,35),other=ape(g,'mandrill',0,-35);g.champions.veteran(a);g.champions.veteran(other);const d=g.champions.assign('vanguard',a.id,[a.id,b.id,b.id]);assert.equal(d.memberIds.length,2);g.champions.configure(d.id,{destination:{x:350,y:0},formation:'line'});grids(g);g.champions.plan();const start=b.x;for(let i=0;i<20;i++){g.time+=.05;g.navigation.beginFrame(g.time);g.updateApe(b,.05)}assert.ok(b.x>start+45,'follower advances through normal collision navigation');assert.notDeepEqual(g.champions.formation(d,a),g.champions.formation(d,b));g.champions.assign('defenders',other.id,[b.id]);assert.equal(d.memberIds.includes(b.id),false);assert.equal(b.divisionId,'defenders');assert.equal(g.champions.members.get(b.id).id,'defenders')});

test('shared sabotage focus chooses controls over infantry and followers damage the real objective',()=>{const {g}=arena(),a=ape(g,'chimpanzee',80,0),b=ape(g,'chimpanzee',82,12),human=g.makeHuman(115,40,null),control=object(g,{type:'gateControl',x:110,y:0,discovered:true,hp:200,maxHp:200});g.champions.promote(a,{archetype:'saboteur'});const d=g.champions.assign('saboteurs',a.id,[b.id]);g.champions.configure(d.id,{stance:'sabotage',priority:'devices',destination:{x:200,y:0}});grids(g);g.champions.plan();assert.equal(d.target.id,control.id);const hp=control.hp;g.updateApe(a,.1);assert.ok(control.hp<hp);assert.equal(human.hp,human.maxHp);assert.ok(g.champions.plannerStats.candidates<=52)});

test('fallback rules, commander loss and direct recalls remain authoritative',()=>{const {g}=arena(),a=ape(g,'mandrill',300,0),b=ape(g,'chimpanzee',300,35);g.champions.veteran(a);const d=g.champions.assign('vanguard',a.id,[b.id]);g.champions.configure(d.id,{destination:{x:800,y:0}});a.hp=a.maxHp*.2;grids(g);g.champions.plan();assert.equal(d.fallingBack,true);const start=a.x;g.updateApe(a,.2);assert.ok(a.x<start,'wounded division retreats toward king');g.champions.configure(d.id,{fallback:'never'});a.hp=0;grids(g);g.champions.plan();assert.equal(d.fallingBack,undefined,'hold-at-all-costs keeps the surviving division active');g.champions.configure(d.id,{fallback:'commander'});g.champions.plan();assert.equal(d.fallingBack,true);g.commandCD=0;assert.equal(g.command('recall'),true);assert.equal(d.suspended,true);assert.equal(b.state,'follow')});

test('divisions continue offscreen and cannot overlap formation slots in a full 256-ape division',()=>{const {g}=arena(),a=ape(g,'gorilla',2100,0);g.champions.veteran(a);for(let i=0;i<255;i++)ape(g,'chimpanzee',2100+i%16*20,Math.floor(i/16)*20);const d=g.champions.assign('vanguard',a.id,g.apes.map(a=>a.id));g.champions.configure(d.id,{destination:{x:2700,y:0}});assert.equal(g.actorTier(a),1);for(const formation of ['wedge','line','spread','column','shield']){g.champions.configure(d.id,{formation});const positions=g.apes.map(a=>g.champions.formation(d,a));assert.equal(new Set(positions.map(p=>p.x+','+p.y)).size,256)}});

test('champions, injury, gear, division orders and fallen-command retreat survive save/load without stat growth',()=>{const {g,c}=arena(),a=ape(g,'gorilla'),b=ape(g,'chimpanzee');g.champions.promote(a,{archetype:'wallbreaker'});g.champions.assign('vanguard',a.id,[b.id]);g.champions.configure('vanguard',{stance:'rescue',formation:'spread',destination:{x:540,y:250}});a.hp=111;const max=a.maxHp;for(let i=0;i<3;i++){const loaded=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(g.serialize()))),copy=loaded.apesById.get(a.id);assert.equal(copy.champion.item,'Gate maul');assert.equal(copy.maxHp,max);assert.equal(copy.hp,111);assert.equal(loaded.champions.divisions.vanguard.stance,'rescue');assert.equal(loaded.champions.members.get(b.id).id,'vanguard')}a.hp=0;grids(g);g.champions.plan();const loaded=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(g.serialize())));assert.equal(loaded.champions.divisions.vanguard.fallingBack,true);assert.equal(loaded.champions.divisions.vanguard.commanderId,a.id)});

test('stationed support roles produce bounded economic bonuses and refits have a finite cap',()=>{const {g}=arena(),a=ape(g,'orangutan'),b=ape(g,'orangutan');g.champions.promote(a,{archetype:'masterBuilder'});g.champions.promote(b,{archetype:'greatForager'});g.command('settle');const s=g.settlements[0],bonus=g.champions.settlementBonus(s);assert.equal(bonus.build,1.2);assert.equal(bonus.food,1.2);assert.equal(g.champions.reforge(a.id),true);assert.equal(g.champions.reforge(a.id),true);assert.equal(g.champions.reforge(a.id),false);assert.equal(a.champion.gearLevel,2);a.recoveryRemaining=20;assert.equal(g.champions.settlementBonus(s).build,1)});

test('a strong mandrill rally reaches a larger area, lasts longer and retains cooldown',()=>{const {g}=arena(),a=ape(g,'mandrill'),b=ape(g,'chimpanzee',210,0);g.champions.promote(a,{archetype:'warcaller'});grids(g);g.siege.select(['mandrill']);assert.equal(g.siege.rally(),true);g.time=.5;g.siege.updateRally(a);assert.equal(b.rallyUntil,10.5);assert.equal(g.siege.rallyReady,23.5);assert.equal(g.siege.rally(),false)});

test('large army planning costs are bounded by six divisions and does not mutate random state',()=>{const {g,c}=arena();for(let i=0;i<600;i++)ape(g,'chimpanzee',i%30*15,Math.floor(i/30)*15);for(let i=0;i<6;i++){const leader=g.apes[i*100];g.champions.veteran(leader);g.champions.assign(c.ATSDivisions[i].id,leader.id,g.apes.slice(i*100,i*100+100).map(a=>a.id));g.champions.configure(c.ATSDivisions[i].id,{stance:'assault'})}for(let i=0;i<100;i++)g.makeHuman(200+i%10*15,Math.floor(i/10)*15,null);grids(g);const random=c.Math.random;let draws=0;c.Math.random=()=>{draws++;return .5};g.champions.plan();c.Math.random=random;assert.equal(draws,0);assert.equal(g.champions.plannerStats.groups,6);assert.ok(g.champions.plannerStats.candidates<=312);assert.ok(g.performance.counters.losTests<=96)});

test('species rebalance, training and scout assignment retain champion health exactly once',()=>{const {g}=arena(),a=ape(g);g.champions.promote(a,{archetype:'wallbreaker'});a.hp=80;const base=a.maxHp;g.siege.balance(a,true);assert.equal(a.maxHp,base);assert.equal(a.hp,80);g.applyTraining(a,2);assert.equal(a.maxHp,base+24);g.command('settle');g.commandCD=0;g.command('patrol');assert.equal(a.state,'scout');assert.equal(a.maxHp,base+49);assert.equal(a.hp,80);g.siege.balance(a,true);assert.equal(a.maxHp,base+49);assert.equal(a.hp,80)});

test('stealth concealment never blocks critical projectile visibility checks',()=>{const {g}=arena(),a=ape(g,'gibbon',400,0),h=g.makeHuman(200,0,null);g.champions.promote(a,{archetype:'silentInfiltrator'});grids(g);assert.equal(g.lineVisible(h,a),false);g.performance.losRemaining=0;assert.equal(g.lineVisible(h,a,true),true)});

test('rescue division attacks release machinery rather than wasting strikes on locked cells',()=>{const {g}=arena(),a=ape(g,'chimpanzee',0,0);g.champions.veteran(a);const d=g.champions.assign('reserve',a.id,[]),cell=object(g,{type:'cage',x:50,count:3,prisonLock:'control',siteId:'lock-test'}),control=object(g,{type:'prisonControl',x:180,siteId:'lock-test'});g.world.sites.set('lock-test',{id:'lock-test',prison:{controlsDown:false}});g.champions.configure(d.id,{stance:'rescue'});grids(g);g.champions.plan();assert.equal(d.target.id,control.id);assert.notEqual(d.target.id,cell.id)});
