'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {loadEngine}=require('./performance-harness.cjs');
function arena(){const c=loadEngine();if(!c.ATSEquipment)vm.runInContext(fs.readFileSync(path.join(__dirname,'../equipment.js'),'utf8'),c);const g=new c.ATSGame('EQUIPMENT-TEST');g.world.objects.clear();g.world._spatial.clear();g.world.sites.clear();g.world.ensure=()=>{};g.world.getSites=()=>[];g.world.terrain=()=>({biome:'forest',water:false});g.world.waterBlocked=()=>false;g.world.lineClear=()=>true;g.world.discovered.clear();g.spawnSites=()=>{};g.nextDirectorAt=g.nextConvoyAt=g.heliTimer=1e9;Object.defineProperty(g,'progression',{value:{tier:1}});return{g,c}}
function ape(g,species='capuchin',x=50,y=30){const a=g.makeApe(x,y,'follow');a.species=species;g.siege.balance(a,true);g.syncIndexes();return a}
function village(g){for(let i=0;i<8;i++)ape(g,'chimpanzee');g.command('settle');const s=g.settlements[0];s.wood=2000;s.food=2000;s.attack=false;const w={id:s.id+'-equipment-workshop',kind:'workShelter',x:55,y:0,stage:4,hp:250,maxHp:250};s.structures.push(w);g.syncIndexes();return{s,w}}
function buy(g,s,w,kind){return g.equipment.purchase(s.id,w.id,kind)}
function work(g,seconds){for(let i=0;i<seconds;i++){g.time++;g.equipment.tick(1)}}

test('workshop purchases require milestone, completed building, proximity, and real village supplies',()=>{const {g}=arena(),{s,w}=village(g);ape(g);g.progression.tier=0;let result=buy(g,s,w,'spear');assert.equal(result.ok,false);assert.match(result.reason,/100 apes/);assert.equal(s.wood,2000);g.progression.tier=1;w.stage=3;assert.equal(buy(g,s,w,'spear').ok,false);w.stage=4;g.king.x=400;assert.equal(buy(g,s,w,'spear').ok,false);g.king.x=0;s.food=23;assert.equal(buy(g,s,w,'spear').ok,false);s.food=2000;assert.equal(buy(g,s,w,'spear').ok,true);assert.equal(s.wood,1972);assert.equal(s.food,1976);assert.equal(g.equipment.workshopAt().settlement,s)});

test('global artisan queue equips exactly one individual at a time across multiple workshops',()=>{const {g}=arena(),{s,w}=village(g),a=ape(g),b=ape(g),other={...w,id:w.id+'-other',x:60};s.structures.push(other);assert.equal(buy(g,s,w,'spear').ok,true);assert.equal(buy(g,s,other,'spear').ok,true);assert.notEqual(g.equipment.queue[0].actorId,g.equipment.queue[1].actorId);work(g,17);assert.equal(g.equipment.queue[0].progress,17);assert.equal(g.equipment.queue[1].progress,0);assert.equal(g.equipment.stats.activeWorkers,1);work(g,1);assert.equal(a.equipment.spear,true);assert.equal(b.equipment,undefined);assert.equal(g.equipment.queue[0].progress,0);work(g,18);assert.equal(b.equipment.spear,true);assert.equal(g.equipment.queue.length,0)});

test('real recipients walk to workshops; raids, distance, and destruction pause progress',()=>{const {g}=arena(),{s,w}=village(g),a=ape(g,'gorilla',230,0);assert.equal(buy(g,s,w,'cuffs').ok,true);work(g,3);assert.equal(g.equipment.queue[0].progress,0);const x=a.x;g.navigation.beginFrame(g.time);g.equipment.updateApe(a,.1);assert.ok(a.x<x);a.x=w.x+55;a.y=w.y;work(g,4);assert.equal(g.equipment.queue[0].progress,4);s.attack=true;work(g,3);assert.equal(g.equipment.queue[0].progress,4);s.attack=false;w.hp=0;work(g,3);assert.match(g.equipment.state(),/destroyed/);assert.equal(g.equipment.queue[0].progress,4);assert.equal(a.equipment,undefined);g.equipment.cancel(g.equipment.queue[0].id);assert.ok(s.wood<2000&&s.wood>1964);assert.equal(g.equipment.queue.length,0)});

test('individual spears travel and damage on impact, while cuffs strengthen melee',()=>{const {g}=arena(),{s,w}=village(g),a=ape(g),gorilla=ape(g,'gorilla');buy(g,s,w,'spear');work(g,18);const before=g.apeDamage(gorilla,20);buy(g,s,w,'cuffs');work(g,22);assert.ok(Math.abs(g.apeDamage(gorilla,20)-before*1.35)<1e-8);const h=g.makeHuman(150,30,null);h.hp=h.maxHp=100;g.forces.armor=(a,n)=>n;g.syncIndexes();g.humanGrid.rebuild(g.humans);a.hitTimer=0;assert.equal(g.siege.throwAt(a,h,'human'),true);g.time+=.5;g.siege.releaseThrow(a);assert.equal(h.hp,100);assert.equal(g.siege.stones.length,1);const spear=g.siege.stones[0];assert.equal(spear.equipmentType,'spear');assert.ok(spear.damage>g.apeDamage(a,6)*2);g.siege.updateStones(spear.duration+.01);assert.ok(h.hp<90);assert.equal(g.siege.stones.length,0)});

test('torches light the area, make wall climbers conspicuous, and accelerate structural attacks',()=>{const {g}=arena(),{s,w}=village(g),a=ape(g,'gibbon');buy(g,s,w,'torch');work(g,16);assert.equal(a.equipment.torch,true);const lights=g.getLights().filter(l=>l.equipmentTorch);assert.equal(lights.length,1);assert.equal(lights[0].range,115);const target={id:'torch-building',type:'barracks',x:90,y:30,hp:200,maxHp:200,solid:true,faction:'human'};g.world.objects.set(target.id,target);g.damageObject(target,20,a);assert.equal(target.hp,167);const h=g.makeHuman(120,30,null);h.dir=0;g.syncIndexes();g.apeGrid.rebuild([a]);g.performance.beginStep(g);assert.equal(g.perceive(h,{range:180,angle:.3}).seen,a);assert.ok(g.performance.counters.losTests<=96);a.hp=0;work(g,1);assert.equal(g.equipment.lights().length,0)});

test('royal armor is staged to 500 health, protects and strengthens without repeat healing',()=>{const {g,c}=arena(),{s,w}=village(g);g.king.hp=115;assert.equal(buy(g,s,w,'armor').ok,true);assert.equal(buy(g,s,w,'armor').ok,false);work(g,25);assert.equal(g.king.maxHp,240);assert.equal(g.king.hp,195);assert.equal(g.equipment.armorLevel,1);assert.equal(buy(g,s,w,'armor').ok,false);g.progression.tier=2;buy(g,s,w,'armor');work(g,35);assert.equal(g.king.maxHp,350);assert.equal(g.king.hp,305);buy(g,s,w,'armor');work(g,50);assert.equal(g.king.maxHp,500);assert.equal(g.king.hp,455);assert.equal(buy(g,s,w,'armor').ok,false);g.hurt(g.king,100,{type:'bullet',x:100,y:0});assert.equal(g.king.hp,377);const enemy=g.makeHuman(20,0,null);enemy.hp=enemy.maxHp=1000;g.forces.armor=(a,n)=>n;g.hurt(enemy,100,g.king);assert.equal(enemy.hp,830);let loaded=g;for(let i=0;i<3;i++){loaded=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(loaded.serialize())));assert.equal(loaded.king.maxHp,500);assert.equal(loaded.king.hp,377);assert.equal(loaded.equipment.armorLevel,3)}});

test('partly completed queue, actor gear, torches, and traveling spear persist through save/load',()=>{const {g,c}=arena(),{s,w}=village(g),a=ape(g,'gibbon'),b=ape(g,'gorilla');buy(g,s,w,'torch');work(g,16);buy(g,s,w,'cuffs');work(g,7);g.siege.stones.push({id:'saved-spear',equipmentType:'spear',owner:a.id,from:{x:0,y:0},to:{x:100,y:20},x:30,y:6,z:32,z0:28,z1:18,age:.15,duration:.5,targetId:'human-missing',kind:'human',damage:14});let loaded=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(g.serialize())));assert.equal(loaded.apesById.get(a.id).equipment.torch,true);assert.equal(loaded.equipment.torchIds.has(a.id),true);assert.equal(loaded.equipment.queue.length,1);assert.equal(loaded.equipment.queue[0].actorId,b.id);assert.equal(loaded.equipment.queue[0].progress,7);assert.equal(loaded.equipment.queue[0].duration,22);assert.equal(loaded.siege.stones[0].equipmentType,'spear');assert.equal(loaded.siege.stones[0].age,.15);const supplies=loaded.settlement(s.id).wood;loaded=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(loaded.serialize())));assert.equal(loaded.settlement(s.id).wood,supplies);assert.equal(loaded.equipment.queue[0].progress,7)});

test('gear caps, queue size and light roster stay bounded with large armies',()=>{const {g}=arena(),{s,w}=village(g);for(let i=0;i<16;i++){const a=ape(g);a.equipment={spear:true}}ape(g);assert.match(g.equipment.catalog(s.id,w.id).find(e=>e.kind==='spear').reason,/16/);g.progression.tier=2;assert.equal(buy(g,s,w,'spear').ok,true);for(let i=0;i<8;i++)ape(g);for(let i=0;i<7;i++)assert.equal(buy(g,s,w,'spear').ok,true);assert.equal(g.equipment.queue.length,8);assert.equal(buy(g,s,w,'spear').ok,false);for(let i=0;i<100;i++){const a=ape(g,'gibbon');a.equipment={torch:true};g.equipment.torchIds.add(a.id)}assert.equal(g.equipment.lights().length,24);assert.equal(g.equipment.stats.torchLights,24)});

test('repeated light collection does not accumulate torch entries',()=>{const {g}=arena(),{s,w}=village(g);ape(g,'gibbon');buy(g,s,w,'torch');work(g,16);for(let i=0;i<40;i++){const lights=g.getLights();assert.equal(lights.filter(l=>l.equipmentTorch).length,1);assert.equal(new Set(lights.map(l=>l.id)).size,lights.length)} });

test('self-lit torch perception respects fog range even outside the flashlight cone',()=>{const {g}=arena(),{s,w}=village(g),a=ape(g,'gibbon');buy(g,s,w,'torch');work(g,16);a.x=0;a.y=0;const h=g.makeHuman(150,0,null);h.dir=0;g.syncIndexes();g.apeGrid.rebuild([a]);g._weather={kind:'fog',until:g.time+100};g.getLights();g.performance.beginStep(g);assert.equal(g.perceive(h,{range:200,angle:.3}).seen,null,'150 paces exceeds 124 pace fog visibility');h.x=100;delete h._sense;g.performance.beginStep(g);assert.equal(g.perceive(h,{range:200,angle:.3}).seen,a,'torch remains conspicuous inside fog visibility');});
