/* Standalone UI purchase and real renderer gallery for gear, crowns and climbs. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const errors=[];
 const shot=async(page,name)=>{if(process.env.QA_ARTIFACT_DIR){fs.mkdirSync(process.env.QA_ARTIFACT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.QA_ARTIFACT_DIR,name+'.png')})}};
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1040}});page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../../apes-together-strong.html')).href);await page.locator('#newRun').click();await page.keyboard.press('Escape');
  const setup=await page.evaluate(()=>{const g=ATS.game;g.apes=[];g.humans=[];g.vehicles=[];g.helis=[];g.world.objects.clear();g.world._spatial.clear();g.world.sites.clear();g.world.ensure=()=>{};g.world.getSites=()=>[];g.world.terrain=()=>({biome:'forest',water:false,road:false});g.world.waterBlocked=()=>false;g.world.lineClear=()=>true;g.spawnSites=()=>{};g.nextDirectorAt=g.nextConvoyAt=g.heliTimer=1e9;g.progression.tier=2;g.progression.acknowledged=2;g.king.x=g.king.y=0;g.commandCD=0;for(let i=0;i<8;i++)g.makeApe(i*4,20,'follow');g.syncIndexes();g.command('settle');const s=g.settlements[0];s.wood=s.food=2000;s.attack=false;const w={id:s.id+'-ui-workshop',kind:'workShelter',x:250,y:0,stage:4,hp:250,maxHp:250};s.structures.push(w);g.king.x=250;g.king.y=0;const a=g.makeApe(275,30,'follow');a.species='capuchin';g.siege.balance(a,true);g.syncIndexes();window.gearUITest={s,w,a};return{lodgeDistance:Math.hypot(g.king.x-s.x,g.king.y-s.y),workshopDistance:Math.hypot(g.king.x-w.x,g.king.y-w.y)}});
  assert.ok(setup.lodgeDistance>90);assert.equal(setup.workshopDistance,0);await page.locator('#resumeRun').click();await page.keyboard.press('b');assert.equal(await page.evaluate(()=>ATS.screen),'build');assert.ok(await page.locator('#buildTitle').textContent().then(s=>s.includes('Workshop')));const before=await page.evaluate(()=>({wood:gearUITest.s.wood,food:gearUITest.s.food,time:ATS.game.time}));
  const spearCard=page.locator('.equipment-card').filter({has:page.getByText('Throwing spears',{exact:true})});await spearCard.getByRole('button',{name:'Equip one capuchin',exact:true}).click();const purchased=await page.evaluate(()=>({wood:gearUITest.s.wood,food:gearUITest.s.food,queue:ATS.game.equipment.queue.map(j=>({...j})),time:ATS.game.time}));assert.equal(purchased.wood,before.wood-28);assert.equal(purchased.food,before.food-24);assert.equal(purchased.queue.length,1);assert.equal(purchased.time,before.time);assert.equal(purchased.queue[0].progress,0);await shot(page,'workshop-purchase-desktop');
  await page.locator('#closeBuild').click();await page.keyboard.press('Escape');const fitted=await page.evaluate(()=>{const g=ATS.game,a=g.equipment.actor(g.equipment.queue[0]);for(let i=0;i<260;i++)g.update(.1,{});return{equipped:a.equipment?.spear,queue:g.equipment.queue.length,kingHp:g.king.hp,state:g.equipment.state(),position:{x:a.x,y:a.y}}});assert.equal(fitted.equipped,true,JSON.stringify(fitted));assert.equal(fitted.queue,0);assert.ok(fitted.kingHp>0);assert.deepEqual(errors,[]);
  const gallery=await page.evaluate(()=>{const g=ATS.game,root=document.createElement('section');root.id='equipmentGallery';root.style.cssText='position:fixed;inset:0;z-index:1000;overflow:auto;background:#081c21;display:grid;place-content:start center;padding:20px';const cv=document.createElement('canvas');cv.width=1360;cv.height=940;cv.style.cssText='width:min(1360px,96vw);height:auto;display:block';root.append(cv);document.body.append(root);const r=new ATSRenderer(cv),c=cv.getContext('2d');cv.width=1360;cv.height=940;r.w=1360;r.h=940;r.dpr=1;r.camera.zoom=1;r.detailLevel=0;r.quality='high';r.reducedMotion=true;r.time=12;r._equipmentGame=g;c.fillStyle='#081c21';c.fillRect(0,0,cv.width,cv.height);const text=(s,x,y,size=18,color='#dac48d')=>{c.fillStyle=color;c.font='600 '+size+'px Arial';c.textAlign='center';c.fillText(s,x,y)},card=(x,y,w,h)=>{c.fillStyle='#102b2b';c.fillRect(x,y,w,h);c.strokeStyle='#35584c';c.strokeRect(x+.5,y+.5,w-1,h-1)},unit=(a,x,y,scale=2.1,king=false)=>{c.save();c.translate(x,y);c.scale(scale,scale);r.drawApe(c,a,king);c.restore()};text('APES TOGETHER STRONG · PROGRESSION & EQUIPMENT',680,35,23);const actor=(id,species,equipment={})=>({id,species,equipment,hp:160,maxHp:160,dir:.1,age:100,phase:0,state:'follow'});
   for(let tier=0;tier<3;tier++){const x=30+tier*442;card(x,58,422,250);text(['Underpowered King','King of the Jungle','Warlord'][tier],x+211,86);unit({...actor('king'),crownTier:tier},x+211,281,1.5,true)}
   const gear=[['Throwing spears',actor('gear-spear','capuchin',{spear:true})],['Wooden fist cuffs',actor('gear-cuffs','gorilla',{cuffs:true})],['Climber torch',actor('gear-torch','gibbon',{torch:true})],['Sovereign armor · 500 HP',{...actor('king',undefined,{armorLevel:3}),crownTier:2,maxHp:500,hp:500}]];gear.forEach(([label,a],i)=>{const x=30+i*331;card(x,325,311,268);text(label,x+155,355,17);unit(a,x+155,559,i===3?1.55:2.2,i===3)});
   for(let i=0;i<3;i++){const x=30+i*442;card(x,611,422,294);text(['Palisade · climbing','Palisade · crest','Palisade · jump down'][i],x+211,642,17);const a=actor('climber-'+i,'chimpanzee',{torch:true});a.palisadeClimb={elapsed:[.2,.43,.6][i],height:38,fromX:0,fromY:-35,crestX:0,crestY:0,exitX:0,exitY:35};c.save();c.translate(x+211,853);c.scale(2.1,2.1);r.drawFieldBarrier(c,{team:'ape',kind:'palisade',w:94,h:14,hp:200,maxHp:200});c.restore();unit(a,x+211,869,2.1);text(['Slows to climb','Reaches the top','Lands on the far side'][i],x+211,889,13,'#acbfae')}
   const pixels=c.getImageData(0,0,1360,940).data;let lit=0;for(let i=0;i<pixels.length;i+=64)if(pixels[i]>95&&pixels[i+1]>70)lit++;return{lit,gearSprites:r.apeSprites.size,errors:[]};});assert.ok(gallery.lit>1000);await shot(page,'gear-crowns-palisades-gallery');assert.deepEqual(errors,[]);
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.getElementById('equipmentGallery').remove());await page.locator('#resumeRun').click();await page.keyboard.press('b');assert.equal(await page.evaluate(()=>ATS.screen),'build');await page.locator('#equipmentCouncil').scrollIntoViewIfNeeded();await shot(page,'workshop-mobile');const overflow=await page.locator('#equipmentCouncil').evaluate(el=>el.scrollWidth-el.clientWidth);assert.ok(overflow<=2);assert.deepEqual(errors,[]);console.log(JSON.stringify({workshopOutsideLodge:true,purchase:purchased.queue[0].kind,realSimulationFitted:fitted.equipped,mobileOverflow:overflow,gallery}));
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
