'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{performance}=require('node:perf_hooks'),{loadEngine}=require('./performance-harness.cjs');
function engine(){const c=loadEngine();if(!c.ATSHordeCommands)vm.runInContext(fs.readFileSync(path.join(__dirname,'../horde-commands.js'),'utf8'),c);return c}
function arena(){const c=engine(),g=new c.ATSGame('HORDE-COMMANDS');g.world.objects.clear();g.world._spatial.clear();g.world.sites.clear();g.world.ensure=()=>{};g.world.stream=()=>{};g.world.terrain=()=>({biome:'forest',water:false});g.world.waterBlocked=()=>false;return{c,g}}
function grids(g){g.syncIndexes();g.apeGrid.rebuild([g.king,...g.apes]);g.humanGrid.rebuild(g.humans);g.navigation.beginFrame(g.time);g.performance.beginStep(g)}
function settlement(g,x=900){const s={id:'home-'+g.nextId++,name:'Home',x,y:0,population:0,radius:100,level:1,food:50,wood:20,age:0,known:false,attack:false,birthTimer:0,starveTimer:0,lastRaid:-120,nextWarn:0};g.settlements.push(s);g.colonies.init(s);return s}
test('Q queries nearby cells and recruits only free unowned actors, even when species are selected',()=>{
 const {g}=arena(),wild=Array.from({length:5},(_,i)=>g.makeApe(20+i*20,0)),owned=Array.from({length:5},(_,i)=>g.makeApe(20+i*20,20,'charge')),distant=g.makeApe(500,0),s=settlement(g,0),resident=g.makeApe(0,60,'settled',s.id),prisoner=g.makeApe(0,80);prisoner.prisoner=true;
 for(const a of owned){a.target={x:900,y:200};a.armyOrder={group:'old',index:0};a.nearestOrder={kind:'human',until:20}}
 const disguised=g.makeApe(0,100,'follow');disguised.state='free';const cage=g.makeApe(0,120);cage.cageId='locked';g.world.objects.set('locked',{id:'locked',type:'cage',hp:100,dead:false});
 grids(g);g.siege.select(['gorilla']);let queries=0;const near=g.apeGrid.near.bind(g.apeGrid);g.apeGrid.near=(...args)=>{queries++;return near(...args)};const snapshot=owned.map(a=>JSON.stringify(a));g.apes.filter=()=>{throw Error('Q scanned the population')};
 assert.equal(g.command('call'),true);assert.equal(g.lastHordeCommand.count,5);assert.equal(queries,1);for(const a of wild){assert.equal(a.state,'follow');assert.equal(a.hordeOwner,'king')}owned.forEach((a,i)=>assert.equal(JSON.stringify(a),snapshot[i]));for(const a of [distant,prisoner,disguised,cage])assert.equal(a.state,'free');assert.equal(resident.settlementId,s.id);
});
test('nearby R uses exact distance and settlement assignment rather than transient state',()=>{
 const {g}=arena(),near=g.makeApe(200,0,'hold'),edge=g.makeApe(260,0,'charge'),far=g.makeApe(261,0,'hold'),free=g.makeApe(10,0),s=settlement(g,0),resident=g.makeApe(40,0,'settled',s.id),guard=g.makeApe(80,0,'scout',s.id);resident.state='charge';grids(g);g.command('recall');
 assert.equal(g.lastHordeCommand.count,2);assert.equal(near.state,'follow');assert.equal(edge.state,'follow');assert.equal(far.state,'hold');assert.equal(free.state,'free');assert.equal(resident.state,'charge');assert.equal(guard.state,'scout');
});
test('R hold and T tap share global field semantics regardless of selection or cooldown',()=>{
 for(const cmd of ['recallField']){const {g}=arena(),a=g.makeApe(15000,0,'hold'),s=settlement(g),b=g.makeApe(40,0,'settled',s.id),stray=g.makeApe(100,0,'follow');stray.state='free';g.siege.select(['gorilla']);g.commandCD=1;g.command(cmd);assert.equal(g.lastHordeCommand.count,2);assert.equal(a.state,'follow');assert.equal(stray.state,'follow');assert.equal(b.settlementId,s.id);assert.equal(a.x,15000);assert.equal(g.navigation.stats.searches,0)}
});
test('T hold removes resident, guard, tower and mission duties without duplication or teleportation',()=>{
 const {g}=arena(),s=settlement(g),resident=g.makeApe(900,0,'settled',s.id),scout=g.makeApe(980,0,'scout',s.id),young=g.makeApe(950,0,'young',s.id,true),free=g.makeApe(1000,0);resident.job='builder';resident.workCohort='cohort';resident.towerId='tower';resident.trainingFacilityId='training';resident.kingdomMission={id:'mission',sourceId:s.id,kind:'supply'};s.facilities=[{id:'tower',staffedBy:resident.id},{id:'training',trainingResidents:[resident.id]}];grids(g);const before=g.apes.map(a=>[a.id,a.x,a.y]);g.command('recallAll');
 assert.equal(g.lastHordeCommand.count,3);assert.equal(g.lastHordeCommand.mobilized,3);assert.deepEqual(g.apes.map(a=>[a.id,a.x,a.y]),before);assert.equal(g.apes.length,4);assert.equal(free.state,'free');for(const a of [resident,scout,young]){assert.equal(a.hordeOwner,'king');assert.equal(a.settlementId,null);assert.equal(a.previousSettlementAssignment.settlementId,s.id);assert.equal(a.recallOrder.kind,'all')}assert.equal(resident.previousSettlementAssignment.job,'builder');assert.equal(resident.previousSettlementAssignment.kingdomMission.id,'mission');assert.equal(resident.kingdomMission,undefined);assert.equal(resident.towerId,undefined);assert.equal(s.facilities[0].staffedBy,null);assert.equal(s.facilities[1].trainingResidents.length,0);assert.equal(s._members.length,0);assert.equal(s.population,0);
 const x=resident.x;g.updateApe(resident,.1);assert.ok(resident.x<x);assert.equal(resident.settlementId,null);const yx=young.x;g.updateApe(young,.1);assert.ok(young.x<yx);assert.equal(young.state,'young');assert.ok(young.age<1);
});
test('mobilized young mature as field followers without changing growth or health on recall',()=>{const {g}=arena(),s=settlement(g),a=g.makeApe(900,0,'young',s.id,true),hp=a.hp;g.command('recallAll');assert.equal(a.hp,hp);a.hitTimer=.28;g.updateApe(a,.3);assert.equal(a.hitTimer,0);a.age=34.9;grids(g);g.updateApe(a,.2);assert.equal(a.state,'follow');assert.equal(a.settlementId,null);assert.ok(a.maxHp>hp);assert.equal(a.recallOrder.kind,'all');assert.ok(Math.abs(a.age-35.1)<.001)});
test('new direct attacks and species movement replace recall without an old order reasserting itself',()=>{const {g}=arena(),a=g.makeApe(150,0,'hold');grids(g);g.command('recallField');assert.ok(a.recallOrder);g.command('nearestHuman',{x:1,y:0});assert.equal(a.recallOrder,undefined);assert.equal(a.nearestOrder.kind,'human');g.command('recallField');g.siege.select([a.species]);g.siege.immediate('move',{x:450,y:0});assert.equal(a.recallOrder,undefined);assert.ok(a.armyOrder);g.time+=.1;g.updateApe(a,.1);assert.ok(a.armyOrder)});
test('global recall removes a division override and a preexisting nearest attack',()=>{const {g}=arena(),a=g.makeApe(200,0,'follow'),b=g.makeApe(210,20,'follow');g.champions.veteran(a);g.champions.veteran(b);g.champions.assign('vanguard',a.id,[b.id]);grids(g);g.command('nearestHuman');g.command('recallField');assert.equal(a.nearestOrder,undefined);assert.equal(a.divisionId,undefined);assert.equal(b.divisionId,undefined);g.champions.tick();assert.equal(a.state,'follow')});
test('version-1 saves migrate ownership while preserving recalled assignments and positions',()=>{const {c,g}=arena(),s=settlement(g),a=g.makeApe(900,0,'settled',s.id),wild=g.makeApe(120,0);g.command('recallAll');const save=JSON.parse(JSON.stringify(g.serialize()));delete save.apes.find(p=>p.id===a.id).hordeOwner;delete save.apes.find(p=>p.id===wild.id).hordeOwner;const loaded=c.ATSGame.fromJSON(save),r=loaded.apesById.get(a.id),w=loaded.apesById.get(wild.id);assert.equal(r.hordeOwner,'king');assert.equal(w.hordeOwner,null);assert.equal(r.x,a.x);assert.equal(r.settlementId,null);assert.equal(r.previousSettlementAssignment.settlementId,s.id);assert.equal(r.recallOrder.kind,'all');loaded.command('recallField');assert.equal(loaded.lastHordeCommand.count,1)});
test('a thousand-ape mobilization schedules no synchronous per-ape pathfinding or particles',()=>{const {g}=arena(),s=settlement(g);for(let i=0;i<1000;i++)g.makeApe(i*12,500,i%3?'hold':'settled',i%3?null:s.id);grids(g);const effects=g.effects.length,searches=g.navigation.stats.searches,start=performance.now();g.command('recallAll');const duration=performance.now()-start;assert.equal(g.lastHordeCommand.count,1000);assert.equal(g.navigation.stats.searches,searches);assert.equal(g.effects.length-effects,1);assert.equal(new Set(g.apes.map(a=>a.id)).size,1000);assert.ok(duration<150,'mobilization bounded at '+duration.toFixed(1)+' ms');console.log('1000-ape mobilization: '+duration.toFixed(2)+' ms; 0 synchronous path searches; 1 pulse')});
test('keyboard tap, exact-threshold release, completed hold and repeat each commit once',()=>{const {ATSHoldCommandInput:Input}=engine(),out=[],progress=[],input=new Input(c=>out.push(c),p=>progress.push(p));input.press('r','key:r',0);input.press('r','key:r',500);input.release('key:r',599);assert.deepEqual(out,['recall']);input.press('r','key:r',1000);input.tick(1600);input.tick(2000);input.release('key:r',2500);assert.deepEqual(out,['recall','recallField']);input.press('t','key:t',3000);input.release('key:t',3020);input.press('t','key:t',4000);input.release('key:t',4600);assert.deepEqual(out,['recall','recallField','recallField','recallAll']);assert.ok(progress.some(p=>p?.held&&p.key==='r'));assert.equal(progress.at(-1),null)});
test('pointer cancellation, pause/blur cancellation and concurrent inputs cannot leak settlement recall',()=>{const {ATSHoldCommandInput:Input}=engine(),out=[],input=new Input(c=>out.push(c));input.press('t','pointer:1',0);input.cancel('pointer:1');input.tick(900);input.release('pointer:1',1000);input.press('t','key:t',1200);assert.equal(input.press('t','pointer:2',1300),false);input.cancel();input.release('key:t',2000);input.tick(3000);assert.deepEqual(out,[]);input.press('r','pointer:3',4000);input.tick(4250);input.release('pointer:3',4500);assert.deepEqual(out,['recall'])});
