'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {loadEngine}=require('./performance-harness.cjs');
function audio(){let playCalls=0;const music={paused:true,volume:1,loop:false,play(){playCalls++;this.paused=false;return Promise.resolve()},pause(){this.paused=true}};const c=vm.createContext({console,Math,Map,Set,Promise,document:{hidden:false,getElementById:()=>music}});c.window=c;vm.runInContext(fs.readFileSync(path.join(__dirname,'../audio.js'),'utf8'),c);const a=new c.ATSAudio();a.ctx={currentTime:0,state:'running'};return{a,c,music,calls:()=>playCalls}}
const flush=()=>new Promise(resolve=>setImmediate(resolve));
test('soundtrack starts only in play, stays quiet, loops and respects both mutes and hidden tabs',async()=>{const{a,c,music,calls}=audio();a.setSettings({});assert.equal(calls(),0);a.pause(false);await flush();assert.equal(music.paused,false);assert.equal(music.loop,true);assert.ok(music.volume<=.1);a.pause(false);assert.equal(calls(),1,'no overlapping music instances');a.pause();assert.equal(music.paused,true);a.pause(false);await flush();a.setSettings({musicEnabled:false});assert.equal(music.paused,true);a.setSettings({musicEnabled:true,enabled:false});assert.equal(music.paused,true);a.setSettings({enabled:true,musicVolume:0});assert.equal(music.paused,true);a.setSettings({musicVolume:.22});await flush();c.document.hidden=true;a._syncMusic();assert.equal(music.paused,true);});
test('late playback promises cannot restart music after pause; rejected autoplay can retry',async()=>{const{a,music,calls}=audio();let finish;music.play=function(){return new Promise(resolve=>{finish=()=>{this.paused=false;resolve()}})};a.pause(false);a.pause(true);finish();await flush();assert.equal(music.paused,true);music.play=()=>Promise.reject(Error('gesture required'));a.pause(false);await flush();assert.equal(a.musicPending,false);music.play=function(){this.paused=false;return Promise.resolve()};a.pause(false);await flush();assert.equal(music.paused,false);});
test('weather saves its schedule without rerolling and old saves derive a safe initial climate',()=>{const c=loadEngine(),g=new c.ATSGame('weather-save');g.time=220;const kind=g.weather.kind,until=g.weather.until;const d=JSON.parse(JSON.stringify(g.serialize())),loaded=c.ATSGame.fromJSON(d);assert.equal(loaded.weather.kind,kind);assert.equal(loaded.weather.until,until);delete d.weather;const old=c.ATSGame.fromJSON(d);assert.ok(c.ATSWeatherTypes[old.weather.kind]);g.time=until+1;assert.notEqual(g.weather.kind,kind);});
test('fog changes detection, rain masks movement and mud slows travel without speeding capped steps',()=>{const c=loadEngine(),g=new c.ATSGame('weather-rules');g._weather={kind:'fog',until:300,wind:0};const human={id:'human-test',x:0,y:0},ape={id:'ape-test',x:500,y:0};assert.equal(g.lineVisible(human,ape),false);const clear=g.world.lineClear;g.world.lineClear=()=>true;assert.equal(g.lineVisible(human,ape,true),true,'weather never blocks a physical projectile');g._weather.kind='rain';g.noise(0,0,100,'footsteps');assert.equal(g.noises.at(-1).radius,70);assert.ok(g.terrainPace(ape,{biome:'farmland'})<1);assert.equal(g.terrainPace(ape,{biome:'farmland',road:true}),1);g.world.lineClear=clear;});
