'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {loadEngine}=require('./performance-harness.cjs');
function arena(kind='blacksite',count=44){const c=loadEngine();if(!c.ATSChampions&&fs.existsSync(path.join(__dirname,'../champions.js')))vm.runInContext(fs.readFileSync(path.join(__dirname,'../champions.js'),'utf8'),c);if(!c.ATSPrisonOperations)vm.runInContext(fs.readFileSync(path.join(__dirname,'../prisons.js'),'utf8'),c);const g=new c.ATSGame('PRISON-OPERATIONS');g.world.objects.clear();g.world._spatial.clear();g.world.sites.clear();g.world.ensure=()=>{};g.world.stream=()=>{};g.world.terrain=()=>({biome:'forest',water:false});g.world.waterBlocked=()=>false;g.spawnSites=()=>{};g.nextDirectorAt=g.nextConvoyAt=g.heliTimer=1e9;const chunk=g.world.chunks.get('0,0');chunk.objects=[];chunk.sites=[];g.world._buildSite(chunk,{id:'operation',x:0,y:0,name:'Operation test',type:kind==='transfer'?'regionalCommand':'armoredDepot',prisonKind:kind,military:true,tier:4,guards:12,count,radius:540,extentX:466,extentY:300,layout:0});const s=g.world.sites.get('operation');s.known=true;const objects=s.objects.map(id=>g.world.objects.get(id));return{c,g,s,objects,cells:objects.filter(o=>o.type==='cage')}}
function grids(g){g.syncIndexes();g.apeGrid.rebuild([g.king,...g.apes]);g.humanGrid.rebuild(g.humans);g.vehicleGrid.rebuild(g.vehicles);g.navigation.beginFrame(g.time);g.performance.beginStep(g)}
function open(g,s,cell){const control=g.world.objects.get(s.prison.controlId);g.damageObject(control,10000,g.king);g.damageObject(cell,10000,g.king);return s.prison.cohorts.find(c=>c.cageId===cell.id)}
test('all four facilities retain finite captive stocks, real access and distinctive rewards',()=>{for(const kind of['regional','blacksite','transfer','labor']){const {g,s,objects,cells}=arena(kind,55);assert.equal(cells.reduce((n,c)=>n+c.count,0),55);assert.ok(s.gates.length>=3);assert.equal(s.climbRoutes.length,2);assert.ok(objects.some(o=>o.type==='generator'));assert.ok(objects.some(o=>o.type==='prisonControl'));assert.equal(g.prisons.recon(s).kind,({regional:'Regional Prison',blacksite:'Blacksite Research Compound',transfer:'Transfer Fortress',labor:'Quarry Labor Prison'})[kind]);assert.ok(cells.every(c=>c.hp>=230));if(kind==='blacksite'||kind==='transfer')assert.equal(cells.filter(c=>c.prisonReward==='champion').length,1)}});
test('steel cells reject unlimited raw damage; power and internal controls unlock different blocks',()=>{const {g,s,cells}=arena();const power=cells.find(o=>o.prisonLock==='power'),steel=cells.find(o=>o.prisonLock==='control'),hp=power.hp;g.damageObject(power,1e9,g.king);assert.equal(power.hp,hp);assert.equal(s.prison.cohorts.length,0);g.damageObject(g.world.objects.get(s.prison.powerId),1e5,g.king);assert.ok(g.prisons.unlocked(power));assert.equal(g.prisons.unlocked(steel),false);assert.equal(g.getLights().filter(l=>l.kind==='tower').length,0);g.damageObject(steel,1e9,g.king);assert.equal(steel.dead,false);g.damageObject(g.world.objects.get(s.prison.controlId),1e5,g.king);g.damageObject(steel,1e9,g.king);assert.equal(steel.dead,true);assert.ok(s.prison.cohorts.length===1)});
test('escape cohorts reserve population slots and credit actual safe rescues exactly once',()=>{const {g,s,cells}=arena();for(let i=0;i<997;i++)g.makeApe(700+i%10,700,'follow');const c=open(g,s,cells[0]);assert.equal(c.count,3);assert.equal(g.population,1000);assert.equal(g.makeApe(0,0),null);assert.equal(g.stats.freed,0);const remaining=cells[0].count;g.prisons.reward(s,c);assert.equal(g.apes.length,1000);assert.equal(g.population,1000);assert.equal(g.stats.freed,3);assert.equal(cells[0].count,remaining);g.prisons.reward(s,c);assert.equal(g.stats.freed,3)});
test('isolated escaped captives can be recaptured without duplicating population or rewards',()=>{const {g,s,cells}=arena();const c=open(g,s,cells[0]),n=c.count;assert.equal(g.population,n);g.prisons.recapture(s,c);assert.equal(g.population,0);assert.equal(cells[0].count,n);assert.equal(g.stats.freed,0);assert.equal(g.prisons.release(cells[0]),0);g.time=13;assert.equal(g.prisons.release(cells[0]),n);assert.equal(g.population,n)});
test('reinforcements spend saved reserves and cease after relay sabotage',()=>{const {g,s}=arena();s.alarm=true;s.prison.powerDown=false;grids(g);g.prisons.response(s);const spent=s.prison.reserveCommitted;assert.ok(spent>0);assert.equal(s.prison.reserve,20-spent);g.time=30;s.radioDown=true;g.prisons.response(s);assert.equal(s.prison.reserveCommitted,spent);s.radioDown=false;for(let i=0;i<10;i++){g.time+=30;g.prisons.response(s)}assert.ok(s.prison.waves<=3);assert.ok(s.prison.reserveCommitted<=20)});
test('save/load preserves damaged locks, cohort reservations and paid rescue rewards',()=>{const {c,g,s,cells}=arena();const cohort=open(g,s,cells[0]);cohort.x=91;cohort.exposed=2.1;s.prison.reserve=7;s.prison.rewardPaid=true;const saved=JSON.parse(JSON.stringify(g.serialize())),loaded=c.ATSGame.fromJSON(saved),p=loaded.world.sites.get(s.id).prison;assert.equal(p.cohorts[0].x,91);assert.equal(p.cohorts[0].exposed,2.1);assert.equal(p.reserve,7);assert.equal(p.rewardPaid,true);assert.equal(loaded.population,cohort.count);assert.equal(loaded.world.objects.get(p.controlId).dead,true)});
test('escorts navigate an open exit and wait for safety beyond the perimeter',()=>{const {g,s,cells}=arena('regional',8),c=open(g,s,cells[0]);s.radioDown=true;for(const id of s.gates)g.siege.openGate(g.world.objects.get(id));c.x=0;c.y=170;g.king.x=0;g.king.y=370;for(let i=0;i<140&&c.count;i++){g.time+=.25;grids(g);g.prisons.tick(.25);if(g.king.y<500&&Math.hypot(g.king.x-c.x,g.king.y-c.y)<130)g.king.y+=20}assert.equal(c.count,0,'crowd passes the real gate and reaches safety '+JSON.stringify(c));assert.equal(g.stats.freed,2);assert.equal(g.prisons.reserved,0)});
test('lockdown seals the inner gate without rebuilding a destroyed gate',()=>{const {g,s}=arena(),gate=g.world.objects.get(s.prison.riotId);s.alarm=true;s.prison.alarmLevel=3;g.time=1;grids(g);g.prisons.tick(.25);assert.equal(gate.solid,true);assert.equal(gate.gateState,'closed');g.damageObject(gate,1e9,g.king);g.time=2;grids(g);g.prisons.tick(.25);assert.equal(gate.solid,false);assert.equal(gate.dead,true)});
test('successful blacksite extractions award one persistent champion and an injured legend',()=>{const {c,g,s,cells}=arena(),champion=open(g,s,cells[0]),legend=open(g,s,cells[1]);g.prisons.reward(s,champion);g.prisons.reward(s,legend);assert.equal(g.apes.filter(a=>a.champion).length,2);const saboteur=g.apes.find(a=>a.champion?.archetype==='saboteur'),bulwark=g.apes.find(a=>a.champion?.archetype==='bulwark');assert.ok(saboteur);assert.ok(bulwark?.recoveryRemaining>0);assert.ok(bulwark.hp<bulwark.maxHp);const loaded=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(g.serialize())));assert.equal(loaded.apes.filter(a=>a.champion).length,2);assert.equal(loaded.apes.find(a=>a.id===saboteur.id).champion.item,saboteur.champion.item)});
test('procedural prison variants use existing military parcels and preserve opening rescues',()=>{const {c}=arena(),w=new c.ATSWorld('KINGDOM-PRISONS'),kinds=new Set();assert.equal(w._sitePlan(0,-1).prisonKind,undefined);assert.equal(w._sitePlan(0,0).count,6);for(let y=-24;y<=24;y+=3)for(let x=-23;x<=25;x+=3){const p=w._sitePlan(x,y);if(!p?.prisonKind)continue;kinds.add(p.prisonKind);assert.equal(p.military,true);assert.ok(p.extentX>=300);assert.ok(p.approach.length>=2)}assert.equal(kinds.size,4)});
test('a climbing raider reaches the internal release controls in each real prison blueprint',()=>{for(const kind of['regional','blacksite','transfer','labor']){const {g,s}=arena(kind);s.radioDown=true;const target=g.world.objects.get(s.prison.controlId),a=g.makeApe(-s.extentX-100,0,'follow');a.species='gibbon';g.siege.balance(a,true);g.siege.issue(['gibbon'],[{id:'release-controls',type:'sabotage',targetId:target.id,targetKind:'object',x:target.x,y:target.y}]);for(let frame=0;frame<5000&&!target.dead;frame++){g.time+=1/30;grids(g);g.siege.tick(1/30);g.updateApe(a,1/30)}assert.ok(target.dead,kind+' release controls reachable '+JSON.stringify({x:a.x,y:a.y,route:a.siegeRoute,order:g.siege.groups.gibbon}));assert.equal(s.prison.controlsDown,true)}});
test('a saved high-value crowd resumes its physical escape and awards its champion only at safety',()=>{let {c,g,s,cells}=arena('blacksite',12);s.radioDown=true;let crowd=open(g,s,cells[0]);for(const id of s.gates)g.siege.openGate(g.world.objects.get(id));g.king.x=0;g.king.y=60;for(let i=0;i<40&&crowd.y<10;i++){g.time+=.25;grids(g);g.prisons.tick(.25)}assert.equal(g.apes.length,0);const n=crowd.count;g=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(g.serialize())));s=g.world.sites.get('operation');crowd=s.prison.cohorts[0];assert.equal(g.population,n);assert.equal(crowd._nav,undefined);g.world.terrain=()=>({biome:'forest',water:false});g.world.waterBlocked=()=>false;let target=60;for(let i=0;i<200&&crowd.count;i++){if(Math.abs(crowd.y-target)<100)target=Math.min(540,target+110);g.king.x=0;g.king.y=target;g.time+=.25;grids(g);g.prisons.tick(.25)}assert.equal(crowd.count,0,JSON.stringify(crowd));assert.equal(g.stats.freed,n);assert.equal(g.apes.filter(a=>a.champion?.archetype==='saboteur').length,1);const saved=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(g.serialize())));assert.equal(saved.stats.freed,n);assert.equal(saved.population,n);assert.equal(saved.apes.filter(a=>a.champion).length,1)});
test('liberated family cohorts become saved journeys and celebrate only after reaching home',()=>{const {c,g,s,cells}=arena('labor',8),home={id:'sanctuary-home',name:'Sanctuary',x:1300,y:800,population:1,food:500,wood:100,housing:20,level:1,age:0,birthTimer:0,known:true};g.settlements.push(home);g.makeApe(home.x,home.y,'settled',home.id);g.refreshSettlements();g.colonies.init(home);g.kingdom.specialize(home.id,'sanctuary');const crowd=open(g,s,cells.find(c=>c.prisonReward==='family'));crowd.x=0;crowd.y=500;g.prisons.reward(s,crowd);const survivors=g.apes.filter(a=>a.rescuedFrom===s.id);assert.equal(survivors.length,2);assert.ok(survivors.every(a=>a.kingdomMission?.kind==='survivors'));assert.ok(survivors.every(a=>a.x<100));assert.equal(home.moraleUntil,0);const loaded=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(g.serialize()))),destination=loaded.settlement(home.id);for(const a of loaded.apes.filter(a=>a.rescuedFrom===s.id)){a.x=destination.x;a.y=destination.y}loaded.kingdom.tick(destination);assert.ok(destination.moraleUntil>loaded.time);assert.ok(destination.kingdomEvents.some(e=>e.kind==='survivors'));assert.equal(loaded.population,3)});




