/* Real standalone game: milestone pause, audio decoding, crowns, save and touch. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const{pathToFileURL}=require('node:url'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const errors=[];
 const shot=async(p,name)=>{if(process.env.QA_ARTIFACT_DIR){fs.mkdirSync(process.env.QA_ARTIFACT_DIR,{recursive:true});await p.screenshot({path:path.join(process.env.QA_ARTIFACT_DIR,name+'.png')});}};
 try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}});page.on('pageerror',e=>errors.push(e.message));
 const url=pathToFileURL(path.resolve(__dirname,'../../apes-together-strong.html')).href;await page.goto(url);await page.locator('#newRun').click();
 await page.waitForFunction(()=>!ATS.audio.music.paused&&ATS.audio.music.currentTime>.05);assert.equal(await page.locator('#campaignMusic').getAttribute('data-track'),'underpowered-king');
 await page.evaluate(()=>{const g=ATS.game;g.king.hp=g.king.maxHp=1e6;g.spawnSites=()=>{};g.nextDirectorAt=g.nextConvoyAt=g.heliTimer=1e9;for(let i=g.population;i<99;i++)g.makeApe(100+(i%10)*9,100+Math.floor(i/10)*9,'follow');g.checkProgression()});
 assert.equal(await page.evaluate(()=>ATS.screen),'play');
 await page.evaluate(()=>{ATS.game.makeApe(100,100,'follow');ATS.game.checkProgression()});await page.waitForFunction(()=>ATS.screen==='coronation');
 assert.match(await page.locator('#coronationTitle').innerText(),/King of the Jungle/);const frozen=await page.evaluate(()=>ATS.game.time);await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>ATS.game.time),frozen);assert.equal(await page.evaluate(()=>ATS.audio.music.paused),true);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>ATS.screen),'coronation');assert.equal(await page.evaluate(()=>ATS.game.king.crownTier),1);await shot(page,'royal-coronation');
 await page.locator('#continueCoronation').click();await page.waitForFunction(()=>!ATS.audio.music.paused&&ATS.audio.music.currentTime>.05);assert.equal(await page.locator('#campaignMusic').getAttribute('data-track'),'ceremonial-tom');
 await page.evaluate(()=>{const g=ATS.game;for(let i=g.population;i<200;i++)g.makeApe(100+i%20*8,100+Math.floor(i/20)*8,'follow');g.checkProgression()});await page.waitForFunction(()=>ATS.screen==='coronation');assert.match(await page.locator('#coronationTitle').innerText(),/Warlord/);await shot(page,'warlord-coronation');await page.locator('#continueCoronation').click();await page.waitForFunction(()=>!ATS.audio.music.paused&&ATS.audio.music.currentTime>.05);assert.equal(await page.locator('#campaignMusic').getAttribute('data-track'),'primal-roar');
 await page.evaluate(()=>{for(const a of ATS.game.apes.slice(80))a.hp=0;ATS.game.checkProgression()});await page.keyboard.press('Escape');await page.locator('#saveRun').click();await page.reload();await page.locator('#continueRun').click();assert.equal(await page.evaluate(()=>ATS.screen),'play');assert.equal(await page.evaluate(()=>ATS.game.king.crownTier),2);assert.equal(await page.locator('#campaignMusic').getAttribute('data-track'),'primal-roar');
 await page.keyboard.press('Escape');await page.locator('#settingsButton').click();await page.locator('#musicToggle').uncheck();await page.locator('#backSettings').click();await page.locator('#resumeRun').click();assert.equal(await page.evaluate(()=>ATS.audio.music.paused),true);
 // Keep actual renderer/canvas overlays active for all new gear and crowns.
 await page.evaluate(()=>{const g=ATS.game;g.spawnSites=()=>{};g.nextDirectorAt=g.nextConvoyAt=g.heliTimer=1e9;for(const a of g.apes)a.hp=0;g.world.objects.clear();g.world._spatial.clear();g.world.terrain=()=>({biome:'forest',water:false,road:false});g.world.blocked=()=>false;g.world.settlementPlot=()=>({valid:true,trees:[]});for(let i=0;i<30;i++)g.makeApe(g.king.x+(i%6)*8,g.king.y+Math.floor(i/6)*8,'follow');g.food=1000;g.commandCD=0;g.command('settleAll');const s=g.settlements[0];s.food=5000;s.wood=5000;s.expansionTier=2;g.colonies.init(s);s.structures.push({id:s.id+'-forge-qa',kind:'workShelter',x:g.king.x+45,y:g.king.y,hp:180,maxHp:180,stage:4});g.world.syncSettlementBuildings(s,g);g.syncIndexes();g.refreshSettlements();});
 await page.keyboard.press('b');assert.equal(await page.evaluate(()=>ATS.screen),'build');assert.match(await page.locator('#equipmentCouncil').innerText(),/workshop|equipment|armor/i);assert.match(await page.locator('#buildCatalog').innerText(),/Citadel|citadel|Warlord/);await shot(page,'reign-building-council');await page.locator('#closeBuild').click();await shot(page,'reign-gameplay');
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(url);await mobile.locator('#newRun').tap();await mobile.evaluate(()=>{const g=ATS.game;g.king.hp=g.king.maxHp=1e6;g.spawnSites=()=>{};for(let i=g.population;i<100;i++)g.makeApe(100+i%10*8,100+Math.floor(i/10)*8,'follow');g.checkProgression()});await mobile.waitForFunction(()=>ATS.screen==='coronation');assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await mobile.locator('#continueCoronation').scrollIntoViewIfNeeded();await shot(mobile,'royal-coronation-touch');await mobile.locator('#continueCoronation').tap();assert.equal(await mobile.evaluate(()=>ATS.screen),'play');
 assert.deepEqual(errors,[]);console.log('Reign browser checks passed: three decoded tracks, frozen ceremonies, tier crowns, persistent unlocks, workshop council, desktop/touch.');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
