'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {loadEngine}=require('./performance-harness.cjs');
function setup(n=0){const c=loadEngine(),g=new c.ATSGame('RELENTLESS');g.world.objects.clear();g.world._spatial.clear();g.world.sites.clear();g.world.getSites=()=>[];g.world.ensure=()=>{};g.world.stream=()=>{};g.world.boundsReady=()=>true;g.world.blocked=()=>false;g.world.lineClear=()=>true;g.world.terrain=()=>({biome:'farmland',road:true,water:false});g.world.vehicleBlocked=()=>false;g.world.vehicleStaging=(s,k,i)=>({x:s.x+i*60,y:s.y});for(let i=0;i<n;i++)g.makeApe(i%25*14,Math.floor(i/25)*14,'hold');g.time=200;g.syncIndexes();g.apeGrid.rebuild([g.king,...g.apes]);g.updateResponseStage();return{g,c}}
function base(g,x,y=0){const s={id:'base-'+x+','+y,name:'Iron Road',x,y,tier:5,guards:0,strength:250,spawned:true,objects:[],lastRaid:-100,vehicleInventory:{jeep:4,command:3,truck:8,apc:8,ifv:4,tank:8,heli:6},armorCapacity:150,staging:[{x,y}],approach:[{x,y},{x:x-300,y}],roadblocks:[]};g.world.sites.set(s.id,s);return s}
function cage(g,count){const s={id:'captives',name:'Camp',count,strength:0,tier:1,objects:['cage']},o={id:'cage',type:'cage',x:0,y:0,hp:10,count,prisoners:count,r:24,siteId:s.id,solid:true};g.world.sites.set(s.id,s);g.world.objects.set(o.id,o);g.world._indexObject(o);return{o,s}}
test('partial rescues keep remaining captives, statistics and save data until space is available',()=>{const{g,c}=setup(985),{o,s}=cage(g,40);g.damageObject(o,20,g.king);assert.equal(g.population,c.MAX_APE_POPULATION);assert.equal(o.count,25);assert.equal(s.count,25);assert.equal(g.stats.freed,15);assert.equal(g.stats.prisons,0);assert.equal(s.rescued,false);assert.ok(g.messages.some(m=>m.text.includes('25 captives remain')));const loaded=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(g.serialize()))),saved=loaded.world.objects.get(o.id);assert.equal(saved.count,25);for(const a of loaded.apes.slice(0,25))loaded.hurt(a,1000,loaded.king);loaded.tickSecond(true);assert.equal(loaded.population,1000);assert.equal(saved.count,0);assert.equal(loaded.stats.freed,40);assert.equal(loaded.stats.prisons,1);assert.equal(loaded.world.sites.get(s.id).rescued,true);loaded.tickSecond(true);assert.equal(loaded.stats.freed,40)});
test('a full population leaves an entire opened cage available instead of deleting its apes',()=>{const{g}=setup(1000),{o,s}=cage(g,12);g.damageObject(o,20,g.king);assert.equal(g.population,1000);assert.equal(g.stats.freed,0);assert.equal(o.prisoners,12);assert.equal(s.cleared,undefined);assert.equal(g.makeApe(0,0),null)});
test('destroyed cages in old saves do not turn already rescued apes back into pending captives',()=>{const{g,c}=setup(40),{o,s}=cage(g,40);o.dead=true;o.hp=0;s.count=0;g.stats.freed=40;g.stats.prisons=1;const saved=JSON.parse(JSON.stringify(g.serialize()));delete saved.populationVersion;const loaded=c.ATSGame.fromJSON(saved),camp=loaded.world.sites.get(s.id);loaded.checkSite(camp);assert.equal(camp.cleared,true);assert.equal(loaded.stats.freed,40);assert.equal(loaded.population,40)});
test('old campaigns near 600 immediately rescue above the previous ceiling',()=>{const{g,c}=setup(599);const saved=JSON.parse(JSON.stringify(g.serialize()));delete saved.populationVersion;saved.militaryVersion=1;const loaded=c.ATSGame.fromJSON(saved),{o}=cage(loaded,40);loaded.damageObject(o,20,loaded.king);assert.equal(loaded.population,639);assert.equal(loaded.stats.freed,40)});
test('all war intensity ranges scale weighted force, troops, armor and reevaluation independently',()=>{for(const[n,intensity,budget,people,tanks,armor,interval]of [[219,0,250,220,3,4,28],[220,1,340,220,3,4,15],[250,1,340,260,3,4,15],[300,2,500,320,6,9,12],[400,2,566,346,6,9,11],[450,3,950,500,10,16,9],[650,4,1450,700,15,24,6.5],[850,5,1950,900,22,34,4.5],[1000,5,2250,1000,22,34,3]]){const{g}=setup(n);assert.equal(g.warIntensity,intensity);assert.equal(g.responseBudget,budget);assert.equal(g.activeHumanCapacity(),people);assert.equal(g.vehicleLimits.tank,tanks);assert.equal(g.vehicleLimits.armored,armor);assert.equal(g.directorInterval,Math.max(3,interval*(n>=200?.82:n>=100?.9:1)),'earned crowns shorten dispatch intervals without raising force budgets')}});
test('field pursuit and regional settlement assault dispatch in the same decision',()=>{const{g}=setup(500);for(const[x,y]of [[1400,0],[-1400,0],[0,1400],[0,-1400]])base(g,x,y);g.settlements.push({id:'home',name:'Moonroot',x:300,y:300,known:true,population:80,lastRaid:-100,scouts:2});g.addIntel(0,0,20);g.responseDirector();assert.ok(g.events.some(e=>e.type==='raid'&&!e.settlementId));assert.ok(g.events.some(e=>e.type==='raid'&&e.settlementId==='home'));assert.ok(g.forceWeight()<=g.responseBudget);assert.ok(g.humans.length+g.vehicles.reduce((n,v)=>n+v.troops,0)<=g.activeHumanCapacity());assert.ok(g.vehicles.filter(v=>v.kind==='tank').length<=g.vehicleLimits.tank)});
test('sustained confirmed contact requests another response and pursuit predicts only observations',()=>{const{g,c}=setup(300);const s=base(g,1400);g.recordHordeContact({siteId:s.id},{x:0,y:0},200);g.nextFieldOperation=999;for(let i=1;i<=26;i++){g.time++;g.recordHordeContact({siteId:s.id},{x:i*40,y:0},200)}assert.equal(g.nextFieldOperation,0);assert.ok(g.pursuitOperation.vx>0);const predicted=g.pursuitTarget();assert.ok(predicted.x>g.pursuitOperation.x);g.king.x=-8000;assert.equal(g.pursuitTarget().x,predicted.x);const loaded=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(g.serialize())));assert.equal(loaded.pursuitOperation.estimatedSize,200);g.time+=151;assert.equal(g.pursuitTarget(),null)});
test('major offensives and tank platoons still debit real regional reserves',()=>{const{g}=setup(750);const a=base(g,1400),b=base(g,-1400);g.addIntel(0,0,20);g.responseDirector();const raids=g.events.filter(e=>e.type==='raid');assert.ok(raids.length>=2);assert.ok(raids.some(e=>e.package==='Major Offensive'));const infantry=raids.reduce((n,e)=>n+e.people,0);assert.ok(infantry>=120&&infantry<=230,'larger columns remain within the population-scaled offensive commitment');assert.equal(a.strength+b.strength,500-infantry);assert.ok(g.vehicles.filter(v=>v.kind==='tank').length>=3);assert.ok(g.vehicles.filter(v=>v.kind==='tank').every(v=>v.platoonId));assert.ok(g.nextMajorOffensive>g.time);assert.ok(g.forceWeight()<=g.responseBudget)});
test('armor ceilings count IFVs, APCs and other armored support together',()=>{const{g}=setup(850);for(let i=0;i<g.vehicleLimits.armored;i++)g.vehicles.push({id:'support-'+i,kind:i%2?'ifv':'apc',hp:100});assert.equal(g.vehicleRoom('apc'),false);assert.equal(g.vehicleRoom('ifv'),false);assert.equal(g.vehicleRoom('tank'),true)});
test('frequent squad observations still measure movement for a predictive intercept',()=>{const{g}=setup(350);g.recordHordeContact({siteId:'radio'},{x:0,y:0},350);for(let i=1;i<=80;i++){g.time+=.025;g.recordHordeContact({siteId:'radio'},{x:i*2,y:0},350)}assert.ok(g.pursuitOperation.vx>60);assert.ok(g.pursuitTarget().x>g.pursuitOperation.x+100)});
