'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {loadEngine}=require('./performance-harness.cjs');
// Damage and migration cases exercise homes already occupied in an old save.
// Fresh settlement construction is covered separately below and in living-settlements.
function colony(n=18){const c=loadEngine(),g=new c.ATSGame('hut-expansion');g.world.getSites=()=>[];g.world.getObjects=()=>[];g.world.terrain=()=>({biome:'forest',water:false});g.world.blocked=()=>false;g.world.lineClear=()=>true;for(let i=0;i<n;i++)g.makeApe(i,0,'follow');g.food=n*10;assert.equal(g.command('settleAll'),true);const s=g.settlements[0];Object.assign(s,{housing:Math.ceil(n/6)*6,food:n*12,wood:100,birthTimer:-100000,suitability:{fertility:1,wood:24,capacity:c.MAX_APE_POPULATION,water:true}});delete s.structuresVersion;g.colonies.init(s);return{c,g,s}}
function tick(g,s,n=1){for(let i=0;i<n;i++){g.time++;g.refreshSettlements();g.colonies.tick(s);for(const a of g.settlementMembers.get(s.id)||[]){const p=g.colonies.activityTarget(a,s);a.x=p.x;a.y=p.y}}}
test('builders spend timber to create real huts and expand the base footprint',()=>{
 const{g,s}=colony(6),before=s.radius;assert.equal(s.huts.length,0);tick(g,s,3);assert.equal(s.huts.length,1,'a visible frame persists while work is unfinished');assert.equal(s.huts[0].hp,0);assert.equal(s.housing,6,'unfinished structures cannot house residents');tick(g,s,26);assert.equal(s.huts.length,1);const hut=s.huts[0];assert.equal(hut.hp,100);assert.equal(s.housing,16);assert.ok(Math.hypot(hut.x-s.x,hut.y-s.y)>45,'hut stands in the residential ring');assert.ok(s.radius>=before,'construction never shrinks claimed ground');assert.ok(s.wood<100,'construction spends its timber');
 for(let i=0;i<8;i++)g.colonies.addHut(s);const expanded=g.colonies.footprint(s);assert.ok(expanded>s.radius,'a new ring enlarges the built base');g.refreshSettlements();assert.equal(s.radius,expanded,'population refresh retains built extent');
});
test('humans need nearby line of sight to destroy huts and remove their housing',()=>{
 const{g,s}=colony(),hut=s.huts[0],housing=s.housing,raider=g.makeHuman(hut.x+60,hut.y,null);raider.state='search';raider.raidTarget=s.id;g.humanGrid.rebuild(g.humans);g.world.lineClear=()=>false;tick(g,s,3);assert.equal(hut.hp,100);g.world.lineClear=()=>true;tick(g,s,21);assert.equal(hut.hp,0);assert.equal(s.housing,housing-hut.capacity);assert.ok(g.messages.some(m=>m.text.includes('housing destroyed')));assert.ok(g.effects.some(e=>e.type==='siegeShot'));assert.ok(s.huts.includes(hut),'destroyed home remains a persistent ruin');
});
test('new huts avoid water and obstacles and unavailable plots preserve work and timber',()=>{
 const{g,s}=colony(6);let checks=0;g.world.terrain=(x,y)=>({biome:'forest',water:x>0&&y>0});g.world.blocked=(x,y)=>{checks++;return x>0&&y<=0};const hut=g.colonies.addHut(s);assert.ok(hut);assert.ok(hut.x<=0);assert.ok(!g.world.terrain(hut.x,hut.y).water);assert.ok(checks<=48);assert.ok(Math.hypot(hut.x-s.x,hut.y-s.y)>=140);
 s.huts=[];g.colonies.updateHousing(s);s.wood=20;s.suitability.wood=0;g.world.terrain=()=>({biome:'wetland',water:true});tick(g,s,20);assert.equal(s.huts.length,0);assert.equal(s.wood,20,'failed siting spends no timber');assert.equal(s.buildProgress,0,'builders must claim a valid physical plot before working');assert.equal(s.status,'Need open ground');g.world.terrain=()=>({biome:'forest',water:false});g.world.blocked=()=>false;tick(g,s);assert.equal(s.huts.length,1);assert.equal(s.huts[0].hp,0);assert.equal(s.wood,20);g.colonies.plan=()=>{};tick(g,s,36);assert.equal(s.huts[0].hp,100);assert.equal(s.wood,14,'isolated hut construction deducts its six timber exactly once');
});
test('damaged and ruined huts survive saves and rebuilding costs work and timber',()=>{
 const{c,g,s}=colony(30),first=s.huts[0],second=s.huts[1];g.colonies.damageHut(s,first,100);g.colonies.damageHut(s,second,45);const saved=JSON.parse(JSON.stringify(g.serialize())),loaded=c.ATSGame.fromJSON(saved),home=loaded.settlements[0];assert.equal(home.huts[0].hp,0);assert.equal(home.huts[1].hp,55);assert.equal(home.housing,s.housing);loaded.world.getObjects=()=>[];loaded.world.getSites=()=>[];home.suitability.wood=0;home.wood=0;tick(loaded,home,20);assert.equal(home.huts[0].hp,0,'no free rebuild without timber');home.wood=6;tick(loaded,home,1);assert.equal(home.huts[0].hp,0,'one work tick cannot rebuild');tick(loaded,home,30);assert.equal(home.huts[0].hp,100);assert.equal(home.wood,0);assert.equal(home.housing,s.housing+first.capacity);assert.equal(home.huts[1].hp,55,'rebuild does not heal other huts');
});
test('old settlements migrate their full housing to huts without resetting supplies',()=>{
 const{c,g,s}=colony(24);s.housing=54;s.food=37;s.wood=19;delete s.structuresVersion;delete s.huts;const loaded=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(g.serialize()))),home=loaded.settlements[0];assert.equal(home.economyVersion,2);assert.equal(home.structuresVersion,1);assert.equal(home.housing,54);assert.equal(home.huts.length,4);assert.equal(home.food,37);assert.equal(home.wood,19);loaded.colonies.init(home);assert.equal(home.huts.length,4,'migration runs once');
});
test('explosives damage nearby homes with falloff while distant huts stay intact',()=>{
 const{g,s}=colony(30),hut=s.huts[0],other=s.huts[1];g.colonies.damageNearby(hut.x,hut.y,30,60,{x:hut.x,y:hut.y});assert.equal(hut.hp,40);assert.equal(other.hp,100);assert.equal(s.housing,30);g.colonies.damageNearby(hut.x,hut.y,30,60);assert.equal(hut.hp,0);assert.equal(s.housing,30-hut.capacity);
});
test('settlements give birth above the old cap and preserve bounded family progress at the new cap',()=>{
 const{c,g,s}=colony(24);s.gardens=10;g.colonies.addHut(s);for(let i=g.population;i<650;i++)g.makeApe(3000+i,0,'follow');s.birthTimer=30;tick(g,s);assert.ok(g.population>650);for(let i=g.population;i<c.MAX_APE_POPULATION;i++)g.makeApe(5000+i,0,'follow');s.birthTimer=17;tick(g,s,100);assert.equal(g.population,c.MAX_APE_POPULATION);assert.equal(s.birthTimer,17,'family progress pauses exactly');s.birthTimer=900;tick(g,s);assert.equal(s.birthTimer,30,'stale progress cannot create a birth burst');const before=g.stats.born;g.apes.at(-1).hp=0;tick(g,s);assert.equal(g.population,c.MAX_APE_POPULATION);assert.equal(g.stats.born,before+1,'only the new single space is filled');assert.ok(s.birthTimer<30);
});
function renderer(){const calls=[],gradient={addColorStop(){}};const ctx=()=>new Proxy({globalAlpha:1,createLinearGradient:()=>gradient,createRadialGradient:()=>gradient},{get(o,k){return k in o?o[k]:(...args)=>{for(const a of args)if(typeof a==='number')assert.ok(Number.isFinite(a),String(k));calls.push([k,...args])}},set(o,k,v){o[k]=v;return true}}),canvas=()=>({getBoundingClientRect:()=>({width:900,height:600}),getContext:ctx});const c=vm.createContext({console,Math,Map,Set,devicePixelRatio:1,innerWidth:900,innerHeight:600,document:{createElement:canvas}});c.window=c;for(const name of ['render','render-details'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',name+'.js'),'utf8'),c);return{r:new c.ATSRenderer(canvas()),calls}}
test('settlement finder shows multiple destinations on every screen edge at all zooms',()=>{
 const{r}=renderer(),g={king:{x:0,y:0},settlements:[]};for(let i=0;i<8;i++){const a=i*Math.PI/4,p=r.unproject(r.w/2+Math.cos(a)*3000,r.h*.53+Math.sin(a)*3000);g.settlements.push({id:'home-'+i,name:'Home '+i,population:10,...p})}g.settlements.push({id:'empty',name:'Empty',x:10000,y:10000,population:0});for(const [w,h]of [[900,600],[390,844],[844,390]])for(const zoom of [.45,1,1.8]){r.w=w;r.h=h;r.camera.zoom=zoom;const markers=r.settlementIndicators(g);assert.equal(markers.length,9);assert.ok(markers.some(m=>m.settlement.id==='empty'),'rallied empty homes stay findable');assert.equal(new Set(markers.map(m=>m.edge)).size,4);for(const m of markers){assert.ok(m.x>0&&m.x<w);assert.ok(m.y>0&&m.y<h);const p=r.project(m.settlement.x,m.settlement.y),origin=r.project(0,0);assert.ok(Math.abs(m.angle-Math.atan2(p.y-origin.y,p.x-origin.x))<1e-10)}}
});
test('settlement arrows keep coincident bearings separate and track the camera',()=>{
 const{r}=renderer(),g={king:{x:100,y:50},settlements:Array.from({length:4},(_,i)=>({id:'same-'+i,name:'Village '+i,x:10000+i*100,y:-10000-i*100,population:12}))};r.camera.x=100;r.camera.y=50;const markers=r.settlementIndicators(g);assert.equal(markers.length,4);assert.equal(new Set(markers.map(m=>m.y)).size,4);const previous=markers[0].angle;g.king.x+=80;r.camera.x+=80;assert.notEqual(r.settlementIndicators(g)[0].angle,previous);
});
test('hut damage, pending captives and mortar warnings render finite visible cues',()=>{
 const{r,calls}=renderer();r.time=10;for(const hp of [100,55,0])r.drawHut(r.ctx,{hp,maxHp:100,lastHit:9.9});r.drawObject(r.ctx,{type:'cage',dead:true,rescueOpened:true,count:25,hp:0,maxHp:100});r.drawThreats({time:10,humans:[],vehicles:[],forces:{hazards:[{type:'mortar',x:30,y:20,start:9,fuse:2.1,radius:100},{type:'airstrike',x:180,y:20,start:9,fuse:2,radius:80}]}});assert.ok(!calls.some(c=>c[0]==='fillText'),'captivity and attack tells stay wordless');assert.ok(calls.some(c=>c[0]==='ellipse'&&Math.abs(c[3]-100*.8*Math.SQRT2)<1e-9),'mortar circle remains visible');assert.ok(calls.some(c=>c[0]==='ellipse'&&Math.abs(c[3]-80*.8*Math.SQRT2)<1e-9),'airstrike circle remains visible');calls.length=0;r.drawThreats({time:10,humans:[],vehicles:[],forces:{hazards:[{type:'mortar',x:30000,y:30000,start:9,fuse:2.1,radius:100}]}});assert.equal(calls.length,0,'offscreen mortar warnings are culled');
});
test('all explosive warning boundaries match the projected damage radius at every quality and zoom',()=>{
 const{r,calls}=renderer(),hazards=[{type:'grenade',radius:76,fromX:-30,fromY:0},{type:'mortar',radius:100},{type:'airstrike',radius:80}].map(h=>({...h,x:0,y:0,start:9,fuse:2,life:1})),tank={kind:'tank',x:-30,y:0,hp:100,cannonTarget:{x:0,y:0,start:9,duration:2}};
 for(const quality of [0,5])for(const zoom of [.45,1,1.8]){r.detailLevel=quality;r.camera.zoom=zoom;calls.length=0;r.drawThreats({time:10,humans:[],vehicles:[tank],forces:{hazards}});const origin=r.project(0,0);for(const radius of [76,100,80,104]){const warning=calls.find(c=>c[0]==='ellipse'&&Math.abs(c[3]-radius*.8*Math.SQRT2)<1e-9&&Math.abs(c[4]-radius*.42*Math.SQRT2)<1e-9);assert.ok(warning,'warning survives quality '+quality+' for radius '+radius);for(let i=0;i<16;i++){const a=i*Math.PI/8,p=r.project(Math.cos(a)*radius,Math.sin(a)*radius),boundary=((p.x-origin.x)/(warning[3]*zoom))**2+((p.y-origin.y)/(warning[4]*zoom))**2;assert.ok(Math.abs(boundary-1)<1e-9,'projected blast boundary lies on warning')}}}
});
