/* Actual desktop/touch commands, isolated King input, rendering and save checks. */
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {pathToFileURL}=require('node:url'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const errors=[];try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../../apes-together-strong.html')).href);await page.locator('#newRun').click();await page.waitForFunction(()=>ATS.game?.time>.1);
 await page.evaluate(()=>{const g=ATS.game;g.spawnSites=()=>{};g.nextDirectorAt=g.nextConvoyAt=g.heliTimer=1e9;g.humans=[];g.world.objects.clear();g.world._spatial.clear();g.world.sites.clear();g.world.ensure=()=>{};g.world.stream=()=>{};g.world.waterBlocked=()=>false;g.world.terrain=()=>({biome:'forest',water:false});g.king.hp=g.king.maxHp=10000;for(let i=0;i<36;i++){const a=g.makeApe(-130+i%6*22,(Math.floor(i/6)-3)*24,'follow');a.species=ATSSiegeSpecies[i%6];g.siege.balance(a,true);if(i%6<2)a.shield={hp:180,maxHp:180}}g.syncIndexes();ATS.army.update(true)});
 const bar=page.locator('#armyDock .army-commands'),bounds=await bar.boundingBox();assert.ok(bounds.y>740);const button=page.locator('#armyDock [data-army-command=nearestTarget]');const size=await button.boundingBox();assert.ok(size.width<=34&&size.height<=38);assert.equal(await button.locator('kbd').innerText(),'E');assert.equal(await button.locator('canvas').count(),1);
 await page.keyboard.press('4');assert.deepEqual(await page.evaluate(()=>ATS.game.siege.selected),['gibbon']);let point=await page.evaluate(()=>ATS.renderer.project(160,-100));const before=await page.evaluate(()=>({x:ATS.game.king.x,y:ATS.game.king.y,attack:ATS.game.king.attackTimer}));await page.mouse.click(point.x,point.y);point=await page.evaluate(()=>ATS.renderer.project(280,40));await page.mouse.click(point.x,point.y);assert.equal(await page.evaluate(()=>ATS.game.siege.drafts.gibbon.length),2);const after=await page.evaluate(()=>({x:ATS.game.king.x,y:ATS.game.king.y,attack:ATS.game.king.attackTimer}));assert.equal(after.x,before.x);assert.equal(after.y,before.y);assert.ok(after.attack<=before.attack);await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>ATS.game.siege.groups.gibbon.orders.length),2);
 await page.keyboard.press('e');assert.ok(await page.evaluate(()=>ATS.game.apes.filter(a=>a.species==='gibbon').every(a=>a.state==='charge'&&a.nearestOrder?.kind==='all')));await page.keyboard.press('o');assert.equal(await page.evaluate(()=>ATS.screen),'play');assert.deepEqual(await page.evaluate(()=>ATS.game.siege.selected),[]);
 await page.keyboard.press('4');await page.keyboard.down('4');await page.keyboard.down('4');await page.keyboard.up('4');assert.deepEqual(await page.evaluate(()=>ATS.game.siege.selected),[],'one new keydown toggles off, autorepeat cannot toggle back on');await page.keyboard.press('4');
 point=await page.evaluate(()=>ATS.renderer.project(110,-80));await page.mouse.click(point.x,point.y);point=await page.evaluate(()=>ATS.renderer.project(200,70));await page.mouse.click(point.x,point.y,{button:'right'});assert.deepEqual(await page.evaluate(()=>ATS.game.siege.groups.gibbon.orders.map(o=>o.type)),['move','attackArea']);assert.equal(await page.evaluate(()=>ATS.game.siege.drafts.gibbon.length),0);
 await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>ATS.screen),'pause');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>ATS.screen),'play');assert.deepEqual(await page.evaluate(()=>ATS.game.siege.selected),['gibbon']);
 const cancel=page.locator('#armyDock .army-cancel');assert.equal(await cancel.locator('kbd').innerText(),'O');assert.match(await cancel.innerText(),/Cancel/);await cancel.click();assert.deepEqual(await page.evaluate(()=>ATS.game.siege.selected),[]);assert.equal(await page.evaluate(()=>ATS.game.siege.groups.gibbon.orders.at(-1).type),'attackArea');
 await page.keyboard.press('4');point=await page.evaluate(()=>ATS.renderer.project(100,-50));await page.mouse.click(point.x,point.y);const go=page.locator('#armyDock .army-route [data-army-command=go]');await go.hover();await page.mouse.down();await page.evaluate(()=>{window.heldGo=document.querySelector('.army-route [data-army-command=go]');for(let i=0;i<5;i++)ATS.army.update(true)});assert.ok(await page.evaluate(()=>window.heldGo===document.querySelector('.army-route [data-army-command=go]')));await page.mouse.up();assert.equal(await page.evaluate(()=>ATS.game.siege.drafts.gibbon.length),0);assert.equal(await page.evaluate(()=>ATS.game.siege.groups.gibbon.orders[0].type),'move');
 await cancel.focus();await page.keyboard.press('Enter');assert.deepEqual(await page.evaluate(()=>ATS.game.siege.selected),[],'keyboard activation clicks Cancel');
 await page.evaluate(()=>{const g=ATS.game;window.originalUpdate=g.update;g.update=function(dt,input){window.lastInput=input;return window.originalUpdate.call(this,dt,input)}});await page.keyboard.down('Control');await page.keyboard.down('w');await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>window.lastInput.sneak&&Math.hypot(window.lastInput.x,window.lastInput.y)>.9),'Control still permits sneaking movement');await page.keyboard.up('w');await page.keyboard.up('Control');await page.evaluate(()=>{ATS.game.update=window.originalUpdate});
 await page.keyboard.press('6');await page.keyboard.press('l');await page.waitForTimeout(650);assert.ok(await page.evaluate(()=>ATS.game.siege.rallyReady>ATS.game.time));await page.evaluate(()=>{ATS.game.time=ATS.game.siege.rallyReady+1;ATS.army.update()});assert.equal(await page.locator('#armyDock [data-army-command=rally]').isEnabled(),true,'cooldown refreshes without changing selection');
 await page.keyboard.press('0');await page.evaluate(()=>{const g=ATS.game;g.world._buildSite({objects:[],sites:[]},{id:'showcase',x:340,y:-100,type:'forwardBase',military:true,tier:3,guards:40,count:45,radius:420,extentX:346,extentY:260,layout:0});const site=g.world.sites.get('showcase');site.known=true;for(const id of site.objects){const o=g.world.objects.get(id);if(o.type==='gateControl')o.discovered=true}g.world.reveal(340,-100,1000);ATS.renderer.camera.zoom=.72;g.siege.draft({x:-140,y:-270},'move');const winch=site.objects.map(id=>g.world.objects.get(id)).find(o=>o.type==='gateControl');g.siege.draft(winch);ATS.army.update(true)});await page.waitForTimeout(200);
 const winchPoint=await page.evaluate(()=>{const o=ATS.game.world.sites.get('showcase').objects.map(id=>ATS.game.world.objects.get(id)).find(o=>o.type==='gateControl');return ATS.renderer.project(o.x,o.y,22)});await page.mouse.click(winchPoint.x,winchPoint.y);assert.equal(await page.evaluate(()=>ATS.game.siege.drafts.gorilla.at(-1).type),'sabotage','clicking the drawn winch selects the real control');
 await page.keyboard.press('Control+Shift+2');await page.keyboard.press('4');await page.keyboard.press('Shift+1');assert.deepEqual(await page.evaluate(()=>ATS.game.siege.selected),['gibbon','gorilla']);await page.keyboard.press('Control+2');assert.equal(await page.evaluate(()=>ATS.game.siege.selected.length),6,'saved preset restores selected species');
 if(process.env.QA_ARTIFACT_DIR){fs.mkdirSync(process.env.QA_ARTIFACT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.QA_ARTIFACT_DIR,'siege-desktop.png')})}
 const context=await browser.newContext({viewport:{width:430,height:860},isMobile:true,hasTouch:true,deviceScaleFactor:1});const mobile=await context.newPage();mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(pathToFileURL(path.resolve(__dirname,'../../apes-together-strong.html')).href);await mobile.locator('#newRun').tap();await mobile.waitForFunction(()=>ATS.game?.time>.1);await mobile.evaluate(()=>{const g=ATS.game;g.spawnSites=()=>{};const a=g.makeApe(0,20,'follow');a.species='gibbon';g.siege.balance(a,true);ATS.army.update(true)});await mobile.locator('#armyDock [data-species=gibbon]').tap();await mobile.touchscreen.tap(250,350);await mobile.touchscreen.tap(180,310);assert.equal(await mobile.evaluate(()=>ATS.game.siege.drafts.gibbon.length),2);await mobile.locator('#armyDock [data-army-command=go]').tap();assert.equal(await mobile.evaluate(()=>ATS.game.siege.groups.gibbon.orders.length),2);const mobileButton=await mobile.locator('#armyDock [data-species=gibbon]').boundingBox();assert.ok(mobileButton.height>=44);
 const zoom=await mobile.evaluate(()=>{const a=ATS.army,z=ATS.renderer.camera.zoom;a.down({pointerId:90,clientX:100,clientY:250});a.down({pointerId:91,clientX:200,clientY:250});a.move({pointerId:91,clientX:260,clientY:250});a.up({pointerId:90});a.up({pointerId:91});return{before:z,after:ATS.renderer.camera.zoom,count:ATS.game.siege.drafts.gibbon.length}});assert.ok(zoom.after>zoom.before);assert.equal(zoom.count,0,'pinch never adds accidental orders');await mobile.locator('#armyDock .army-expand').tap();await mobile.locator('#armyDock [data-army-command=finish]').tap();await mobile.touchscreen.tap(230,330);assert.equal(await mobile.evaluate(()=>ATS.game.siege.groups.gibbon.orders.at(-1).type),'attackArea');await mobile.locator('#armyDock .army-cancel').tap();assert.deepEqual(await mobile.evaluate(()=>ATS.game.siege.selected),[]);if(process.env.QA_ARTIFACT_DIR)await mobile.screenshot({path:path.join(process.env.QA_ARTIFACT_DIR,'siege-mobile.png')});assert.deepEqual(errors,[]);console.log('PASS: persistent clickable Cancel/O, Escape pause, right-click/touch terminal attack, key repeat, keyboard button activation, small icon/hotkey buttons, species selection, two-point routes, immediate charge, rally cooldown, King input isolation, desktop rendering, touch commands, pinch and zero browser errors.');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
