'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {loadEngine}=require('./performance-harness.cjs');
function arena(){const c=loadEngine(),g=new c.ATSGame('FORTRESS-SIEGE');g.world.objects.clear();g.world._spatial.clear();g.world.sites.clear();g.world.ensure=()=>{};g.world.stream=()=>{};g.world.terrain=()=>({biome:'forest',water:false});g.world.waterBlocked=()=>false;g.spawnSites=()=>{};g.nextDirectorAt=g.nextConvoyAt=g.heliTimer=1e9;g.king.x=-400;return{c,g}}
function object(g,p){const o={id:'siege-prop-'+g.nextId++,x:0,y:0,hp:500,maxHp:500,solid:true,r:12,...p};g.world.objects.set(o.id,o);g.world._indexObject(o);return o}
function ape(g,species,x=-150,y=0){const a=g.makeApe(x,y,'follow');a.species=species;g.siege.balance(a,true);a.attackCD=0;return a}
function grids(g){g.syncIndexes();g.apeGrid.rebuild([g.king,...g.apes]);g.humanGrid.rebuild(g.humans);g.vehicleGrid.rebuild(g.vehicles);g.navigation.beginFrame(g.time);g.performance.beginStep(g)}
function step(g,n=1){for(let i=0;i<n;i++){g.time+=1/30;grids(g);g.siege.tick(1/30);for(const a of g.apes)g.updateApe(a,1/30)}}
function fortress(g){const s={id:'test-fortress',x:200,y:0,extentX:200,extentY:200,radius:350,military:true,fortressVersion:1,objects:[],guards:0,strength:0,stairs:[],walkways:[],known:true};g.world.sites.set(s.id,s);const wall=object(g,{type:'wall',siteId:s.id,x:0,y:0,w:20,h:350,collision:'rect',visualHeight:80,walkHeight:80,walkable:true,climbAccess:true});const gate=object(g,{type:'gate',siteId:s.id,x:200,y:200,w:140,h:20,collision:'rect',gateState:'closed'});const control=object(g,{type:'gateControl',siteId:s.id,x:200,y:115,gateId:gate.id,discovered:true,hp:60,maxHp:60});s.gates=[gate.id];s.climbRoutes=[[wall.id]];s.walkways=[wall.id];s.objects=[wall.id,gate.id,control.id];return{s,wall,gate,control}}
test('species queues snapshot followers, exclude villagers, and preserve each mandatory flank waypoint',()=>{
 const {g}=arena(),a=ape(g,'gibbon'),resident=ape(g,'gibbon',-170);resident.state='settled';const {control,gate}=fortress(g);grids(g);g.siege.select('gibbon');
 assert.ok(g.siege.draft({x:-120,y:-145},'move'));assert.ok(g.siege.draft(control));assert.equal(g.siege.drafts.gibbon[1].type,'sabotage');assert.equal(g.siege.dispatch(),true);assert.equal(resident.armyOrder,undefined);
 const late=ape(g,'gibbon',-300);assert.equal(late.armyOrder,undefined);let flank=false,crossed=false;
 for(let i=0;i<1000&&control.hp>0;i++){step(g);if(Math.hypot(a.x+120,a.y+145)<30)flank=true;if(a.x>0){assert.ok(flank,'the flank must finish before entering the fortress');crossed=true}}
 assert.ok(crossed);assert.ok(control.dead,'gibbon reaches and destroys interior winch');assert.equal(gate.solid,false);assert.equal(gate.gateState,'open');assert.equal(g.navigation.blocked(gate.x,gate.y,10,'ape'),false);
});
test('replace, append, undo data and immediate charge retain separate species groups',()=>{
 const {g}=arena(),a=ape(g,'gibbon'),b=ape(g,'gorilla');grids(g);g.siege.select('gibbon');g.siege.draft({x:100,y:0},'move');g.siege.dispatch();const id=a.armyOrder.group;g.siege.draft({x:200,y:0},'move');g.siege.dispatch(true);assert.equal(g.siege.groups.gibbon.orders.length,2);assert.equal(a.armyOrder.group,id);assert.equal(b.armyOrder,undefined);
 g.siege.immediate('charge',{x:300,y:100});assert.equal(g.siege.groups.gibbon.orders.length,1);assert.equal(g.siege.groups.gibbon.orders[0].type,'charge');assert.notEqual(a.armyOrder.group,id);
 for(let i=0;i<15;i++)assert.ok(g.siege.draft({x:400+i,y:0},'move'));assert.equal(g.siege.draft({x:600,y:0},'move'),false);
});
test('heavy units wait for a real gate opening; high wall access rejects heavy species',()=>{
 const {g}=arena(),a=ape(g,'gorilla',200,290),{wall,gate,control}=fortress(g);grids(g);g.siege.issue(['gorilla'],[{id:'inside',type:'sabotage',targetId:control.id,targetKind:'object',x:control.x,y:control.y}]);step(g,130);assert.equal(gate.solid,true);assert.ok(a.y>200);assert.equal(g.tactics.canClimb(a,wall),false);g.siege.openGate(gate);step(g,200);assert.ok(a.y<200);assert.ok(control.dead);
});
test('capuchin throws release after windup and deal light ranged damage with cover and altitude checks',()=>{
 const {g}=arena(),a=ape(g,'capuchin',0),h=g.makeHuman(130,0,null);grids(g);const hp=h.hp;assert.ok(g.siege.throwAt(a,h,'human'));g.time=.41;g.siege.releaseThrow(a);assert.equal(g.siege.stones.length,0);g.time=.43;g.siege.releaseThrow(a);assert.equal(g.siege.stones.length,1);g.siege.updateStones(1);assert.equal(h.hp,hp-6);assert.equal(a.animation.kind,'throw');
 const w=object(g,{type:'wall',x:60,y:0,w:20,h:100,collision:'rect',visualHeight:95});g.time=2;assert.equal(g.siege.throwAt(a,h,'human'),false);w.dead=true;h.elevation=100;assert.equal(g.siege.meleeAllowed(a,h),false);assert.ok(g.siege.throwAt(a,h,'human'));a.hitTimer=.28;g.time=3;g.siege.releaseThrow(a);assert.equal(a.throwWindup,undefined);assert.equal(g.siege.stones.length,0,'interrupted throws create no late damage');
});
test('Rally Roar has one shared cooldown, only buffs nearby allies, and expires',()=>{
 const {g}=arena(),m=ape(g,'mandrill',0),near=ape(g,'chimpanzee',60),far=ape(g,'gorilla',400);grids(g);g.siege.select('mandrill');assert.ok(g.siege.rally());g.time=.46;g.siege.updateRally(m);assert.equal(near.rallyUntil,6.46);assert.equal(far.rallyUntil,undefined);assert.equal(g.siege.rally(),false);g.time=31;assert.ok(g.siege.rally());assert.ok(near.rallyUntil<g.time);
});
test('logs absorb frontal bullets, preserve flank damage and break without regeneration',()=>{
 const {g}=arena(),a=ape(g,'gorilla',0);a.dir=0;a.shield={hp:180,maxHp:180};assert.equal(g.siege.absorb(a,54,{x:100,y:0,type:'bullet'}),0);assert.equal(a.shield.hp,126);assert.equal(g.siege.absorb(a,54,{x:-100,y:0,type:'bullet'}),54);assert.equal(a.shield.hp,126);assert.equal(g.siege.absorb(a,200,{x:100,y:0,type:'shell'}),130);assert.equal(a.shield.hp,0);step(g,30);assert.equal(a.shield.hp,0);
});
test('human sightings share last known positions locally and deliver radio reports after a delay',()=>{
 const {g}=arena(),a=ape(g,'gibbon',100),watch=g.makeHuman(0,0,null),near=g.makeHuman(100,100,null),remote=g.makeHuman(700,0,null);watch.hasRadio=remote.hasRadio=true;grids(g);g.siege.report(watch,a);assert.equal(near.lastX,100);assert.equal(remote.reportAt,undefined);a.x=300;g.time=1;g.siege.tickReports();assert.equal(remote.reportAt,undefined);g.time=2;g.siege.tickReports();assert.equal(remote.lastX,100,'radio never follows an unseen actor');g.time=31;g.siege.tickReports();assert.equal(g.siege.reports.length,0);
});
test('tower exterior detection raises the real siren, respecting power and cover',()=>{
 const {g}=arena(),a=ape(g,'gibbon',150),alarm=object(g,{type:'alarm',x:-30,y:40}),tower=object(g,{type:'tower',x:0,y:0,height:100,angle:0,scanRange:600,siteId:'tower-site'}),s={id:'tower-site',objects:[alarm.id,tower.id],alarm:false};g.world.sites.set(s.id,s);grids(g);g.siege.scanTowers();assert.equal(s.alarm,true);assert.equal(alarm.active,true);assert.ok(g.siege.stats.towerChecks<=12);
 s.alarm=false;tower.powered=false;g.time=1;g.siege.scanTowers();assert.equal(s.alarm,false);tower.powered=true;object(g,{type:'wall',x:70,w:22,h:160,visualHeight:150,collision:'rect'});g.time=2;grids(g);g.siege.scanTowers();assert.equal(s.alarm,false);
});
test('saved queues, gate collision, shields, reports and legitimate climbs resume without healing',()=>{
 const {c,g}=arena(),a=ape(g,'gibbon',-34),{wall,gate,control}=fortress(g);g.siege.select('gibbon');g.siege.issue(['gibbon'],[{id:'winch',type:'sabotage',targetId:control.id,targetKind:'object',x:control.x,y:control.y}]);a.hp=47.5;a.shield={hp:15,maxHp:145};grids(g);assert.ok(g.siege.startTransition(a,wall,{x:34,y:0}));g.siege.openGate(gate);g.time=1;g.siege.transition(a,.5);const loaded=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(g.serialize()))),b=loaded.apes.find(x=>x.id===a.id);assert.equal(b.hp,47.5);assert.equal(b.shield.hp,15);assert.ok(b.siegeTransition);assert.equal(loaded.world.objects.get(gate.id).solid,false);assert.equal(loaded.siege.groups.gibbon.orders[0].targetId,control.id);
 const legacy=JSON.parse(JSON.stringify(g.serialize()));delete legacy.siege;delete legacy.apes[0].speciesBalanceVersion;legacy.apes[0].hp=60;legacy.apes[0].maxHp=120;const migrated=c.ATSGame.fromJSON(legacy);assert.equal(migrated.apes[0].maxHp,95);assert.equal(migrated.apes[0].hp,47.5);
});
test('destroyed climbing walls detach actors onto reachable ground',()=>{
 const {g}=arena(),a=ape(g,'gibbon',-34),{wall}=fortress(g);grids(g);assert.ok(g.siege.startTransition(a,wall,{x:34,y:0}));g.siege.transition(a,1.4);wall.dead=true;wall.hp=0;g.siege.transition(a,.1);assert.equal(a.siegeTransition,undefined);assert.equal(a.elevation,0);assert.equal(g.navigation.blocked(a.x,a.y,9,'ape'),false);
});
test('new real fortresses have finite reserves, weaker gates, access corridors and inner defenses',()=>{
 const {g}=arena();for(const [i,type]of ['forwardBase','armoredDepot','regionalCommand'].entries()){const x=i*2000,s={id:'generated-'+type,x,y:0,type,military:true,tier:i+3,guards:80,count:50,radius:[420,540,690][i],extentX:[346,466,540][i],extentY:[260,300,330][i],layout:i%2};g.world._buildSite({objects:[],sites:[]},s);const site=g.world.sites.get(s.id),objects=site.objects.map(id=>g.world.objects.get(id)),gates=objects.filter(o=>o.type==='gate'),wall=objects.find(o=>o.type==='wall'&&!o.barricade);assert.ok(gates.every(o=>o.maxHp<wall.maxHp));assert.equal(objects.filter(o=>o.type==='gateControl').length,gates.length);assert.equal(site.climbRoutes.length,2);assert.ok(site.stairs.length>=2);assert.ok(site.garrisonReserve<=24);if(i===2)assert.ok(gates.some(o=>o.defenseRing===3));}
});
test('1,000 real followers retain bounded queued route work and snapshot membership',()=>{
 const {g}=arena();for(let i=0;i<1000;i++)ape(g,['gorilla','orangutan','chimpanzee','gibbon','capuchin','mandrill'][i%6],-300+i%25*12,(Math.floor(i/25)-20)*12);grids(g);g.siege.issue(['gorilla','orangutan','chimpanzee','gibbon','capuchin','mandrill'],[{id:'mass-route',type:'move',x:200,y:0}]);step(g,30);assert.equal(g.apes.filter(a=>a.armyOrder).length,1000);assert.ok(g.siege.pathCache.size<=256);assert.ok(g.navigation.stats.frameExpanded<=192);assert.ok(g.navigation.stats.frameSearches<=3);assert.ok(g.apes.every(a=>Number.isFinite(a.x)&&Number.isFinite(a.y)));
});
test('gibbons sabotage gates in all three generated fortress tiers through real access geometry',()=>{
 for(const [i,type]of ['forwardBase','armoredDepot','regionalCommand'].entries()){const {g}=arena();g.world._buildSite({objects:[],sites:[]},{id:'real-'+type,x:0,y:0,type,military:true,tier:i+3,guards:0,count:50,radius:[420,540,690][i],extentX:[346,466,540][i],extentY:[260,300,330][i],layout:i%2});const s=g.world.sites.get('real-'+type),control=s.objects.map(id=>g.world.objects.get(id)).find(o=>o.type==='gateControl');control.discovered=true;const a=ape(g,'gibbon',-s.extentX-145,-80);g.siege.issue(['gibbon'],[{id:'real-winch',type:'sabotage',targetId:control.id,targetKind:'object',x:control.x,y:control.y}]);for(let f=0;f<3000&&!control.dead;f++)step(g);assert.ok(control.dead,type+' winch reached: '+JSON.stringify({x:a.x,y:a.y,route:a.siegeRoute,blocked:g.siege.groups.gibbon?.blocked}));assert.equal(g.world.objects.get(control.gateId).solid,false);}
});
test('shield advance places logs in front and individual selection leaves the other species members idle',()=>{
 const {g}=arena(),front=ape(g,'gorilla',0),back=ape(g,'capuchin',0),other=ape(g,'gorilla',-10);front.shield={hp:180,maxHp:180};grids(g);g.siege.issue(['capuchin','gorilla'],[{id:'shield-line',type:'shield',x:200,y:0}]);assert.ok(front.armyOrder.formation.back<back.armyOrder.formation.back);assert.equal(g.siege.startTransition(front,fortress(g).wall,{x:34,y:0}),false);
 g.siege.selectUnits([other.id]);g.siege.immediate('hold');assert.equal(g.siege.groups.gorilla.members.length,1);assert.equal(g.siege.groups.gorilla.members[0],other.id);
});
test('regional inner gate controls require a second wall crossing and open the inner lane',()=>{
 const {g}=arena();g.world._buildSite({objects:[],sites:[]},{id:'inner-command',x:0,y:0,type:'regionalCommand',military:true,tier:5,guards:0,count:80,radius:690,extentX:540,extentY:330,layout:0});const s=g.world.sites.get('inner-command'),gate=s.gates.map(id=>g.world.objects.get(id)).find(o=>o.defenseRing===3),control=g.world.objects.get(gate.controlId),a=ape(g,'gibbon',-100,140);control.discovered=true;g.siege.issue(['gibbon'],[{id:'inner-order',type:'sabotage',targetId:control.id,targetKind:'object',x:control.x,y:control.y}]);for(let f=0;f<2500&&!control.dead;f++)step(g);assert.ok(control.dead,JSON.stringify({x:a.x,y:a.y,route:a.siegeRoute,blocked:g.siege.groups.gibbon?.blocked}));assert.equal(gate.solid,false);
});
test('human stair ascent and elevated bullets cannot be replaced by ground melee',()=>{
 const {g}=arena(),{s,wall}=fortress(g),stairs=object(g,{type:'stairs',x:50,y:0,wallId:wall.id,solid:false}),h=g.makeHuman(50,0,s),a=ape(g,'gorilla',-120,0);s.stairs=[stairs.id];h.wallAssignment={stairId:stairs.id,post:0};grids(g);for(let i=0;i<80;i++){g.time+=1/30;g.siege.updateHuman(h,1/30)}assert.equal(h.onWallId,wall.id);assert.equal(h.elevation,80);const hp=h.hp;g.hurt(h,50,a);assert.equal(h.hp,hp);assert.equal(g.siege.clearRay(h,a),true);h.shootTimer=0;g.shoot(h,a);assert.ok(g.bullets.at(-1).z>80);assert.ok(g.bullets.at(-1).vz<0);wall.dead=true;wall.hp=0;g.siege.updateHuman(h,.1);assert.equal(h.elevation,0);assert.equal(h.onWallId,undefined);
});
test('finite barracks reserves stop when exhausted or sabotaged',()=>{
 const {g}=arena(),{s}=fortress(g);const barracks=object(g,{type:'barracks',x:260,y:0,siteId:s.id});s.objects.push(barracks.id);Object.assign(s,{alarm:true,garrisonReserve:7,strength:7,reserveCommitted:0,lastSightingAt:1000,lastHostileAt:1000});g.king.x=100;g.world.getSites=()=>[s];grids(g);g.siege.garrison();assert.equal(s.garrisonReserve,3);g.time=13;g.siege.garrison();assert.equal(s.garrisonReserve,0);assert.equal(s.strength,0);assert.equal(s.reserveCommitted,7);g.time=26;g.siege.garrison();assert.equal(s.reserveCommitted,7);s.garrisonReserve=s.strength=4;s.barracksDown=true;g.time=40;g.siege.garrison();assert.equal(s.reserveCommitted,7);
});
test('human flankers react to frontal log protection and prefer visible unshielded targets',()=>{
 const {g}=arena(),a=ape(g,'gorilla',0),h=g.makeHuman(170,0,null);a.dir=0;a.shield={hp:180,maxHp:180};Object.assign(h,{role:'flanker',targetId:a.id,_tacticalThink:0});grids(g);g.forces.tacticalTarget(h);assert.ok(h._shieldFlank);assert.ok(Math.abs(h._shieldFlank.y)>100);const b=ape(g,'gibbon',20,80);g.time=1;grids(g);g.forces.tacticalTarget(h);assert.equal(h.targetId,b.id);
});
