const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
function engine(){const c=vm.createContext({console,Math,Map,Set});c.window=c;for(const name of ['world','navigation','settlements','forces','sim'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',name+'.js'),'utf8'),c);return c}
function clearGame(){const c=engine(),g=new c.ATSGame('TEST','survival');g.world.objects.clear();g.world._spatial.clear();g.world.ensure=()=>{};g.world.getObjects=()=>[];g.world.getSites=()=>[];g.world.lineClear=()=>true;g.world.terrain=()=>({biome:'forest',water:false});g.world.sites.clear();return {g,c}}
test('major facilities are spaced between outposts and every site has a defined approach',()=>{const c=engine(),w=new c.ATSWorld('world-design');w.ensure(6400,6400,4200);const sites=[...w.sites.values()];const major=sites.filter(s=>s.tier>=4);assert.ok(major.length>1);for(const s of sites){assert.equal(w.terrain(s.x,s.y).water,false);assert.ok(s.approach.length>=2)}for(let i=0;i<major.length;i++)for(let j=i+1;j<major.length;j++)assert.ok(Math.hypot(major[i].x-major[j].x,major[i].y-major[j].y)>1400);assert.ok(sites.some(s=>s.tier<=2));});
test('world terrain and site layouts are deterministic across chunk traversal order',()=>{const c=engine(),a=new c.ATSWorld('layout'),b=new c.ATSWorld('layout');const points=[[0,0],[1400,2800],[-2300,4700]];for(const p of points)a.ensure(...p,800);for(const p of points.slice().reverse())b.ensure(...p,800);const normalize=w=>JSON.stringify([...w.sites.values()].sort((a,b)=>a.id.localeCompare(b.id)));assert.equal(normalize(a),normalize(b));});
test('shield guard blocks frontal attacks but flanking causes full damage',()=>{const {g}=clearGame(),h=g.makeHuman(100,0,null);h.role='shield';h.dir=Math.PI;g.apeGrid.rebuild([g.king]);const before=h.hp;g.hurt(h,30,{x:0,y:0});const frontal=before-h.hp;h.hp=before;g.hurt(h,30,{x:200,y:0});assert.ok(frontal<15);assert.equal(before-h.hp,30)});
test('grenades have a full warning interval and then damage exposed units',()=>{const {g}=clearGame();g.apeGrid.rebuild([g.king]);g.forces.hazards.push({type:'grenade',x:0,y:0,start:0,life:1.8,fuse:1.8,radius:67});g.forces.tick(1.7);assert.equal(g.king.hp,160);g.forces.tick(.11);assert.ok(g.king.hp<100);assert.equal(g.forces.hazards.length,0)});
test('marksman commits to the warned location instead of instantly tracking a dodge',()=>{const {g}=clearGame(),h=g.makeHuman(200,0,null);h.role='sniper';h.kind='sniper';h.state='combat';h.targetId='king';h.shootTimer=0;g.forces.update(h,.1);assert.equal(h.aiming.x,0);g.king.y=150;g.time=1.5;g.forces.update(h,.1);assert.ok(g.bullets.length>0);assert.ok(Math.abs(g.bullets[0].vy)<30);});
test('settlement growth needs work and resources; priorities and supplies survive a save',()=>{const c=engine(),g=new c.ATSGame('colony');g.world.getSites=()=>[];g.spawnSites=()=>{};g.nextDirectorAt=g.nextConvoyAt=g.heliTimer=1e9;for(let i=0;i<18;i++)g.makeApe(i,0,'follow');g.food=100;assert.equal(g.command('settleAll'),true);const s=g.settlements[0];g.colonies.action(s.id,'fortify');g.colonies.action(s.id,'supply');const before=s.level;g.colonies.tick(s);assert.equal(s.level,before);for(let i=0;i<500;i++)g.update(.2,{});assert.ok(s.maxDefense>0||s.housing>18);const saved=JSON.parse(JSON.stringify(g.serialize())),loaded=c.ATSGame.fromJSON(saved);assert.equal(loaded.settlements[0].policy,'fortify');assert.equal(loaded.settlements[0].housing,s.housing);assert.equal(loaded.settlements[0].food,s.food);assert.equal(loaded.navigation.world,loaded.world)});
test('dead units record varied falling bodies while leaving combat exactly once',()=>{const {g}=clearGame();for(let i=0;i<12;i++){const h=g.makeHuman(100+i*5,100,null);g.hurt(h,1000,g.king);g.hurt(h,1000,g.king)}assert.equal(g.corpses.length,12);assert.equal(g.stats.humans,12);assert.ok(new Set(g.corpses.map(c=>c.fallVariant)).size>=3)});
test('older saves migrate tree trunks and settlement economy without restoring stale routes',()=>{const c=engine(),g=new c.ATSGame('migration');g.makeApe(0,0,'follow');g.command('settleAll');const saved=JSON.parse(JSON.stringify(g.serialize()));delete saved.settlements[0].economyVersion;saved.apes[0]._nav={path:[{x:99999,y:99999}]};const loaded=c.ATSGame.fromJSON(saved);assert.equal(loaded.settlements[0].economyVersion,2);assert.equal(loaded.apes[0]._nav,undefined);for(const tree of loaded.world.objects.values())if(tree.type==='tree')assert.ok(tree.moveRadius<tree.r)});
test('distant garrisons free the active budget and return with their saved wounds',()=>{
  const c=engine(),g=new c.ATSGame('garrisons');g.spawnSites();
  const human=g.humans.find(h=>h.siteId==='opening-hunters');assert.ok(human);human.hp=31;
  g.king.x=9000;g.sleepDistantForces();
  assert.ok(!g.humans.some(h=>h.id===human.id));
  const loaded=c.ATSGame.fromJSON(JSON.parse(JSON.stringify(g.serialize())));
  loaded.king.x=0;loaded.king.y=0;loaded.spawnSites();
  assert.equal(loaded.humans.filter(h=>h.id===human.id).length,1);
  assert.equal(loaded.humans.find(h=>h.id===human.id).hp,31);
  assert.equal(loaded.world.sites.get('opening-hunters').sleepingHumans.length,0);
});
